### ISSUE TITLE
"lines the lines" in EOLANG and φ-calculus (2111.13384)

### ISSUE THREAD

**Issue by piotrkot** [objectionary/eo#1000]
The phrase "lines the lines" is found in four places in the document (4.1, 8.2, 8.3, 8.3), like:
"instantiated. However, the attribute radius of the EO object circle at the lines the lines 366–371 can’t be modiﬁed."
 I think it's a mistake.

**Comment by yegor256** [comment]
@piotrkot fixed in 0c8dd286 thanks!
