### ISSUE TITLE
list create_by_len

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1005]
let's add a new attribute to list that create a new list witn length and elements by arguments. Smth like that:
`[length elem]` > list-by-len
@yegor256 @EugeneDar

**Comment by EugeneDar** [comment]
@levBagryansky I think we can't implement it via while method, because we have problems with array wrapped in memory. We can implement it via recursion.

**Comment by yegor256** [comment]
@levBagryansky what is the purpose of this?

**Comment by levBagryansky** [comment]
@yegor256 
This will make it easier to use. May be if list of the specal object ordered to make work with arrays easier we can add this enough popular method to it.
Of course evebody can do it by himself:
```
[len elem] > array_by_len
  if. > @
    len.lte 0
    *
    (array_by_len (len.minus 1) elem).with elem
```

**Comment by Graur** [comment]
@levBagryansky Can't we use instead:
```
(*).with "some object"
```
