### ISSUE TITLE
Ram is not thread safe

### ISSUE THREAD

**Issue by andreoss** [objectionary/eo#1007]
Ram is a singleton, if it's being used from two threads, CME will happen.
https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/EOorg/EOeolang/Ram.java
https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/ram.eo

**Comment by yegor256** [comment]
@andreoss go ahead pls
