### ISSUE TITLE
eo-test - new module for test utils

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1008]
Let's create a new module and move the following existing classes into it:

  * `CheckPack` - let's turn it into Hamcrest matcher
  * `CheckXSL` - also, let's make a matcher out of it

Then, let's create a new JUnit5 `ArgumentsProvider`, and use it in `PacksTest`, `SyntaxTest`, and `OptimizePacksTest`.

**Comment by yegor256** [comment]
@Graur please, take care of this

**Comment by Graur** [comment]
@MikhailLipanin please, help us here

**Comment by MikhailLipanin** [comment]
@Graur, new module `eo-test` means placing it like that `eo/eo-parser/src/test/eo-test/CheckPack.java` ?

**Comment by Graur** [comment]
@MikhailLipanin As I understand, it will be a `eo/eo-test` module. 
@yegor256 Am I right?

**Comment by yegor256** [comment]
@Graur @MikhailLipanin yes, at the same level as `eo-parser`. Thus, it will be `eo/eo-test`

**Comment by andreoss** [comment]
Related to https://github.com/objectionary/eo/issues/1109

**Comment by Graur** [comment]
@MikhailLipanin  Do you have any progress here?

**Comment by Graur** [comment]
@MikhailLipanin Please, remove this todo #1109 in related to this issue pull request. Since this issues are similar

**Comment by MikhailLipanin** [comment]
@yegor256 This one can be closed?

**Comment by yegor256** [comment]
@MikhailLipanin yes
