### ISSUE TITLE
Assert documentation

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1009]
I didn't find where I can read about `assert-that`. I think it's necessary because this cause questions
For example it's not clear why this code 
```
[] > assert_problem
  memory 0 > m
  seq > @
    m.write
      m.plus 5
    QQ.io.stdout
      QQ.txt.sprintf
        "m = %d\n"
        m
    assert-that
      m
      $.equal-to 5
```
do that
![image](https://user-images.githubusercontent.com/32939651/183466227-a7b79d18-879e-48c0-ac41-641a719b4d58.png)

**Comment by levBagryansky** [comment]
@Graur, Thank you
Is this fine that assert infuence on repeating sequence like in example above?

**Comment by Graur** [comment]
@levBagryansky If you want to avoid it, just pass `seq` object as parameter to `assert-that` object. Or decorate it as abstract object
