### ISSUE TITLE
Central must understand classifiers of dependencies

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1010]
At the moment the classifier is not specified at all: https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/java/org/eolang/maven/Central.java#L99-L105 We should make it possible to use Maven dependencies with a classifier, like this:

```
+rt jvm org.eolang:eo-sys:jar-with-dependencies:0.0.0
```

Here, the classifier is `jar-with-dependencies`.

**Comment by yegor256** [comment]
@Graur please, take care of this

**Comment by Graur** [comment]
@MikhailLipanin please, take this task

**Comment by yegor256** [comment]
@Graur @MikhailLipanin what's up with this one? it's blocking a few other issues

**Comment by MikhailLipanin** [comment]
@yegor256 Okay, I'll start doing it.

**Comment by MikhailLipanin** [comment]
@yegor256, `classifier` should be a required parameter for dependency ? 
i.e. always we should point it out ? 
or if it is absent there will be an empty space? : `+rt jvm org.eolang:eo-sys::0.0.0`

**Comment by yegor256** [comment]
@MikhailLipanin not really. We may use either format:

```
+rt jvm org.eolang:eo-sys:0.0.0
+rt jvm org.eolang:eo-sys:jar-with-dependencies:0.0.0
```

Both are valid.
```

**Comment by mximp** [comment]
@yegor256 is it ready to be closed?

**Comment by yegor256** [comment]
@mximp yes, thanks!
