### ISSUE TITLE
Make max dataization log level configurable

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1013]
In order to simplify debugging let's make below hardcoded value configurable via jvm property `-Dmax.dataization.log`.
It must be defaulted to `4`.

`Dataized.java`
```
if (Dataized.LOGGER.isLoggable(Level.FINE)
                && Dataized.LEVEL.get() < 4
            )
```

**Comment by mximp** [comment]
Budget: 30min

**Comment by yegor256** [comment]
@yegor256 I don't mind

**Comment by Graur** [comment]
@mximp I don't mind too

**Comment by mximp** [comment]
@Karina5005 please have a look at this task.

**Comment by mximp** [comment]
@Karina5005 Thanks!
