### ISSUE TITLE
Unused aliases false positive

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#1014]
This code
```
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf
+alias org.eolang.txt.sprintf

[] > main
  stdout > @
    sprintf
      "I am %d years old"
      21
```
should not be executed because of duplicated aliases.

However, compiler will fail with the following mistakes:
![image](https://user-images.githubusercontent.com/57731693/183843577-f236b41d-8ff6-4da5-a4ab-1c0784007419.png)

It says that both `sprintf` aliases are not used, even though one of them is.

**Comment by yegor256** [comment]
@mximp definitely a bug, please help

**Comment by mximp** [comment]
@EugeneDar would you try to fix it?

**Comment by EugeneDar** [comment]
@mximp sure, I'll try to do it

**Comment by EugeneDar** [comment]
@yegor256 @mximp what type of error should we get in this case? Probably only `the alias "..." is dublicated`?

**Comment by mximp** [comment]
@EugeneDar That's right. In this case there should be single `alias duplicated` error.

**Comment by EugeneDar** [comment]
@yegor256 @mximp @Graur 
The problem is that when converting from EO to XMIR, we get duplication, as you can see on the fifth line below.
```
   <objects>
      <o abstract="" line="5" name="foo" pos="0">
         <o line="5" name="x" pos="1"/>
         <o base="org.eolang.io.stdout" line="6" name="@" pos="2">
            <o base="org.eolang.txt.sprintf org.eolang.txt.sprintf"
               line="7"
               pos="4">
               <o base="string" data="string" line="8" pos="6">Hello</o>
            </o>
         </o>
      </o>
   </objects>
```
In that case, is this XMIR correct?

**Comment by yegor256** [comment]
@EugeneDar this is _definitely_ a broken XMIR

**Comment by mximp** [comment]
@EugeneDar What is your question?

**Comment by EugeneDar** [comment]
> @EugeneDar What is your question?

I wanted to know if this XMIR is correct in order to know if the translator in XMIR needs to be fixed or if the error search needs to be fixed.

**Comment by EugeneDar** [comment]
@mximp I wanted to know if this XMIR is correct in order to know if the translator in XMIR needs to be fixed or if the error search needs to be fixed.

**Comment by EugeneDar** [comment]
@OlesiaSub this problem fixed here https://github.com/objectionary/eo/pull/1041

**Comment by OlesiaSub** [comment]
@EugeneDar thanks!
