### ISSUE TITLE
eo.skip option for eo-maven-plugin

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1015]
Let's introduce `eo.skip` option for our Maven plugin. So that it would be possible to do this in XML:

```
<configuation>
  <skip>true</skip>
</configuration>
```

Also, from command line:

```
$ mvn -Deo.skip
```

**Comment by yegor256** [comment]
@mximp should be pretty easy to implement, please help

**Comment by mximp** [comment]
@yegor256 what should it skip?

**Comment by yegor256** [comment]
@mximp the execution of a mojo. Just return and that's it, if the flag is set.

**Comment by mximp** [comment]
@OlesiaSub please assist with this.

**Comment by OlesiaSub** [comment]
@mximp @yegor256 could you please give a more detailed explanation of the idea or maybe an example of what should happen? I didn't quite get it.

**Comment by mximp** [comment]
@OlesiaSub If you check `pom.xml` in `eo-runtime` module you will see `eo-maven-plugin` configuration. 
It's required to be able to supply `<skip/>` option in configuration to suppress execution of plugin goals. Defaulted to `false`.
All plugin logic is in `eo-maven-plugin` module. Please check `SafeMojo` class which is common for all plugin goals.
 I believe skip option check can be placed there.

**Comment by OlesiaSub** [comment]
@mximp thanks!
Just to clarify, should `skip` option suppress execution of all goals at once or should it be specific for particular goals?

**Comment by mximp** [comment]
@OlesiaSub Execution of all goals

**Comment by mximp** [comment]
@yegor256 all is done. The task can be closed.

**Comment by yegor256** [comment]
@mximp @OlesiaSub thanks!
