### ISSUE TITLE
Can't run program with stdin

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1016]
I tried to run a program from the [paper](https://arxiv.org/abs/2111.13384)(p.6, 2.10) like this:
```
[] > hello
  QQ.io.stdout > say
    QQ.txt.sprintf
      "The length of %s is %d"
      QQ.io.stdin.next-line > x!
      x.length
```
then `eoc dataize hello`. The problem is that there isn't 'data' attribute, when I run this. I tried to write ` QQ.io.stdout > @` instead of, but now there is a problem with stdin, I think.

First, I think it would be nice to improve example from paper. Second, I get this error after changing a program:

_hello
EOorg.EOeolang.EOstringν19="There is no line in the standard input stream to consume"SF_

**Comment by ivan-egorov42** [comment]
Update: I realized, that this problem bounds to `string.length`, because program works without `x.length`(e.g. just `x`)

**Comment by includealex** [comment]
@ivan-egorov42 It is quite interesting, that such a code works and gives correct answer.
```
+alias org.eolang.io.stdout
+alias org.eolang.io.stdin
+alias org.eolang.txt.sprintf

[] > hello
  stdout > say
    sprintf
      "The length is %d, the string is %s\n"
      x.length
      stdin.next-line > x!

[] > problem
  hello.say > @
```
![image](https://user-images.githubusercontent.com/70340829/183916746-55b7c53e-e0ed-4503-8f4c-312263c33420.png)

**Comment by ivan-egorov42** [comment]
@includealex That's very funny. Now I have a question, why program works, if we just swapped two lines? (`x.length` and `stdin.next-line > x!`)

**Comment by levBagryansky** [comment]
I suppose it happens because when eo dataize sprintf, it starts from the  last attributes. In commaon, possibly, it dataize using recursion, that is why it starts from the end. So wnem it firstly try to dataize x.length it gets null. 
That's my theory.

**Comment by includealex** [comment]
@ivan-egorov42 I think, that problem is bounded with either `stdin` or `sprintf`. Here is a simple test, that shows that swapping lines shouldn't cause an error.
[swapping-lines](https://user-images.githubusercontent.com/70340829/183958741-1b47db98-fa62-4978-a624-2a747b65a07f.png)
 
@Graur, @mximp, what do you think about this so-called swapped-lines bug?

**Comment by Graur** [comment]
@includealex @ivan-egorov42 Indeed, it is a bug. You are welcome to fix it

**Comment by includealex** [comment]
@Graur, I'll try to fix this one.

**Comment by Graur** [comment]
@includealex Go ahead

**Comment by includealex** [comment]
@ivan-egorov42 now it works. Please, close the issue.

**Comment by ivan-egorov42** [comment]
@includealex thanks!)
