### ISSUE TITLE
HashOfTag goes to Internet too often

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1017]
At the moment, `HashOfTag` goes to the Internet on every call to `.hash()`. This is not effective and dangerous. If a new release happens during the build -- we'll have mixed .eo files. I suggest to cache the value retrieved inside HashOfTag, in a static HashMap.

**Comment by yegor256** [comment]
@mximp please, help

**Comment by EugeneDar** [comment]
@mximp sure

**Comment by EugeneDar** [comment]
@yegor256 it's done.

**Comment by yegor256** [comment]
@EugeneDar thanks!
