### ISSUE TITLE
remove depricated attributes

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1020]
Please remove depricated `list.reduce` and `list.reducei` in [eo/eo-runtime/src/main/eo/org/eolang/collections/list.eo](https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/collections/list.eo) after update of [eo-harmcrest/src/main/eo/org/eolang/hamcrest/assert-that.eo](https://github.com/objectionary/eo-hamcrest/blob/d39a19051b38a8e4f7c02de4d68b436c45c2d7a4/src/main/eo/org/eolang/hamcrest/assert-that.eo)
One test in eo use one attribute of `assert-that` that use deprecated attributes.

**Comment by Graur** [comment]
@levBagryansky Please do so after the next release of `eo-hamcrest`
