### ISSUE TITLE
eo maven plugin build fails

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#1022]
Invocation of `mvn clean install` fails on an untouched clone of this repository:

![image](https://user-images.githubusercontent.com/57731693/183899504-360c1892-7a93-45cd-ab62-46ae350b0799.png)

Build summary:

![image](https://user-images.githubusercontent.com/57731693/183905450-7c6b1671-09e6-4541-ba36-798a09b57b23.png)

My OS is Windows. Afaik this doesn't happen on linux (might be wrong).

**Comment by Graur** [comment]
@OlesiaSub Please, try it now

**Comment by OlesiaSub** [comment]
@Graur problem was solved, but now it fails because of stylecheck
![image](https://user-images.githubusercontent.com/57731693/184162075-15d9b591-3628-4e40-bb2b-5501e3a8b20a.png)

**Comment by Graur** [comment]
@OlesiaSub try it now, please

**Comment by OlesiaSub** [comment]
Fixed, thank you!

**Comment by Graur** [comment]
@OlesiaSub please close the ticket if you don’t have any further questions.
