### ISSUE TITLE
Comparating of different objects

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1025]
Not all objects have eq attributes, but list.found, for example, implies that we can compare any two objects. Throwing an error
![image](https://user-images.githubusercontent.com/32939651/183965701-44da7e85-01dd-461e-b9e0-33f57ac77fdb.png)
I think we need to be able to compare any object,
@yegor256 @Graur @mximp

**Comment by Graur** [comment]
@levBagryansky I think you should ask such questions in the related tickets. This one is related to https://github.com/objectionary/eo/issues/1012

**Comment by mximp** [comment]
@levBagryansky I agree let's keep this conversation in initial task so far. 
Can you post comment there with problem code and close this issue.

**Comment by levBagryansky** [comment]
Ok
