### ISSUE TITLE
Failure of non-existent attributes

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#1027]
This code worked fine.

![image](https://user-images.githubusercontent.com/57731693/184124034-97d88051-2dca-476c-bba6-be4f133e200c.png)

Then I modified the code and replaced `app` with `main`. And I launched `eoc dataize app` (I know I need to have an `app` object to do it, but I was inattentive).
And, as you can see below, instead of giving me the warning about the absence of the `app` object the compiler told me something about `foo` and `bar`, which are not even present in this program anymore. I think it may be quite misleading.

![image](https://user-images.githubusercontent.com/57731693/184123999-a114285b-478d-49b6-83f5-5e0a8bc915e4.png)

**Comment by yegor256** [comment]
@OlesiaSub indeed, a misleading behavior. This happened because you didn't run

```
$ eoc clean
```

Some files remained in `.eoc` directory, already compiled. I think we need to improve `TranspileMojo`. When generating Java files it has to maintain a `Tojos` catalog of them (maybe in `target/eo/transpiled.csv`). Before the transpilation of each `.eo` file, it has to read the list of files _previously_ generated and delete them.

**Comment by yegor256** [comment]
@mximp please, help (or delegate)

**Comment by mximp** [comment]
@Karina5005 is this something you can assist with?

**Comment by Karina5005** [comment]
@mximp Do I understand correctly that when I do a transpile, I have to store the filenames in `target/eo/transpiled.csv.` The next time I want to transpile a file and it is in the `target/eo/transpiled.csv.`, that means I must first remove the java files generated from that file.

**Comment by mximp** [comment]
@Karina5005 `transpiled.csv` is supposed to contain generated Java file names per EO program (`.eo` file). When transpiling a program you first check `transpiled.csv` and remove all files listed there for this program.
And yes all newly generated files for a program you add to `transpiled.csv`

**Comment by Graur** [comment]
@mximp @Karina5005 Looks like we can close this issue

**Comment by mximp** [comment]
@OlesiaSub Can you please check & close if all fine.

**Comment by volodya-lombrozo** [comment]
I've checked examples from the issue description and it seems that we don't have that problem anymore.
Also we have implemented the required logic in #1170.
