### ISSUE TITLE
Updating list.map, list.reduce

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1031]
@Graur,
There were changed list.map, list.reduce, list.mapi, list.reduced to list.mapped, list.reduced, list.mappedi, list.reducedi. So we need to update it in this repository

**Comment by Graur** [comment]
@levBagryansky go ahead

**Comment by levBagryansky** [comment]
@Graur ok

**Comment by levBagryansky** [comment]
@Graur , how is objectionary/eo related with objectionary/collecctions? It seems that eo  repo does not see new `reduced` and `mapped`.

**Comment by Graur** [comment]
@levBagryansky `objectionary/eo` includes `objectionary/collections` as a jar library. Right now `objectionary/collections` has version `0.0.2`. So we need to wait until `objectionary/collections` will be released, and only after that we can do these changes
