### ISSUE TITLE
JUnit5 tests and their methods are 'public' -- it's unnecessary

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1035]
see https://stackoverflow.com/questions/55215949/why-junit-5-default-access-modifier-changed-to-package-private

let's make both classes and methods package-private. simply, remove the `public`.

**Comment by yegor256** [comment]
@Graur pls, take care of this

**Comment by andreoss** [comment]
There is a PMD check for that

https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#junit5testshouldbepackageprivate

**Comment by Graur** [comment]
@andreoss Indeed, thanks! 
@yegor256 Should we use this rule as mandatory? And add `JUnit5TestShouldBePackagePrivate` to [qulice pmd ruleset](https://github.com/yegor256/qulice/blob/master/qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml)

**Comment by yegor256** [comment]
@Graur @andreoss yes, definitely, let's add this to PMD and release new version of Qulice
