### ISSUE TITLE
Parse fail of comments

### ISSUE THREAD

**Issue by includealex** [objectionary/eo#1042]
Adding comments in file like this
```
+package sandbox

[a b] > test
  seq > @
    boo
  [] > boo
    div. > @
      a
      b

[args...] > app
# Commit for potted cactus
  QQ.io.stdout > @
    QQ.txt.sprintf
      "%d\n"
      test 44 11

```
will cause an error.
[Error](https://user-images.githubusercontent.com/70340829/184701125-12174371-a3c8-4d20-96d8-96839d21cc81.png)
Code without string with symbol "#" works correctly.

**Comment by andreoss** [comment]
Comments are not erased and part of the grammar.
This comment would be part of `abstraction` and should be indented.


https://github.com/objectionary/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L51

**Comment by includealex** [comment]
@andreoss If I understand you correctly, this code with indent should work
```
+package sandbox

[a b] > test
  seq > @
    boo
  [] > boo
    div. > @
      a
      b

[args...] > app
  # Commit for potted cactus
  QQ.io.stdout > @
    QQ.txt.sprintf
      "%d\n"
      test 44 11

```

But it still has the same error.

**Comment by yegor256** [comment]
@includealex comments inside objects are prohibited. The only legal place for a comment is _before_ an abstract objects:

```
# Commit for potted cactus
[args...] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "%d\n"
      test 44 11
```
