### ISSUE TITLE
BytesOf.java:34-37: Implement shift & left methods. New...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1043]
The puzzle `632-18c86a21` from #632 has to be resolved: 

https://github.com/objectionary/eo/blob/ffaa3579b37da050f31e3ae1303d9e4147b28a7d/eo-runtime/src/main/java/org/eolang/BytesOf.java#L34-L37

The puzzle was created by @rultor on 15-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please, take care of this, budget is 30. @Graur FYI

**Comment by andreoss** [comment]
@yegor256 @Graur 

1) 

`>>` & `<<` should preserve original size?
`FF-FF-FF-FF.left 8` -> `FF-FF-FF-00`
`00-FF-00-00.shift 8` -> `00-00-FF-00`

2)

`>>` & `<<` should preserve sign?

`FF-FF-00-00.shift 8` -> `FF-FF-FF-00` 
or
`FF-FF-00-00.shift 8` -> `00-FF-FF-00`
?

**Comment by yegor256** [comment]
@andreoss the first option, keep the size intact

**Comment by andreoss** [comment]
@yegor256 The current implementation is backed by `BigInteger` and will expand/shrink array
For example: 
```
jshell> BigInteger.valueOf(0xFFFFFFFFL).toByteArray()
$1 ==> byte[5] { 0, -1, -1, -1, -1 }
jshell> BigInteger.valueOf(0xFFFFFFFFL).shiftLeft(8).toByteArray()
$2 ==> byte[6] { 0, -1, -1, -1, -1, 0 } // 00-FF-FF-FF-FF-00 (byte was addded)
```

**Comment by yegor256** [comment]
@andreoss this is wrong. we must keep the size intact.

**Comment by yegor256** [comment]
@andreoss also, I think we need just one method: `shift`. It must accept either positive or negative numbers. No need to have two methods, I believe.

**Comment by 0pdd** [comment]
The puzzle `632-18c86a21` has disappeared from the source code, that's why I closed this issue.
