### ISSUE TITLE
BytesOf.java:34-37: Current shift implementation does not...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1046]
The puzzle `632-74990ab1` from #632 has to be resolved: 

https://github.com/objectionary/eo/blob/f7d8f3901dc4c2a1653bd784a145c043761e8774/eo-runtime/src/main/java/org/eolang/BytesOf.java#L34-L37

The puzzle was created by @rultor on 16-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by andreoss** [comment]
@yegor256 @Graur `shift` with sign should be by default or a separate operation?

**Comment by yegor256** [comment]
@andreoss I don't even know what is "shift with sign"... I think shift operations must not pay attention to the "sign". they just shift the bits, that's all. what the bytes will become after the shift -- we don't care.

**Comment by andreoss** [comment]
@yegor256 Java has two types of shift operators `>>` (signed) and `>>>` (un-signed). 
Right now, only the unsigned version is implemented.

**Comment by yegor256** [comment]
@andreoss I didn't know this. So, let's implement two methods: `shift` and `sshift`

**Comment by yegor256** [comment]
@andreoss it's yours. @Graur FYI

**Comment by 0pdd** [comment]
The puzzle `632-74990ab1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1142](https://github.com/objectionary/eo/issues/1142) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1183](https://github.com/objectionary/eo/issues/1183), [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185) are still not solved; solved: [#1142](https://github.com/objectionary/eo/issues/1142).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1183](https://github.com/objectionary/eo/issues/1183), [#1185](https://github.com/objectionary/eo/issues/1185) are still not solved; solved: [#1142](https://github.com/objectionary/eo/issues/1142), [#1184](https://github.com/objectionary/eo/issues/1184).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1183](https://github.com/objectionary/eo/issues/1183), [#1207](https://github.com/objectionary/eo/issues/1207) are still not solved; solved: [#1142](https://github.com/objectionary/eo/issues/1142), [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1183](https://github.com/objectionary/eo/issues/1183) is still not solved; solved: [#1142](https://github.com/objectionary/eo/issues/1142), [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185), [#1207](https://github.com/objectionary/eo/issues/1207).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#1142](https://github.com/objectionary/eo/issues/1142), [#1183](https://github.com/objectionary/eo/issues/1183), [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185), [#1207](https://github.com/objectionary/eo/issues/1207).
