### ISSUE TITLE
Can't run program with ^-symbol

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1048]
I tried to dataize this program(on the pic), but got error 

![image](https://user-images.githubusercontent.com/104271817/184899071-aa714601-eb0d-40b4-9135-9f6265fb4c8e.png)

Then, I just tried to remove `^` symbol and it's work. Is it bug?

![image](https://user-images.githubusercontent.com/104271817/184899437-69dc0432-6bc5-4847-86c3-c12b3d9d5941.png)

**Comment by Graur** [comment]
@ivan-egorov42 Looks like expected behavior to me. `^` means the nearest abstract object, so there are no `a` and `b` in `sum`.

**Comment by ivan-egorov42** [comment]
But the same example is in the paper(p.5, 2.7):

```
# A point on a 2D canvas
[x y] > point
  [to] > distance
    length. > len 
      vector
        to.x.minus (^.x)
        to.y.minus (^.y)
```

Is it correct? And why can sum see `a` and `b` if they are in other scope?

**Comment by Graur** [comment]
@yegor256 Could you tell us, please, is this description with `^` object in paper is wrong? Or maybe @ivan-egorov42 found a new bug

**Comment by yegor256** [comment]
@Graur @ivan-egorov42 the code is right:

```
[] > app
  42 > a
  [] > sum
    ^.a.plus 1 > r
  QQ.io.stdout > @
    QQ.txt.sprintf
      "sum is %d"
      sum.r
```

@ivan-egorov42 by the way, try to avoid pasting images with code samples -- it's very inconvenient, since the code can't be copied

**Comment by yegor256** [comment]
@ivan-egorov42 please, share your full program sample (in Markdown, not as a picture), and we can run it too.

**Comment by includealex** [comment]
@yegor256 I've run these two programs:
```
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

+package sandbox

[args...] > app
  20 > a
  2 > b

  [] > sum
    plus. > r
      plus.
        ^.a
        ^.b
      ^.a

  stdout > @
    sprintf
      "sum is %d\n"
      sum.r

```
and
```
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

+package sandbox

[args...] > app
  20 > a
  2 > b

  [] > sum
    plus. > r
      plus.
        a
        b
      a

  stdout > @
    sprintf
      "sum is %d\n"
      sum.r

```
(difference is only in removing symbols "^"). And they both work correctly. Should it be like that? I think, that in the second case there should be thrown an error that we are trying to apply to non-visible objects.

**Comment by ivan-egorov42** [comment]
@yegor256 @Graur 
Sorry for using images. Here is my code and it still doesn't work. I run my program with `eoc` and it crashed. Try to run it in the same way.
```
[] > get
  5 > a
  7 > b
  [] > sum
    plus. > res
      ^.a.plus ^.b
      ^.a
  QQ.io.stdout > @
    QQ.txt.sprintf
      "result is %d\n"
      sum.res
```
P.S. @includealex Now I tried to run your program with `eoc` and it fails, but it works when it is run with `sandbox`.

**Comment by yegor256** [comment]
@ivan-egorov42 try this one instead:

```
[] > get
  5 > a
  7 > b
  [] > sum
    plus. > res
      ^.a.plus (^.b)
      ^.a
  QQ.io.stdout > @
    QQ.txt.sprintf
      "result is %d\n"
      sum.res
```

This code:

```
^.a.plus ^.b
```

is understood as such:

```
(^.a.plus ^).b
```

See #614 (it's sort of a bug)

**Comment by ivan-egorov42** [comment]
@yegor256  thank you, now it works. But is it okay that we can run this program with `^` and without `^`  (like in example of _includealex_)  and it works in both cases?

**Comment by yegor256** [comment]
@ivan-egorov42 of course, `^.a` is the same as `a` as long as looking up the object tree the same `a` is found in both cases.

**Comment by ivan-egorov42** [comment]
@yegor256 OK, thank you.
