### ISSUE TITLE
rules of importing objects with identical names

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#1050]
I had this simple piece of code located in 2 files, `app.eo` and `animal.eo`. When launched, it produced string `I am alive` as a result.

![image](https://user-images.githubusercontent.com/57731693/184908439-9b3f827d-76d6-4fc2-9721-ade373ccd3ed.png)

`animal.eo` was located in folder `animals`.
![image](https://user-images.githubusercontent.com/57731693/184908761-e3e74037-6743-45df-8dc8-e9bcbb04ac70.png)

Then I added `animal_mod.eo` file to the same folder where `animal.eo` was located (I didn't delete `animal.eo`). Below are the contents of `animal_mod.eo`, as you can see, it also has an object `animal`.

![image](https://user-images.githubusercontent.com/57731693/184907366-e98e8d98-fe37-4598-a2ba-59b9f3eb8aec.png)

And here is the output I received:

![image](https://user-images.githubusercontent.com/57731693/184907846-3f1fe408-fc5d-4a2a-ad6e-c9368166f1d7.png)

Apparently, compiler decided to use the newer version of the `animal` object without giving any warnings/errors about it being duplicated.

My question is, how does the compiler decide which `animal` object to use in this case? And is this code even conceptually correct or we shouldn't do this kind of things when writing code in EO?

I guess to avoid such behaviour I should've used packages, but is there anything I could've done to make compiler use the first version of `animal` object without any modifications to source files?

**Comment by yegor256** [comment]
@OlesiaSub please, try to not paste images with the code, since it's hard to work with it -- can't copy. Instead, use Markdown.

**Comment by yegor256** [comment]
@OlesiaSub seems to be a duplicate of #1027

**Comment by yegor256** [comment]
@OlesiaSub while we are fixing #1027, you can do `eoc clean` every time you change the structure of the code and/or introduce new objects. This should help.

**Comment by OlesiaSub** [comment]
@yegor256 the reason here and in #1027 might be the same, but my questions are different.
What if I really wanted my code to look like this and have two objects with similar names?
I am asking this question because it's reslly important for the project I am currently working on, I need to know exaclty which objects are being imported, but it seems impossible in cases like this one. 
So my question is: is this code even conceptually correct or we shouldn't do this kind of things when writing code in EO?

**Comment by OlesiaSub** [comment]
If I do `eoc clean` it fails like this by the way
![image](https://user-images.githubusercontent.com/57731693/185045292-b978b4bd-6fd3-4c8a-adba-0d258786a56d.png)
So can I assume that this code is wrong?

**Comment by yegor256** [comment]
@OlesiaSub again, why do you paste images into message? :) why can't you copy the text and use Markdown? images are not convenient for readers -- we can't copy anything from them

**Comment by OlesiaSub** [comment]
@yegor256 ok, I thought it was only related to code samples.
```
$ eoc dataize app
EO objects registered in C:\Users\user\5eo\.eoc\eo-foreign.json
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.27.0:assemble (default-cli) on project eoc: Execution default-.eolang:eo-maven-plugin:0.27.0:assemble failed: org.apache.maven.plugin.MojoFailureException: Failed to execute org.eolang: Failed while trying to save to C:\Users\user\5eo\.eoc\04-pull\animal.eo: https://raw.githubusercontent.com/objectionary/630d5af2be10a76e9e0821598e5d38/objects/animal.eo -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eolang:eo-maven-plugin:0.27.0:assemble n project eoc: Execution default-cli of goal org.eolang:eo-maven-plugin:0.27.0:assemble failed: org.apache.maven.plugin.Moion: Failed to execute org.eolang.maven.PullMojo
```

I can send full log if you need as well

**Comment by yegor256** [comment]
@OlesiaSub can you post the full code here again. it's very hard to read the images you posted above.

**Comment by OlesiaSub** [comment]
animal.eo
```
[] > animal
  [] > live
    QQ.io.stdout > @
      "I am alive"
```

app.eo
```
+alias animal

[] > cat
  animal > @

[args...] > app
  cat > tom
  tom.live > @
```

animal_mod.eo
```
[] > animal
  [] > live
    QQ.io.stdout > @
      "alive!!!"

[] > animal_mod
  [] > live
    QQ.io.stdout > @
      "alive mod"
```

**Comment by yegor256** [comment]
@OlesiaSub you define two objects with the same name in the same package: `animal`. Of course, the behavior of the program is unpredictable. see #499

**Comment by OlesiaSub** [comment]
Yes, I know I should have used packages to avoid it.
I just wanted to know if it is wrong to write such code. And if it is wrong - why there were no warnings.
But as I can see from #499 it really is a bug. Thanks!
