### ISSUE TITLE
'array' must not be a data object, but only a syntax sugar

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1060]
At the moment, `array` is a data object, with special processing in `data.xsl` and everywhere. I suggest we remove this and make it a normal object, but with a syntax sugar in the syntax. This code:

```
* 1 2 3
```

Should generate the same code as this one:

```
array
.with 1
.with 2
.with 3
```

**Comment by yegor256** [comment]
@andreoss can you help? @Graur FYI

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1087](https://github.com/objectionary/eo/issues/1087), [#1088](https://github.com/objectionary/eo/issues/1088) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1087](https://github.com/objectionary/eo/issues/1087) is still not solved; solved: [#1088](https://github.com/objectionary/eo/issues/1088).

**Comment by yegor256** [comment]
@mximp can you please pick this up

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1820](https://github.com/objectionary/eo/issues/1820) is still not solved; solved: [#1087](https://github.com/objectionary/eo/issues/1087), [#1088](https://github.com/objectionary/eo/issues/1088).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#1087](https://github.com/objectionary/eo/issues/1087), [#1088](https://github.com/objectionary/eo/issues/1088), [#1820](https://github.com/objectionary/eo/issues/1820).
