### ISSUE TITLE
let's cache optimized XMIR in ~/.eo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1061]
Let's extend `OptimizeMojo` with the following: before optimizing a new XMIR `foo/abc.xmir` file it should check whether a cached result already exists in `~/.eo/optimized/75acef9/foo/abc.xmir`. Here, `75acef9` is Git hash of the .eo source being optimized. If cache exists, just take it from there. If it doesn't, do the optimization and save the cache.

**Comment by yegor256** [comment]
@mximp please, take care of this. I believe, the speed of the build will boost after this

**Comment by mximp** [comment]
@OlesiaSub please have a look.
Same approach as in #1064 can be leveraged.

**Comment by yegor256** [comment]
Duplicate of #1223
