### ISSUE TITLE
eo-maven-plugin:clean

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1063]
Let's add a new goal to our Maven plugin: `clean`. It should simply delete the directory `target/eo` (which is configurable through Maven property) and report about it in the log.

**Comment by yegor256** [comment]
@Graur please, take care of this

**Comment by Graur** [comment]
@includealex please, take this task

**Comment by Graur** [comment]
@includealex First you need to create a new Mojo, let's call it `CleanMojo`. Then pay attention to how `ResolveMojo` class store files in `target/eo` directory. Then implement in you new `CleanMojo` deleting of this directory (maybe also `UnplaceMojo` help you with this). And finally, place this new goal in `AssembleMojo`

**Comment by includealex** [comment]
@Graur sure.

**Comment by Graur** [comment]
@l3r8yJ Can you help us here?

**Comment by l3r8yJ** [comment]
@Graur yeah

**Comment by l3r8yJ** [comment]
@Graur 

```
@Mojo(
    name = "clean",
    defaultPhase = LifecyclePhase.CLEAN,
    threadSafe = true
)
public class CleanMojo extends SafeMojo {

    @Override
    void exec() throws IOException {
        try (Stream<Path> paths = Files.walk(this.targetDir.toPath())) {
            paths
                .sorted(Comparator.reverseOrder())
                .map(Path::toFile)
                .forEach(File::delete);
        }
    }
}
```
can i use try with resource in this way?

**Comment by Graur** [comment]
@l3r8yJ Sure

**Comment by l3r8yJ** [comment]
@Graur what should I write in the javadoc tag `@since x.x.x` instead of `x.x.x`?

**Comment by Graur** [comment]
@l3r8yJ The next EO version

**Comment by l3r8yJ** [comment]
@Graur 0.28.6, right?

**Comment by Graur** [comment]
@l3r8yJ Yep, `0.28.6`

**Comment by l3r8yJ** [comment]
@Graur  In `AssembleMojo` i should put my `CleanMojo` to 
```
final Moja<?>[] mojas = {
    new Moja<>(ParseMojo.class),
    new Moja<>(OptimizeMojo.class),
    new Moja<>(DiscoverMojo.class),
    new Moja<>(PullMojo.class),
    new Moja<>(ResolveMojo.class),
    new Moja<>(MarkMojo.class),
    new Moja<>(PlaceMojo.class),
    new Moja<>(CleanMojo.class), // here or we got mojo which turns on after we have built and tested? 
};
```

**Comment by Graur** [comment]
@l3r8yJ Maybe we don't need to put it in `AssembleMojo`. We can make this `CleanMojo` as optional configuration.
@yegor256 What do you think?

**Comment by yegor256** [comment]
@yegor256 @Graur `eo:clean` should be a standalone command, a very simple one, just deleting `eo/target`. It has nothing to do with other commands.

**Comment by l3r8yJ** [comment]
@yegor256 got you

**Comment by l3r8yJ** [comment]
@yegor256 @Graur do we have more separate plugin commands so I can see an example of how to make it?
