### ISSUE TITLE
rename ~/.eo/sources to ~/.eo/pulled

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1064]
Let's rename the directory, to be more in alignment with #1062 and #1061

**Comment by mximp** [comment]
@potatmen please assist with this one.

**Comment by potatmen** [comment]
@mximp I can't find in what place we trying to access `~/.eo/sources` directory, at least in `objectionary/eo` repo. Can you let me know please, where I can find files that create and use this directory in order to rename them.

**Comment by mximp** [comment]
@potatmen Please check `org.eolang.maven.OyCaching#get`

**Comment by potatmen** [comment]
@yegor256 https://github.com/objectionary/eo/pull/1100 please check this merged PR, it solves the issue

**Comment by yegor256** [comment]
@potatmen thanks!
