### ISSUE TITLE
stackoverflow?

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1067]
@Graur @EugeneDar @includealex 
Please help with determinate the error. I wrote this simple test:
```
[] > r-match-new-transitions-by-star-stack-overflow
  [list1 list2] > eq-sets
    reduced. > @
      list1
      TRUE
      [acc item]
        and. > @
          acc
          gte.
            found.
              list2
              item
            0
  eq. > @
    TRUE
    eq-sets
      list
        *
          list (* 12 2 3)
          list (* 11 0 1)
          list (* 100 1 2)
          list (* 100 3 0)
      list
        *
          list (* 11 0 1)
          list (* 12 2 3)
          list (* 100 1 2)
          list (* 100 3 0)
```
So I get this error:
["Unexpected error 'null' of type StackOverflowError; caused by "SF](https://github.com/objectionary/eo/files/9375066/error1.txt)
But when I run the test with 3 triples(not 4) it works correctly
```
[] > r-match-new-transitions-by-star-stack-overflow
  [list1 list2] > eq-sets
    reduced. > @
      list1
      TRUE
      [acc item]
        and. > @
          acc
          gte.
            found.
              list2
              item
            0
  eq. > @
    TRUE
    eq-sets
      list
        *
          list (* 12 2 3)
          list (* 11 0 1)
          list (* 100 1 2)
      list
        *
          list (* 11 0 1)
          list (* 12 2 3)
          list (* 100 1 2)
```
So now I am looking for reason, except for realy stackoverflow, why it cause the error. Please tell your ideas.

**Comment by EugeneDar** [comment]
@levBagryansky can you please simplify the test?

**Comment by levBagryansky** [comment]
@levBagryansky , 
It has already been simplified

**Comment by EugeneDar** [comment]
@levBagryansky I'm sorry, but it's still hard to read

**Comment by EugeneDar** [comment]
@levBagryansky perhaps the problem is that EOLANG is still not optimized for complex applications

**Comment by levBagryansky** [comment]
@EugeneDar ,
I created 2 objects: triple(has 3 free attributes) and eq-sets that compares content of lists without order. In `assert-that` just compare two lists with triples

**Comment by EugeneDar** [comment]
@levBagryansky you can use only one `and` attribute in `eq` method because it gains data sequence

**Comment by levBagryansky** [comment]
> @levBagryansky you can use `reduced` instead of `reducedi` in the code above

It will not simplify because reduced uses reducedi in its implementation

**Comment by EugeneDar** [comment]
@levBagryansky maybe you can try use three-element array instead of triple object

**Comment by EugeneDar** [comment]
> > @levBagryansky you can use `reduced` instead of `reducedi` in the code above
> 
> It will not simplify because reduced uses reducedi in its implementation but ok

it really doesn't improve code performance, but it does improve readability. And if I understand correctly, the question is whether StackOverflow is your bug or a problem with the language in general. Please read this https://www.yegor256.com/2022/03/29/bugs-occam-razor.html

**Comment by levBagryansky** [comment]
> > > @levBagryansky you can use `reduced` instead of `reducedi` in the code above
> > 
> > It will not simplify because reduced uses reducedi in its implementation but ok
> 
> @levBagryansky it really doesn't improve code performance, but it does improve readability. And if I understand correctly, the question is whether StackOverflow is your bug or a problem with the language in general. Please read this https://www.yegor256.com/2022/03/29/bugs-occam-razor.html

@EugeneDar , thank you, I agree with the statement. That's why a simplified the test. My goal was to simplify test but to save its complexity for computer. I think we did it.

**Comment by levBagryansky** [comment]
Seems its realy stackoverflow
