### ISSUE TITLE
eo-runtime RamTest fails

### ISSUE THREAD

**Issue by Karina5005** [objectionary/eo#1069]
I found that using `@Execution(CONCURRENT)` needs junit-platform.properties (https://stackoverflow.com/questions/50586201/parallel-test-case-execution-with-junit-5) to make it work. I didn't find such a file, so I added it. 
RumTest started to fall. It uses `@Execution(CONCURRENT)` and apparently before that the parallelism did not work and the test passed, but now it is falling sometimes.

```
[ERROR] Failures: 
[ERROR]   RamTest.writesAndReads:38 
Expected: is "hello"
     but: was "ello "
```

**Comment by yegor256** [comment]
@andreoss please, check this one. @Graur FYI

**Comment by Graur** [comment]
@yegor256 @andreoss Looks like we can close this one

**Comment by yegor256** [comment]
@Graur closing
