### ISSUE TITLE
EOsprintf.java:93-96: Current implementation supports...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1076]
The puzzle `1049-0e7c200c` from #1049 has to be resolved: 

https://github.com/objectionary/eo/blob/e7761125791271e4f0baccd512c763783ddf4e1c/eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java#L93-L96

The puzzle was created by @rultor on 22-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Graur** [comment]
closed, since `sprintf` moved to `eo-strings`: https://github.com/objectionary/eo-strings/issues/27
