### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by dours** [objectionary/eo#1077]
Translation of python code with several (say, 4) levels of structural control flow hierarchy (i.e, an `if` clause inside a double `for` loop inside a function) leads to EO code with an hierarchy of about 40 objects in my case. Java files for this EO code have too long file names (for Ubuntu 20!), so the compilation process fails. 

The easiest way to reproduce this problem is to use this EO generator:
```
print("+package org.eolang\n")

print("[] > test")
space = 0
for i in range(1, 40):
    space = (" " * (i * 2))
    print(space + "blah > @")
    print(space + "[] > blah")
print(space + "  TRUE > @")
```

**Comment by yegor256** [comment]
@mximp can we do something about this?

**Comment by mximp** [comment]
@dours Can you please provide example of Java name the parser is trying to produce?

**Comment by dours** [comment]
@mximp , yes: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project test: Compilation failure
[ERROR] /home/bogus/py2eo/runEO/target/generated-test-sources/EOorg/EOeolang/EOnested_for_break_continueTest.java:[6639,14] error while writing EOorg.EOeolang.EOnested_for_break_continueTest.EOω1apply.EOω2φ.EOω3t42$EOt1$EOa1.EOω4apply.EOω5φ.EOω6t41$EOt30$EOt1$EOa0.EOω7t4$EOt0$EOt1$EOa0.EOω8t1$EOt0$EOa1.EOω9t2$EOt0$EOt1$EOa0.EOω10t2$EOt15$EOt1$EOa0.EOω11t4$EOt0$EOt1$EOa0.EOω12t1$EOt0$EOa1.EOω13t2$EOt0$EOt1$EOa0: /home/bogus/py2eo/runEO/target/test-classes/EOorg/EOeolang/EOnested_for_break_continueTest$EOω1apply$EOω2φ$EOω3t42$EOt1$EOa1$EOω4apply$EOω5φ$EOω6t41$EOt30$EOt1$EOa0$EOω7t4$EOt0$EOt1$EOa0$EOω8t1$EOt0$EOa1$EOω9t2$EOt0$EOt1$EOa0$EOω10t2$EOt15$EOt1$EOa0$EOω11t4$EOt0$EOt1$EOa0$EOω12t1$EOt0$EOa1$EOω13t2$EOt0$EOt1$EOa0.class: File name too long
```

**Comment by dours** [comment]
@mximp Do you have an estimate on how long will it take to fix this one? Is it complicated? It currently blocks around 5 tests in the py2eo translator, I would like to know if I need to think about a workaround.

**Comment by mximp** [comment]
@dours should be finished by tomorrow

**Comment by mximp** [comment]
@dours fixed. please check & close

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.2`

**Comment by dours** [comment]
@mximp I tried 0.28.2, but still get
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project test: Compilation failure
[ERROR] /home/bogus/py2eo/runEO/target/generated-test-sources/EOorg/EOeolang/EOfor_break_continue_nestedTest.java:[6984,14] error while writing EOorg.EOeolang.EOfor_break_continue_nestedTest.EOω1ap.EOω2φ.EOω3t43$EOt1$EOa1.EOω4ap.EOω5φ.EOω6t55$EOt28$EOt1$EOa0.EOω7t4$EOt0$EOt1$EOa0.EOω8t1$EOt0$EOa1.EOω9t2$EOt0$EOt1$EOa0.EOω10t2$EOt15$EOt1$EOa0.EOω11t4$EOt0$EOt1$EOa0.EOω12t1$EOt0$EOa1.EOω13t2$EOt0$EOt1$EOa0: /home/bogus/py2eo/runEO/target/test-classes/EOorg/EOeolang/EOfor_break_continue_nestedTest$EOω1ap$EOω2φ$EOω3t43$EOt1$EOa1$EOω4ap$EOω5φ$EOω6t55$EOt28$EOt1$EOa0$EOω7t4$EOt0$EOt1$EOa0$EOω8t1$EOt0$EOa1$EOω9t2$EOt0$EOt1$EOa0$EOω10t2$EOt15$EOt1$EOa0$EOω11t4$EOt0$EOt1$EOa0$EOω12t1$EOt0$EOa1$EOω13t2$EOt0$EOt1$EOa0.class: File name too long
```
the file is [for_break_continue_nested.eo.txt](https://github.com/objectionary/eo/files/9507006/for_break_continue_nested.eo.txt)

**Comment by dours** [comment]
(and the pom is)
[pom.xml.txt](https://github.com/objectionary/eo/files/9507024/pom.xml.txt)

**Comment by mximp** [comment]
@dours can you confirm initial case from the description works fine on your machine?

Could you please also try to save the file manually:
`EOfor_break_continue_nestedTest$EOω1ap$EOω2φ$EOω3t43$EOt1$EOa1$EOω4ap$EOω5φ$EOω6t55$EOt28$EOt1$EOa0$EOω7t4$EOt0$EOt1$EOa0$EOω8t1$EOt0$EOa1$EOω9t2$EOt0$EOt1$EOa0$EOω10t2$EOt15$EOt1$EOa0$EOω11t4$EOt0$EOt1$EOa0$EOω12t1$EOt0$EOa1$EOω13t2$EOt0$EOt1$EOa0.class`
Max file length in Ubuntu is 255 chars so it must fit.

**Comment by mximp** [comment]
@dours please check

**Comment by dours** [comment]
@mximp sorry for the delay. I've made a workaround for this bug, so it currently prevents me from executing only 1 test ([for_break_continue_nested](https://github.com/objectionary/eo/files/9507006/for_break_continue_nested.eo.txt) ) . 

I can create the file manually. The initial case also passes. BUT! If add `+junit` to the .eo file of the initial case, then it fails with error 
```
[ERROR] /tmp/reproduce/target/generated-test-sources/EOorg/EOeolang/EOtestTest.java:[887,14] error while writing EOorg.EOeolang.EOtestTest.EOω1blah.EOω2blah.EOω3blah.EOω4blah.EOω5blah.EOω6blah.EOω7blah.EOω8blah.EOω9blah.EOω10blah.EOω11blah.EOω12blah.EOω13blah.EOω14blah.EOω15blah.EOω16blah.EOω17blah.EOω18blah.EOω19blah.EOω20blah.EOω21blah.EOω22blah.EOω23blah.EOω24blah.EOω25blah.EOω26blah.EOω27blah.EOω28blah.EOω29blah.EOω30blah.EOω31blah.EOω32blah.EOω33blah.EOω34blah.EOω35blah.EOω36blah.EOω37blah.EOω38blah.EOω39blah: /tmp/reproduce/target/test-classes/EOorg/EOeolang/EOtestTest$EOω1blah$EOω2blah$EOω3blah$EOω4blah$EOω5blah$EOω6blah$EOω7blah$EOω8blah$EOω9blah$EOω10blah$EOω11blah$EOω12blah$EOω13blah$EOω14blah$EOω15blah$EOω16blah$EOω17blah$EOω18blah$EOω19blah$EOω20blah$EOω21blah$EOω22blah$EOω23blah$EOω24blah$EOω25blah$EOω26blah$EOω27blah$EOω28blah$EOω29blah$EOω30blah$EOω31blah$EOω32blah$EOω33blah$EOω34blah$EOω35blah$EOω36blah$EOω37blah$EOω38blah$EOω39blah.class: File name too long
```

Checked everything with the release 0.28.2

**Comment by mximp** [comment]
When you add `+junit` another mechanism of Java code generation is enabled. It's driven by `junit.xsl` and `rename-junit-inners.xsl`.

**Comment by yegor256** [comment]
@mximp definitely, we need to fix such XSLs

**Comment by mximp** [comment]
#1249 is created.
@dours let's close this issue.

**Comment by mximp** [comment]
@dours reminder
