### ISSUE TITLE
XeListener.java:48-51: Make changes to store INT as...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1085]
The puzzle `348-e3a36069` from #348 has to be resolved: 

https://github.com/objectionary/eo/blob/301c65bcd5c561eb8acd81305acc8405ffa4f120/eo-parser/src/main/java/org/eolang/parser/XeListener.java#L48-L51

The puzzle was created by @rultor on 24-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please, fix this. @Graur FYI

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1099](https://github.com/objectionary/eo/issues/1099) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1103](https://github.com/objectionary/eo/issues/1103), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1103](https://github.com/objectionary/eo/issues/1103), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1116](https://github.com/objectionary/eo/issues/1116) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1103](https://github.com/objectionary/eo/issues/1103), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1103](https://github.com/objectionary/eo/issues/1103), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1103](https://github.com/objectionary/eo/issues/1103), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
The puzzle `348-e3a36069` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1144](https://github.com/objectionary/eo/issues/1144) is still not solved; solved: [#1099](https://github.com/objectionary/eo/issues/1099), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by Graur** [comment]
@andreoss Please, check the SolarStaff platform

**Comment by 0pdd** [comment]
@0pdd all 9 puzzles are solved here: [#1099](https://github.com/objectionary/eo/issues/1099), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1116](https://github.com/objectionary/eo/issues/1116), [#1144](https://github.com/objectionary/eo/issues/1144).
