### ISSUE TITLE
XeListener.java:52-57: Avoid using Java types in XSLT...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1086]
The puzzle `348-be1aef9e` from #348 has to be resolved: 

https://github.com/objectionary/eo/blob/301c65bcd5c561eb8acd81305acc8405ffa4f120/eo-parser/src/main/java/org/eolang/parser/XeListener.java#L52-L57

The puzzle was created by @rultor on 24-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please, fix this. @Graur FYI

**Comment by 0pdd** [comment]
The puzzle `348-be1aef9e` has disappeared from the source code, that's why I closed this issue.
