### ISSUE TITLE
_datas.xsl:36-39: Avoid duplication with a better...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1088]
The puzzle `1060-769da541` from #1060 has to be resolved: 

https://github.com/objectionary/eo/blob/a13b15c64b8827a22d4e739098b7948faa061596/eo-parser/src/main/resources/org/eolang/parser/_datas.xsl#L36-L39

The puzzle was created by @rultor on 24-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please, take this one. @Graur FYI

**Comment by 0pdd** [comment]
The puzzle `1060-769da541` has disappeared from the source code, that's why I closed this issue.
