### ISSUE TITLE
xmir-to-eo.xsl:30-33: Current bytes to string conversion...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1103]
The puzzle `1099-4eccfaec` from #1099 has to be resolved: 

https://github.com/objectionary/eo/blob/991c8250b50373b5daf01651dfd55a51bd80e170/eo-parser/src/main/resources/org/eolang/parser/xmir-to-eo.xsl#L30-L33

The puzzle was created by @rultor on 27-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp please, help

**Comment by mximp** [comment]
@Karina5005 please take a look

**Comment by Karina5005** [comment]
@mximp I have a question:
I found that all primitive types in xmir should be save as byte, but than I tried use double-qouted string after parsing it is still have type string. Am I doing something wrong?
In .eo:
`"a" > a`
In .xmir I got:
`<o base="string" data="string" name="a">a</o>`

**Comment by mximp** [comment]
@Karina5005 Is that after some changes or as it works now? What about other primitives?

**Comment by Karina5005** [comment]
@mximp As it works now. It works for bool, int, so they are saved as bytes.
The issue about save all primitives in byte is not closed yet. Maybe for string this is simply not implemented yet. But in that case, the part of this issue about double-quoted string can't be done yet.

**Comment by 0pdd** [comment]
The puzzle `1099-4eccfaec` has disappeared from the source code, that's why I closed this issue.
