### ISSUE TITLE
SnippetTest.java:69-71: Method `jdkExecutable` is...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1109]
The puzzle `1107-eeae8c2b` from #1107 has to be resolved: 

https://github.com/objectionary/eo/blob/e21f9fc226cbd44e182275dfe83ddc44af9768f2/eo-maven-plugin/src/test/java/org/eolang/maven/SnippetTest.java#L69-L71

The puzzle was created by rultor on 29-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@Graur please, resolve this. I suggest making a new class inside `src/test/java`

**Comment by Graur** [comment]
@l3r8yJ Please, help us here

**Comment by l3r8yJ** [comment]
@Graur this method is implemented in two modules, which one would be better to place the new class in `eo-runtime/src/test/java` or `eo-maven-plugin/src/test/java`?
