### ISSUE TITLE
Groovy test for XSL @id checking

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1112]
Let's create a new Groovy test in `src/test/groovy` directory. Let's configure `org.codehaus.groovy.maven:gmaven-plugin` in `pom.xml` to execute them all in this directory. This particular test will find all `.xsl` files in the entire project and make sure that `xsl:stylesheet/@id` attribute is equal to the name of the file without the `.xsl` extension.

**Comment by yegor256** [comment]
@mximp please, take care of this

**Comment by mximp** [comment]
@yegor256 why can't we do the same in plain Java unit test?

**Comment by yegor256** [comment]
@mximp which module will this unit test belong to and what will be the name of it?

**Comment by mximp** [comment]
@yegor256 It can be called `TransformValidation` and have various `@Test`'s for specific validations including this one. Why do we need another tool here?

**Comment by yegor256** [comment]
@mximp which module it will belong to? Also, it's a good practice to have exactly one test per production file: `ParseMojo -> ParseMojoTest`, etc.

**Comment by yegor256** [comment]
@mximp as a second Groovy test I would make one that would check that each `*Test.java` have a corresponding `*.java` file

**Comment by mximp** [comment]
@yegor256 I'm fine with that - it's just with Groovy you would do the same things with separate tool. The same questions will arise. JUnit tests can be used for this as well.

**Comment by yegor256** [comment]
@mximp Groovy scripts will stay in the parent module, which is of type `pom` and that's why can't have any Java code. Also, Groovy scripts will check the entire repository, not one module. That's why the best location for such tests is in Groovy scripts, I believe. Also, Groovy is much simpler than Java :)

**Comment by mximp** [comment]
@yegor256 it seems that running groovy plugin from parent module will cause some issues. The major one is that parent project is built before children (see [here](https://stackoverflow.com/questions/39027585/maven-multi-module-project-execute-parent-after-child)) hence plugin will run before children are built.
Also plugins from parent are propagated into children modules and we will need to create stubs of the plugin to disable execution in every child module.

What do you think about creating separate child module for this purpose and implement all logic there?

**Comment by yegor256** [comment]
> The major one is that parent project is built before children (see [here](https://stackoverflow.com/questions/39027585/maven-multi-module-project-execute-parent-after-child)) hence plugin will run before children are built.

@mximp why this is a problem?

**Comment by mximp** [comment]
@yegor256 it's not an issue for this particular check... But if we want to verify generated files in the future we won't be able to do this

**Comment by mximp** [comment]
@yegor256 all is done. Please close the task

**Comment by yegor256** [comment]
@mximp thanks!
