### ISSUE TITLE
xmir-to-eo.xsl:37-41: Add XST transformation to convert...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1115]
The puzzle `1110-82c0e078` from #1110 has to be resolved: 

https://github.com/objectionary/eo/blob/1966067e38151610d43df1060700d59b468ae19a/eo-parser/src/main/resources/org/eolang/parser/xmir-to-eo.xsl#L37-L41

The puzzle was created by @andreoss on 29-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please help. @Graur FYI

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1144](https://github.com/objectionary/eo/issues/1144) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `1110-82c0e078` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1144](https://github.com/objectionary/eo/issues/1144) is solved here.
