### ISSUE TITLE
_funcs.xsl:26-29: Implement eo:bytes-to-int which will...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1116]
The puzzle `1110-e2869e1b` from #1110 has to be resolved: 

https://github.com/objectionary/eo/blob/1966067e38151610d43df1060700d59b468ae19a/eo-parser/src/main/resources/org/eolang/parser/_funcs.xsl#L26-L29

The puzzle was created by @andreoss on 29-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by andreoss** [comment]
@yegor256 Ready to take this

**Comment by yegor256** [comment]
@andreoss go ahead. @Graur FYI

**Comment by 0pdd** [comment]
The puzzle `1110-e2869e1b` has disappeared from the source code, that's why I closed this issue.
