### ISSUE TITLE
ParsingTrain usage

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#1120]
I want to use ParsingTrain class in my own project to perform some transformations to my xmir files.
`.xsl` files with transformations are defined in my project.

This is where I'd like to use ParsingTrain.
```
/**
 * Creates a new xml by applying several xsl transformations to it
 *
 * @param inFilename to the input xmir file
 * @param outFilename path to the output xmir file
 */
fun transformXml(
    inFilename: String,
    outFilename: String
) {
    // transformation using ParsingTrain
}
```

Can you please help me with it?

**Comment by OlesiaSub** [comment]
@yegor256 please have a look

**Comment by mximp** [comment]
@OlesiaSub what help do you need?

**Comment by OlesiaSub** [comment]
I can't understand how to use ParsingTrain as an external dependency. How to launch it correctly, how to pass values to it, etc

But actually we've just discussed it with @yegor256 so I think he will understand my question

**Comment by yegor256** [comment]
@OlesiaSub I'll take care of this

**Comment by yegor256** [comment]
@OlesiaSub check this out, should help: https://news.eolang.org/2022-08-30-parser-external-usage.html
