### ISSUE TITLE
Implementation of EObool$EOwhile.java

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1121]
Now, object "while." returns count of iterations of the loop as a result of dataization.
I think is will be more correctly to return dataization of last iteration as a result.

So, after this change, this code will be correct:

```
[] > check
  memory 0 > temp
  assert-that > @
    while.
      temp.eq 0
      [i]
        seq > @
          temp.write 1
          229
    $.equal-to
      229
```

**Comment by Graur** [comment]
@MikhailLipanin  @yegor256 What should we return if the while condition is false from the beginning of the loop? I suggest `TRUE`

**Comment by MikhailLipanin** [comment]
May be `TRUE`, or I remember that there was a question, how to implement 'empy' (null) object, if it is done, may be we can use it

**Comment by MikhailLipanin** [comment]
I figured out, that this empty object would be only in Polystat (not in EO). So it doesn't fit. `TRUE` is a good solution

**Comment by Graur** [comment]
@MikhailLipanin short description is here https://news.eolang.org/2022-08-31-new-while-dataization-result.html
