### ISSUE TITLE
Can't dataize integer or float

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1123]
I think it's necessary to notify users of EO that we can't dataize integer or float like this:
```
[] > app
  5 > @
```
Here is output after `eoc dataize app`:
```
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.Long to java.lang.Boolean
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.eolang.Dataized.take(Dataized.java:127)
	at org.eolang.Main.run(Main.java:190)
	at org.eolang.Main.main(Main.java:98)
```
Or maybe I do smth wrong?

**Comment by yegor256** [comment]
@mximp currently, in `org.eolang.Main` we have this code:

```
        if (!new Dataized(app).take(Boolean.class)) {
            throw new IllegalStateException(
                "Runtime dataization failure"
            );
        }
```

In other words, we expect the object being dataized to become a `Boolean`. In the example above, it becomes a `Long`, that's why the exception. Let's change `Main` so that it doesn't fail, but instead print the result of dataization.

**Comment by mximp** [comment]
@Nypiaka please have a look

**Comment by mximp** [comment]
@yasamprom please assist

**Comment by Graur** [comment]
@yasamprom What's up with this issue? Do you want to continue ? I can assign it to another person either

**Comment by yasamprom** [comment]
@mximp @Graur there were problem with possible runtime error but I think it is fixed now. Check please

**Comment by yegor256** [comment]
@mximp still a bug?

**Comment by mximp** [comment]
@yegor256 Still open bug. Needed to be fixed.
