### ISSUE TITLE
List of SHEETS in ParsingTrain.java

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1124]
Now, list of XSL-transformations are 'private'.
Since many other projects use this class, it would be very helpful to add the ability to modify this list.
For example make "setter" to remove some of this SHEETS.
@yegor256 , what do you think?

**Comment by yegor256** [comment]
@MikhailLipanin what is your use case? The array you are referring to is immutable. Making it public won't give you the ability to modify it. You can reuse the "train" as explained here: https://news.eolang.org/2022-08-30-parser-external-usage.html

**Comment by MikhailLipanin** [comment]
@yegor256 , In my case, I need to split this default XSL transformations, i.e. for example I apply first 10 transformations from `ParsingTrain`, then I'm doing my own custom XSL-transformations and finally I apply other transformations from `ParsingTrain`

**Comment by yegor256** [comment]
@MikhailLipanin you should build the list of transformations from scratch. This is the only right way, as explained here: https://news.eolang.org/2022-08-30-parser-external-usage.html
