### ISSUE TITLE
Can't run program with &-symbol

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1129]
I tried to compile this simple piece of code and it fails with this [log.txt](https://github.com/objectionary/eo/files/9461508/log.txt)
```
[b] > app
  b.&.add 5 > sum
```
But code like this I can compile:
```
[b] > app
  b.add 5 > sum
```
P.S. I just wanted to get binary so it is full code.

**Comment by yegor256** [comment]
@ivan-egorov42 if the error log is reasonably small, it's better to post it right here. Otherwise, we have to download it and open -- it's annoying.

**Comment by yegor256** [comment]
@ivan-egorov42 neither `&` nor `$` may be part of an expression, they may only start it. This is the limitation of our current grammar and semantic too. It's impossible to refer to "home" or "itself" when you are outside of abstract object context.

**Comment by ivan-egorov42** [comment]
@yegor256 thanks
