### ISSUE TITLE
Codacy problem with packages with upper case characters

### ISSUE THREAD

**Issue by includealex** [objectionary/eo#1133]
If user tries to add a new file with package to some of directories in objectionary/eo, unexpected problems will be shown. For example, if it is written
```java
/**
 * EO org.eolang.io package.
 *
 * @since 0.27.0
 * @checkstyle PackageNameCheck (4 lines)
 */
package EOorg.EOeolang.EOio;
...
``` 
An error will occur:
```
Package name contains upper case characters
```
Example of such a case is [here](https://app.codacy.com/gh/objectionary/eo/pullRequest?prid=9993279).
@mximp @Graur what do you think about it?

**Comment by mximp** [comment]
@includealex who throws this error/warning? What steps do you perform?

**Comment by includealex** [comment]
@mximp  this error is thrown by Codacy Static Code Analysis in CI checks.

**Comment by mximp** [comment]
@includealex can you post a link to failed CI build.

**Comment by includealex** [comment]
@mximp sure
[link to the pull request with failing CI](https://github.com/objectionary/eo/pull/1051)

**Comment by mximp** [comment]
@yegor256 Is Codacy check something we have configured? Or it's standard Github check?
Do we pay attention to this?

**Comment by yegor256** [comment]
@mximp we don't care much about Codacy, it's not part of our build/release/merge pipelines

**Comment by mximp** [comment]
Thanks!
@includealex this can be ignored.

**Comment by includealex** [comment]
@mximp got it.
