### ISSUE TITLE
Windows build failed

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1136]
I run `mvn clean install` at `objectionary/eo` and `eo-runtime` module fails
with error:
```
[ERROR] Failures: 
[ERROR]   MainTest.jvmFullRun:68 
Expected: (a string containing "EOLANG" and a string containing "Hello, " and a string containing "?( " and a string containing "string")
     but: a string containing "Hello, " was "EOLANG Runtime 1.0-SNAPSHOT
"
```

full log:
https://pastebin.com/jGwP0vhk

**Comment by yegor256** [comment]
@Graur please, check. I'm not sure there is a bug, since GitHub Actions don't complain about Windows build

**Comment by Graur** [comment]
@MikhailLipanin Are you sure you are using clean `master` branch?

**Comment by MikhailLipanin** [comment]
@Graur Yes, right now I cloned the repository again, launched it and got this log:
https://pastebin.com/Rd72Daug

**Comment by MCJOHN974** [comment]
@Graur I have same problem in #1182. I sync my fork and then pulled before I started change the code. Changes are only in README

**Comment by MCJOHN974** [comment]
Btw we have several PRs that fails only on windows test

**Comment by Graur** [comment]
@MikhailLipanin Please, make a change your java version from 18 to 17

**Comment by MikhailLipanin** [comment]
@Graur with JDK 17, the same problem. May be I haven't change it somewhere else?
![image](https://user-images.githubusercontent.com/95661085/190629074-28a5b36c-0aad-40e9-b521-b83c6f8263ef.png)
![image](https://user-images.githubusercontent.com/95661085/190629116-98b5d2a3-e16b-4287-90d9-dc994d527fa2.png)

**Comment by Graur** [comment]
@MikhailLipanin This is your IDE java version, but what if you type: `java -version` in your terminal?

**Comment by MikhailLipanin** [comment]
@Graur My bad. Yes, changing JDK version to 17 solved the problem, thanks!
