### ISSUE TITLE
BytesOf.java:34-37: Use this class for operations on...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1142]
The puzzle `1046-b55b5a37` from #1046 has to be resolved: 

https://github.com/objectionary/eo/blob/0f785b1ad0c45729a3b2c42b289922d775d3166a/eo-runtime/src/main/java/org/eolang/BytesOf.java#L34-L37

The puzzle was created by @rultor on 03-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please, go ahead with this one. @Graur

**Comment by 0pdd** [comment]
The puzzle `1046-b55b5a37` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1183](https://github.com/objectionary/eo/issues/1183), [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1183](https://github.com/objectionary/eo/issues/1183), [#1185](https://github.com/objectionary/eo/issues/1185) are still not solved; solved: [#1184](https://github.com/objectionary/eo/issues/1184).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1183](https://github.com/objectionary/eo/issues/1183), [#1207](https://github.com/objectionary/eo/issues/1207) are still not solved; solved: [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1183](https://github.com/objectionary/eo/issues/1183) is still not solved; solved: [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185), [#1207](https://github.com/objectionary/eo/issues/1207).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#1183](https://github.com/objectionary/eo/issues/1183), [#1184](https://github.com/objectionary/eo/issues/1184), [#1185](https://github.com/objectionary/eo/issues/1185), [#1207](https://github.com/objectionary/eo/issues/1207).
