### ISSUE TITLE
xcop does not check *.xsl files

### ISSUE THREAD

**Issue by andreoss** [objectionary/eo#1143]
[xcop](https://github.com/objectionary/eo/blob/master/.github/workflows/xcop.yml) workflow does not check `*.xsl`

**Comment by yegor256** [comment]
@andreoss waiting for https://github.com/g4s8/xcop-action/issues/3

**Comment by mximp** [comment]
@yegor256 @andreoss what's up with this task?

**Comment by yegor256** [comment]
@maxonfjvipon maybe you can help

**Comment by maxonfjvipon** [comment]
@yegor256 can we close the issue or wait until [this PR](https://github.com/g4s8/xcop-action/pull/7#issuecomment-1633652761) is merged and changes in our CI is done after that?

**Comment by yegor256** [comment]
@maxonfjvipon I suggest to wait for the fix in the plugin
