### ISSUE TITLE
PacksTest.java:40-44: Test case synthetic-attributes.yaml...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1145]
The puzzle `415-3d65bb62` from #415 has to be resolved: 

https://github.com/objectionary/eo/blob/15622488f9847aa83bc9e376ef20642662ea0bab/eo-parser/src/test/java/org/eolang/parser/PacksTest.java#L40-L44

The puzzle was created by @rultor on 03-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss please, help @Graur FYI

**Comment by 0pdd** [comment]
The puzzle `415-3d65bb62` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1167](https://github.com/objectionary/eo/issues/1167) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2093](https://github.com/objectionary/eo/issues/2093) is still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2110](https://github.com/objectionary/eo/issues/2110) is still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2175](https://github.com/objectionary/eo/issues/2175).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126), [#2190](https://github.com/objectionary/eo/issues/2190) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2175](https://github.com/objectionary/eo/issues/2175).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2216](https://github.com/objectionary/eo/issues/2216) are still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190), [#2217](https://github.com/objectionary/eo/issues/2217).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2216](https://github.com/objectionary/eo/issues/2216) is still not solved; solved: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190), [#2217](https://github.com/objectionary/eo/issues/2217).

**Comment by 0pdd** [comment]
@0pdd all 11 puzzles are solved here: [#1167](https://github.com/objectionary/eo/issues/1167), [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190), [#2216](https://github.com/objectionary/eo/issues/2216), [#2217](https://github.com/objectionary/eo/issues/2217).
