### ISSUE TITLE
GMI to .dot files

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1146]

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1150](https://github.com/objectionary/eo/issues/1150) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.1`

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1150](https://github.com/objectionary/eo/issues/1150) is solved here.
