### ISSUE TITLE
protected attributes in SafeMojo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1149]
We have two `protected` attributes in `SafeMojo`. This is a mistake. We _never_ use the word `protected` in Java, unless we are absolutely forced to do this. Let's fix this.

**Comment by yegor256** [comment]
@mximp please, help

**Comment by mximp** [comment]
@yegor256 in `SafeMojo` we have not two `protected` props but much more. The suggestion is to remove them all? Or do you mean some particular props?

**Comment by yegor256** [comment]
@mximp this is my mistake. Indeed, we have many `protected` attributes. This is the design enforced by Maven. We can't change it.
