### ISSUE TITLE
New object org.eolang.rust

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1161]
Let's create a new object `org.eolang.rust`:

```
[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "Random number is %d"
      rust
        """
        use reo::universe::Universe;
        use reo::data::Data;
        use rand::rand;

        pub fn foo(uni: &mut Universe, v: u32) -> Result<u32> {
          let i = copy!(find!("org.eolang.int"));
          uni.data(i, Data::from_int(random::<i64>()))?;
          Ok(i)
        }
        """
        *
          "reo: 0.0.2"
          "rand: 0.5.5""
```

Also, let's create a new Maven goal for our plugin: `binarize`. It will extract all Rust programs from XMIRs and compile them into `.so` objects, placing them into `target/classes/eo-binaries` (they will be packaged into the JAR too).

Dataization of `rust` object will find the necessary `.so` object in classpath and execute it, passing Java implementation of `Universe` into it and our ID of the object. The implementation of `Universe` must be identical to what exists in [`reo`](https://github.com/objectionary/reo) project.

The second parameter of `rust` object is a list of Rust dependencies and their versions.

**Comment by yegor256** [comment]
@andreoss what do you think about this? Interested in starting?

**Comment by andreoss** [comment]
@yegor256 Yes, please assign.

In order to call a dynamic library from JVM there should be a java class with a method mapped to the one in binary. In your case
```
class EOrust {
    public int native foo();
}
```
So we have to know a method name, a return type, and parameter types to generate a class like that.

**Comment by yegor256** [comment]
@andreoss the Rust function will always have the same signature, of course

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1327](https://github.com/objectionary/eo/issues/1327) are still not solved.

**Comment by levBagryansky** [comment]
@yegor256 please assign me

**Comment by levBagryansky** [comment]
@yegor256 are eo objects supposed to be used inside `rust` object via universe? So we need to create `universe` on rust at some stage.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1864](https://github.com/objectionary/eo/issues/1864) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1876](https://github.com/objectionary/eo/issues/1876), [#1877](https://github.com/objectionary/eo/issues/1877) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864).

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1877](https://github.com/objectionary/eo/issues/1877), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1877](https://github.com/objectionary/eo/issues/1877), [#1901](https://github.com/objectionary/eo/issues/1901) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1900](https://github.com/objectionary/eo/issues/1900).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1877](https://github.com/objectionary/eo/issues/1877) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1964](https://github.com/objectionary/eo/issues/1964), [#1965](https://github.com/objectionary/eo/issues/1965) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1877](https://github.com/objectionary/eo/issues/1877), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1326](https://github.com/objectionary/eo/issues/1326), [#1965](https://github.com/objectionary/eo/issues/1965) are still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1877](https://github.com/objectionary/eo/issues/1877), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901), [#1964](https://github.com/objectionary/eo/issues/1964).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1326](https://github.com/objectionary/eo/issues/1326) is still not solved; solved: [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1877](https://github.com/objectionary/eo/issues/1877), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901), [#1964](https://github.com/objectionary/eo/issues/1964), [#1965](https://github.com/objectionary/eo/issues/1965).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#2032](https://github.com/objectionary/eo/issues/2032), [#2033](https://github.com/objectionary/eo/issues/2033) are still not solved; solved: [#1326](https://github.com/objectionary/eo/issues/1326), [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1877](https://github.com/objectionary/eo/issues/1877), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901), [#1964](https://github.com/objectionary/eo/issues/1964), [#1965](https://github.com/objectionary/eo/issues/1965), [#2031](https://github.com/objectionary/eo/issues/2031).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2033](https://github.com/objectionary/eo/issues/2033) is still not solved; solved: [#1326](https://github.com/objectionary/eo/issues/1326), [#1327](https://github.com/objectionary/eo/issues/1327), [#1864](https://github.com/objectionary/eo/issues/1864), [#1876](https://github.com/objectionary/eo/issues/1876), [#1877](https://github.com/objectionary/eo/issues/1877), [#1900](https://github.com/objectionary/eo/issues/1900), [#1901](https://github.com/objectionary/eo/issues/1901), [#1964](https://github.com/objectionary/eo/issues/1964), [#1965](https://github.com/objectionary/eo/issues/1965), [#2031](https://github.com/objectionary/eo/issues/2031), [#2032](https://github.com/objectionary/eo/issues/2032).

**Comment by maxonfjvipon** [comment]
@yegor256 I think this ticket can be closed since `rust` object is implemented

**Comment by yegor256** [comment]
@levBagryansky thanks!
