### ISSUE TITLE
synthetic-references.xsl:28-34: This stylesheet just...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1167]
The puzzle `1145-0cc8cffc` from #1145 has to be resolved: 

https://github.com/objectionary/eo/blob/f4945ed5e68942823cf5e96a283f53517fdecaba/eo-parser/src/main/resources/org/eolang/parser/synthetic-references.xsl#L28-L34

The puzzle was created by @rultor on 05-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss go ahead. @Graur FYI

**Comment by Graur** [comment]
@andreoss What's up with this one?

**Comment by yegor256** [comment]
@Graur let's finish this

**Comment by volodya-lombrozo** [comment]
@Graur Are you going to continue here?

**Comment by Graur** [comment]
@volodya-lombrozo I haven't even started yet. Take this one if you want

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2093](https://github.com/objectionary/eo/issues/2093) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2110](https://github.com/objectionary/eo/issues/2110) is still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2175](https://github.com/objectionary/eo/issues/2175).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126), [#2190](https://github.com/objectionary/eo/issues/2190) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2175](https://github.com/objectionary/eo/issues/2175).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2126](https://github.com/objectionary/eo/issues/2126) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2119](https://github.com/objectionary/eo/issues/2119), [#2216](https://github.com/objectionary/eo/issues/2216) are still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190), [#2217](https://github.com/objectionary/eo/issues/2217).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2216](https://github.com/objectionary/eo/issues/2216) is still not solved; solved: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190), [#2217](https://github.com/objectionary/eo/issues/2217).

**Comment by 0pdd** [comment]
@0pdd all 10 puzzles are solved here: [#2093](https://github.com/objectionary/eo/issues/2093), [#2110](https://github.com/objectionary/eo/issues/2110), [#2119](https://github.com/objectionary/eo/issues/2119), [#2120](https://github.com/objectionary/eo/issues/2120), [#2122](https://github.com/objectionary/eo/issues/2122), [#2126](https://github.com/objectionary/eo/issues/2126), [#2175](https://github.com/objectionary/eo/issues/2175), [#2190](https://github.com/objectionary/eo/issues/2190), [#2216](https://github.com/objectionary/eo/issues/2216), [#2217](https://github.com/objectionary/eo/issues/2217).
