### ISSUE TITLE
Assertion error in fibonacci\pom.xml

### ISSUE THREAD

**Issue by includealex** [objectionary/eo#1178]
When running CI, maven plugin on windows gives such an error
```bash
Running post-build script: D:\a\eo\eo\eo-maven-plugin\target\it\fibonacci\verify.groovy
Assertion failed: 

assert log.contains(it)
       |   |        |
       |   false    '6th Fibonacci number is 8'
```
example of such a failure is [here](https://github.com/objectionary/eo/runs/8193325208?check_suite_focus=true).

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by mximp** [comment]
@potatmen please take this one.

**Comment by potatmen** [comment]
@Graur sure
