### ISSUE TITLE
EObytes$EOright.java:43-46: This object can be...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1184]
The puzzle `1142-c462e1ca` from #1142 has to be resolved: 

https://github.com/objectionary/eo/blob/c8913ee47d818a32ed988e3e93890d286aade56c/eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOright.java#L43-L46

The puzzle was created by rultor on 07-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@Graur please, dispatch this one

**Comment by Graur** [comment]
@levBagryansky take this task, please

**Comment by 0pdd** [comment]
The puzzle `1142-c462e1ca` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1207](https://github.com/objectionary/eo/issues/1207) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1207](https://github.com/objectionary/eo/issues/1207) is solved here.
