### ISSUE TITLE
BytesOf.java:34-37: Bytes should be easily convertible to...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1185]
The puzzle `1142-e53246c0` from #1142 has to be resolved: 

https://github.com/objectionary/eo/blob/c8913ee47d818a32ed988e3e93890d286aade56c/eo-runtime/src/main/java/org/eolang/BytesOf.java#L34-L37

The puzzle was created by rultor on 07-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss take care of this please. @Graur FYI

**Comment by 0pdd** [comment]
The puzzle `1142-e53246c0` has disappeared from the source code, that's why I closed this issue.
