### ISSUE TITLE
Let's add a comment to .gmi files we generate in GmiMojo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1187]
We add information about the version of Maven plugin into `.java` files we generate in `TranspileMojo`. Let's do the same with `.gmi` files that we generate in `GmiMojo`. We can use a similar text in the comment.

**Comment by mximp** [comment]
@potatmen Can you please handle this?

**Comment by potatmen** [comment]
@mximp Ok

**Comment by potatmen** [comment]
@mximp Do I correctly understand that comment about Maven plugin and compilation that is in generated `.java` files looks like this:
```
/*
 * This file was auto-generated by eolang-maven-plugin
 * on 2022-09-29T23:50:24.338836+08:00. Don't edit it,
 * your changes will be discarded on the next build.
 *
 * The EO sources were compiled to XMIR on
 * 2022-09-29T15:50:11.184971Z by the compiler v.1.0-SNAPSHOT.
 */
```

**Comment by mximp** [comment]
@potatmen that's correct

**Comment by mximp** [comment]
@volodya-lombrozo please pick this up.
