### ISSUE TITLE
Remove Q and QQ from final XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1188]
At the moment, if I write this code:

```
[] > app
  QQ.io.stdout > @
    "Hello, world!\n"
```

It produces the following, after all optimizations of `OptimizeMojo`:

```
<o abstract="" line="1" name="app" original-name="app" pos="0">
   <o base=".stdout" line="2" name="@" pos="7">
      <o base=".io" line="2" pos="4">
         <o base="QQ" line="2" pos="2"/>
      </o>
      <o base="org.eolang.string" data="string" line="3" pos="4">Hello, world!\n</o>
   </o>
</o>
```

Let's create a new XSL transformation, which will remove this `QQ` base and replace it with `Q.org.eolang`.

**Comment by yegor256** [comment]
@mximp please, take care of this

**Comment by mximp** [comment]
@yegor256 What do we have `Q` in `Q.org.eolang` for?

**Comment by yegor256** [comment]
@mximp it means "root object"

**Comment by mximp** [comment]
@yegor256 this can be closed

**Comment by yegor256** [comment]
@mximp thanks!

**Comment by yegor256** [comment]
@mximp we still have `QQ` mentioned in `to-java.xsl`. I think, this should be removed.

**Comment by yegor256** [comment]
@mximp also check `add-default-package.xsl` and `unknown-names.xsl`

**Comment by mximp** [comment]
@yegor256 I believe it can be closed

**Comment by yegor256** [comment]
@mximp thanks!
