### ISSUE TITLE
New Maven goal for our plugin: ddr

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1197]
Let's add `DdrMojo` to our Maven plugin, make it use this tool: https://github.com/objectionary/ddr

**Comment by OlesiaSub** [comment]
@yegor256 maybe we shall close this issue and convert corresponding pull request to draft? DDR is now paused and I don't see the reason to keep this issue opened until work on DDR is resumed.

**Comment by Graur** [comment]
@OlesiaSub closing
