### ISSUE TITLE
Problem with nested atoms called by QQ

### ISSUE THREAD

**Issue by potatmen** [objectionary/eo#1200]
There are two same programs:
```
+package sandbox

+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > app
  stdout > @
    sprintf
      "Current PID is %d"
      20
```
and

```
+package sandbox

[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "Current PID is %d"
      20
```
In first case program compiled and runs successfully, but the second problem compiled successfully and then after running returns this error `EOorg.EOeolang.EOstringν12="Error at "EOorg.EOeolang.EOio.EOstdout#text" attribute; caused by Can't #copy() package object 'org.eolang.txt.sprintf'"SF`

The same is happening if we do like this:

```
+package sandbox

+alias org.eolang.io.stdout

[] > app
  stdout > @
    QQ.txt.sprintf
      "Current PID is %d"
      20

```

And the most interesting that this works successfully:

```
+package sandbox

+alias org.eolang.txt.sprintf

[] > app
  QQ.io.stdout > @
    sprintf
      "Current PID is %d"
      20
```

**Comment by Graur** [comment]
@mnj2kk please, help us to investigate this

**Comment by Graur** [comment]
@ivan-egorov42 please, help us to investigate this

**Comment by volodya-lombrozo** [comment]
I have the same problem with the example from the README file and version 0.28.9`. 
How to reproduce:
1. Create the `app.eo` file with the next content (from `README.md`):
```eo
[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "Hello, %s!"
      "Jeffrey"
```
2. Clean the local `.eoc` folder
```
rm -rf .eoc
```
3. Compile and run the program:
```
eoc dataize app
```

Output:
```
EO version is 0.28.9
EO objects registered in /Workspace/EOlang/.eoc/eo-foreign.json
EO version is 0.28.9
EO program assembled in /Workspace/EOlang/.eoc
EO version is 0.28.9
Java sources generated in /Workspace/EOlang/.eoc/generated-sources
EO version is 0.28.9
Java .class files compiled into /Workspace/EOlang/.eoc
EO version is 0.28.9
Executable JAR created at /Workspace/EOlang/.eoc/eoc.jar
EOorg.EOeolang.EOstringν12="Error at "EOorg.EOeolang.EOio.EOstdout#text" attribute; caused by Can't #copy() package object 'org.eolang.txt.sprintf'"SF
```

**Comment by ivan-egorov42** [comment]
@volodya-lombrozo now this problem is being solved: objectionary/eo/issues/1323. Try to use `alias` meta and etc. for now.

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo now this problem is being solved: [/issues/1323](https://github.com/objectionary/eo/issues/1323). Try to use `alias` meta and etc. for now.

Yes, with `alias` it's working fine. Thank you.

**Comment by Graur** [comment]
@ivan-egorov42 @volodya-lombrozo closing
