### ISSUE TITLE
org.eolang.cti

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1205]
Let's create a new object `org.eolang.cti` (Compile Time Instruction):

```
[] > foo
  cti > @
    2.times 2
    "warning"
    "This method is deprecated!"
[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "The result is %d\n"
      foo
```

In runtime this object doesn't do anything special, just transparently dataizes its _first_ argument. 

Then, we create a new XSL, which will be applied after all other transformations and optimizations. It will try to find all visible "paths" from all `<o>` in XMIR to the object `foo.@`. When found, it will do what the second parameter of `cti` suggests doing. In this particular case, it will add a warning to `/program/errors` collection of XMIR.

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by mximp** [comment]
@yegor256 what do you call _'all visible "paths" from all <o> in XMIR to the object foo.@'_? Does it mean that can be reached (called) during execution of a program?
What if `foo` is used in another XMIR?

**Comment by yegor256** [comment]
@mximp I'm not sure... let's think about it a bit more

**Comment by mximp** [comment]
Let's get back to this later

**Comment by volodya-lombrozo** [comment]
@yegor256 What is the purpose of the object?

**Comment by yegor256** [comment]
@volodya-lombrozo as in the example above, to highlight deprecated methods, for example

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2044](https://github.com/objectionary/eo/issues/2044) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2044](https://github.com/objectionary/eo/issues/2044) is solved here.
