### ISSUE TITLE
LatexMojo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1206]
Let's create a new `LatexMojo`, which will take `.xmir` files from `target/eo/03-optimize` and generate `.tex` files for each of them in `target/eo/latex`. Each `.tex` file should be a standalone compilable document. Also, let's generate a summary `target/eo/universe.tex`, which includes all objects.

**Comment by yegor256** [comment]
@Graur can you handle this?

**Comment by Graur** [comment]
@potatmen Can you help us here?

**Comment by potatmen** [comment]
@Graur sure

**Comment by potatmen** [comment]
@Graur I want to elaborate on this issue. So, we have many `.xmir` files inside given directory and I need to add some program which will take all files, put all generated text from them to corresponding `.tex` files right?

**Comment by Graur** [comment]
@potatmen Right, and don't forget about summary `target/eo/universe.tex` file

**Comment by potatmen** [comment]
@Graur please take a look at the resulted `.pdf` file which is successfully compiled from generated `.tex` file 
[Result.pdf](https://github.com/objectionary/eo/files/9565607/Basic_Template__1_.pdf)

**Comment by potatmen** [comment]
@Graur Now I see only one problem, it's related to page breaking. Is it important or not?

**Comment by Graur** [comment]
@potatmen Looks good to me!


> @Graur Now I see only one problem, it's related to page breaking. Is it important or not?

@potatmen Do you have a solution?

**Comment by potatmen** [comment]
@Graur well, I got one, but it's too complex for this kind of problem

**Comment by Graur** [comment]
@potatmen I think it is necessary, but maybe @yegor256 have another opinion

**Comment by potatmen** [comment]
@Graur take a look please

**Comment by potatmen** [comment]
@Graur Comments fixed

**Comment by Graur** [comment]
@yegor256 Should we add this `LatexMojo` to `AssembleMojo`? Or we can just create a configuration parameter for maven-plugin

**Comment by yegor256** [comment]
@Graur no, this is a completely standalone mojo, just like `GmiMojo`

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#2066](https://github.com/objectionary/eo/issues/2066), [#2067](https://github.com/objectionary/eo/issues/2067) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#2066](https://github.com/objectionary/eo/issues/2066), [#2089](https://github.com/objectionary/eo/issues/2089) are still not solved; solved: [#2067](https://github.com/objectionary/eo/issues/2067).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2066](https://github.com/objectionary/eo/issues/2066) is still not solved; solved: [#2067](https://github.com/objectionary/eo/issues/2067), [#2089](https://github.com/objectionary/eo/issues/2089).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#2066](https://github.com/objectionary/eo/issues/2066), [#2067](https://github.com/objectionary/eo/issues/2067), [#2089](https://github.com/objectionary/eo/issues/2089).
