### ISSUE TITLE
EObytes$EOor.java:46-49: This object is almost identical...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1207]
The puzzle `1184-826d9a05` from #1184 has to be resolved: 

https://github.com/objectionary/eo/blob/54fa4965adc43f9d48ddcdb34020f28ffbf06add/eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOor.java#L46-L49

The puzzle was created by @rultor on 11-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by andreoss** [comment]
@yegor256 Please, assign to me

**Comment by yegor256** [comment]
@andreoss go ahead

**Comment by 0pdd** [comment]
The puzzle `1184-826d9a05` has disappeared from the source code, that's why I closed this issue.
