### ISSUE TITLE
OptimizeMojo doesn't fail on errors in XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1209]
I may be wrong, but it seems that in its current version `OptimizeMojo` doesn't throw runtime errors if XMIR contains `/program/errors/error` after all optimizations. This is definitely wrong. I think it would be nice to 1) create a unit test confirming my suspicion, and 2) change the implementation of the Mojo. Let's add one more `if`, similar to the one inside `optimize()` method:

```
if (this.trackOptimizationSteps) {
  // wrap the Train in SpyTrain
}
if (this.failOnError) {
  // add one more Shift to the train, that will take
  // all existing "/program/errors/error" and print to 
  // console and then throw a runtime exception
}
```

**Comment by yegor256** [comment]
@mximp please help us here

**Comment by mximp** [comment]
@yegor256 completed

**Comment by yegor256** [comment]
@mximp thanks!
