### ISSUE TITLE
MarkMojo.java:80-83: The mojo doesn't update program...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1222]
The puzzle `1062-6d8a2439` from #1062 has to be resolved: 

https://github.com/objectionary/eo/blob/2bb6d7d2680d2e526e80f0d87a79e6a6cdedcd8d/eo-maven-plugin/src/main/java/org/eolang/maven/MarkMojo.java#L80-L83

The puzzle was created by rultor on 15-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@yegor256 any objection on the tasks?

**Comment by yegor256** [comment]
@mximp no objections, let's do it

**Comment by mximp** [comment]
@OlesiaSub Please assist with this

**Comment by OlesiaSub** [comment]
@mximp could you please give me a quick overview of what is going on in foreign catalog?
And what exactly "program version" is? I thought is it +version meta, but apparently it is something else. Maybe you can tell me where I can find an example to reproduce this issue?

**Comment by OlesiaSub** [comment]
@yegor256 can you please help, it is true that to solve this issue I'll have to add a `replace` method to `Tojo` in your lib or maybe there is another solution that I didn't think of?

**Comment by yegor256** [comment]
@OlesiaSub you can simply use `Tojo#set()` method. Why not?

**Comment by OlesiaSub** [comment]
@yegor256 as you stated: "It's illegal to use #set() to change '%s' attribute" and I need to change the `version` attribute, so it won't work, right?... or am I missing smth

**Comment by yegor256** [comment]
@OlesiaSub it's illegal to change `id` attribute

**Comment by mximp** [comment]
> @yegor256 as you stated: "It's illegal to use #set() to change '%s' attribute" and I need to change the `version` attribute, so it won't work, right?... or am I missing smth

@OlesiaSub `Tojo::set()` is used exactly for setting foreign attribute versions. Check `MarkMojo` class: actual version is set there.
