### ISSUE TITLE
Footprint doesn't care about EO version

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1226]
Right now `Footprint` only cares about the hash of Objectionary. I think we should add one more parameter to it: version of EO maven plugin. Different versions may produce different files. We should not mix them. Also, if the version is `*-SNAPSHOT` we should not cache.

Maybe we should create a factory: `Footprints`, which will create a `Footprint` according to the hash, the version, etc.

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by mximp** [comment]
@yasamprom please have a look.
I think it can be something like this:
```
// use factory
Footprint footprint = Footprints.get(String hash, String version);


class FtCached implements Footprint {
    // extend constructor
    public FtCached(String[] labels, Path main, Path cache) {
        ...
    }

    // change logic to evaluate cached path based on labels.
}
```

**Comment by volodya-lombrozo** [comment]
@yasamprom @mximp Are you going to continue here? 
If not, I can get the issue, if you don't mind.

**Comment by mximp** [comment]
@volodya-lombrozo please do.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1857](https://github.com/objectionary/eo/issues/1857) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1857](https://github.com/objectionary/eo/issues/1857) is solved here.
