### ISSUE TITLE
ParseMojo in parallel threads

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1230]
Let's make it parse in parallel threads. Total number of threads should be configured via `maxThreads` parameter.

**Comment by yegor256** [comment]
@mximp please, take care of this

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1337](https://github.com/objectionary/eo/issues/1337), [#1338](https://github.com/objectionary/eo/issues/1338) are still not solved.

**Comment by mximp** [comment]
@yegor256 this can be closed.

**Comment by yegor256** [comment]
@mximp thanks!

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1338](https://github.com/objectionary/eo/issues/1338) is still not solved; solved: [#1337](https://github.com/objectionary/eo/issues/1337).

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#1337](https://github.com/objectionary/eo/issues/1337), [#1338](https://github.com/objectionary/eo/issues/1338).
