### ISSUE TITLE
Home.java:65-67: we need to modify function. It has to...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1247]
The puzzle `1105-a0243dc5` from #1105 has to be resolved: 

https://github.com/objectionary/eo/blob/f037ce68a9f1d9e7f46ea638739c134400809555/eo-maven-plugin/src/main/java/org/eolang/maven/Home.java#L65-L67

The puzzle was created by rultor on 20-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp please, take care of this one

**Comment by mximp** [comment]
@yasamprom please assist

**Comment by yasamprom** [comment]
@yegor256 As I understand we want to change file path to avoid bad characters
We will probably do it in new class `Home`, but I found some assertions in our code, they save files and then check if it exists. Assertions fail. How should we deal with this? Should we write own `exists` function in `Home` and add path changing there? 
Or may be we can create special function `goodPath` in `Home` and use it everywhere we want to pass usual path?

**Comment by yegor256** [comment]
@yasamprom I think that `Home().exists()` is the right direction

**Comment by 0pdd** [comment]
The puzzle `1105-a0243dc5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1261](https://github.com/objectionary/eo/issues/1261) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1261](https://github.com/objectionary/eo/issues/1261) is solved here.
