### ISSUE TITLE
Home.java:155-156: We should remove this function and get...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1248]
The puzzle `1105-2b0b7358` from #1105 has to be resolved: 

https://github.com/objectionary/eo/blob/f037ce68a9f1d9e7f46ea638739c134400809555/eo-maven-plugin/src/main/java/org/eolang/maven/Home.java#L155-L156

The puzzle was created by rultor on 20-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp please, take care of this one

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1292](https://github.com/objectionary/eo/issues/1292) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1292](https://github.com/objectionary/eo/issues/1292) is solved here.
