### ISSUE TITLE
How can we distinguish eo objects in java

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1254]
@yegor256 @Graur 
For example we get two the same objects via  `rho.attr("ρ").get()`:
```
Phi phi1 = rho.attr("ρ").get()
Phi phi2 = rho.attr("ρ").get()
```
Do we have opportunity in java to understand if `phi1` and `phi2` are the same objects in eo?
Should we override `equals`  method for `Phi`?
More precisially I thonk we need smth like `==`

**Comment by yegor256** [comment]
@levBagryansky just do `phi1.hashCode() == phi2.hashCode()`
