### ISSUE TITLE
`keepBinaries` property is not respected in `UnplaceMojo`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1256]
Within `UnplaceMojo` we have config parameter `keepBinaries` which is supposed to prevent specified compiled (placed) files from removal. 
However current implementation ignore it since it calls consequently two steps:
1. `keepThem` step would remove everything but specified in `keepBinaries`
2. `killThem` step would remove everything with no respect to `keepBinaries`

Need to make `killThem` respect `keepBinaries` property.

**Comment by mximp** [comment]
@yegor256 any objection?

**Comment by mximp** [comment]
@yegor256 I believe there should be described precedence if we want to keep them both. Alternatively we might remove one of them or mandate them to be mutually exclusive.  
With current implementation `keepBinaries` has no effect at all.
For now let's correct `killThem` to be aware of `keepBinaries`

**Comment by yegor256** [comment]
@mximp `keepBinaries` will make sure that some files are staying for sure. Then, you can `killBinaries` some of files too. They don't contradict each other. Give me an example which is impossible to express with these two options.

**Comment by mximp** [comment]
@yegor256 1) what is the expected behaviour if a file is mentioned within both `keepBinaries` and `removeBinaries`?  There must be an order of application.
2) For this task I'm just saying that with current implementation `keepBinaries` doesn't work as expected. The binaries will be deleted in any case.

**Comment by yegor256** [comment]
@mximp check 17e240eb and this: https://github.com/objectionary/news.eolang.org/commit/e31dfbab22ad60b43b172a90cd614011343eea9d
