### ISSUE TITLE
Home.java:195-197: we need to modify function. It has to...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1261]
The puzzle `1247-d57a5fca` from #1247 has to be resolved: 

https://github.com/objectionary/eo/blob/3ee7426d44ddbc40104130d162f6bbfa899cfd0e/eo-maven-plugin/src/main/java/org/eolang/maven/Home.java#L195-L197

The puzzle was created by Stepa Strunkov on 22-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@Graur please, check

**Comment by Graur** [comment]
@includealex can you take this task?

**Comment by includealex** [comment]
@Graur Do I need to get rid of non-ASCII characters?

**Comment by Graur** [comment]
@includealex According to this ticket description, we need to replace non-UTF-8 characters to UTF-8 characters

**Comment by includealex** [comment]
@Graur still don't understand you. I need to encode every path that I get to UTF-8 path, right?
