### ISSUE TITLE
ANTLR version

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1265]
@yegor256 
Here is output after `eoc gmi`. Is it important to have 4.10.1 version of ANTLR? If it is, maybe need to add this to the readme?
```
EO objects registered in /home/ivan/codes/eolang/rust-transpiler/.eoc/eo-foreign.json
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.11.1
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.11.1
EO program assembled in /home/ivan/codes/eolang/rust-transpiler/.eoc
GMI files generated in /home/ivan/codes/eolang/rust-transpiler/.eoc
```

**Comment by yegor256** [comment]
@mximp please, check

**Comment by mximp** [comment]
@OlesiaSub do you think you can handle this?

**Comment by mximp** [comment]
Has the same cause as #1303

**Comment by OlesiaSub** [comment]
@ivan-egorov42 I checked this issue and opened another one with the description of the problem (#1303 ). When #1303 is solved - this warning will disappear. You can check the progress in #1303 now.

**Comment by OlesiaSub** [comment]
@ivan-egorov42 fixes. this issue can be closed

**Comment by mximp** [comment]
@ivan-egorov42 please check and close

**Comment by ivan-egorov42** [comment]
All is OK. Thanks!
