### ISSUE TITLE
We need to increase the stack size

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#1278]
A lot of tests and structures just can't be checked correctly because of StackoverFlow. We should find a way to increase stack size.

**Comment by EugeneDar** [comment]
@yegor256 @Graur what do you think?

**Comment by Graur** [comment]
@EugeneDar go ahead

**Comment by Graur** [comment]
@ivan-egorov42 Sure, you are welcome to do it

**Comment by EugeneDar** [comment]
@ivan-egorov42 thanks
