### ISSUE TITLE
SpyTrain.java:48-51: we need to implement StLambdaQuiet...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1292]
The puzzle `1248-52399106` from #1248 has to be resolved: 

https://github.com/objectionary/eo/blob/4a80878e27a1e6d41b71b4d2ab4949b741a1c51f/eo-maven-plugin/src/main/java/org/eolang/maven/SpyTrain.java#L48-L51

The puzzle was created by rultor on 30-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@Graur please, handle this

**Comment by Graur** [comment]
@ivan-egorov42 please, take care of this ticket

**Comment by MikhailLipanin** [comment]
@Graur , this ticket equals to https://github.com/yegor256/xsline/issues/40 at Xsline, I will try to implement it

**Comment by Graur** [comment]
@MikhailLipanin Sure, go ahead

**Comment by 0pdd** [comment]
The puzzle `1248-52399106` has disappeared from the source code, that's why I closed this issue.
