### ISSUE TITLE
returning of the same object changes hashCode

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1296]
@yegor256 @Graur I have a problem with returning `Phi`  from atom. Take a look at the instance:
Let there be such an object in eo:
```
[] > my-atom
  TRUE > @
  [] > self /my-atom
  [] > print-hash /bool
```
`my-atom.self`  just returns `my-atom`:
```
//EOmy_atom$EOself
...
                rho -> {
                    final Phi parent = rho.attr("ρ").get();
                    return parent;
                }
...
```
`my-atom.hash` returns prints `my-atom`'s hashcode and returns `TRUE`:
```
//EOmy_atom$EOprint_hash
...
                rho -> {
                    System.out.println("print " + rho.attr("ρ").get().hashCode());
                    return new Data.ToPhi(true);
                }
...
```
The problem is hashCodes of `my-atom` and `my-atom.self` are different:
```
[] > hash-test
  my-atom > a
  seq > @
    print-hash.
      a
    print-hash.
      self.
        a
```
shows
```
print 8
print 13
```
I think it is a bug because objects must be the same.

**Comment by yegor256** [comment]
@levBagryansky looks like a bug indeed

**Comment by mximp** [comment]
@levBagryansky can you please provide full sources for `EOmy_atom$EOself` and `EOmy_atom$EOprint_hash`

**Comment by levBagryansky** [comment]
@mximp sure, please check this one:
https://github.com/levBagryansky/eo/tree/my-atom
Ьore precisely sources for `EOmy_atom$EOself` and `EOmy_atom$EOprint_hash` are [here](https://github.com/levBagryansky/eo/tree/my-atom/eo-runtime/src/main/java/EOorg/EOeolang):

**Comment by mximp** [comment]
@levBagryansky @yegor256 @Graur 

Currently when we are retrieving attribute for an object and the attribute is not in the object itself but rather in its `φ` - then we move (i.e. change its parent) found object into current one.
So in this example:
```
[] > hash-test
  my-atom > a
  seq > @
    print-hash.
      a
    print-hash.
      self.
        a
```
the following mapping will be true:
`a.print-hash.ρ` = `my-atom`
`a.self.print-hash.ρ` = `self`.

Hence you see different hashes printed as `print-hash` uses `ρ` of itself to get hash.
