### ISSUE TITLE
different antlr versions used in the project

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#1303]
In the project's `pom.xml` file antlr has a `4.11.1` version. However, if you take a look at the `generated-sources` directory created by `TranspileMojo` -- you'll notice, that the sources are `Generated from org/eolang/parser/Program.g4 by ANTLR 4.10.1`. The version here is different. 
I believe it is the cause of #1265 and we need to fix it.
 
I don't know why this happens, but maybe the root of the problem is located in the external libraries that we use. I checked a few external libs and found that in [jcabi-parent pom](https://github.com/jcabi/jcabi-parent/blob/master/pom.xml) antlr versions are not stated everywhere, there even is a [comment](https://github.com/jcabi/jcabi-parent/blob/master/pom.xml#L959) about the runtime version. Maybe it affects the behaviour of TranspileMojo somehow?

**Comment by OlesiaSub** [comment]
@yegor256 @mximp maybe you have any ideas what might cause the antlr version in generated sources to differ from the one that is stated in the project's pom.xml?

It really doesn't affect the execution, but it throws warnings and confuses people, which is not good either. We already have two issues mentioning those warnings.

**Comment by mximp** [comment]
@OlesiaSub @yegor256 The issue is that in our parent pom we use
```

```
This version defines `<version>4.10.1</version>` for antlr4 (see https://github.com/jcabi/jcabi-parent/blob/0.62.0/pom.xml).
Hence the warning in build logs.
We need to release new version of Jacabi parent (current `master` branch contains correct ANTLR version).

**Comment by OlesiaSub** [comment]
@yegor256 @mximp pls update me when you release the fixed version and then I will update the version in EO project.

**Comment by mximp** [comment]
@yegor256 can we release `jacabi-parent`?

**Comment by yegor256** [comment]
@mximp 0.63.0 released

**Comment by mximp** [comment]
@yegor256 after https://github.com/objectionary/eo/pull/1310 is merged we need to release new version of `eo-runtime`.
One release dependency needs to be updated in `eo-maven-plugin` to eliminate the warning.

**Comment by mximp** [comment]
Waiting for `eo-runtime` release.

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.9`

**Comment by OlesiaSub** [comment]
@mximp the version is already updated in eo pom.xml, right?

**Comment by mximp** [comment]
@OlesiaSub it's updated for `jcabi-parent` in `eo-runtime`... but still not updated for references to `eo-runtime` in tests.

**Comment by mximp** [comment]
@OlesiaSub now all is up-to-date in master

**Comment by OlesiaSub** [comment]
@mximp great, thanks! can I close the issue now?

**Comment by OlesiaSub** [comment]
@mximp it did, thanks
