### ISSUE TITLE
prohibit /? for objects outside of org.eolang

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1305]
Let's prohibit `/?` syntax for objects outside of `org.eolang` package. Let's do this inside `eo-parser` with a new XSL.

**Comment by yegor256** [comment]
@mximp please, take care of this one

**Comment by mximp** [comment]
@holydrug please assist with this task.

**Comment by mximp** [comment]
@holydrug what's up with this?

**Comment by holydrug** [comment]
@mximp I could not deal with xml

**Comment by mximp** [comment]
> @mximp Can you give me advice to understanding in xsl and xml. Now I learn it with hello-world project to understand at least something. Is it okey way? May be you know some lectures, book, etc.

@holydrug check https://www.w3schools.com/xml/default.asp

**Comment by mximp** [comment]
@PickBas please assist with this

**Comment by yegor256** [comment]
@maxonfjvipon please, help with this one

**Comment by maxonfjvipon** [comment]
@yegor256 what about object `bool.if` with return type `/t`?

**Comment by yegor256** [comment]
@maxonfjvipon replace it with `/?`

**Comment by maxonfjvipon** [comment]
@yegor256 what about objects in other packages that starts or contain `org.eolang`?
We have [such](https://github.com/objectionary/eo-sys/blob/master/src/main/eo/org/eolang/sys/win32.eo) object in `eo-sys`

```
+architect yegor256@gmail.com
+home https://github.com/objectionary/eo-sys
+package org.eolang.sys
+rt jvm org.eolang:eo-sys:jar-with-dependencies:0.0.10
+version 0.0.10

# Makes a call to Win32.
#
# For example, this is how you get the ID of the current running process:
#
# ```
# QQ.sys.win32 "GetCurrentProcessId"
# ```
#
[function args...] > win32 /?
```

**Comment by yegor256** [comment]
@maxonfjvipon they should change. I think here we should return `bytes`

**Comment by maxonfjvipon** [comment]
@yegor256 what do you think about [this](https://github.com/objectionary/eo-math/blob/da0fe6ead76a18d57b5f4092a954c6eac17fdf3d/src/main/eo/org/eolang/math/number.eo#L195) one?
The original idea was: `(number x).pow y` => if `x` and `y` are `int` - the result is `int`, if at least one of them is `float` - the result is `float`

**Comment by yegor256** [comment]
@maxonfjvipon maybe we can declare it as such:

```
[x] > number
  [p] > pow /number
    ...
```
