### ISSUE TITLE
prohibit the usage of "org.eolang" package

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1306]
Let's make it impossible for custom packages to be called `org.eolang`. Our Maven plugin should fail compilation if such a package is met and it's not part of eo Maven reactor.

**Comment by yegor256** [comment]
@mximp please, take care of this one

**Comment by mximp** [comment]
@yegor256 so we want `org.eolang` to be used only within `eo-runtime`, `eo-maven-plugin` or `eo-parser` maven modules, correct?

**Comment by yegor256** [comment]
@mximp I believe, it would be better to add a new XSL checker into `eo-parser`, which will fail an object if it's package is `org.eolang`, but it's name doesn't belong to a "white list" of names: int, float, cage, memory, etc.

**Comment by mximp** [comment]
@owner-maker Please assist with this task

**Comment by mximp** [comment]
@Owner-maker what's up with this?

**Comment by Owner-maker** [comment]
> @Owner-maker what's up with this?

Hey! In progress, Was busy with work. I think I will do it within 7 days.

**Comment by mximp** [comment]
@PickBas please take this over

**Comment by yegor256** [comment]
@maxonfjvipon please, help

**Comment by maxonfjvipon** [comment]
@yegor256 what about objects in other packages which name starts with `org.eolang` like `org.eolang.math`?
