### ISSUE TITLE
Mark unplaced files during `UnplaceMojo`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1319]
Let's update `UnplaceMojo` so that it marks those `.class` files which were unplaced (removed). Marking should be done in `placed.csv` by setting attribute `uplaced` with the value of path to removed file. If all `.class` files for a dependency are removed then `unplaced` attribute should be set for a dependency `jar` entry as well.

**Comment by mximp** [comment]
@yegor256 any objections?

**Comment by yegor256** [comment]
@mximp good idea

**Comment by mximp** [comment]
@OlesiaSub please assist

**Comment by OlesiaSub** [comment]
@mximp why do we need to set path to the deleted file in `unplaced` attr if the path is already available in `id` attr? Why can't I just set `unplaced` to `true` if the file was unplaced?

**Comment by mximp** [comment]
@OlesiaSub you are right.. let's populate it with `true`

**Comment by 0pdd** [comment]
@mximp the puzzle [#1471](https://github.com/objectionary/eo/issues/1471) is still not solved.

**Comment by 0pdd** [comment]
@mximp the only puzzle [#1471](https://github.com/objectionary/eo/issues/1471) is solved here.
