### ISSUE TITLE
Make `PlaceMojo` to respect 'unplaced' attributes in 'placed.csv'

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1320]
Once #1319 is implemented, `placed.csv` will contain `uplaced` attribute which mark the removed files.
During _place_ phase let's check this attribute to decide wether the file should be re-copied: if a file in `placed.csv` and there is no `unplaced` attribute set, then there is no need to copy it again.
After placing a file `unplaced` attribute should be reset to empty value.

**Comment by mximp** [comment]
@OlesiaSub please assist with this.

**Comment by mximp** [comment]
@OlesiaSub what's up with this task?

**Comment by 0pdd** [comment]
@mximp the puzzle [#1904](https://github.com/objectionary/eo/issues/1904) is still not solved.

**Comment by 0pdd** [comment]
@mximp the only puzzle [#1904](https://github.com/objectionary/eo/issues/1904) is solved here.
