### ISSUE TITLE
`QQ` should be expanded in aliases

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1321]
In `+alias` meta we need to expand `QQ` to `org.eolang` just like we do in objects.
For example `+alias QQ.txt.sprintf` should become `+alias org.eolang.txt.sprintf`

**Comment by mximp** [comment]
@yegor256  WDT?

**Comment by yegor256** [comment]
@mximp yes, good idea

**Comment by mximp** [comment]
done
