### ISSUE TITLE
Unique hashcodes in parallel

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1322]
@yegor256 @mximp Now the test passes succesfully with `threads = 100` but failes when `threads = 1000`:
```
    @Test
    public void phiUniqueHashesInDynamic() {
        final int threads = 1000;
        final Set<Integer> hashes = ConcurrentHashMap.newKeySet();
        new Threads<>(
            threads,
            Stream.generate(
                () -> (Scalar<Integer>) () -> (new EOmutex$EOacquire(Phi.Φ)).hashCode()
            ).limit(threads).collect(Collectors.toList())
        ).forEach(hashes::add);
        MatcherAssert.assertThat(
            hashes.size(),
            Matchers.equalTo(threads)
        );
    }
```
```
[ERROR] Failures: 
[ERROR]   EOmutexTest.phiUniqueHashesInDynamic:88 
Expected: <1000>
     but: was <988>
[ERROR] Tests run: 27, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by yegor256** [comment]
@mximp please, take a look

**Comment by mximp** [comment]
@levBagryansky @yegor256 
Indeed there is one more concurrency flaw in the code of `Vertices.next()`:
```
return this.seen.computeIfAbsent(
            String.format("next:%d", this.count.addAndGet(1)),
            key -> this.seen.size() + 1
        );
```
`this.seen.size() + 1` part is not guaranteed to be executed in a thread-safe manner even for `ConcurrentHashMap` (see [specification](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-)

@yegor256 do we have a requirement for Phi hash code to be strictly sequential? Or the sequence can have gaps, for instance: 1, 5, 7, 20...?

**Comment by yegor256** [comment]
@mximp there is no promise about numbers, they can go in any particular order

**Comment by mximp** [comment]
@levBagryansky fixed. can be closed.

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.10`

**Comment by levBagryansky** [comment]
@mximp thanks
