### ISSUE TITLE
ParseMojo.java:56-57: Make number of threads used in...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1338]
The puzzle `1230-026e5a63` from #1230 has to be resolved: 

https://github.com/objectionary/eo/blob/2fd90f407b6a33a8679a8575314d9659932d968e/eo-maven-plugin/src/main/java/org/eolang/maven/ParseMojo.java#L56-L57

The puzzle was created by rultor on 14-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@holydrug please assist

**Comment by holydrug** [comment]
Should I create overloaded method to be able to pass test without parameter and create another one method with parameter?

**Comment by mximp** [comment]
@holydrug what's up with this?

**Comment by holydrug** [comment]
@mximp It's a pity but I cannot modify Mojo to be able to pass tests

**Comment by mximp** [comment]
@holydrug Could you clarify what exactly is failing?

**Comment by holydrug** [comment]
@mximp Your question made me look into the matter. Does pull request look good? [#1338 added number of threads used in thread executor within exec() method](https://github.com/objectionary/eo/pull/1369)
