### ISSUE TITLE
Home object design

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1346]
I think (but I can be wrong there) the `org.eolang.maven.Home` object contains several design problems:
____
1. Some of the methods are declared in code, but they aren't using in other modules.

Save methods:
```java
    /**
     * Saving stream.
     *
     * @param stream Input stream
     * @param path Path to file
     * @throws IOException If fails
     */
    public void save(final InputStream stream, final Path path) throws IOException {
        this.save(new InputOf(stream), path);
    }
``` 
```java
    /**
     * Saving bytes.
     *
     * @param bytes Byte array
     * @param path Path to file
     * @throws IOException If fails
     */
    public void save(final byte[] bytes, final Path path) throws IOException {
        this.save(new InputOf(bytes), path);
    }
```
Load method
```java
public Bytes load(final Path path) throws IOException {
    return new BytesOf(Files.readAllBytes(this.path(path)));
}
```
We can remove them without any problems.
___
2. The class itself and most of his methods declared as `public`, but we can restrict visibility to `package-private` without any problems. 
___
3.  Some of the methods have not so clear design.  Let’s take a look on `save` or `load` methods again. They are static methods de facto. They don’t use inner state of the object and if we add `static` modifier - nothing changes.  If we assume to use exactly `Home` object, I think, the best way would be to save or to load files using relative path of the Home object itself (not an absolute path as we do it for now).  Or if we need to use the methods with absolute paths, we can introduce a new separate object for it.

**Comment by yegor256** [comment]
@volodya-lombrozo it's better to report different problems in different tickets. Try not to mix them into one. Please, split and we'll continue.

**Comment by volodya-lombrozo** [comment]
New issues: 
1) [Home object design. Unused methods](https://github.com/objectionary/eo/issues/1350)
2) [Home object design. Visibility modifiers.](https://github.com/objectionary/eo/issues/1351)
3) [Home object design. Save method design. ](https://github.com/objectionary/eo/issues/1352)
