### ISSUE TITLE
OptimizeMojo.java:86-89: Replace creation of new `Train`...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1348]
The puzzle `1336-46427220` from #1336 has to be resolved: 

https://github.com/objectionary/eo/blob/4f975ace982571388678f4d918627b6d1eded428/eo-maven-plugin/src/main/java/org/eolang/maven/OptimizeMojo.java#L86-L89

The puzzle was created by rultor on 19-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
[#185](https://github.com/jcabi/jcabi-xml/issues/185) is closed. 
This can be proceeded.

**Comment by mximp** [comment]
@volodya-lombrozo please assist with this
