### ISSUE TITLE
Home object design. Unused methods

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1350]
The `org.eolang.maven.Home` object contains unused methods like:
```java
 /**
     * Saving stream.
     *
     * @param stream Input stream
     * @param path Path to file
     * @throws IOException If fails
     */
    public void save(final InputStream stream, final Path path) throws IOException {
        this.save(new InputOf(stream), path);
    }
``` 
and 
```java
    /**
     * Saving bytes.
     *
     * @param bytes Byte array
     * @param path Path to file
     * @throws IOException If fails
     */
    public void save(final byte[] bytes, final Path path) throws IOException {
        this.save(new InputOf(bytes), path);
    }
```
We can remove them without any problems.

**Comment by yegor256** [comment]
@volodya-lombrozo maybe it's better to start using them, where we use `Files.save`. This was/is the intention.

**Comment by yegor256** [comment]
@Graur please, take care of this

**Comment by Graur** [comment]
@includealex Please, help us here

**Comment by mximp** [comment]
@includealex please note there is quite big change for `Home` object in neighbour issue: https://github.com/objectionary/eo/pull/1367

**Comment by volodya-lombrozo** [comment]
@includealex Are you going to continue here?

**Comment by includealex** [comment]
@volodya-lombrozo no

**Comment by volodya-lombrozo** [comment]
Now we use both of the methods. The issue doesn't relevant anymore.
