### ISSUE TITLE
Home object design. Visibility modifiers.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1351]
The `org.eolang.maven.Home` object itself and most of his methods are declared as public, but we can restrict visibility to `package-private`.

**Comment by yegor256** [comment]
@volodya-lombrozo definitely a bug. @mximp please, help

**Comment by mximp** [comment]
@yegor256 @volodya-lombrozo I believe this issue relevant not only to `Home`: we have a number of public classes within `org.eolang.maven` used solely in it.
Need to fix all.

**Comment by mximp** [comment]
@volodya-lombrozo fixed.
