### ISSUE TITLE
Home object design. Save method design.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1352]
The `org.eolang.maven.Home` object contains several methods which have not so clear design.  Let’s take a look on `save` methods. They are static methods de facto. They don’t use inner state of the object and if we add static modifier - nothing changes.  If we assume to use exactly `Home` object, I think, the best way would be to save or to load files using relative path of the Home object itself (not an absolute path as we do it for now).  Or if we need to use the methods with absolute paths, we can introduce a new separate object for it.

**Comment by yegor256** [comment]
@volodya-lombrozo I agree, it's a bug. I suggest making those methods use encapsulated path for logging (for now this will be enough).

**Comment by mximp** [comment]
@yegor256 @volodya-lombrozo I believe the idea for `Home` was to encapsulate base path and make all operations relative to that path. So the behaviour is not about logging only. All `path` arguments within methods should be considered as relative to base path.

**Comment by volodya-lombrozo** [comment]
> @yegor256 @volodya-lombrozo I believe the idea for `Home` was to encapsulate base path and make all operations relative to that path. So the behaviour is not about logging only. All `path` arguments within methods should be considered as relative to base path.
+, it's exactly what I ment

**Comment by yegor256** [comment]
@mximp yes, ideally this is how it should be

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#1376](https://github.com/objectionary/eo/issues/1376), [#1377](https://github.com/objectionary/eo/issues/1377), [#1378](https://github.com/objectionary/eo/issues/1378) are still not solved.

**Comment by mximp** [comment]
@volodya-lombrozo this can be closed

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#1376](https://github.com/objectionary/eo/issues/1376), [#1378](https://github.com/objectionary/eo/issues/1378) are still not solved; solved: [#1377](https://github.com/objectionary/eo/issues/1377).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1376](https://github.com/objectionary/eo/issues/1376) is still not solved; solved: [#1377](https://github.com/objectionary/eo/issues/1377), [#1378](https://github.com/objectionary/eo/issues/1378).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 3 puzzles are solved here: [#1376](https://github.com/objectionary/eo/issues/1376), [#1377](https://github.com/objectionary/eo/issues/1377), [#1378](https://github.com/objectionary/eo/issues/1378).
