### ISSUE TITLE
`if` executes both blocks

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1355]
In this example of code `if` executes both blocks of code instead of one, so `seq` assignments both `a` and `b`. But I suppose there should be error instead of successful execution of the program.

Here is code:
```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > app
  seq > @
    TRUE > t
    FALSE > f
    if.
      eq.
        t
        f
      5 > a
      6 > b
    stdout
      sprintf
        "The a is %d\nThe b is %d\n"
        a
        b
```

And the output:
```
The a is 5
The b is 6

```

**Comment by ivan-egorov42** [comment]
@Graur @mximp please, have a look.

**Comment by mximp** [comment]
@ivan-egorov42 what error do you expect here?

**Comment by ivan-egorov42** [comment]
@mximp the `b` shouldn't be printed to console, because it shouldn't be just exist or assigned.

**Comment by mximp** [comment]
@ivan-egorov42 Attributes `a` and `b` exist regardless to dataization of previous `if`. You address attribute `a` and it can be found and equals to `5` as well as `b` can be found and evaluated to `6`.

**Comment by ivan-egorov42** [comment]
@mximp ok, I understand it. But in any other language it leads to error. It is very unintuitive behavior.
