### ISSUE TITLE
Qulice check is extremely slow

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1359]
In the project we make *qulice* static analysis by using  the next command:

```
mvn clean install -Pqulice --errors --batch-mode
```

It’s working correctly but the execution time is quite long, on my laptop it takes around 1 minute:
```
Total time:  01:21 min
```

In pipelines it takes around 2 minutes before we see some syntax mistakes:
```
Total time:  01:47 min
```
[Filed pipeline example](https://github.com/objectionary/eo/actions/runs/3296150402/jobs/5435476039#step:5:1025)

The main problem is we have to wait a quite long time before we see a some small syntax mistake. If you have 1-10 mistakes, it isn’t a big deal, but yesterday I got 90 and it turned to a problem, because I had to run the command many times.
If we will able to check syntax mistakes on early phases, we will be able fix mistakes faster during development, also we will probably reduce the waste of CPU during running of CI pipelines.

**Comment by mximp** [comment]
@volodya-lombrozo For local quick checks you can run qulice plugin separately with `mvn qulice:check`

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo For local quick checks you can run qulice plugin separately with `mvn qulice:check`.
> This must be fairly quick.

@mximp Thank you for suggestion! Also both commands give different results on the same branch. Using previousely mentioned maven command everything pass:
```
mvn clean install -Pqulice --errors --batch-mode
```

but when I'm using  `mvn qulice:check` the plugin gives me some duplicate exceptions:
```
[WARNING] Found duplicate (but equal) classes in [com.google.code.findbugs:annotations:3.0.1u2,com.google.code.findbugs:jsr305:3.0.1] :
[WARNING]   javax.annotation.CheckForNull
[WARNING]   javax.annotation.CheckForSigned
[WARNING]   javax.annotation.CheckReturnValue
[WARNING]   javax.annotation.Detainted
...
```

I think it's because we have to use some exclusions from rom our `pom.xml`:
```xml
<configuration>
        <excludes combine.children="append">
        <exclude>checkstyle:/src/site/resources/.*</exclude>
        <exclude>duplicatefinder:.*</exclude>
        </excludes>
</configuration>
```

In order to do so we can use maven profile `-Pqulice`. In other words, `mvn qulice:check -Pqulice` works for me.

**Comment by mximp** [comment]
@volodya-lombrozo can this be closed?

**Comment by volodya-lombrozo** [comment]
@mximp Don't you think, that it's better to check the code before running the tests? In that case we will consume less CPU for CI runners.

**Comment by yegor256** [comment]
@volodya-lombrozo I do this: `mvn -DskipTests -Pqulice` and it skips everything until the Qulice check

**Comment by mximp** [comment]
@volodya-lombrozo I don't think we win a lot in terms of CPU on CI. Normally it should be checked locally first.
