### ISSUE TITLE
DiscoverMojo tests are absent

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1360]
I think we have to add at least some tests for `org.eolang.maven.DiscoverMojo`. It will help with unerstanding for newcomers how `DiscoverMojo` actually works. Moreover, with tests we will able to change `DiscoverMojo` design securely.

**Comment by volodya-lombrozo** [comment]
I have some tests in my local repo

**Comment by mximp** [comment]
@volodya-lombrozo feel free to add the tests!
