### ISSUE TITLE
Common test naming rule 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1366]
I think, we have the lack of naming rule for tests. There are a lot of different tests with absolutely different namings:
```java
testSimpleParsing
```
```java
copiesSources
```
```java
testContentOfNoCacheFile
```
```java
bigSlowTest
```
```
loadBytesFromExistingFile
```
and so on.
It brings some mess to the project. Moreover it's absolutely unclear which testing rule to use for new tests:  
> @volodya-lombrozo just a small hint: it's better to name test methods as if you finish a sentence that starts with "The object under test...". In your case it would be: "The object under test execute discovery phase for eo correct programs". It's better to say "executes". But I may be wrong :) https://stackoverflow.com/questions/155436/unit-test-naming-best-practices
https://github.com/objectionary/eo/pull/1362#discussion_r1002730921

It's better to rewrite all tests according with the naming rule, suggested by @yegor256 above.

**Comment by yegor256** [comment]
@volodya-lombrozo I think it could be a pretty standalone Maven plugin: checker of test methods names using Machine Learning :) But we can start with something primitive, like checking for the presence of "s" at the end of the first word. In any case, I'm against any manual improvements of repository -- it's waste of time, since tomorrow our "cleaning" will be broken.

**Comment by volodya-lombrozo** [comment]
@yegor256 we can use the [test-naming-conventions](https://github.com/volodya-lombrozo/test-naming-conventions) plugin (I'm an author).
In order to check how it works, you can just to run the next command under the `eo/eo-maven-plugin` folder (! exactly that path, because I haven't implemented a support of maven modules yet):
```shell
mvn com.github.volodya-lombrozo:test-naming-conventions:check
```

**Comment by yegor256** [comment]
@volodya-lombrozo great, let's use it! can you add your plugin to our `pom.xml` and submit a PR?

**Comment by mximp** [comment]
@volodya-lombrozo @yegor256 Maybe we can think of writing Checkstyle check for this rule? I believe it's good to have all code style checks to be driven by Quilice. So `test-nameing-conventions` could be something more generic which provides new extension points for Checkstyle, PMD, etc. and we integrate it via Qulice configuration.
