### ISSUE TITLE
seq-tests.eo:30-33: Implement test that will check output...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1370]
The puzzle `1299-22a667db` from #1299 has to be resolved: 

https://github.com/objectionary/eo/blob/9da4040592b22e767fced89bca2d25f06947132d/eo-runtime/src/test/eo/org/eolang/seq-tests.eo#L30-L33

The puzzle was created by @rultor on 26-Oct-22. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
@Graur can i try this one?

**Comment by Graur** [comment]
@l3r8yJ Sure, go ahead

**Comment by 0pdd** [comment]
The puzzle `1299-22a667db` has disappeared from the source code, that's why I closed this issue.
