### ISSUE TITLE
CommitHash.java:30-32: It's much better to move...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1374]
The puzzle `1174-05a7b1c3` from #1174 has to be resolved: 

https://github.com/objectionary/eo/blob/a187606d59dd290fa375a4410dba6ddc0bf4a4a3/eo-maven-plugin/src/main/java/org/eolang/maven/CommitHash.java#L30-L32

The puzzle was created by volodya-lombrozo on 28-Oct-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@yegor256 I can take care of that issue
