### ISSUE TITLE
Home.java:47-48: Prohibit absolute paths in methods...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1376]
The puzzle `1352-39528ceb` from #1352 has to be resolved: 

https://github.com/objectionary/eo/blob/09faccc4fba201855269a0b61108053e460c21f3/eo-maven-plugin/src/main/java/org/eolang/maven/Home.java#L47-L48

The puzzle was created by rultor on 31-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@cosmincalinescu91 please assist with this.
