### ISSUE TITLE
AssembleMojo.java:43-47: Create `ProbeMojo` and include...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1395]
The puzzle `1323-f376339c` from #1323 has to be resolved: 

https://github.com/objectionary/eo/blob/f11eeabb70c9373128ec0d9b932b5b5564cfdca9/eo-maven-plugin/src/main/java/org/eolang/maven/AssembleMojo.java#L43-L47

The puzzle was created by rultor on 02-Nov-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@MikhailLipanin can you please assist with this puzzle.

**Comment by MikhailLipanin** [comment]
@mximp Okay, I will try

**Comment by mximp** [comment]
@MikhailLipanin what's up with this?

**Comment by 0pdd** [comment]
The puzzle `1323-f376339c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1677](https://github.com/objectionary/eo/issues/1677), [#1678](https://github.com/objectionary/eo/issues/1678), [#1679](https://github.com/objectionary/eo/issues/1679) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1677](https://github.com/objectionary/eo/issues/1677), [#1678](https://github.com/objectionary/eo/issues/1678) are still not solved; solved: [#1679](https://github.com/objectionary/eo/issues/1679).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1700](https://github.com/objectionary/eo/issues/1700) is still not solved; solved: [#1677](https://github.com/objectionary/eo/issues/1677), [#1678](https://github.com/objectionary/eo/issues/1678), [#1679](https://github.com/objectionary/eo/issues/1679).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#1677](https://github.com/objectionary/eo/issues/1677), [#1678](https://github.com/objectionary/eo/issues/1678), [#1679](https://github.com/objectionary/eo/issues/1679), [#1700](https://github.com/objectionary/eo/issues/1700).
