### ISSUE TITLE
eo-maven-plugin testing

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1396]
How does testing actually work? If I'm not mistaken when I run `mvn clean test` it executes the next stages: `register`, `assemble` and `transpile`. After that generated sources are executing by `java`, so I'm interested what part(classes) of `eo-maven-plugin` are responsible for this execution because I can't find it in a source code.

**Comment by mximp** [comment]
@ivan-egorov42 Tests are triggered by Maven Surefire Plugin. It configured within POM file. The plugin runs Junit 5 tests (which are methods marked with `@Test` annotation).

**Comment by ivan-egorov42** [comment]
@mximp thanks
