### ISSUE TITLE
ChRemote.java:37-40: We definitely have to split {@link...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1397]
The puzzle `1382-5825e083` from #1382 has to be resolved: 

https://github.com/objectionary/eo/blob/06eae1d8dc3b3fdda11427e2077c34a3c4170fa2/eo-maven-plugin/src/main/java/org/eolang/maven/ChRemote.java#L37-L40

The puzzle was created by rultor on 02-Nov-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
I can solve it

**Comment by yegor256** [comment]
@volodya-lombrozo go ahead
