### ISSUE TITLE
Comments parsing rules

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo#1398]
I found some problems with parsing comments in EO.

According to syntax, any comment on a new line should be recognized: **comment := '#' {`ANY`} `EOL`**

But in the fact, it doesn't work so. Here is example:
``` eo
# this works
  # this doesn't work
[] > comments
  # this works
# this doesn't work
  [] > parentObject
    42 > magicNumber
    # this works
    [] > childObject
      # this doesn't work
      24 > magicNumber
      # this doesn't work
      plus. > @
        # this doesn't work
        ^.magicNumber
        magicNumber
```

Comments depends on indent, due to nested structure of EO I guess. Also comments can be written only above abstraction.

**Comment by mximp** [comment]
@c71n93 according to [grammar definition](https://github.com/objectionary/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4) comments cannot be put in a random place. It can be put as part of a license or before an object. And surely it must comply with indentation of an object.

**Comment by c71n93** [comment]
@mximp I checked [grammar definition](https://github.com/objectionary/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4). If I'm parse files only using this grammar, it allows me to write comments like this:
``` eo
# this works
[] > parentObject
  # this works
  42 > magicNumber
      # this works
  [] > childObject
  # this works
    24 > magicNumber
    # this works
    plus. > @
      ^.magicNumber
      magicNumber
```

So I can write comments above any object and this comments are not sensitive to indents, as stated [here](https://github.com/objectionary/eo/blob/ec0c301594dc187b2a24963c5b4a5017375ac736/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L23-L30):

And I don't understand when comment can be recognized as a part of abstraction. Why do we need `(COMMENT EOL)*` [here](https://github.com/objectionary/eo/blob/ec0c301594dc187b2a24963c5b4a5017375ac736/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L49-L57)?

But anyway, when I compile EO programs, comments are behave wrong. I use [sandbox repo](https://github.com/objectionary/sandbox), could there be a problem with it?

**Comment by c71n93** [comment]
@mximp Also I don't understand how to build [parser](https://github.com/objectionary/eo/tree/master/eo-parser). When I cloned this repo, I found out that there are unresolved dependencies associated with the absence of generated Java files with parser. After I generated parser and put it [here](https://github.com/objectionary/eo/tree/master/eo-parser/src/main/java/org/eolang/parser), dependencies was resolved. Where can i find the generated parser that is currently in use?

**Comment by mximp** [comment]
@c71n93 once repo is cloned you can generate everything needed by running Maven from parent module:
```
mvn clean install -Pqulice --errors --batch-mode
```
It will generate all relevant files.
I can see that eo-sandbox uses quite old EO version. Please submit an issue there to upgrade EO. Also you can try locally with recent version (update POM):
```
<eolang.version>0.28.10</eolang.version>
```

**Comment by Graur** [comment]
@c71n93 please close the ticket if you don’t have any further questions
