### ISSUE TITLE
The same static fields `ATTR_HASH`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1418]
We have two identical fields in two separate classes:
`PlaceMojo.java`:
```java
    /**
     * Attr in CSV.
     */
    public static final String ATTR_HASH = "hash";
```
and
`AssembleMojo.java`:
```java
    /**
     * Tojo ATTR.
     */
    public static final String ATTR_HASH = "hash";
```

They both are using in different scenarios. Is there any intention in such a division?

**Comment by yegor256** [comment]
@volodya-lombrozo they are for different `.csv` files. I think it's worth adding an explanation.

**Comment by mximp** [comment]
@volodya-lombrozo done, please close
