### ISSUE TITLE
`OyRemote` test absent

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1419]
The test for `OyRemote` class absents. It's hard to understand how it works.

**Comment by volodya-lombrozo** [comment]
@mximp I see several options here:
1) Mock the connection somehow
2) Make a real http request, but disable test if URL isn't available 

Extending JavaDoc can be a good addition.  During reading the code I was interested in URL that we compile in that code:
```java
  @Override
    public Input get(final String name) throws MalformedURLException {
        final URL url = new URL(
            String.format(this.template, name.replace(".", "/"))
        );
        Logger.debug(
            this, "The object '%s' will be pulled from %s...",
            name, url
        );
        return new InputOf(url);
    }
```
Also it's hard to understand from the code - what is the `name` and it's possible values.

**Comment by mximp** [comment]
@volodya-lombrozo done!
