### ISSUE TITLE
add option `timeout` file compilation in pom.xml 

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#1423]
The idea is that files for which the limit was exceeded fell with a timeout exception instead of an infinite wait. Something like this setting, name, time units and log message of course at your choice.

`pom.xml:`
```xml
<configuration>
  ...
  <failOnError>false</failOnErrror>
  <timeout>60</timeout>                   <-------- the option
  ...
</configuration>
```

It is important that when the `failOnError=false`, compilation is skipped with `warning` for a specific file, and the rest continue to compile. Output log example:

```java
[INFO] Generated 1 .java file(s) from ./target/06-transpile/c2eo/coperators/post-inc-float32.xmir to ./target/generated-sources
[INFO] Generated 1 .java file(s) from ./target/06-transpile/c2eo/coperators/lte.xmir to ./target/generated-sources
...
[WARNING] Compilation was skipped due to failOnError=false.  ./target/06-transpile/c2eo/coperators/stress.xmir with error: File compilation timeout
...
[INFO] Generated 1 .java file(s) from ./target/06-transpile/c2eo/coperators/post-inc-uint32.xmir to ./target/generated-sources
```

**Comment by IngeniariusSoftware** [comment]
@yegor256, done

**Comment by Graur** [comment]
@IngeniariusSoftware @yegor256  Can we close it?

**Comment by IngeniariusSoftware** [comment]
@Graur I meant that I created the issue that yegor asked for)

**Comment by yegor256** [comment]
@volodya-lombrozo let's try to implement this
