### ISSUE TITLE
global cache is not used by all Mojos, that's why slow compilation

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1426]
The code in attachments compiles around ~50min. It's important to understand where we have a bottleneck and why the compilation process takes so long time. Code:
[stress_eo_example.zip](https://github.com/objectionary/eo/files/9968863/stress_eo_example.zip)

The approximate number of `xmir` and `java` files:
```
Transpiled 164 XMIRs, created 533 Java files in ./target/generated-sources
```
Profiling results of compilation:
1) for first 10 minutes: [eo_stress_on_cpu.html.zip](https://github.com/objectionary/eo/files/9968876/eo_stress_on_cpu.html.zip)
2) for all 40 minutes of compilation: [eo_stress_on_cpu_40_min.html.zip](https://github.com/objectionary/eo/files/9968880/eo_stress_on_cpu_40_min.html.zip).
___
Also I've noticed that we almost don't use parallelism and during compilation CPU utilisation per core was %30-50, and we used ~4 CPU in parallel  (even if the system has more). But it has to be proved.

**Comment by mximp** [comment]
@volodya-lombrozo do you also have build log for 40 minutes compilation?

**Comment by volodya-lombrozo** [comment]
@mximp Yes. Here is it:
[long_compilation.log](https://github.com/objectionary/eo/files/9969321/long_compilation.log)
Also I wanted to notice that the next step spent most of time during transpilation step, from the logs:
```
[INFO] Generated 208 .java file(s) from ./target/06-transpile/c2eo/src/csmith-tests/1.xmir to ./target/generated-sources
```

**Comment by mximp** [comment]
@volodya-lombrozo There is compilation error within the log you've attached. Is there a successful build?

**Comment by volodya-lombrozo** [comment]
@mximp No, I don have it and I haven't tried anymore - it takes a lot of time.

**Comment by mximp** [comment]
@volodya-lombrozo Do I get it right you didn't manage to get the example to build successfully?

**Comment by volodya-lombrozo** [comment]
@mximp Yes

**Comment by mximp** [comment]
I also wonder if we can add timestamps into the logs.. It would allow get performance statistics by analysing the log.

**Comment by volodya-lombrozo** [comment]
@mximp It would be perfect. Actually we can use a lot of tools and approaches to investigate the problem more detailed. I can do it, if you will assign the issue to me :)

**Comment by yegor256** [comment]
@mximp @volodya-lombrozo I suggest to finish the implementation of parallelism in `OptimizeMojo`  and `TranspileMojo`. After that, continue with this task.

**Comment by Graur** [comment]
@volodya-lombrozo Still an issue?

**Comment by volodya-lombrozo** [comment]
@Graur It is broad issue and as I understand it still exists.

**Comment by Graur** [comment]
@volodya-lombrozo Got it, thanks!

**Comment by qlexl** [comment]
@maxonfjvipon, please assign me

**Comment by maxonfjvipon** [comment]
@qlexl sure, go ahead!

**Comment by yegor256** [comment]
@maxonfjvipon it's yours. Let's fix our global cache once and for all.

**Comment by maxonfjvipon** [comment]
@yegor256 can we close this one?

**Comment by yegor256** [comment]
@maxonfjvipon @volodya-lombrozo yes, this one is resolved
