### ISSUE TITLE
OptimizeMojoTest.java:140-143: Implement caching for...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1431]
The puzzle `1223-c08eee6b` from #1223 has to be resolved: 

https://github.com/objectionary/eo/blob/f3a875d7b385081c926978d98ab1ee23d3117910/eo-maven-plugin/src/test/java/org/eolang/maven/OptimizeMojoTest.java#L140-L143

The puzzle was created by rultor on 09-Nov-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@yegor256 assign to me, please

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1442](https://github.com/objectionary/eo/issues/1442), [#1443](https://github.com/objectionary/eo/issues/1443) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1442](https://github.com/objectionary/eo/issues/1442), [#1443](https://github.com/objectionary/eo/issues/1443).
