### ISSUE TITLE
Cannot compile a file with a name starting with "." on ubuntu 20

### ISSUE THREAD

**Issue by dours** [objectionary/eo#1434]
For example, trying to `mvn clean test` a file called `.empty.eo` with contents
```
+package org.eolang

[] > nothing
```
leads to
`Failed while trying to save to /empty.xmir: /empty.xmir (Permission denied)`

**Comment by mximp** [comment]
@dours '.' (dot) has special meaning and there is logic within EO build process which manipulates source files names. 
Is there a particular reason to use dot in sources' name?

**Comment by yegor256** [comment]
@dours I believe, a similar error would happen if you try to use `javac` with a file named this way

**Comment by yegor256** [comment]
@mximp let's add a check into `RegisterMojo`, to validate the names of files. If a file name doesn't match `^[a+zA-Z0-9-]+\.eo$ -- we throw an exception. Let's also add `strictFileNames` parameter to the Mojo (with default to `true`). If it's set to `false`, all file names are accepted.

**Comment by mximp** [comment]
> Let's also add `strictFileNames`parameter to the Mojo (with default to`true`). If it's set to `false`, all file names are accepted.

@yegor256 what is the expected behaviour if it's set to `false` and file name is incorrect? Build will fail anyway.
Do we really need to allow skipping the validation?

**Comment by yegor256** [comment]
@mximp yes, if it's set to `false` and the name is incorrect, we let our parsing fail later. It's better to have this flag for backward compatibility.
