### ISSUE TITLE
OptCached.java:40-43: Unit test are required. We have to...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1442]
The puzzle `1431-4de3d363` from #1431 has to be resolved: 

https://github.com/objectionary/eo/blob/1d30f508c22c72d6b4fc0ef1a13c6c3abf97eaf9/eo-maven-plugin/src/main/java/org/eolang/maven/optimization/OptCached.java#L40-L43

The puzzle was created by rultor on 11-Nov-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
Working on that issue
