### ISSUE TITLE
What is `GMI`?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1448]
Guys, I can't find a proper information about `.gmi` format.  As far as I understand, it somehow connected with graphs, but I don't see any docs about the format itself and how we can use it.
- Is it [dot](https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29) notation?
- Where can we use the format?

**Comment by yegor256** [comment]
@volodya-lombrozo I refactored this part and now it's called SODG, see the JavaDoc at `SodgMojo`. If you have additional questions, please open a new ticket.
