### ISSUE TITLE
Space inside locator must be prohibited

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1468]
This syntax is invalid (because of the space), but it does parse well (I'm adding a file to `eo-parser/src/test/resources/org/eolang/parser/typos` to check):

```
[] > hello
  a. b > x
```

Let's make sure spaces are not allowed inside locators.

**Comment by Graur** [comment]
@EugeneDar Can you help us here?

**Comment by EugeneDar** [comment]
@volodya-lombrozo you can take it.

**Comment by maxonfjvipon** [comment]
@yegor256 it seems the code in the issue is valid. It's the same as: `if. TRUE 1 2`. I believe we should allow it.
But I think this should not be valid: `a. b. c`. WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon you are right
