### ISSUE TITLE
Empty lines inside object body must be prohibited

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1469]
This syntax is invalid (because of the empty line inside object body), but it does parse well (I'm adding a file to `eo-parser/src/test/resources/org/eolang/parser/typos` to check):

```
[] > hello
  one
  two

  three
```

Let's make sure empty lines are not allowed inside object body.

**Comment by Graur** [comment]
@EugeneDar Maybe you can help?

**Comment by EugeneDar** [comment]
@Graur Sure, I'll try to help.

**Comment by Graur** [comment]
@maxonfjvipon can you help us with this one?

**Comment by maxonfjvipon** [comment]
@yegor256 why the code that you gave as an example is invalid? What's wrong with empty line between objects?

**Comment by yegor256** [comment]
@maxonfjvipon every object formation must be "solid", containing no empty lines inside
