### ISSUE TITLE
UnplaceMojo.java:125-126: If all .class files for a...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1471]
The puzzle `1319-d1162eae` from #1319 has to be resolved: 

https://github.com/objectionary/eo/blob/0fc0a8b0bc77c2401e163ccbb18ba4a16a4ba363/eo-maven-plugin/src/main/java/org/eolang/maven/UnplaceMojo.java#L125-L126

The puzzle was created by rultor on 18-Nov-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@OlesiaSub Could you please assist with this as well

**Comment by mximp** [comment]
@OlesiaSub any progress with this?
