### ISSUE TITLE
What is the "vertex"?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1480]
I've faced with the next expression:
```eo
"Hello".<.eq ("Hello".<)
```
I don't understand what is "<" or "VERTEX" (from syntax). There is no information about that operation. Moreover, I haven't found anything about vertex in that [article](https://arxiv.org/pdf/2206.02585.pdf).

**Comment by mximp** [comment]
@volodya-lombrozo From [main paper](https://arxiv.org/pdf/2111.13384.pdf):

> 2.12 Object Identity
> Each object has a special attribute < , which is an integer
> refering to a unique identifier of an object in the entire runtime scope of a program. All of the following expressions
> are true:
> ```
> 109 TRUE.<.eq (TRUE.<)
> 110 42.<.eq (42.<)
> 111 point.<.eq (point.<)
> ```
> All of the following expressions are false:
> ```
> 112 42.<.eq (7.<)
> 113 (2.plus 2).<.eq (4.<)
> 114 (point 3 5).<.eq ((point 3 5).<)
> 115 (* 1 2).<.eq ((* 1 2).<)
> ```

**Comment by volodya-lombrozo** [comment]
@mximp Oh, it's clear now. Thank you. I've missed that.
