### ISSUE TITLE
`UnplaceMojoTest` uses Java 11 functionality

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1481]
`UnplaceMojoTest`  uses the next statement several times `Files.readString(placed)`. The `Files.readString()` function was added to Java only from 11 version. Since we aim to work with Java 8+, it could be a problem.  From README:
> You will need [Maven 3.3+](https://maven.apache.org/) and Java 8+ installed.

Moreover I got some build exceptions related to that statements in my local environment.

**Comment by Graur** [comment]
@yegor256 @mximp @volodya-lombrozo I don't mind

**Comment by yegor256** [comment]
@volodya-lombrozo I don't mind. let's officially migrate to Java 11 and update README and all GitHub Action and Rultor configs

**Comment by yegor256** [comment]
@volodya-lombrozo I fixed this in #1448
