### ISSUE TITLE
PDD. Default duration of a puzzle

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1486]
I've got an important [comment](https://github.com/objectionary/eo/pull/1483#discussion_r1031568359) from @mximp that we create all puzzles within 30 min interval. It's true in most cases. But we have several places where I've already put 90 min ~~because I'm a realist :)~~ because linter allows me to do so. AFAIK we have the interval in [30:90] min. 
If no one is against that all puzzles should be 30 min then we have to adjust linter first of all and then, I'll fix all puzzles with 90 min.

**Comment by volodya-lombrozo** [comment]
@yegor256 @Graur what do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo I think 90min is fine, sometimes it happens

**Comment by yegor256** [comment]
@mximp yes, indeed, if you put 90mins there, it means that the task is much more complex and will require more time to _decompose_ itself, not to implement. All implementations are 30 mins.
