### ISSUE TITLE
1e-5 float parsing

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1487]
@Graur @EugeneDar I think it would be useful to have an opportunity to code floats via this format: `1e-15 > value`. It can improve readability in eo-math. Now this style fails with error 
`[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.28.11:assemble (compile) on project eo-math: Execution compile of goal org.eolang:eo-maven-plugin:0.28.11:assemble failed: Failed to parse /home/tardis3/eo-math/src/main/eo/org/eolang/math/number.eo: java.lang.IllegalArgumentException: Failed to parse /home/tardis3/eo-math/src/main/eo/org/eolang/math/number.eo: [379:13] extraneous input 'e-15' expecting EOL: "            1e-15" -> [Help 1]
`

**Comment by Graur** [comment]
@levBagryansky Looks like we already support similar structure in our parser: https://github.com/objectionary/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L291-L292

Should work. Your example is not float. Try  `1.0e-15`.If it fail too, we must fix it.

**Comment by levBagryansky** [comment]
@Graur Indeed this format works correctly. But 1e1 and does not return `int`

**Comment by Graur** [comment]
@levBagryansky I believe in such cases we need to use `float` instead. But maybe someone else have different opinion

**Comment by levBagryansky** [comment]
@Graur Ok, thanks!
