### ISSUE TITLE
FakeMaven.java:117-119: The method withEoForeign() has to...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1489]
The puzzle `1479-03b130b4` from #1479 has to be resolved: 

https://github.com/objectionary/eo/blob/353dffcf114989b22056d7b0cf489f182d6a3180/eo-maven-plugin/src/test/java/org/eolang/maven/FakeMaven.java#L117-L119

The puzzle was created by rultor on 24-Nov-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@Graur assign to me, pls

**Comment by Graur** [comment]
@volodya-lombrozo Sure, go ahead
