### ISSUE TITLE
Syntax.java:85-90: The {@link org.eolang.parser.Syntax}...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1490]
The puzzle `485-f1fd9ef1` from #485 has to be resolved: 

https://github.com/objectionary/eo/blob/f421072d5232c3f8dd93122f6870b4fd34adb960/eo-parser/src/main/java/org/eolang/parser/Syntax.java#L85-L90

The puzzle was created by rultor on 25-Nov-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@volodya-lombrozo please, continue here. I believe that we should use Xembly instructions inside `XeListener` in order to inject `<errors><error severity="warning">` element into the XMIR in case of redundant brackets. We can do this with the help of `PUSH` and `POP` Xembly instructions.

**Comment by volodya-lombrozo** [comment]
@yegor256 Your comment isn't related to the current puzzle. I've added the new [issue](https://github.com/objectionary/eo/issues/1493) for that.
