### ISSUE TITLE
Redundant Brackets. Add warnings to `XMIR` errors section.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1493]
Add warnings about redundant brackets to `XMIR` errors section.

> @volodya-lombrozo please, continue here. I believe that we should use Xembly instructions inside XeListener in order to inject `<errors><error severity="warning">` element into the XMIR in case of redundant brackets. We can do this with the help of `PUSH` and `POP` Xembly instructions.

The issue comes from that [comment](https://github.com/objectionary/eo/issues/1490#issuecomment-1327157473).

**Comment by yegor256** [comment]
@volodya-lombrozo go ahead
