### ISSUE TITLE
Use `FakeMaven` inside `OptimizeMojo` tests

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1494]
I think it's important to continue with tests refactoring of `eo-maven-plugin`. The next step would be refactoring of the `OptimzeMojoTest` class. To do so we have to apply our new object `FakeMaven`.

**Comment by volodya-lombrozo** [comment]
Assign to me

**Comment by volodya-lombrozo** [comment]
@yegor256 I believe it's a mistake to create something with "perfect design". We don't have enough information about the future class usage before we actually try to apply it in real life. It's better to go step by step and improve `FakeMojo` in each that step. The current issue it's a just a next small step. I'm not only going to apply `FakeMaven` for the `OptimizeMojo`, I'll have a chance to improve `FakeMaven` itself.
___
Moreover, other issues related to the `FakeMaven` are finished and we can continue with that issue.

**Comment by volodya-lombrozo** [comment]
@yegor256 assign to me

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1514](https://github.com/objectionary/eo/issues/1514) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#1514](https://github.com/objectionary/eo/issues/1514) is solved here.
