### ISSUE TITLE
bool.while doesn't return the last body, but dataizes it and returns data

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1502]
This is wrong. This is how `write` should work:

<img width="237" alt="Screen Shot 2022-11-29 at 11 50 07 AM" src="https://user-images.githubusercontent.com/526301/204482561-1c9e9990-b0cb-416d-b2af-113858bae650.png">

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1505](https://github.com/objectionary/eo/issues/1505) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1505](https://github.com/objectionary/eo/issues/1505) is solved here.
