### ISSUE TITLE
vararg must not be allowed in the middle of attributes

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1511]
This code, if I create a new file `eo-parser/src/test/resources/org/eolang/parser/typos/varargs-inside.yaml`, fail the `TyposTest`:

```
line: 1
eo: |
  [a b... c] > hello
    "hello"
```

This syntax is not valid and our `Program.g4` must catch it. Vararg may only be the last attribute.

**Comment by yegor256** [comment]
@Graur please, take a look

**Comment by Graur** [comment]
@includealex Please, help us here

**Comment by yegor256** [comment]
@Graur what's up with this?

**Comment by Graur** [comment]
@yegor256 Indeed, this issue is stuck. I will take care of it

**Comment by Graur** [comment]
@yegor256 Is this code valid ? 

```
"foo" > x...
```
