### ISSUE TITLE
Test API. Add simple methods for each mojo execution.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1518]
Now we execute `ParseMojo` and `OptimizeMojo` using the next commands:

```java
//ParseMojoTest.java
.execute(ParseMojo.class)
...
//OptimizeMojoTest.java
.execute(ParseMojo.class)
.execute(OptimizeMojo.class)
``` 

I suggest to create a separate methods that will encapsulate that calls like `.parse()` and `.optimize()` - it will simplify the test code significantly. Moreover it will be especially useful for future test where we have to execute 3-4 mojos (see `TranspileMojoTest`).

**Comment by mximp** [comment]
@volodya-lombrozo It seems that `FakeMaven` is becoming quite huge. Maybe we will just make `execute` to accept an `Iterable<Class<Mojo>>`?

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo It seems that `FakeMaven` is becoming quite huge. Maybe we will just make `execute` to accept an `Iterable<Class<Mojo>>`? With this we will be able to externalize phases specification.

@mximp I think your code won't work, the best way to use wildcards together with generics:
```java
    public FakeMaven execute(final Iterable<Class<? extends AbstractMojo>> mojo) throws IOException {
        for (final Class<? extends AbstractMojo> clazz : mojo) {
            this.execute(clazz);
        }
        return this;
    }
```
Or we even can try to use varargs:
```java
    @SafeVarargs
    public final FakeMaven execute(final Class<? extends AbstractMojo>... mojo) throws IOException {
        for (final Class<? extends AbstractMojo> clazz : mojo) {
            this.execute(clazz);
        }
        return this;
    }
``` 
But both options almost do not give us something useful.  Just compare:
```java
.execute(OptimizeMojo.class)
.execute(AssembleMojo.class)
```
and
```java
.execute(
    OptimizeMojo.class,
    AssembleMojo.class
)
```
As you can see - both statements almost identical. The better would be to create `optimize()` and `parse()` methods that look elegant.

**Comment by mximp** [comment]
@volodya-lombrozo with my proposal 1) `FakeMaven` will not grow by 5 methods; 2) we will be able to wrap required set of phases into a separate class or method or just constant:
```
.execute(
    new Assemble()
)

class Assemble implements Iterable<Class<? extends AbstractMojo>> {
    public Iterator<> iterator() {
        return Array.of(
            OptimizeMojo.class,
            AssembleMojo
        );
    }
}
```
You can pass to `.execute` whatever is convenient.  
The idea is that you have it externally and can extend without blowing `FakeMaven`.

**Comment by mximp** [comment]
@volodya-lombrozo :) as fist approximation I believe we can just have `.execute` to accept `Iterator` and create inner classes with most used lists.
