### ISSUE TITLE
Why `<metas>` attribute in XMIR is optional?

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1522]
I have this program:
```
[] > main
  QQ.io.stdout > @
    QQ.txt.sprintf "ans is %d"
      13
```
Since `<metas>` is optional attribute in XMIR now, and in the program above there is no `alias`-es and `probe`-s (and others), there is no `<metas/>` section in final XMIR.
But work of [`add-probes.xsl`](https://github.com/objectionary/eo/blob/master/eo-parser/src/main/resources/org/eolang/parser/add-probes.xsl) depends on `<metas>` section and without it, XSL will not work.
So, if I add simple `meta` --- `package`, it will work:
```
+package org.eolang.custom

[] > main
  QQ.io.stdout > @
    QQ.txt.sprintf "ans is %d"
      13
```

So, we can make `<metas>` section is mandatory in XMIR-s or rewrite `add-probe.xsl` and all others XSL-s (if they are exist).

**Comment by MikhailLipanin** [comment]
@yegor256 WDYT?

**Comment by yegor256** [comment]
@MikhailLipanin I didn't understand the problem. What doesn't work now?

**Comment by MikhailLipanin** [comment]
When I have this program:
```
[] > main
  QQ.io.stdout > @
    QQ.txt.sprintf "ans is %d"
      13
```
I get the following XMIR:
```
<program>
  <listing>
    ...
  </listing>
  <errors>
    <error check="missing-package"
              line=""
              severity="warning"
              sheet="mandatory-package-meta"
              step="0">Missing package</error>
  </errors>
  <sheets>
    ...
  </sheets>
  <objects>
    ...
  </objects>
</program>
```

But when I have this program (the only difference in `+package org.eolang.custom`:
```
+package org.eolang.custom

[] > main
  QQ.io.stdout > @
    QQ.txt.sprintf "ans is %d"
      13
```
I get the following XMIR:
```
<program>
  <listing>
    ...
  </listing>
  </errors>
  <sheets>
    ...
  </sheets>
  <metas>
    <meta line="1">
      <head>package</head>
      <tail>org.eolang.custom</tail>
      <part>org.eolang.custom</part>
    </meta>
    <meta line="4">
      <head>probe</head>
      <tail>Q.org.eolang.io.stdout</tail>
      <part>Q.org.eolang.io.stdout</part>
    </meta>
    <meta line="4">
      <head>probe</head>
      <tail>Q.org.eolang.io</tail>
      <part>Q.org.eolang.io</part>
    </meta>
    <meta line="5">
      <head>probe</head>
      <tail>Q.org.eolang.txt.sprintf</tail>
      <part>Q.org.eolang.txt.sprintf</part>
    </meta>
    <meta line="5">
      <head>probe</head>
      <tail>Q.org.eolang.txt</tail>
      <part>Q.org.eolang.txt</part>
    </meta>
    <meta line="5">
      <head>probe</head>
      <tail>Q.org.eolang</tail>
      <part>Q.org.eolang</part>
    </meta>
    <meta line="5">
      <head>probe</head>
      <tail>Q.org</tail>
      <part>Q.org</part>
    </meta>
  </metas>
  <objects>
    ...
  </objects>
</program>
```

Note, that the difference here is in `<metas>` section.
The question is: why `probes` is added only if there is another `meta` (like `+package` for example) ? 
______________
I think it is because some XSL - templates depends on `<metas>` section of XMIR (for example if there is `<template match="//metas..."`)

So, we can make <metas> section is mandatory in XMIR-s or rewrite add-probe.xsl and all others XSL-s (if they are exist).

@yegor256 FYI

**Comment by yegor256** [comment]
@MikhailLipanin why it's a problem? Yes, this is how `add-probes.xsl` works. Why it's a problem for you?

**Comment by MikhailLipanin** [comment]
@yegor256 Because we don't correctly add `probes` for objects if there is no other metas

**Comment by MikhailLipanin** [comment]
So in first example, I can't say, what is `QQ.io.stdout` without its `probe`

**Comment by yegor256** [comment]
@MikhailLipanin try to always report a bug in this format: 1) I do this, 2) I expect this result, 3) I'm getting this instead.

**Comment by MikhailLipanin** [comment]
Here, I expected in both examples of EO-programs the second XMIR, but get it only in first example

**Comment by mximp** [comment]
@pollyvolk please assist

**Comment by mximp** [comment]
@pollyvolk @MikhailLipanin @yegor256 I believe `metas` element should be added by default just like it's done for `errors` (see `XeListener` in `eo-parser`).

**Comment by mximp** [comment]
> @mximp I don't mind, let's make it mandatory

Just to make it clear: it will not be mandatory from EO language point of view but rather `<metas>` tag will be added into XMIR by default (even with no metas inside).

**Comment by MikhailLipanin** [comment]
This one is related to #1323

**Comment by yegor256** [comment]
@mximp let's make it mandatory in XMIR (let's update `xmir.xsd` for that too). In the language syntax it's of course optional
