### ISSUE TITLE
Mandate metas order

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1526]
As far as I know we can use metas in any order:
```eo
+package org.eolang.http
+alias org.eolang.hamcrest.assert-that
+alias org.eolang.http.http-request
+junit
```
or
```
+alias org.eolang.hamcrest.assert-that

+junit

+alias org.eolang.http.http-request

+package org.eolang.http
```

Moreover, we can use empty lines between. I believe it's better to create a particular order for metas - it could increase readability of code.

**Comment by mximp** [comment]
@volodya-lombrozo please rename the issue to reflect intention. `Mandate metas order` sounds better I believe.

**Comment by yegor256** [comment]
@volodya-lombrozo we already have a checker for this: it complains if metas are not sorted alphabetically. As for the empty lines between them -- definitely a bug.

**Comment by Graur** [comment]
@yegor256 Is it legal to use spaces between metas?

**Comment by yegor256** [comment]
@Graur nope, it's not legal

**Comment by yegor256** [comment]
@Graur I would add a test to `TyposTest`
