### ISSUE TITLE
make sure all objects have +home and +version meta

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1542]
Let's add a test to Makefile, which will make sure all `.eo` objects have `+home` meta, which has a URL as a tail. Also, let's check for the presence of `+version` meta with a SemVer in the tail.

**Comment by Graur** [comment]
@levBagryansky I believe it should be a part of `eo-parser`

**Comment by levBagryansky** [comment]
@Graur please assign me.
Waiting for solving #1545

**Comment by Graur** [comment]
@levBagryansky Sure, go ahead

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1809](https://github.com/objectionary/eo/issues/1809) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1809](https://github.com/objectionary/eo/issues/1809) is solved here.
