### ISSUE TITLE
DcsTransitive doesn't take into account "classifier"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1543]
The `DcsTransitive` class doesn't pay attention to `classifier` of a dependency, but only to `artifactId` and `groupId`. That's why the plugin complains about `eo-sys:jar-with-dependencies`

**Comment by yegor256** [comment]
@volodya-lombrozo please, take a look

**Comment by volodya-lombrozo** [comment]
@yegor256 is it solved [here](https://github.com/objectionary/eo/pull/1546)?

**Comment by yegor256** [comment]
@volodya-lombrozo yep
