### ISSUE TITLE
Mojos to a new package (refactoring)

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1548]
Maybe we will separate the "util" classes (like `Place`, `Home`, `JavaFiles` and others) from all the others in `eo-maven-plugin` and make a separate package --- just like we did with `objectionary`, `hash`, `footprint` and `optimize`.

Or do we make a package `org.eolang.maven.mojos` and put all Mojo there so that there are not many classes in one place?

**Comment by MikhailLipanin** [comment]
@yegor256 WDYT?

**Comment by yegor256** [comment]
@MikhailLipanin how Apache plugins do this? Let's copy their design.

**Comment by MikhailLipanin** [comment]
@yegor256, different plugins made differently:
[invoker](https://github.com/apache/maven-invoker-plugin/tree/master/src/main/java/org/apache/maven/plugins/invoker)
[dependency](https://github.com/apache/maven-dependency-plugin/tree/master/src/main/java/org/apache/maven/plugins/dependency)

I think that grouping classes (like in dependency plugin) is more convenient

**Comment by yegor256** [comment]
@MikhailLipanin I also like the approach of the "dependency" plugin

**Comment by yegor256** [comment]
@MikhailLipanin let's make a package `org.eolang.maven.utils` and move everything there, except Mojos

**Comment by MikhailLipanin** [comment]
@yegor256 [this](https://github.com/objectionary/eo/pull/1549) approach is bad, right?

**Comment by yegor256** [comment]
@MikhailLipanin I think it's bad. a better one is the one used in the "dependency" plugin, you mentioned above
