### ISSUE TITLE
Add `ChResolve` to reuse it later in `ProbeMojo`

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1568]
resolving [this PR](https://github.com/objectionary/eo/pull/1473) need to split it into several PR-s:

- `ChResolve` -- resolves the implementation, which you need to use, depends on the parameters (`tag`, `offlineHash`, `offlineHashFile`)

**Comment by yegor256** [comment]
@MikhailLipanin I don't understand this ticket. Is is a bug report (something is broken) or a suggestion of a new feature?

**Comment by MikhailLipanin** [comment]
@yegor256, see [this one](https://github.com/objectionary/eo/issues/1566#issuecomment-1357439478)
