### ISSUE TITLE
`.&` expression is not handled properly

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1570]
```
[] > app
  [] > @
    [] > @
      &.&.a > @
  1 > a 
```
Leads to a execution error:
`Caused by: org.eolang.ExUnset: Can't get(), attribute "&" is absent among other ...`

Expected: `&.&.a` correctly refers to `app.a`.

**Comment by mximp** [comment]
Hint: the problem is in transformation `to-java.xsl` where `.&amp;` is not handled properly.

**Comment by yegor256** [comment]
@mximp go ahead, fix it please, but don't forget to add a simple test to reproduce it first
