### ISSUE TITLE
Add integration test for `eo-runtime` library

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1575]
We have to add some integration tests or maybe unit tests in order to check correct build of `eo-runtime` library. 
At least we have to check that all classes were added to the final jar (comes from that issue: #1547)

**Comment by volodya-lombrozo** [comment]
@yegor256 assign to me

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1582](https://github.com/objectionary/eo/issues/1582) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#1582](https://github.com/objectionary/eo/issues/1582) is solved here.
