### ISSUE TITLE
Check a puzzle format locally 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1581]
I quite often face with the problem of the correct formatting of a puzzle in the code. I've read notation, but some problems can reveal anyway (Short description, Wrong puzzle time, etc). I've found only the single way to check the puzzle format - to push.
Is it exist any other way to check a puzzle format before pushing it?

**Comment by yegor256** [comment]
@volodya-lombrozo we can add the checking of puzzle formatting into the `pom.xml`, using [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/). Otherwise, we can create a new Maven plugin for that.

**Comment by yegor256** [comment]
@volodya-lombrozo in the meantime, you can check formatting locally. You need to install [`pdd`](https://github.com/cqfn/pdd) and then run:

```
$ pdd -f /dev/null
```

**Comment by yegor256** [comment]
@volodya-lombrozo I agree, we should wait for the Maven plugin made by the PDD "team"

**Comment by Graur** [comment]
@yegor256 @volodya-lombrozo I believe we can close it

**Comment by volodya-lombrozo** [comment]
Since we are waiting for https://github.com/cqfn/pdd/issues/219 to be completed, I agree that we can close this issue and reference it next time if we have the similar questions.
