### ISSUE TITLE
can't release due to the 'redundant parenthesis' warning 

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1584]
see https://github.com/objectionary/eo/issues/1547#issuecomment-1357699694

I can't understand, how do we merge pull requests, when this bug is there..?

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1587](https://github.com/objectionary/eo/issues/1587) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1587](https://github.com/objectionary/eo/issues/1587) is solved here.
