### ISSUE TITLE
pom.xml:116: Set failOnWarning to 'true'. It's not a good...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1587]
The puzzle `1584-082116ed` from #1584 has to be resolved: 

https://github.com/objectionary/eo/blob/00d4db35175eddca362e787327a5f674fcacb6f3/eo-runtime/pom.xml#L116-L116

The puzzle was created by @volodya-lombrozo on 19-Dec-22. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@Graur pls, help us here
