### ISSUE TITLE
Code coverage restrictions

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1597]
I strongly believe that  we have to set test coverage restrictions. For example, code coverage can't be less than 80% - in that case we can automatically detect PR that wasn't covered by tests.

**Comment by volodya-lombrozo** [comment]
Moreover, I quite often in PR`s reviews write messages about missed tests.

**Comment by yegor256** [comment]
@volodya-lombrozo totally agree, let's do it. see the example here: https://github.com/yegor256/cactoos/blob/0.55.0/pom.xml#L180-L238

**Comment by mximp** [comment]
Let's define current coverage ratio and set it as min value.

**Comment by mximp** [comment]
@PickBas please assist

**Comment by mximp** [comment]
@volodya-lombrozo this can be closed
