### ISSUE TITLE
EOas_phi class does not compile due to missing dependencies

### ISSUE THREAD

**Issue by mattbrk** [objectionary/eo#1605]
Description:

I am trying to use the EOas_phi class in my project, but it does not compile due to missing dependencies. The class extends PhDefault and has a constructor that takes a single parameter of type Phi, but these classes are not found in my project.

I have tried importing these classes from various packages, but I am unable to find them.

Steps to reproduce:

    Include the EOas_phi class in a Java project
    Attempt to compile the project

Expected behavior:

The project should compile without errors

Actual behavior:

The project fails to compile due to missing dependencies for PhDefault and Phi

Error messages and stack traces:
```
error: cannot find symbol
public class EOas_phi extends PhDefault {
                              ^
  symbol: class PhDefault

error: cannot find symbol
public EOas_phi(final Phi sigma) {
                           ^
  symbol:   class Phi
  location: class EOas_phi
```
```
Stack trace
java.lang.NullPointerException
    at MyClass.myMethod(MyClass.java:42)
    at Main.main(Main.java:14)
```
System details:

    Operating system: Ubuntu-latest
    Java version: 17

Additional context:

I am not sure where these classes are supposed to come from. It would be helpful if the code included proper import statements or if the documentation provided more information about the dependencies for this class.

**Comment by mximp** [comment]
@mattbrk please clarify what do you mean by "Include the EOas_phi class in a Java project".
Do you have [`eo-runtime.jar`](https://search.maven.org/artifact/org.eolang/eo-runtime)  in your classpath?

**Comment by mximp** [comment]
@mattbrk reminder

**Comment by mximp** [comment]
@mattbrk is this still relevant?
