### ISSUE TITLE
Unit test for `JavaFiles`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1634]
Apparently, it would be better to add unit test for `JavaFiles` to describe its behaviour and add more flexibility in refactoring.

**Comment by yegor256** [comment]
@volodya-lombrozo try to formulate _all_ tickets you submit as either 1) new features, or 2) bugs. This one is neither of those. It's a task. Try _not_ to report tasks.

**Comment by volodya-lombrozo** [comment]
@yegor256 Ok, I'll. Can you assign the issue to me, please?
