### ISSUE TITLE
ChResolve.java:33-37: Now, this class is a configurable....

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1644]
The puzzle `1569-254a5fb6` from #1569 has to be resolved: 

https://github.com/objectionary/eo/blob/ece321e208aa459ff46c05aeaebb61a3287d9f99/eo-maven-plugin/src/main/java/org/eolang/maven/hash/ChResolve.java#L33-L37

The puzzle was created by rultor on 30-Dec-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@MikhailLipanin Are you going to continue here, or I can reassign the issue?

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo you can reassign
