### ISSUE TITLE
Why do we need `@ref` attribute inside XMIR?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1665]
I'm working for #1475 issue and trying to understand whether that [check](https://github.com/objectionary/eo/blob/master/eo-parser/src/main/resources/org/eolang/parser/errors/broken-refs.xsl) is `critical`, but I can't find any information about `@ref` attribute and if it's critical to have broken "ref"

**Comment by mximp** [comment]
@volodya-lombrozo Check https://news.eolang.org/2022-11-25-xmir-guide.html, section 'References'.

**Comment by volodya-lombrozo** [comment]
@mximp It helps a lot. Thank you!

**Comment by volodya-lombrozo** [comment]
> Using the information from ref attributes you can distinguish base references to objects that are not visible in the current document (they don’t have ref attribute) from objects that are present in the current document (they have ref attribute with the value equal to the number of the line where the object is found).
