### ISSUE TITLE
Make `PhLocated` and `AtLocated` to accept location source information

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1666]
Let's extend `PhLocated` and `AtLocated` to hold source information along with line and position.
Potentially the source is contained within `loc` attribute in XMIR:
```
<o base=".with" line="87" loc="Φ.org.eolang.collections.multimap$find-in-list$t2$a2.φ.α0" pos="11"> 
``` 
It also should be printed within location information:
```
<Φ.org.eolang.collections.multimap$find-in-list$t2$a2.φ.α0:82:10>
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.17`
