### ISSUE TITLE
Pass through XMIR `loc` attribute into `PhLocated`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#1667]
When `new PhLocated(` java code is generated let's pass `loc` attribute into the constructor along with `line` and `pos`.

**Comment by mximp** [comment]
Can be done after #1666 is released with `eo-runtime`.

**Comment by yegor256** [comment]
@mximp I believe, it's possible to continue here

**Comment by volodya-lombrozo** [comment]
The issue was solved [here](https://github.com/objectionary/eo/pull/1952)
