### ISSUE TITLE
No need in `critical-errors`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1668]
It seems like the `critical-errors` that come from that [issue](https://github.com/objectionary/eo/issues/1024) are redundant.
Let's me explain a little bit.
We have 3 types of errors now:
- critical-errors
- errors
- warnings

We added `critical-errors` in order to "stop" compilation even if `failsOnError=false`.
Then I was given a [task](https://github.com/objectionary/eo/issues/1475) to "check" if we have any other "critical-errors" among the "errors".

Here is my results (I can be mistaken of corse):

```
org/eolang/parser/errors/
abstract-decoratee.xsl - critical  
broken-aliases.xsl - critical
broken-refs.xsl - ?
data-objects.xsl - critical
duplicate-aliases.xsl - warning
empty-object.xsl - warning
global-nonames.xsl - critical
many-free-attributes.xsl - warning
middle-varargs.xsl -critical
noname-attributes.xsl  - warning
not-empty-atoms.xsl - critical
same-line-names.xsl - critical
self-naming.xsl - critical
unknown-names.xsl - critical
unused-aliases.xsl - warning
```
"critical" here means that further compilation will fail if check shows some errors, "warning" - further compilation should pass anyway.
As far as I know, we added `critical-errors` in order to ignore `failsOnError` flag and to fail anyway (if we met `critical-error`). But as you can see from the list above - almost all checks will fail further compilation.
What the point in existence of "critical-errors"? What is the difference with simple "errors"? 
What I suggest:
1. Remove `failsOnError` flag at all.
2. Remove `critical-errors` at all.
3. Collect all "errors" during parsing phase 
4. On the next phase **always** throw exception if `errors` are not empty.

Actually `failsOnError` flag was introduced only to collect  all "errors":
https://github.com/objectionary/eo/issues/694#issuecomment-1378675221
> @volodya-lombrozo sometimes a user may want to compile a collection of 1000 files. The user doesn't want to stop after the first error. Instead, the user wants to get a full report of all errors, after which the decision will be made: how many of them to fix, when and who will do it.

And since my algorithm will collect them all anyway - we don't need `failsOnError=false`

**Comment by yegor256** [comment]
@volodya-lombrozo why `broken-aliases.xsl` is critical? If one alias is broken, the rest of the code may be perfectly fine and the entire compilation process may continue. The same for `unknown-names.xsl` -- one name is not known, but everything else looks fine, we can try to continue.

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo, Note that some of XSL-s in `ParsingTrain` have this code:
```
<xsl:message terminate="yes">
  ...
</xsl:message>
```
It means, that during Pipeline in `ParsingTrain` if this code will be executed, an Exception will be thrown.
To avoid this, `critical-errors` has been introduced.

So, If earlier if in Pipeline the code above was executed, the full build was failed.
Now, this code marked as `critical-errors` and if they was found (and `failOnError` == `false`), the Pipeline just stops, and No Exceptions throws.

(At the moment, there is only one `critical-error` -- `duplicate-names.xsl`. Earlier, inside of it, there was ```<xsl:message terminate="yes">```, but now it just adds to `<errors>` section a `critical-error` and stops Pipeline)

**Comment by volodya-lombrozo** [comment]
@yegor256 @MikhailLipanin Why can't we just throw an exception when we can't continue to analyse, for example by using the next code?
```xml
<xsl:message terminate="yes">
  ...
</xsl:message>
```
Why do we need to add one more type for "errors" (particularly `critical-errors`)?

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo, I think that if in such cases we will throw an Exception, and we want to analyze the remaining files -- it is required to catch that thrown exception from XSL and continue working. But it is a "control-flow via exceptions", which is bad (as I know)

**Comment by volodya-lombrozo** [comment]
@MikhailLipanin But as I understand the current behaviour:
1. Parsing eo
2. Checking xmir
3. `critical-error` found
4. Parsing train stops
5. We trow an exception

When we throw an exception on the (2) step - we don't need `critical-errors` at all and we can simplify the current solution.

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo, You are right when `failOnError` flag is `true`.

The main reason of `critical-error` right now is:
- When `failOnError` flag is `true`:
  All works as you described above.
- When `failOnError` flag is `false`:
  1. Parsing eo and checking xmir using `ParsingTrain`
  2. critical-error found
  3. Parsing train stops
  4. The work of the full build goes next, and no Exceptions are thrown.

The reason of introducing `critical-errors` is that if `failOnError` == `false`, we can't just continue build if we don't have some "marks" (as now we have `critical-errors`), on which we can select -- to continue working or to throw an exception

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo So the reason is not only in the presence of `critical-errors` but also in value of `failOnError` flag.

**Comment by volodya-lombrozo** [comment]
@MikhailLipanin Please, note that `failOnError` flag was added in order to "continue" parsing (check https://github.com/objectionary/eo/issues/694) - it is initial purpose of it and I'm not sure that it's an optimal solution. What I suggest (pseudo-code):
```
parse(xmir){
  try{
    errors = train.parse(xmir);
    if(errors.isEmpty()){
      continue;
    } else {
     //do something useful
    }
  } catch (critical-error){
    continue; //do something useful
  }
}
``` 

in that case we don't need `critical-errors` and `failsOnError` - because we can collect `errors` and decide what to do with them further (actually we always have to stop the build if `!errors.isEmpty()`) and we don't have to obtain `critical-errors` in a special way.

**Comment by MikhailLipanin** [comment]
> in that case we don't need `critical-errors` and `failsOnError` - because we can collect `errors` and decide what to do with them further (actually we always have to stop the build if `!errors.isEmpty()`) and we don't have to obtain `critical-errors` in a special way.

@volodya-lombrozo, Why we always have to stop the build if `!errors.isEmpty()`? The `failOnError` flag decides, should we stop train or not. 
What about design, I don't know, how to make another approach than we have right now.

> ```
> parse(xmir){
>   try{
>     errors = train.parse(xmir);
>     if(errors.isEmpty()){
>       continue;
>     } else {
>      //do something useful
>     }
>   } catch (critical-error){
>     continue; //do something useful
>   }
> }
> ```

In this approach, we wouldn't be able to stop the train, without throwing an Exceptions. And what we will do with XSl, where already `<xsl:message terminate="yes">`?

I think the idea of it is that if we run the full build and it will not be terminated -- we can open the "final" XMIR and check, which errors have been happened (and if the last one if `critical` - we understand that the Pipeline has been stopped).

But this is the question about design of build, Idk how to make better.
@yegor256, WDYT about design -- which one is better?

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo, Why we always have to stop the build if !errors.isEmpty()? The failOnError flag decides, should we stop train or not.

Let's assume we have 3 `eo` files and each contains `errors`. We have to parse all of them, collect errors and on the next step stop the entire compilation pipeline and print all found `errors`.  We don't need `failOnError=false` for that.

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you give your decision, please?

**Comment by yegor256** [comment]
@volodya-lombrozo I still believe that we need _three_ levels of errors:

  * critical: we must stop immediately, because if we continue, the result is absolutely unpredictable
  * error: it's better to stop, since something wrong is in the code
  * warning: we can live with it, but it's better to fix

The main purpose of `error` is debugging. Our compiler is in beta-version and many users are testing it. It's better to let them continue the compilation when it's possible.

**Comment by volodya-lombrozo** [comment]
@yegor256 

We can't continue compilation when we have `critical` error (it has exactly the same behaviour as exception). Why then we need it at all?

**Comment by yegor256** [comment]
@volodya-lombrozo for consistency, it's better to keep all errors where we keep them: in `<errors/>` element
