### ISSUE TITLE
Move all `Dcs` classes into a separate package

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1671]
We have several classes that describe the same entity `Dependencies`:
```
DcsDefault
DcsDepgraph
DcsUniquelyVersioned
DcsWithRuntime
```
It would be great to move all of them to a separate package.

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo, Test classes too

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo, Test classes too
> (Earlier we moved only classes in `src/main`)

@MikhailLipanin good comment! Thank you
