### ISSUE TITLE
DcsEachWithoutTransitive.java:37-38: Add fine grained...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1673]
The puzzle `1589-9aa5ee72` from #1589 has to be resolved: 

https://github.com/objectionary/eo/blob/33d7df54cebfbdd5fb5b0425070463a559429353/eo-maven-plugin/src/main/java/org/eolang/maven/DcsEachWithoutTransitive.java#L37-L38

The puzzle was created by volodya-lombrozo on 12-Jan-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by MikhailLipanin** [comment]
@volodya-lombrozo You can reassign
