### ISSUE TITLE
array.at with negative indexes

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1686]
Let's make it possible to use `array.at` with a negative index, just like it works in `Array.at` of JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

**Comment by yegor256** [comment]
@Graur please, help with this (don't forget to update "The Origins" paper)

**Comment by Graur** [comment]
@yegor256 Please close the ticket if you don’t have any further questions

**Comment by yegor256** [comment]
@Graur thanks!
