### ISSUE TITLE
`ProbeMojo` optimisation required. Many HTTP requests.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1705]
I've added logs to `ProbeMojo` to check how many objects we are checking in **objectionary**:
```
[INFO] Probing [array.length, arr.elements.length, arr.elements, anArray.length, anArray.at, a.with, array.at, res.at.plus, list.concat, res.length, res.at.at, res.at, array.with.with.with, array.with.with, array.with, array.empty.length, array.empty.with.with.with, array.empty.with.with, array.empty.with, array.empty] objects 
[INFO] Probing [as-phi.length] objects 
[INFO] Probing [bool.and, int.lt, int.gt, int.eq.if, x.write.eq.and, x.write.eq, number.pow, mFirst.write.eq.and.not.and, mFirst.write.eq.and.not, mFirst.write.eq.and, mThird.write.eq.and.not, mThird.write.eq.and, mFirst.write.eq.or.and, mFirst.write.eq.or, mFirst.write.eq, mFirst.write, mThird.write.eq.or, mThird.write.eq, mThird.write, mFirst.eq, mThird.eq, bool.eq.and, bool.eq, bytes.as-bytes.eq.and, bytes.as-bytes.eq, bytes.as-bytes, m.gt.eq.while, m.gt.eq, m.gt, m.write, m.minus, int.eq.and, int.eq, bool.as-hash, x.lt.while, x.lt, x.write, x.plus] objects 
[INFO] Probing [bytes.slice.size, bytes.slice, bytes.as-string, int.as-bytes.left, int.as-bytes.right, int.as-bytes.not, a.and, bytes.size, bytes.as-bool, a.concat, bool.as-bytes, b1.concat, bytes.concat, string.as-bytes.concat, string.as-bytes, s-bytes.as-string, int.as-hash, int.as-bytes.and.as-int, int.as-bytes.and, int.as-bytes.xor.as-int, int.as-bytes.xor, int.as-bytes.or.as-int, int.as-bytes.or, int.as-bytes, bytes.as-hash] objects 
[INFO] Probing [x.z, list.write, list.second.second, list.second, copy.<, c.x.x, c.x, c.attr, int.plus, sum.write, x.plus, y.write, c.write, ma.write, ma.plus, mb.write, mb.plus, ca.plus, cb.z.plus, cb.z, value.plus, y.value, x.write, tmp.write, x.add, tmp.value.eq, tmp.value] objects 
```
As you can see, it's a huge number of them. For each of them we call:
```java
if (!this.objectionary.contains(name)) {
    continue;
}
```
Where `contains` method is implemented as follows:

```java
@Override
public boolean contains(final String name) throws IOException {
   final int code = ((HttpURLConnection) this.template.value(name).openConnection()).getResponseCode();
   return code >= HttpURLConnection.HTTP_OK && code < HttpURLConnection.HTTP_BAD_REQUEST;
}
```
In other words, we make huge number of HTTP calls during "probing" - it decrease build time significantly, at least on my laptop with bad internet.

**Comment by volodya-lombrozo** [comment]
Caching doesn't help either, because:
1. From the beginning we have cold cache
2. We always have to check object which aren't objects in **objectionary** actually "x.z", "x.plus", "ma.write"

**Comment by yegor256** [comment]
@mximp any ideas?

**Comment by volodya-lombrozo** [comment]
@yegor256 I strongly believe it's much better to restrict using of fully qualified names, as suggested [here](https://github.com/objectionary/eo/issues/1323#issuecomment-1280880219)
> Can we just mandate to use either +alias or +rt metas? Maybe introduce parsing waring if fully qualified names are used and there is no  +rt meta?

Do we really need that syntax sugar?

**Comment by yegor256** [comment]
@volodya-lombrozo it seems that we are making too many probes for names that definitely are local and already "resolved"

**Comment by volodya-lombrozo** [comment]
@yegor256 Of course, we can invent some "crutch" here to fix that particular issue (filtering, checking all objects in a single request, etc...), but does it worth it? We already have:
- ProbeMojo.java
- add-probes.xsl
- Now we are going to fix "optimization" problems
- ... (something will happen else in the future, because it does not correspond to the general concept of aliases).

I believe it's a wrong way at all.

**Comment by volodya-lombrozo** [comment]
@yegor256 Moreover adding "probes" to XMIR already looks like "crutch". Isn't it?

**Comment by mximp** [comment]
@volodya-lombrozo @yegor256 maybe we can have an index of Objectionary names somewhere and download it at the beginning of compilation.. It can be a single file prepared during the build of `objectionary/home`: `objects.txt`, containing all known names (name per line). We will have to make single http call in this case. WDT?

And with regards to the number of probs - we definitely need to check what can be filtered out to reduce the number.

**Comment by volodya-lombrozo** [comment]
@mximp Indeed the good suggestion, but it's still just only fixing symptoms, as for me.

**Comment by mximp** [comment]
@volodya-lombrozo we want to provide this flexibility to language users - not to type what can be inferred. I see limiting the number of produced probes plus web-request optimization as suitable solution for that.

**Comment by volodya-lombrozo** [comment]
@mximp 
1. Clear and simple inference impossible, because [we have an identification problem](https://github.com/objectionary/eo/issues/1323#issuecomment-1280880219).
2. Flexibility in general not is a good choice that leads to [a lower quality](https://www.yegor256.com/2017/04/11/flexibility-equates-lower-quality.html).

Moreover that feature almost doesn't add any flexibility, imho.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you give your decision, please?

**Comment by mximp** [comment]
@yegor256 @volodya-lombrozo I believe we could tune the probing a bit:
```
2023-01-19 15:08:34.910 [INFO] Probing [^.as-bytes.eq, ^.as-bytes, ^.eq.not, x.as-bytes.eq.or.not, ^.eq, x.as-bytes.eq.not, ^.plus, x.neg, x.gt.if, x.gt, x.lt.if, x.lt, x.eq.if, x.as-bytes.eq.or.if, x.as-bytes.eq.or, x.as-bytes.eq, x.as-bytes, nan.as-bytes, x.eq] objects 
```

1. Exclude from probes strings with special symbols (like `^`, `$` etc)
2. Exclude from probes string with less than 2 elements. I suggest to assume that there cannot be fully qualified object like `abc.edf`. Package

**Comment by volodya-lombrozo** [comment]
@mximp Actually, I had to solve it in [that PR](https://github.com/objectionary/eo/pull/1699).
```xml
    <xsl:if test="not(eo:contains-any-of($p, ('$', '^', '@','&lt;')))">
```

**Comment by mximp** [comment]
> @mximp Actually, I had to solve it in [that PR](https://github.com/objectionary/eo/pull/1699).
> 
> ```
>     <xsl:if test="not(eo:contains-any-of($p, ('$', '^', '@','&lt;')))">
> ```

@volodya-lombrozo Apparently it was not fully solved as I still see the log I posted above

**Comment by volodya-lombrozo** [comment]
@mximp I believe we have to decide whether we remove "probes" or continue to fix and invent crutches. If we are going to remove "probes", which is the best solution, as for me, then we don't need to even search problems in that implementation.
@yegor256 Reminder.

**Comment by yegor256** [comment]
@volodya-lombrozo we need to have this feature in the language. If we allow people to say `QQ.txt.sprintf`, it would be silly to _also_ require them to use `alias`. If a fully qualified name of a object is mentioned -- it's our problem: how to compile. We must solve it, not our users.

**Comment by volodya-lombrozo** [comment]
@yegor256 I mean we should ban of usage `QQ.txt.sprintf`, according with [that](https://www.yegor256.com/2017/04/11/flexibility-equates-lower-quality.html)

**Comment by mximp** [comment]
> @yegor256 I mean we should ban of usage `QQ.txt.sprintf`, according with [that](https://www.yegor256.com/2017/04/11/flexibility-equates-lower-quality.html)

@volodya-lombrozo There are cases where the object has to be self-contained, without external references like in `metas`. It becomes evident when you think of interpreter-like implementation or about dataization (symbolically) of a particular inner object. It's needed to be able to pass around just object source and not the whole file:
```eo
[] > inner-object
  QQ.io.stdout 5 > @
```

**Comment by volodya-lombrozo** [comment]
@mximp Sorry I didn't get your point here. Can you explain with examples?

**Comment by yegor256** [comment]
@volodya-lombrozo I think @mximp is talking about a possible REPL or interpreting mode of EO, when a user passes a small piece of code to the computer, not the entire program with headers and metas

**Comment by volodya-lombrozo** [comment]
@yegor256 It's a separate problem that we have to solve in REPL project. And I'm strongly believe that It's wrong way to "adjust" language for foreign tools.

**Comment by mximp** [comment]
@volodya-lombrozo FQN is a common practice in languages. Normally it allows to solve the case with two objects from different packages having the same name.

**Comment by volodya-lombrozo** [comment]
@mximp @yegor256 

Of corse, some languages use the concept of **Fully Qualified Names**.  We can remember some examples from different languages:

* Java: `java.util.ArrayList`
* C#: `System.Collections.Generic.List<T>`
* C++: `std::vector<int>`

In the Java example, `java.util` is the package and `ArrayList` is the class name. In the C# example, `System.Collections.Generic` is the namespace and `List<T>` is the class name. In the C++ example, `std` is the namespace and `vector<int>` is the template class name. 

Languages with dynamic typing, such as Python, JavaScript, Ruby do not typically use the concept of fully qualified names in the same way that statically typed languages like Java, C#, and C++ do. However, they do have a similar concept of fully qualified names:
* JavaScript `import { variableName } from 'moduleName’`
* Ruby `ModuleName::ClassName`
* Python `mypackage.mymodule.MyClass.my_class_method`

Please, notice that there are two concepts exists for almost all languages `package` (or `namespace`, or `module`) on the one hand and `class` or `precedure` or `method` on the other hand. In other words, the division exists between a location (`package`, `module`) and a final aim (`class`, `method`, `procedure`). As far as I know,  we have the same division in `eolang` (packages and objects), but the problem here that the division is not clear at all - we can’t divide where is an object and where is an attribute (see that [comment](https://github.com/objectionary/eo/issues/1323#issuecomment-1280880219)). In opposite, In the examples above you can clearly see that the division always clear and straightforward -  class or procedure always is **the last element**.

The problem actually a quite large, and we can solve it in several ways (at least as I see it):

1. We can invent some division between packages, attributes and objects (for example, give objects names using capital letter and attributes using a regular one) - looks strange, isn't it? 
2. We can continue to “guess” - it is like we do it right now - we will solve tons of “optimization” features like this one, we will check all possible “probes” (whether it is an object or an attribute?). We will guess actually - “What did a programmer want to say using that fully qualified name?”
3. We can ban using **Fully Qualified Names** - which is fast and it will solve all the problems.

Moreover, `eolang` is still “Experimental” language. Do we really need so wide number of features, including “Fully Qualified Names”? I believe for us much better just to ban that functionality since the feature itself is optional and we can live without it and concentrate on more important features and optimisations.

**Comment by yegor256** [comment]
@volodya-lombrozo there are no packages in EO, but only objects -- this is the beauty/ugliness of the language. `org` is an object, `org.eolang` is an object, `org.eolang.int` is also an object, finally, `org.eolang.int.plus` is also an object. They are four object with _equal_ rights and responsibilities. I believe that it's the job of a compiler: how to find out which object to load from where. The probing mechanism may not be perfect in its current implementation, but we must make it perfect. Let's think about more advanced caching. Maybe we can pre-build a map of objects and put somewhere in `objectionary.com` repository? The `ProbeMojo` will download it as a single file once and thus will minimize the number of HTTP probes. WDYT?

**Comment by mximp** [comment]
> @volodya-lombrozo there are no packages in EO, but only objects -- this is the beauty/ugliness of the language. `org` is an object, `org.eolang` is an object, `org.eolang.int` is also an object, finally, `org.eolang.int.plus` is also an object. They are four object with _equal_ rights and responsibilities. I believe that it's the job of a compiler: how to find out which object to load from where. The probing mechanism may not be perfect in its current implementation, but we must make it perfect. Let's think about more advanced caching. Maybe we can pre-build a map of objects and put somewhere in `objectionary.com` repository? The `ProbeMojo` will download it as a single file once and thus will minimize the number of HTTP probes. WDYT?

@yegor256 @volodya-lombrozo I support this idea.

**Comment by yegor256** [comment]
@volodya-lombrozo it's syntax-only. I would say that this:

```
+package foo.bar
[] > hello
```

is equivalent to:

```
[] > foo.bar.hello
```

But the second option is not allowed in our syntax. Maybe it should be!

**Comment by volodya-lombrozo** [comment]
@yegor256

> @volodya-lombrozo there are no packages in EO, but only objects -- this is the beauty/ugliness of the language. `org` is an object, `org.eolang` is an object, `org.eolang.int` is also an object, finally, `org.eolang.int.plus` is also an object. They are four object with _equal_ rights and responsibilities. I believe that it's the job of a compiler: how to find out which object to load from where. The probing mechanism may not be perfect in its current implementation, but we must make it perfect. Let's think about more advanced caching. Maybe we can pre-build a map of objects and put somewhere in `objectionary.com` repository? The `ProbeMojo` will download it as a single file once and thus will minimize the number of HTTP probes. WDYT?

If `org` and `org.eolang` are objects, can I check their code somewhere?
Also in the `eo` we have an "attributes", what is the meaning of the `org.eolang` expression then:
- Is it is an `org` object with an attrubute `eolang`? (`eo` is an object, `eolang` is an attribute, that have to be accessed using dot notation)
- Is `org.eolang` object itself? (`org.eolang` is a separate object that could be used independently, and `org` is a location)

**Comment by yegor256** [comment]
@volodya-lombrozo check `PhPackage.java` class -- this is the code of `org.eolang`. You can get an ID any package, for example:

```
alias org.eolang.txt.sprintf
alias org.eolang.io.stdio

[] > app
  stdout > @
    sprintf
      "The ID of org.eolang is %d"
      org.eolang.<
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Even in java we have a class corresponding to a `package`, does it mean a "location" of an object?
What about another questions?

> Also in the `eo` we have "attributes", what is the meaning of the `org.eolang` expression then:
> - Is it is an `org` object with an attrubute `eolang`? (`eo` is an object, `eolang` is an attribute, that have to be accessed using dot notation)
> - Is `org.eolang` object itself? (`org.eolang` is a separate object that could be used independently, and `org` is a location)

**Comment by yegor256** [comment]
@volodya-lombrozo `org.eolang` is an attribute `eolang` taken from the `org` object. Of course, like any other attribute, it is a _binding_ between two objects. The left object is `org`, while the right object is an instance of `PhPackage`.

**Comment by volodya-lombrozo** [comment]
@yegor256 Can we access attributes of any object using dot notation from any other object violating encapsulation?
```eo
[isbn] > book3
  "Object Thinking" > title 
  memory 0 > price
  [p] > set-price
    ^.price.write p > @

[] > another
  book3.set-price 10 > x
```

**Comment by mximp** [comment]
After all optimisations build time has been reduced (MacBook, JDK17):
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eo 1.0-SNAPSHOT:
[INFO] 
[INFO] eo ................................................. SUCCESS [  5.208 s]
[INFO] eo-parser .......................................... SUCCESS [ 30.237 s]
[INFO] eo-maven-plugin .................................... SUCCESS [02:15 min]
[INFO] eo-runtime ......................................... SUCCESS [02:03 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:54 min
[INFO] Finished at: 2023-02-03T17:51:13+03:00
[INFO] ------------------------------------------------------------------------
```
