### ISSUE TITLE
Cached optimization results cause high number of probes.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1709]
The Issue comes from the [comment at this link](https://github.com/objectionary/eo/issues/1705#issuecomment-1396900739).

The filter for `'$', '^', '@', '<'` characters in `add-probes.xsl` was added in [this issue](https://github.com/objectionary/eo/issues/1700) and it works well, except one problem: if an `eo` program is already optimised, then optimization result will be taken from `~/.eo/oprimized` folder instead of parsing and applying the new feature from `add-probes.xsl`.

This means that cached results in `~/.eo/oprimized` don't allow for the application of new optimization features, even if you update the `eo-maven-plugin`. This behaviour increases high number of probes, causing a high build time.

**Comment by volodya-lombrozo** [comment]
The next command solves the problem:
```
rm -rf ~/.eo/optimized
```

**Comment by volodya-lombrozo** [comment]
@mximp have a look, please

**Comment by mximp** [comment]
@volodya-lombrozo what should I check?

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo what should I check?

@mximp Nothing, it's just an answer why the new feature doesn't work properly. You faced with that problem locally.

**Comment by yegor256** [comment]
Duplicate of #1705
