### ISSUE TITLE
Year workflow

### ISSUE THREAD

**Issue by l3r8yJ** [objectionary/eo#1710]
In the current version `year` workflow is broken

**Comment by mximp** [comment]
@l3r8yJ please clarify what do you mean? What do you mean by "current version"? What are the steps to reproduce the problem and expected result?

**Comment by l3r8yJ** [comment]
![image](https://user-images.githubusercontent.com/46355873/214107247-fc9f911a-f5b7-483e-a10a-357230455b71.png)
@mximp take a look at `year` workflow, please

**Comment by mximp** [comment]
@l3r8yJ Let's have a look at the next iteration of the workflow
