### ISSUE TITLE
Can not find 'nested-while' object

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1717]
I'm trying to understand how while loops are working, and I've checked the new [article](https://news.eolang.org/2023-01-12-declarative-while-nested.html) about it.
I've decided to check whether the example from article correct and `x=15`, I've created `nested-while.eo` file with the next content:
```eo
+alias org.eolang.txt.sprintf

[] > nested-while
  memory 0 > x
  memory 0 > y
  seq > @
    while.
      x.lt 10
      [i]
        seq > @
          y.write 0
          while.
            y.lt 2
            [i]
              seq > @
                write.
                  y
                  y.plus 1
                write.
                  x
                  x.plus 1
    QQ.io.stdout
      sprintf
        "x=%d"
        x
``` 

Then, I invoked `eoc dataize nested-while`.

**Expected behaviour**: In console the next output is present: `x=15`
**Actual behaviour**: 
```
EO version is 0.28.17
EO objects registered in /Users/lombrozo/Workspace/EOlang/learning/hardcode_while/.eoc/eo-foreign.json
EO version is 0.28.17
EO program assembled in /Users/lombrozo/Workspace/EOlang/learning/hardcode_while/.eoc
EO version is 0.28.17
Java sources generated in /Users/lombrozo/Workspace/EOlang/learning/hardcode_while/.eoc/generated-sources
EO version is 0.28.17
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/learning/hardcode_while/.eoc
EO version is 0.28.17
Executable JAR created at /Users/lombrozo/Workspace/EOlang/learning/hardcode_while/.eoc/eoc.jar
Can not find 'nested-while' object
```

**Comment by yegor256** [comment]
@volodya-lombrozo try to rename it to `nested`

**Comment by volodya-lombrozo** [comment]
@yegor256 This way it works fine.

I believe we either have to fix an article or allow names such a `nested-while`

**Comment by mximp** [comment]
@yegor256 @volodya-lombrozo My understanding was that such names are allowed.
@volodya-lombrozo Have you checked the log? Are there any errors?

**Comment by volodya-lombrozo** [comment]
@mximp I haven't noticed them. Here is the full [log.txt](https://github.com/objectionary/eo/files/10507595/log.txt).
I used `--verbose` option.

**Comment by mximp** [comment]
@volodya-lombrozo The issue is that when you try to dataize `nested-while` it tries to locate such class within JVM and since hyphens are prohibited in names `eoc` fails to find it.
Such symbols are sanitized by the EO transpiler: 
```
<xsl:function name="eo:clean" as="xs:string">
    <xsl:param name="n" as="xs:string"/>
    <xsl:value-of select="concat('EO', replace(replace(replace(replace($n, '-', '_'), '@', 'φ'), 'α', '_'), '\$', '\$EO'))"/>
  </xsl:function>
```
So actual object to search is `nested_while`.

**Comment by volodya-lombrozo** [comment]
@mximp Maybe the easiest way to fix that issue just to fix the article? What do you think?

**Comment by mximp** [comment]
@volodya-lombrozo I believe it's a specifics of `eoc` tool. Code in the article is absolutely correct.
Let's make a comment with `eoc` usage in this case.

**Comment by volodya-lombrozo** [comment]
@mximp `eoc` only redirects commands to `eo-maven-plugin`, I don't think it's a good idea to fix something in `eoc`. Let's imagine we will develop another tool (let's call it `eoc2`) that will redirect commands to `eo-maven-plugin` too - in this case we will lose all or crutches and the same bug will happen in `eoc2`. If `nested-while` name is allowed, I believe, we have the next possible solutions:
1. Handle "object" name somewhere inside `eo-maven-plugin`
2. We can add restriction on using "-" char in object names (again, the fix in `eo-maven-plugin`)
3. As I suggested before, we can fix article and do nothing :)

What do you think?

**Comment by yegor256** [comment]
@mximp @volodya-lombrozo it's a bug in eoc or in `Main` class in eo-runtime

**Comment by volodya-lombrozo** [comment]
> @mximp @volodya-lombrozo it's a bug in eoc or in `Main` class in eo-runtime

@mximp @yegor256 Could you assign the issue to me, please? I'll investigate it and will suggest a solution
