### ISSUE TITLE
Overload constructors with logic or introduce separate static methods?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1729]
Recently, we had a [discussion](https://github.com/objectionary/eo/pull/1722#discussion_r1093428013) about the code style to be applied to Java constructors. This discussion keeps recurring in various PRs.
For instance, consider the following code:
```java
ObjectsIndex() {
    this(
        new ScalarOf<Set<String>>(
            () -> new SetOf<>(
                new Mapped<>(
                    ObjectsIndex::convert,
                    new Mapped<>(
                        Text::asString,
                        new Split(
                            new TextOf(
                                new URL("https://home.objectionary.com/objectionary.lst")
                            ),
                            "\n"
                        )
                    )
                )
            )
        )
    );
}

ObjectsIndex(final Scalar<? extends Set<String>> all) {
    this.objects = new Sticky<>(all);
}

```

It looks simple, but the logic in the constructor seems "heavy" to me. So, I decided to introduce a new static method:
```java
ObjectsIndex() {
    this(ObjectsIndex.index());
}

ObjectsIndex(final Scalar<? extends Set<String>> all) {
    this.objects = new Sticky<>(all);
}

private static ScalarOf<Set<String>> index() {
    return new ScalarOf<>(
        () -> new SetOf<>(
            new Mapped<>(
                ObjectsIndex::convert,
                new Mapped<>(
                    Text::asString,
                    new Split(
                        new TextOf(
                            new URL("https://home.objectionary.com/objectionary.lst")
                        ),
                        "\n"
                    )
                )
            )
        )
    );
}
```

The aim - to keep common simple structure of any Java class:
```
//package and imports

//constructors aka initialisation - small and simple 

//all other methods that contains complicated logic
``` 

But as an opposite I get the next comment:
> To me the motivation is quite simple here - we are trying to produce minimum required number of elements. In this particular case to understand what the constructor does I have to drill down into static method which is purely code extraction. Whereas having code declared within constructor I can see the whole logic in one place.
That makes sense too, actually.

The main issue is that we keep spending time on rehashing the discussion and further refactoring. I think we should just agree on one approach and use that issue as a reference to save time in the future.

**Comment by mximp** [comment]
@volodya-lombrozo 
The thing is that in the example you provided there is no logic executed at all... It's just an initialisation of the class. Actual actions are performed later once `Scalar.value()` is called. All objects are lazy. So first version perfectly fits to the ['code-free-constructors'](https://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html) principle. Also in the first version we keep minimum of `new` allocations outside the constructors which is [good](https://www.yegor256.com/2018/01/02/operator-new-is-toxic.html). Also we don't introduce static methods ).
As for structure you mentioned: I believe the order of sections already guarded by code style we have, hence the key question here is what do we call 'small & simple' and 'complex' logic. For that we already have guidance regarding constructors that I mentioned above.
And remember there are always exceptions to any rule so there can be justified cases when when we do not follow the recommendation. And those cases has to be explicitly discussed in each particular case.

**Comment by Graur** [comment]
@volodya-lombrozo Can we close this issue?

**Comment by volodya-lombrozo** [comment]
[Prestructors](https://www.yegor256.com/2021/08/04/prestructors.html) is a technique to avoid large constructors and make constructors [code free](https://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html).
