### ISSUE TITLE
Get rid of transformation 0.0 to -0.0 in `Param.asBytes()` method

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1757]
We decided that we won't transform `0.0` to `-0.0` to get `FALSE` as result of `0.0.eq 0`. 

After [this](https://github.com/objectionary/eo-math/issues/104) ticket is closed it's necessary to get rid of this transformation in `Param.asBytes()` method.

@Graur please assign me

**Comment by Graur** [comment]
@maxonfjvipon Sure, go ahead. The budget is 30 min

**Comment by maxonfjvipon** [comment]
@Graur btw, I forgot to ask: after we remove this transformation 0.0 to -0.0 if we try to do `0.0.eq 0` or `0.eq 0.0` - they both will be `TRUE`. Is this correct? 

Mb we should not only remove this transformation 0.0 to -0.0 but also modify `float.eq` and `int.eq` objects? Like this:
```
[] > float
    [x] > eq
        eq. > @
            ^.neg.as-bytes
            x.neg.as-bytes
```

Then if we do `0.0.eq 0` => `-0.0.eq 0` => `FALSE` and `0.eq 0.0` => `0.eq -0.0` => FALSE

**Comment by Graur** [comment]
@maxonfjvipon  Indeed. Or we can make this rule only for zeroes
