### ISSUE TITLE
Release a new version of `eo` - `0.28.18`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1776]
I believe we have to release a new version of `eo`: `0.28.18`. It's especially useful since we implemented [some optimisations](https://github.com/objectionary/eo/issues/1705). They reduce total dataization time significantly (x2 on my laptop)

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.18`

**Comment by yegor256** [comment]
@volodya-lombrozo done

**Comment by volodya-lombrozo** [comment]
Thanks
