### ISSUE TITLE
Release a new version of `eo` - `0.29.0`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1777]
@yegor256 Since `eo-runtime` was [extended](#1752) with 3 new objects: `nan`, `positive-infinity` and `negative-infinity`; I believe we should release them so we could continue developing in other eo packages relaying on theses new objects (for example - [here](https://github.com/objectionary/eo-math/issues/105))

**Comment by maxonfjvipon** [comment]
@yegor256 When will it be ready to release? It kind of blocks developing in other packages

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.0`

**Comment by maxonfjvipon** [comment]
@yegor256 thanks
