### ISSUE TITLE
What is the footprint for?

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1786]
It is not clear from the comments and tests what the `Footprint` is for and what its methods do. What and where do they `save` and `load`? At first I thought it was like a log, but this class is created anew in the places of use every time.
I guess the description of this class should be made clearer.
@Graur WDYT?

**Comment by volodya-lombrozo** [comment]
@levBagryansky I had been confused with `Footprint` class too. We even discussed that with @mximp  in that [PR](https://github.com/objectionary/eo/issues/1420):
> @volodya-lombrozo In this case footprint refers to a trace of EO program on file system which is quite fortunate analogy with natural meaning of the word.

But I still believe, that we have to make it more clear from the code. I believe we have to add more info in JavaDoc.

**Comment by levBagryansky** [comment]
@volodya-lombrozo Thanks! Now the idea of this class has become clearer for me.

**Comment by volodya-lombrozo** [comment]
@levBagryansky Can I ask you to send a PR that adds description to the `Footprint` JavaDoc? How you understand it. I'm sure, It will be quite helpful for other.

**Comment by levBagryansky** [comment]
@volodya-lombrozo sure
