### ISSUE TITLE
Rename "array" to "tuple"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1790]
I think the name "array" is confusing. See https://stackoverflow.com/questions/49047886/whats-difference-between-array-and-tuple We actually have tuples, not arrays. First, they have objects of different types. Second, they are immutable and have fixed length.

**Comment by yegor256** [comment]
@volodya-lombrozo please, help us here

**Comment by yegor256** [comment]
@volodya-lombrozo don't forget to update the paper (in the `paper/` directory) since it also mentions "arrays"

**Comment by maxonfjvipon** [comment]
@yegor256 speaking of meaning - what's the difference between `array` and `list`?

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1821](https://github.com/objectionary/eo/issues/1821) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.1`

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1821](https://github.com/objectionary/eo/issues/1821) is solved here.
