### ISSUE TITLE
Allow division by float zero in `EOfloat$EOdiv`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1791]
Allow division by float zero in `EOfloat$EOdiv` for being able to make `nan`, `positive-infinity` and `negative-infinity` decorated `0.0.div 0.0`, `1.0.div 0.0` and `-1.0.div 0.0`

This task had to be created by `pdd` bot after [this PR](#1752) but it hadn't for some reason.

@Graur please assign me

**Comment by Graur** [comment]
@maxonfjvipon Sure, go ahead. We will fix `pdd` later.
The budget is 30 min.

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#1803](https://github.com/objectionary/eo/issues/1803) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#1803](https://github.com/objectionary/eo/issues/1803) is solved here.
