### ISSUE TITLE
Remove unwanted objects from nan, +inf and -inf

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1799]
Since these are object are float numbers but special - they should not have extra and unwanted objects that usual float does not have like: neq, signum, as-int. as-bytes also can be removed because it can be got from the result of @ object

The issue had be created by `pdd` bot after [this PR](https://github.com/objectionary/eo/pull/1792) but it had not for some reason. 

@Graur please assign me

**Comment by Graur** [comment]
@maxonfjvipon Sure, go ahead. The budget is 30 min

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#1806](https://github.com/objectionary/eo/issues/1806) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon 3 puzzles [#1824](https://github.com/objectionary/eo/issues/1824), [#1825](https://github.com/objectionary/eo/issues/1825), [#1826](https://github.com/objectionary/eo/issues/1826) are still not solved; solved: [#1806](https://github.com/objectionary/eo/issues/1806).

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#1826](https://github.com/objectionary/eo/issues/1826) is still not solved; solved: [#1806](https://github.com/objectionary/eo/issues/1806), [#1824](https://github.com/objectionary/eo/issues/1824), [#1825](https://github.com/objectionary/eo/issues/1825).

**Comment by 0pdd** [comment]
@maxonfjvipon all 4 puzzles are solved here: [#1806](https://github.com/objectionary/eo/issues/1806), [#1824](https://github.com/objectionary/eo/issues/1824), [#1825](https://github.com/objectionary/eo/issues/1825), [#1826](https://github.com/objectionary/eo/issues/1826).
