### ISSUE TITLE
nan.eo:28-30: Allow division by float zero in...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1800]
The puzzle `1253-c101194f` from #1253 has to be resolved: 

https://github.com/objectionary/eo/blob/6abf13e786ce2aadce74948a30203b4e9cb7b890/eo-runtime/src/main/eo/org/eolang/nan.eo#L28-L30

The puzzle was created by @rultor on 15-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
Duplicate of #1791 
@yegor256 please close

**Comment by yegor256** [comment]
@maxonfjvipon  I can't close it. If I do, PDD will re-open again, since the puzzle is still in the code. The only solution is to remove the puzzle from the code.

**Comment by 0pdd** [comment]
The puzzle `1253-c101194f` has disappeared from the source code, that's why I closed this issue.
