### ISSUE TITLE
positive-infinity.eo:29-31: Make "+inf" and "-inf" looked...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1806]
The puzzle `1799-32659a06` from #1799 has to be resolved: 

https://github.com/objectionary/eo/blob/aadc492f394cb45c812aff39c26c20c5865316a9/eo-runtime/src/main/eo/org/eolang/positive-infinity.eo#L29-L31

The puzzle was created by @rultor on 16-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@maxonfjvipon Sure, go ahead. The budget is 30 min

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1824](https://github.com/objectionary/eo/issues/1824), [#1825](https://github.com/objectionary/eo/issues/1825), [#1826](https://github.com/objectionary/eo/issues/1826) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1826](https://github.com/objectionary/eo/issues/1826) is still not solved; solved: [#1824](https://github.com/objectionary/eo/issues/1824), [#1825](https://github.com/objectionary/eo/issues/1825).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1824](https://github.com/objectionary/eo/issues/1824), [#1825](https://github.com/objectionary/eo/issues/1825), [#1826](https://github.com/objectionary/eo/issues/1826).
