### ISSUE TITLE
ParsingTrain.java:57-60: Add xsl transformation that...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1809]
The puzzle `1542-94d035b1` from #1542 has to be resolved: 

https://github.com/objectionary/eo/blob/8f4cff3e4b5fb18b05e03944c5c718bd9402cd44/eo-parser/src/main/java/org/eolang/parser/ParsingTrain.java#L57-L60

The puzzle was created by rultor on 16-Feb-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@Graur I can do it

**Comment by Graur** [comment]
@levBagryansky Sure, go ahead

**Comment by levBagryansky** [comment]
@yegor256 are alloved only versions versions consisting of three numbers separated by a dot or more free like 1.0.0-alpha.beta?

**Comment by yegor256** [comment]
@levBagryansky just three numbers with dots between them, no letters, no dashes. pure [SemVer](https://semver.org/)
