### ISSUE TITLE
Remake `float.minus` and `int.minus` without using `QQ.collections.list.mapped`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1812]
As already discussed [here](https://github.com/objectionary/eo/issues/1724) it would be nice to make `eo-runtime` independent of `eo-collections`. One of the steps to achieve this - remake `float.minus` and `int.minus` without using `list.mapped` from `eo-collections`

@yegor256 if it's relevant, please assing me, I can do it

**Comment by maxonfjvipon** [comment]
As already discussed [here](https://github.com/objectionary/eo/issues/1724) it would be nice to make `eo-runtime` independent of `eo-collections`. One of the steps to achieve this - remake `float.minus` and `int.minus` without using `list.mapped` from `eo-collections`

@yegor256 if it's relevant, I can do it

**Comment by yegor256** [comment]
@maxonfjvipon let's do it!

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#1818](https://github.com/objectionary/eo/issues/1818) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#1818](https://github.com/objectionary/eo/issues/1818) is solved here.
