### ISSUE TITLE
switch.eo:44-46: Remake "switch" without using...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1818]
The puzzle `1812-9ede52a3` from #1812 has to be resolved: 

https://github.com/objectionary/eo/blob/5c3902fd9817c78d03dab5d1f3d68f671df1ec64/eo-runtime/src/main/eo/org/eolang/switch.eo#L44-L46

The puzzle was created by @maxonfjvipon on 20-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@yegor256 please assign me

**Comment by yegor256** [comment]
@maxonfjvipon go ahead
