### ISSUE TITLE
Flaky tests breaks pipelines (`StackOverflowError `)

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1819]
We again have a problem with flaky tests in `eo-runtime`. The common problem is `StackOverflowError `:
```
EOcompares_string_with_nan_and_infinitesTest.testWorks:127->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256 » Ex EOorg.EOeolang.EOstringν115936="Unexpected error 'null' of type StackOverflowError; caused by "SF
```

Failed pipelines:
1. https://github.com/objectionary/eo/actions/runs/4182605213/jobs/7245904469
2. https://github.com/objectionary/eo/actions/runs/4221651017/jobs/7329203665

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo in first pipeline `EOnegative_infinity_eq_is_validTest` does not exist anymore. Can you merge `master` into your branch and try again?

**Comment by volodya-lombrozo** [comment]
I have [that](https://github.com/objectionary/eo/actions/runs/4221651017/jobs/7329203665#step:5:42563) errors couple of hours ago where master branch was merged. Do you know the reason for such a behaviour? Or at least place where it comes from.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo not really, there's nothing special about `nan`, `+inf` or `-inf`, they're just regular floats. Did the tests pass on your local machine?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Not always

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I think this test may be a reason of such behavior:
```

[] > float-equal-to-nan-and-infinites-is-false
  assert-that > @
    and.
      (0.0.eq nan).eq FALSE
      (0.0.eq positive-infinity).eq FALSE
      (0.0.eq negative-infinity).eq FALSE
      (42.5.eq nan).eq FALSE
      (42.5.eq positive-infinity).eq FALSE
      (42.5.eq negative-infinity).eq FALSE
    $.equal-to TRUE
```

Need to divide to several tests

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Apparently you right. I have tried to make that test even worse:
```eo
[] > float-equal-to-nan-and-infinites-is-false
  assert-that > @
    and.
      (0.0.eq nan).eq FALSE
      (0.0.eq positive-infinity).eq FALSE
      (0.0.eq negative-infinity).eq FALSE
      (42.5.eq nan).eq FALSE
      (42.5.eq positive-infinity).eq FALSE
      (42.5.eq negative-infinity).eq FALSE
      (0.0.eq nan).eq FALSE
      (0.0.eq positive-infinity).eq FALSE
      (0.0.eq negative-infinity).eq FALSE
      (42.5.eq nan).eq FALSE
      (42.5.eq positive-infinity).eq FALSE
      (42.5.eq negative-infinity).eq FALSE
      (0.0.eq nan).eq FALSE
      (0.0.eq positive-infinity).eq FALSE
      (0.0.eq negative-infinity).eq FALSE
      (42.5.eq nan).eq FALSE
      (42.5.eq positive-infinity).eq FALSE
      (42.5.eq negative-infinity).eq FALSE
      (0.0.eq nan).eq FALSE
      (0.0.eq positive-infinity).eq FALSE
      (0.0.eq negative-infinity).eq FALSE
      (42.5.eq nan).eq FALSE
      (42.5.eq positive-infinity).eq FALSE
      (42.5.eq negative-infinity).eq FALSE
    $.equal-to TRUE
```
And test took unreasonable number of time (after 15min I just stopped it), but I think it's much easier (and more correctly) to optimise that code rather than invent some rules for "correct test practices".

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I think one "`eq` = one test" has to solve the problem

**Comment by maxonfjvipon** [comment]
@yegor256 I may check all such heavy and unoptimized tests and fix them if you'll assign me

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo I think "one `eq` = one test" has to solve the problem

It looks like a temporary solution (any new developer will write test that will use several `eq` statements because he/she **can** do it). I believe It would be better to optimise the current runtime instead of applying restrictions that might be violated easily.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo what exactly do you propose?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon I don't know yet. Maybe we can reduce number of delegate objects in order to reduce the Stack usage.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon I don't know yet. Maybe we can reduce number of delegate objects in order to reduce the Stack usage.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo maybe, but I still think that we can optimize and divide these tests now so they won't be a reason of failed pipelines until we figure out how to reduce memory usage

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Looks reasonable to me. Can I ask you to create a separate issue for the real optimisation (to find the root cause of the problem)? In that issue we can "divide" tests.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo sure
