### ISSUE TITLE
positive-infinity.eo:133-135: Make positive-infinity.div...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1826]
The puzzle `1806-865a59ed` from #1806 has to be resolved: 

https://github.com/objectionary/eo/blob/5e7de947b9ccf96e11cbf4729f0d4909a35fdc9e/eo-runtime/src/main/eo/org/eolang/positive-infinity.eo#L133-L135

The puzzle was created by @rultor on 20-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@maxonfjvipon Sure, go ahead. The budget is 30 min
