### ISSUE TITLE
Complex tests with many `eq` operations cause `StackOverflowError` and break CI pipeline

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1829]
(Ref #1819)
For example this test sometimes leads to `StackOverflowError` on CI pipeline (see [here](https://github.com/objectionary/eo/actions/runs/4221651017/jobs/7329203665#step:5:42563)):
```
[] > float-equal-to-nan-and-infinites-is-false
  assert-that > @
    and.
      (0.0.eq nan).eq FALSE
      (0.0.eq positive-infinity).eq FALSE
      (0.0.eq negative-infinity).eq FALSE
      (42.5.eq nan).eq FALSE
      (42.5.eq positive-infinity).eq FALSE
      (42.5.eq negative-infinity).eq FALSE
    $.equal-to TRUE
```

> any new developer will write test that will use several eq statements because he/she can do it (c) @volodya-lombrozo 

Such tests may appear in the future, so need to find the root of the problem why such tests are executed so long and cause StackOverflow

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Thanks

**Comment by volodya-lombrozo** [comment]
It seems that this is the reason why the latest CI/CD build failed

**Comment by volodya-lombrozo** [comment]
The problem remains even with stack size equals `128M`.
In order to reproduce error just run maven tests with the next option:
```
mvn clean test -Dsurefire.runOrder.random.seed=175748496429432
```

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#1986](https://github.com/objectionary/eo/issues/1986) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#1986](https://github.com/objectionary/eo/issues/1986) is solved here.
