### ISSUE TITLE
Caching mechanism in `~/.eo` is misleading.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1836]
Quite often I face with a problem of updating and using cached objects from `~/.eo`. It's especially uncomfortable when we change something inside `eo-runtime` or `eo-parser`. Why it happens:
1. We change objects in `eo-runtime`
2. Install new `eo-runtime` locally by `mvn install` or download a new version from the internet.
3. Then we expect that new logic will applied when we run `eoc dataize`
4. But in reality it doesn't happen
5. When `eo-maven-plugin` starts its work it gets results from old `~/.eo`  cache folder and doesn't apply new changes from `eo-runtime`, `eo-parser` or even from `eo-maven-plugin`

Of course you can just run `rm -rf ~/.eo` and everything will work fine, but sometimes you have to spend time to realise that you have to clean the cache.
I believe it means that we have not so perfect caching mechanism. As I see not only me who have the same problem.

**Comment by yegor256** [comment]
@volodya-lombrozo this will be solved when we fix #1226, I believe

**Comment by volodya-lombrozo** [comment]
Since we implemented improved caching mechanism in #1226, I think, we can close that issue. If we face with the same problem again we can reopen that issue or create an another one.
