### ISSUE TITLE
total lines of code badge is not working

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/eo#1837]
badge "lines of code" [isn't working](https://camo.githubusercontent.com/ddcd95b3ab9ea47890a7e579354034727bbacdb7daaeed68045ae7091eb8d190/68747470733a2f2f696d672e736869656c64732e696f2f746f6b65692f6c696e65732f6769746875622f6f626a656374696f6e6172792f656f). Maybe we can even remove this badge, since we already have "Hits of Code" metric.

**Comment by yegor256** [comment]
@h1alexbel maybe we can replace it with this: https://shields.io/category/size

**Comment by h1alexbel** [comment]
@yegor256 you mean file count? or size in MB? or lines of code?

**Comment by yegor256** [comment]
@h1alexbel I mean lines of code

**Comment by h1alexbel** [comment]
@yegor256 badge on https://shields.io/category/size the same as in README, so it's broken

**Comment by h1alexbel** [comment]
since rn it works ok, I close this ticket
