### ISSUE TITLE
Can not create a `tuple` of objects-functions

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1841]
Let's imagine I have two objects which of which has one free attribute

```
[arg] > first
  arg.plus 1 > @
[arg] > second
  arg.plus 2 > @ 
```

I want to pass these objects TOGETHER to another `object` that will use them the way he wants. I put these objects into `tuple` like this:
```
* > arr
  first
  second

[arr] > object
  arr.at 0 > f
  arr.at 1 > s
  plus. > @
    f 1
    s 2
```

When I do `object arr` and it will be dataized I expect I'll get `6` but I get next:
_Ex EOorg.EOeolang.EOstringν133699="EOorg.EOeolang.EOtuple$EOatν133694 has just 1 attribute(s), can't read the 1-th one"SF_

___
Here's the test I wrote and it fails:
```
[] > tuple-of-two
  [arg] > first
    arg.plus 1 > @
  [arg] > second
    arg.plus 2 > @
  * > t
    first
    second
  assert-that > @
    plus.
      t.at 0
        1
      t.at 1
        2
    $.equal-to 6
```

_Oorg.EOeolang.EOtuple$EOatν100363 has just 1 attribute(s), can't read the 1-th one"SF
[ERROR]   EOtuple_of_twoTest.testWorks:127->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255 » Ex EOorg.EOeolang.EOstringν133699="EOorg.EOeolang.EOtuple$EOatν133694 has just 1 attribute(s), can't read the 1-th one"SF_

**Comment by maxonfjvipon** [comment]
There is also one more similar problem: two or more objects-functions can not be passed to another object
```
[arg] > func1
  arg.plus 1 > @
[arg] > func2
  arg.plus 2 > @

[f1 f2] > obj
  plus. > @
    f1 1
    f2 2

obj > obj-with-funcs
  func1
  func2
```

When `obj-with-funcs` will be tried to dataize it will say:
_Error at "EOorg.EOeolang.EOtuple$EOat#i" attribute; caused by ExReadOnly: This free attribute is already set, can't reset"SF_

**Comment by maxonfjvipon** [comment]
@yegor256 @volodya-lombrozo WDYT? Am I doing something wrong?

**Comment by yegor256** [comment]
@maxonfjvipon can you please post a fully reproducible example? So that I can run it "as is" and see the output.

**Comment by maxonfjvipon** [comment]
@yegor256 will these tests be enough? The first one works fine. The second and the third fails.
```
[] > tuple-of-funcs-1
  [arg] > func1
    arg.plus 1 > @
  [arg] > func2
    arg.plus 2 > @
  [f1 f2] > obj
    plus. > @
      f1 1
      f2 2
  obj > new-obj
    func1
    func2
  assert-that > @
    new-obj
    $.equal-to 6

[] > tuple-of-funcs-2
  [arg] > func1
    arg.plus 1 > @
  [arg] > func2
    arg.plus 2 > @
  [funcs] > obj
    funcs.at 0 > f1
    funcs.at 1 > f2
    plus. > @
      f1 1
      f2 2
  obj > new-obj
    *
      func1
      func2
  assert-that > @
    new-obj
    $.equal-to 6

[] > tuple-of-funcs-3
  [arg] > func1
    arg.plus 1 > @
  [arg] > func2
    arg.plus 2 > @
  [args...] > obj
    args.at 0 > f1
    args.at 1 > f2
    plus. > @
      f1 1
      f2 2
  obj > new-obj
    func1
    func2
  assert-that > @
    new-obj
    $.equal-to 6
```

**Comment by Graur** [comment]
@maxonfjvipon I've got the different error in `tuple-of-funcs-2` and `tuple-of-funcs-3` examples:

```
EOtuple_of_funcs_2Test.testWorks:107->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255 » Ex EOorg.EOeolang.EOstringν67864="The object is at the line #234, position #6 within `?`; caused by Error at "obj.f1" attribute; caused by The object is at the line #231, position #9 within `?`; caused by Error at "obj.funcs" attribute; caused by Error at "tuple.at" attribute; caused by The object is at the line #41, position #2 within `?`; caused by ExReadOnly: Error at "EOorg.EOeolang.EOtuple$EOat#i" attribute; caused by ExReadOnly: This free attribute is already set, can't reset"SF
```

Do we really need an immutable `array` here (or `tuple` in a new EO version) ? Maybe it's better to use mutable structure (or wrapped) object instead?
e.g.:
```
[] > tuple-of-funcs-2
  [] > func3
    [arg] > func1
      arg.plus 1 > @
    [arg] > func2
      arg.plus 2 > @
  [func] > obj
    plus. > @
      func.func1 1
      func.func2 2
  assert-that > @
    obj func3
    $.equal-to 6
```

**Comment by mximp** [comment]
@maxonfjvipon @Graur what is up with this task?

**Comment by maxonfjvipon** [comment]
I found and used a workaround. But I suppose there's a bug here. @Graur WDYT?

**Comment by Graur** [comment]
@maxonfjvipon I disagree. According to this paper: https://arxiv.org/pdf/2206.02585.pdf:

> The object array is an abstraction of an immutable
sequence of objects

But your objects are mutable

**Comment by maxonfjvipon** [comment]
@yegor256 I'm closing it since it's no more relevant because of new implementation of tuple and inability to make an abstract objects in tuple closed
