### ISSUE TITLE
target directories numerating

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1842]
I started `mvn clean install` and looked at folders in target
```
tardis3@RyanGosling:~/eo$ la eo-runtime/target/eo
итого 236K
drwxrwxr-x 3 1000 1000 4,0K фев 24 21:06 01-parse/
drwxrwxr-x 3 1000 1000 4,0K фев 24 21:06 03-optimize/
drwxrwxr-x 3 1000 1000 4,0K фев 24 21:06 04-pull/
drwxrwxr-x 3 1000 1000 4,0K фев 24 21:06 05-pre/
drwxrwxr-x 4 1000 1000 4,0K фев 24 21:06 06-resolve/
drwxrwxr-x 3 1000 1000 4,0K фев 24 21:06 06-transpile/
-rw-rw-r-- 1 1000 1000  33K фев 24 21:07 foreign.csv
-rw-rw-r-- 1 1000 1000  11K фев 24 21:08 placed.csv
-rw-rw-r-- 1 1000 1000 163K фев 24 21:07 transpiled.csv
tardis3@RyanGosling:~/eo$ 
```
So there are 2 folders starting from `06-..`.
Is it ok?
@volodya-lombrozo WDYT

**Comment by levBagryansky** [comment]
and where is `02-...` folder?

**Comment by volodya-lombrozo** [comment]
@levBagryansky Indeed, the numbers are misleading. I believe we need to either understand and describe why the numbers are inaccurate (by updating the JavaDoc or performing a refactoring), or simply fix the numbering. Do you want to implement the issue?

**Comment by volodya-lombrozo** [comment]
@yegor256 Did you put any thought into the numbering?

**Comment by yegor256** [comment]
@volodya-lombrozo they just need to go one after another. If this is not the case, let's fix them.

**Comment by levBagryansky** [comment]
@volodya-lombrozo it is easy to fix but I don't see the way to test it.

**Comment by volodya-lombrozo** [comment]
@levBagryansky You can check after integration tests run. Like we did it [here](https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/it/custom_goals/verify.groovy).

**Comment by yegor256** [comment]
@volodya-lombrozo @levBagryansky @mximp  maybe, in order to prevent this misordering in the future, we can add a Groovy test to our project, which would check that all directories in the `eo-runtime/target/eo` are named correctly. We have similar tests for checking the our `.xsl` stylesheets have proper values of `@id` attributes. Such tests are also structural and global (they check the structure of the project, not its functionality).

**Comment by volodya-lombrozo** [comment]
@yegor256 Totally agree

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#1849](https://github.com/objectionary/eo/issues/1849) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the only puzzle [#1849](https://github.com/objectionary/eo/issues/1849) is solved here.
