### ISSUE TITLE
`0.0.gte -0.0` must be `FALSE` but it's `TRUE` now

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#1844]
- 0.0 is not greater that -0.0 because they are zeros
- 0.0 is not equal to -0.0 because 
  `0.0.as-bytes` => `00-00-00-00-00-00-00-00`
  `-0.0.as-bytes` => `80-00-00-00-00-00-00-00`

This test is not being passed
```
[] > zero-not-eq-to-neg-zero
  assert-that > @
    0.0.gte -0.0
    $.equal-to FALSE
```

The reason - current implementation of `float.gte`:
```
# Tests that $ ≥ x
[x] > gte
  if. > @
    x.as-bytes.eq nan.as-bytes
    FALSE
    not.
      ^.lt x
```

I think it should be:
```
# Tests that $ ≥ x
[x] > gte
  if. > @
    x.as-bytes.eq nan.as-bytes
    FALSE
    or.
      ^.gt x
      ^.eq x
```

The same story with `float.lte`

@yegor256 @Graur WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon let's fix it?

**Comment by maxonfjvipon** [comment]
@yegor256 sure, I can do it

**Comment by yegor256** [comment]
@maxonfjvipon please, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.2`
