### ISSUE TITLE
Rename +junit meta to +tests

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1869]
It seems that the name `junit` is not generic enough. We may compile `.eo` files into other languages, not only Java. I believe, `+tests` name would be more appropriate. Let's rename.

**Comment by yegor256** [comment]
@mximp pls, help with this

**Comment by mximp** [comment]
@yegor256 any objection?

**Comment by mximp** [comment]
@yegor256 can we please release & publish `eo-runtime`.
We need to make `+tests` available to continue changes on this task.

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.4`

**Comment by yegor256** [comment]
@mximp any ideas?

**Comment by mximp** [comment]
@yegor256 not yet.. trying to reproduce it locally.
Has anything been changed in run command?

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.4`
