### ISSUE TITLE
Objects with only one @-bound attribute

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1871]
Imagine this code:

```
x.while
  [i]
    stdout "Hello!" > @
```

Maybe, we can let users make it shorter:

```
x.while
  stdout "Hello!" > [i]
```

Thus, `b > [x y z]` means `[x y z] b > @`.

This syntax sugar will reduce the number of indentations.

**Comment by yegor256** [comment]
@mximp please, help here

**Comment by yegor256** [comment]
@maxonfjvipon please help

**Comment by maxonfjvipon** [comment]
@yegor256 if you ask me, I would leave only horizontal objects:
1. horizontal method
```
x.y.z > [i]
```
2. horizontal application
```
x y z > [i]
```
3. reversed horizontal application
```
if. TRUE a b > [i]
```

**Comment by yegor256** [comment]
@maxonfjvipon I agree, let's make it possible to use this new syntax _only_ in one line
