### ISSUE TITLE
Unexpected content of triple quote """ """

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1885]
The test below
```
[] > print-triple-quotes
  QQ.io.stdout > @
    """
    Hello

    Hello
    """
``` 
prints 
```
Hello
 Hello
```
But the expected (as for me) output is
```
Hello
Hello
```
@yegor256 @Graur Is it so intended or a bug?

**Comment by Graur** [comment]
@levBagryansky Definitely a bug. But I suggest expected like:
```
Hello

Hello
```

Btw, do you have some spaces between these words?

**Comment by levBagryansky** [comment]
@Graur yes, your option is correct
