### ISSUE TITLE
Extremely long build 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1894]
As I see we have a quite long builds last time. 
For example [here](https://github.com/objectionary/eo/actions/runs/4406621594/jobs/7719120942) and [here](https://github.com/objectionary/eo/actions/runs/4405694087/jobs/7716913349).
The same problem I experience on my laptop.  For example, I have the next program:
```eo
[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "Magic number is %d"
      4815162342
```

When I run `eoc dataize app --clean` the compilation process take me ~20 min.
___
I have provided 3 rounds of profiling - results I apply to comments. As I see - the problem in `PlaceMojo#place` method:
```java
final Collection<Tojo> before = this.placedTojos.value().select(
                row -> row.get(Tojos.KEY).equals(target.toString())
                    && "class".equals(row.get(PlaceMojo.ATTR_PLD_KIND))
);
```

**Comment by volodya-lombrozo** [comment]
First 100 sec of compilation
![compile](https://user-images.githubusercontent.com/51804353/224759168-292c6642-8ff3-4f18-b1a1-af697921b685.svg)

**Comment by volodya-lombrozo** [comment]
Last 100 sec of compilation
![compile2](https://user-images.githubusercontent.com/51804353/224759277-c97bbb35-c38c-4a0f-bf92-28f171fc0008.svg)

**Comment by volodya-lombrozo** [comment]
300 sec of a separate compilation
![compile300sec](https://user-images.githubusercontent.com/51804353/224759467-d6ee4123-3b5e-4f07-b293-c78dc2500123.svg)

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1928](https://github.com/objectionary/eo/issues/1928) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#1928](https://github.com/objectionary/eo/issues/1928) is solved here.
