### ISSUE TITLE
Checks on windoss take too long 

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1898]
I created a pr #1895 with a minor change so it must pass check successfully. However tests on windows passed 6 hours and in the end were cancelled.
@Graur please check

**Comment by volodya-lombrozo** [comment]
@Graur why does that object influence `eo` build? Do we use it somewhere inside `eo-runtime`?

**Comment by levBagryansky** [comment]
@volodya-lombrozo there is a test
```
[] > makes-object-a-constant
  [] > foo
    as-int. > @
      number
        times.
          random.pseudo
          100.0
  foo.@ > f!
  assert-that > @
    f
    $.equal-to f
```
in `eo-runtime`

**Comment by volodya-lombrozo** [comment]
@levBagryansky I see. Thanks

**Comment by Graur** [comment]
@levBagryansky @volodya-lombrozo The root of this issue is unreleased `eo-sys`

**Comment by volodya-lombrozo** [comment]
@Graur Are you going to release it?

**Comment by Graur** [comment]
@volodya-lombrozo I will try to do it ASAP
