### ISSUE TITLE
Enable windows build during GitHub actions

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1907]
We temporary disabled Windows build during Github Actions, but when all problems will be fixed we have to return it back.

Source: https://github.com/objectionary/eo/pull/1906

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1934](https://github.com/objectionary/eo/issues/1934) is still not solved.

**Comment by volodya-lombrozo** [comment]
> > @rultor release, tag is `0.29.3`
> 
> @volodya-lombrozo @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/31057-1486787582) (spent 7min)
> 
> ```
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_gt_negative_infinityTest.testWorks:43->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_gte_negative_infinityTest.testWorks:53->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_multiple_floatsTest.testWorks:70->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_multiple_numbers_with_negative_infinityTest.testWorks:69->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_negative_floatTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_negative_infinityTest.testWorks:59->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_negative_intTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_positive_floatTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_positive_infinityTest.testWorks:67->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_minus_positive_intTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_neg_is_negative_infinityTest.testWorks:47->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_not_eq_negative_infinityTest.testWorks:52->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_not_lte_negative_infinityTest.testWorks:53->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_multiple_floatsTest.testWorks:70->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_multiple_numbersTest.testWorks:70->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_multiple_numbers_with_nanTest.testWorks:77->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_multiple_numbers_with_negative_infinityTest.testWorks:70->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_negative_infinityTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_positive_floatTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_positive_infinityTest.testWorks:59->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_plus_positive_intTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_multiple_infinitesTest.testWorks:78->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_multiple_positive_numbersTest.testWorks:70->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_negative_infinityTest.testWorks:59->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_positive_floatTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_positive_infinityTest.testWorks:59->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_positive_intTest.testWorks:60->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m  EOpositive_infinity_times_two_negative_numbersTest.testWorks:65->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256->PhDefault.attr:255->PhDefault.attr:256->PhDefault.attr:256 » IllegalState Recursive update\u001b[m
> [\u001b[1;34mINFO\u001b[m] 
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31mTests run: 709, Failures: 0, Errors: 90, Skipped: 2\u001b[m
> [\u001b[1;34mINFO\u001b[m] 
> [\u001b[1;34mINFO\u001b[m] \u001b[1m------------------------------------------------------------------------\u001b[m
> [\u001b[1;34mINFO\u001b[m] \u001b[1mReactor Summary for eo 0.29.3:\u001b[m
> [\u001b[1;34mINFO\u001b[m] 
> [\u001b[1;34mINFO\u001b[m] eo ................................................. \u001b[1;32mSUCCESS\u001b[m [ 10.948 s]
> [\u001b[1;34mINFO\u001b[m] eo-parser .......................................... \u001b[1;32mSUCCESS\u001b[m [ 30.077 s]
> [\u001b[1;34mINFO\u001b[m] eo-maven-plugin .................................... \u001b[1;32mSUCCESS\u001b[m [ 51.677 s]
> [\u001b[1;34mINFO\u001b[m] eo-runtime ......................................... \u001b[1;31mFAILURE\u001b[m [03:31 min]
> [\u001b[1;34mINFO\u001b[m] \u001b[1m------------------------------------------------------------------------\u001b[m
> [\u001b[1;34mINFO\u001b[m] \u001b[1;31mBUILD FAILURE\u001b[m
> [\u001b[1;34mINFO\u001b[m] \u001b[1m------------------------------------------------------------------------\u001b[m
> [\u001b[1;34mINFO\u001b[m] Total time:  05:04 min
> [\u001b[1;34mINFO\u001b[m] Finished at: 2023-03-28T13:15:37Z
> [\u001b[1;34mINFO\u001b[m] \u001b[1m------------------------------------------------------------------------\u001b[m
> [\u001b[1;31mERROR\u001b[m] Failed to execute goal \u001b[32morg.apache.maven.plugins:maven-surefire-plugin:3.0.0-M8:test\u001b[m \u001b[1m(default-test)\u001b[m on project \u001b[36meo-runtime\u001b[m: \u001b[1;31m\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31m\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31mPlease refer to /home/r/repo/eo-runtime/target/surefire-reports for the individual test results.\u001b[m
> [\u001b[1;31mERROR\u001b[m] \u001b[1;31mPlease refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.\u001b[m
> [\u001b[1;31mERROR\u001b[m] -> \u001b[1m[Help 1]\u001b[m
> [\u001b[1;31mERROR\u001b[m] 
> [\u001b[1;31mERROR\u001b[m] To see the full stack trace of the errors, re-run Maven with the \u001b[1m-e\u001b[m switch.
> [\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
> [\u001b[1;31mERROR\u001b[m] 
> [\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
> [\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [\u001b[1;31mERROR\u001b[m] 
> [\u001b[1;31mERROR\u001b[m] After correcting the problems, you can resume the build with the command
> [\u001b[1;31mERROR\u001b[m]   \u001b[1mmvn <args> -rf :eo-runtime\u001b[m
> \u001b[0m\u001b[0mcontainer 7be839c54a9fb691eb81874594d00e8867634cfca78f98cfa59bc5f6eca69d39 is dead
> Tue 28 Mar 2023 03:16:47 PM CEST
> ```

https://github.com/objectionary/eo/issues/1939

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#1934](https://github.com/objectionary/eo/issues/1934) is solved here.
