### ISSUE TITLE
PlaceMojo.java:252-255: Replace PlaceMojo#placedCache...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1928]
The puzzle `1894-1f27a75b` from #1894 has to be resolved: 

https://github.com/objectionary/eo/blob/7caa635046cd0b16a04e4e6040104881ca80850d/eo-maven-plugin/src/main/java/org/eolang/maven/PlaceMojo.java#L252-L255

The puzzle was created by rultor on 20-Mar-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/yegor256/tojos/pull/63
