### ISSUE TITLE
Parallel TranspileMojo

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1940]
Now `xmir` files in `TranspileMojo` sequentially converted to `.java`. I guess they can be carried out in parallel  since the conversions of different `.xmir` files do not depend on each other. 
@volodya-lombrozo WDYT?

**Comment by volodya-lombrozo** [comment]
@levBagryansky I think you are right. At least it looks like we can transpile `xmir` to `java` in parallel. Let's try.
