### ISSUE TITLE
Refactor Foreign Tojos

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1969]
We have encapsulation problem with foreign tojos file. All attributes of the foreign tojos are scattered throughout the program.  
It's hard to maintain it and add new features. I believe we can refactor it and encapsulate all logic inside `ForeignTojos` class.

Similar to: #1929

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#1989](https://github.com/objectionary/eo/issues/1989), [#1990](https://github.com/objectionary/eo/issues/1990) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#1989](https://github.com/objectionary/eo/issues/1989), [#1990](https://github.com/objectionary/eo/issues/1990), [#2018](https://github.com/objectionary/eo/issues/2018) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#1990](https://github.com/objectionary/eo/issues/1990), [#2018](https://github.com/objectionary/eo/issues/2018) are still not solved; solved: [#1989](https://github.com/objectionary/eo/issues/1989).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 3 puzzles are solved here: [#1989](https://github.com/objectionary/eo/issues/1989), [#1990](https://github.com/objectionary/eo/issues/1990), [#2018](https://github.com/objectionary/eo/issues/2018).
