### ISSUE TITLE
BinarizeMojoTest.java:48-50:...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1986]
The puzzle `1829-71075212` from #1829 has to be resolved: 

https://github.com/objectionary/eo/blob/2a1c35fe39fe9423c34642e673fb543271900fa8/eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeMojoTest.java#L48-L50

The puzzle was created by volodya-lombrozo on 11-Apr-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@volodya-lombrozo sure. Maybe you still have a stack trace error?

**Comment by volodya-lombrozo** [comment]
@levBagryansky We have already fix it.
