### ISSUE TITLE
Codacy fails on conventional package name

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1994]
In pr #1992 I created a new atom `rust` and implemented it in `EOrust.java` class with package `EOorg.EOeolang`. 
Codacy fails on this new line since "Package name contains upper case characters"  [here](https://app.codacy.com/gh/objectionary/eo/pullRequest?prid=11557609#newIssuesView) . It is a problem because rultor now cannot merge changes if some checks fails.
@volodya-lombrozo @yegor256 please check

**Comment by volodya-lombrozo** [comment]
@levBagryansky @yegor256  Maybe we can add `.codacy.yml` file as explained [here](https://docs.codacy.com/repositories-configure/codacy-configuration-file/)?

**Comment by levBagryansky** [comment]
@volodya-lombrozo Is it posiible to disable checks via this file? Seems like it should be configured [here](https://docs.codacy.com/repositories-configure/configuring-code-patterns/).

**Comment by volodya-lombrozo** [comment]
@levBagryansky I haven't tried yet. Maybe you can try it in your PR#1992?

**Comment by levBagryansky** [comment]
@volodya-lombrozo There is not instruction on the site how to disable test. I guess it should be configured from "Code patterns page" by [configuring code patterns](https://docs.codacy.com/repositories-configure/configuring-code-patterns/)

**Comment by volodya-lombrozo** [comment]
@Graur Do you know how we can enable `EOorg.EOeolang` package for `EOrust.java` in Codacy?

**Comment by volodya-lombrozo** [comment]
@yegor256 Can we disable that check somehow?

**Comment by volodya-lombrozo** [comment]
We can add `.codacy.yaml` configuration as you did it in the #1992 with content:
```yaml
exclude_paths:
   - "eo-runtime/src/main/java/EOorg/EOeolang/EOrust.java"
```

@levBagryansky Can we close that issue?

**Comment by levBagryansky** [comment]
@volodya-lombrozo yes, thank you.
