### ISSUE TITLE
EOrust location

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2000]
Relates to #1326 
It is assumed that `EOrust` has a plenty of native methods, each of which corresponds to its own rust insert. In order to call correct native function it needs rust insert location.
There is simplified `EOrust.java` code:
```
public class EOrust extends PhDefault {
...
private static native int .. f_loc1();
private static native int .. f_loc2();
private static native int .. f_loc3();
}
```
The problem is that `PhDefault.locator()` methods looks like:
```
    @Override
    public String locator() {
        return "?";
    }
```
So it does not return real location of the object. Thus, I guess we need to reimplement this method if it is possible.
@yegor256 @volodya-lombrozo WDYT?

**Comment by mximp** [comment]
@levBagryansky please rename the issue so that it gives some meaning
