### ISSUE TITLE
Remove `+junit` meta

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#2008]
Once all libs are updated we need to remove `+junit` meta keeping `+tests` only.
Can be done upon completion of the following tasks:
https://github.com/objectionary/eo-collections/issues/169
https://github.com/objectionary/eo-math/issues/127
https://github.com/objectionary/eo-hamcrest/issues/196
https://github.com/objectionary/eo-strings/issues/148
https://github.com/objectionary/eo-sys/issues/62

**Comment by yegor256** [comment]
@mximp all tasks you mentioned above are completed
