### ISSUE TITLE
EOrust.java:44-46: Name functions according to insert's...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2031]
The puzzle `1326-14112dc1` from #1326 has to be resolved: 

https://github.com/objectionary/eo/blob/f97d48b2774bd03ecbc64f5ee678eb410a2b42f1/eo-runtime/src/main/java/EOorg/EOeolang/EOrust.java#L44-L46

The puzzle was created by @rultor on 28-Apr-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@levBagryansky Could you help us here?

**Comment by 0pdd** [comment]
The puzzle `1326-14112dc1` has disappeared from the source code, that's why I closed this issue.
