### ISSUE TITLE
Documentation as diagrams

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2068]
I believe that documentation in the repository is not enough clear and convenient. If you're young blood and want to contribute – it's quite difficult to understand what's going on in the project and how the entire compiler works (from `.eo` to `.java`).

When I get myself struggling to understand what's going on – I draws diagrams.
I drew some for `eo-maven-plugin` and some of its `Mojos`. Here they are:

<img width="1373" alt="image" src="https://github.com/objectionary/eo/assets/37025995/b5b77086-e22c-4a8a-af44-a101664c71e2">
<img width="1107" alt="image" src="https://github.com/objectionary/eo/assets/37025995/bf5eb6a6-7f1b-4978-ad16-0096e11ad0ee">
<img width="1575" alt="image" src="https://github.com/objectionary/eo/assets/37025995/249913a8-bbb9-4b76-b1a2-e472a562def9">
<img width="1156" alt="image" src="https://github.com/objectionary/eo/assets/37025995/45c94e59-f6a2-4421-8527-4fde75fd21da">
<img width="1505" alt="image" src="https://github.com/objectionary/eo/assets/37025995/08a4bbd3-38c8-488c-8ea1-c3b1b46e1ef1">

I used BPMN notation here. It allows to see the process and the used resources (files, external storages) at the same time. I think we can also use UML in some cases.
I believe it may be quite convenient and understandable for the devs who just come into project and want to understand in general terms what is going on and how the project works. These diagrams show it pretty well.

@yegor256 @mximp @Graur @volodya-lombrozo WDYT? If you think that's a good idea I will draw more diagrams and we can place them in the repo near source code (mb not as pictures but as links to some drawing tool, like [Miro](https://miro.com/app/) or smth).

**Comment by Graur** [comment]
@maxonfjvipon Looks good to me! It can be either part of the `README.md` file or our [EO blog](https://news.eolang.org/)

**Comment by mximp** [comment]
@maxonfjvipon That's great! I agree with @Graur - the best place is EO blog.
I believe README is not good for such information.

**Comment by maxonfjvipon** [comment]
@mximp Yeah, I agree – legend and some text are important. What would be a good format for such docs to place them in EO blog? I believe just pictures are not so good and flexible, because we should keep in mind that if architecture or some logic in the project is changed – we somehow should be able to update these diagrams

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon , I believe that BPMN isn't a good choice here, to be honest, because it serves different purposes that are quite far from the development process. Initially, BPMN notation was developed for managers, not developers. I think UML would be more suitable in this case since it is more widely used and covers various aspects of software development.

For example, to illustrate the general concept, we can use [Use Case](https://en.wikipedia.org/wiki/Use_case_diagram) diagrams, to depict the program flow, [sequence](https://en.wikipedia.org/wiki/Sequence_diagram) diagrams would be the best choice and for representing class structure, class diagrams would be suitable, and so on.

Regarding the placement, I believe we should place it in the eo repository (not to blog), ideally close to the code. Diagrams will help in understanding the code. They are not just the eo concepts and "news".

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I agree that BPMN was developed for managers firstly, but based on my experience it can be used for low level processes too and it's good at it.
- use case diagram makes sense if we have at 2 least two actors to show the difference between their abilities OR if one actor has quite differentiated and different functionality. This project

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I agree that BPMN was developed for managers firstly, but based on my experience it can be used for low level processes too and it's good at it. It scalable, it can show you full algorithm (of compiling in our case) with used resources (files, external storages like GitHub or MavenCentral), it can show you where processes are parallel and where they're sequential and so on.

Since it was developed for managers – it's easier and more readable for "regular" people. UML requires some technical knowledge and every year fewer and fewer people have this knowledge. We're going to write these diagrams not only for ourselves but for potential future developers too. So in my projects I prefer to use BPMN firstly to show how it works in general and then use UML in situations where BPMN is not enough.

About UML:
- use-case diagram makes sense if we have at 2 least two actors to show the difference between their abilities OR if one actor has quite differentiated and different functionality. This project is a compiler, I see only one (maybe two) scenario which actor may use the project – compile) So I don't think use-case is suitable here
- sequence – Yes, I think it can be used, but I don't see for now for such cases exactly. It seems important to me to show the used resources while compilation, because this compiler uses quite many of them (transfers from one file to another) and it's quite difficult to trace where it starts and why it ends the way it ends. Maybe if we use the lines (vertical, in sequence diagram) as the resources – it may work
- classes – it will be painful for the people who will try to read it) Because there're some many of them. I think we can use it too, but if we will highlight only the most important classes
