### ISSUE TITLE
eo-runtime: duplicate classes in the class path

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2072]
When I run tests in `eo-runtime` I get the next collision:
```
eo-runtime
  target
    classes
       EOorg
         EOeolang
           EObool.class
    test-classes
       EOorg
         EOeolang
           EObool.class
```
As you can see, we have the class duplication between folders which can cause some problems in runtime (classes could be loaded differently). It worth mention that in my case `EObool.class` differs between `classes` and `test-classes` folders which is dangerous, of course.

**Comment by volodya-lombrozo** [comment]
Apparently, it is the root problem of #2014

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#2080](https://github.com/objectionary/eo/issues/2080) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#2080](https://github.com/objectionary/eo/issues/2080) is solved here.
