### ISSUE TITLE
Flaky tests and concurrency problems detection

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2085]
I believe that we have to add integration tests and GitHub actions that will be run each day (at night) and they will test all modules many times in order to find flaky tests and concurrency problems.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#2094](https://github.com/objectionary/eo/issues/2094) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#2094](https://github.com/objectionary/eo/issues/2094) is solved here.
