### ISSUE TITLE
`cti` object fails build in `objectionary/home`

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#2092]
I was trying to add the latest version of `eo-collections` to the `objectionary/home` (with the latest version of EO: `0.29.4`) and got a very confusing error:

```
[ERROR] net.sf.saxon.style.XSLText@43cda0fd: Warnings identified: 54 68 69 73 20 6D 65 74 68 6F 64 20 69 73 20 64 65 70 72 65 63 61 74 65 64 21; 
54 68 69 73 20 6D 65 74 68 6F 64 20 69 73 20 64 65 70 72 65 63 61 74 65 64 21; 
```

As far as I understand, in the latest release of EO we added a couple of tests with the `cti` object. Which added warnings if this object existed and failed build if `failOnWarning` flag set to `true`. 
Maybe we need to change behaviour of `xsl` rule with this warning? Or just print corresponding output message?

**Comment by volodya-lombrozo** [comment]
@Graur https://github.com/objectionary/eo/issues/2044

**Comment by Graur** [comment]
@volodya-lombrozo As far as I know this issue is related to the error message. But I'm worried about failed builds in `objectionary/home`. I have to set the `failOnWarning` flag in `pom.xml` wherever the `cti` object exists. So this `cti` object makes the `failOnWarning` flag useless (at least in tests).

**Comment by volodya-lombrozo** [comment]
@Graur I see. To be honest, I had to set `failOnWarning=false` for `eo-runtime` tests, which is "suboptimal" solution, of course. 
If we will just print the message, then `cti` will look useless. Maybe we have to find a way to check only `eo` objects of the current project (exclude dependencies)?

**Comment by yegor256** [comment]
@Graur the problem still exists?

**Comment by Graur** [comment]
@yegor256 No, we can close it
