### ISSUE TITLE
to-java.xsl:26-30: Change the behaviour of conversions...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2096]
The puzzle `1890-dcbd8a31` from #1890 has to be resolved: 

https://github.com/objectionary/eo/blob/1744601ebc290d7c77dcdf43f105ab6d8de57f2f/eo-maven-plugin/src/main/resources/org/eolang/maven/pre/to-java.xsl#L26-L30

The puzzle was created by rultor on 26-May-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
@volodya-lombrozo Are there any technical issue with using double underscore?

**Comment by volodya-lombrozo** [comment]
@mximp I don't see any technical issue since I can't find any disabled tests related to the problem

@Graur or I'm missing something?

**Comment by Graur** [comment]
@mximp @volodya-lombrozo Technical issue: #1890. 
This puzzle was created because our current solution is weak. And it has a counter example. E.g. absolutely valid object named `a--b` and object named `a_b` will have the same name at compile time: `EOa__b`.

**Comment by volodya-lombrozo** [comment]
@Graur Do we have the test for that case?

**Comment by Graur** [comment]
Let's close

**Comment by volodya-lombrozo** [comment]
@Graur Maybe we should remove the puzzle description from the code?
