### ISSUE TITLE
errors unrolling produces hard to read output (too many duplicate lines)

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2099]

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2101](https://github.com/objectionary/eo/issues/2101) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2101](https://github.com/objectionary/eo/issues/2101) is solved here.

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.5`
