### ISSUE TITLE
Optimisation Train: Transformation error message

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2114]
For example, in the XSLT transformation we have the next block of code from `add-refs.xsl`:
```xml
<xsl:message terminate="yes">
    <xsl:text>Attribute @line is absent at "</xsl:text>
    <xsl:value-of select="$x/@name"/>
    <xsl:text>"</xsl:text>
</xsl:message>
```
That code throws an exception during optimisation:
```
Caused by: net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line 66 in add-refs.xsl
```
Full log: [log-transformation-error.txt](https://github.com/objectionary/eo/files/11623612/log-transformation-error.txt)

As you can see - here is no information about the context and no expected text of the message `Attribute @line is absent at ...` is present. So, It significantly complicates the problem search.

**Comment by yegor256** [comment]
@volodya-lombrozo this kind of message from XSL is a signal of some system-level error (not user level). When this happens, something is very wrong with the way we use this file or the entire optimization chain of XSL transformations. It's hard to make this message more context-rich. I can imagine only one reason for this error: `add-refs.xsl` is used with the XML file that was not generated by the EO parser, but was created manually and the creator of it forgot to add the `@line` attribute to some `<o/>` element.

**Comment by volodya-lombrozo** [comment]
@yegor256 We have such a problem not only with `add-refs.xsl`, we have it everywhere, for example in `to-java.xsl`:
```xml
<xsl:message terminate="yes">
        <xsl:text>Found more than one target of '</xsl:text>
        <xsl:value-of select="$o/@base"/>
        <xsl:text>' at the line #</xsl:text>
        <xsl:value-of select="$o/@line"/>
        <xsl:text> leading to </xsl:text>
        <xsl:for-each select="$b">
          <xsl:if test="position()&gt;1">
            <xsl:text>, </xsl:text>
          </xsl:if>
          <xsl:text>&lt;</xsl:text>
          <xsl:value-of select="name(.)"/>
          <xsl:text>/&gt;</xsl:text>
          <xsl:text> at line #</xsl:text>
          <xsl:value-of select="@line"/>
        </xsl:for-each>
        <xsl:text>; it's an internal bug</xsl:text>
      </xsl:message>
```

As you can see - in all cases we are putting some context information inside the message. The problem is that when we apply all that transformations we don't see that message, just high level exception name:
```
Caused by: net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line 357 in to-java.xsl
```
If it's impossible to deliver that information to the user (programmer), I don't understand why then we add this text to the `<message>` body?

**Comment by yegor256** [comment]
@volodya-lombrozo this text is printed to the log stream by Saxon. Try to scroll up, you will find it. How to add it to the exception `.message()` is a question for Saxon project and `jcabi-xml` project (wrapper of Saxon, which we use).

**Comment by volodya-lombrozo** [comment]
@yegor256 Yeah, you are right. I've found the original message above, which is a little bit confusing, to be honest. Actually, the error message and the exception are separated from each other.

**Comment by yegor256** [comment]
@volodya-lombrozo yes, they are, it's a well known problem in Saxon: https://stackoverflow.com/questions/27522994/xsltmessage-in-saxon-where-is-the-message and this: https://www.saxonica.com/documentation9.5/xsl-elements/message.html

**Comment by volodya-lombrozo** [comment]
@yegor256, I've created an issue in the jcabi-xml library (https://github.com/jcabi/jcabi-xml/issues/205) that is related to our problem. I'm not sure whether we can close the current issue since the problem persists. On the other hand, it's uncertain if a solution will be implemented soon.

**Comment by yegor256** [comment]
@volodya-lombrozo I suggest we close this ticket
