### ISSUE TITLE
BinarizeMojo is not generic enough

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2118]
Right now, `BinarizeMojo` only understands Rust and `org.eolang.rust` objects. What if tomorrow we want to introduce another "foreign" language? We will need to create another mojo? Maybe it would be better to put Rust-to-binary compilation process into the class `EOrust`? Something like this (pay attention to the `MustBeCompiled` interface and the `compile()` method):

```
@XmirObject(oname = "rust")
public class EOrust extends PhDefault, MustBeCompiled {
    public EOrust(final Phi sigma) {
        super(sigma);
        this.add("code", new AtFree());
        // the code that we have now...
    }
    
    @Override
    public void compile(Path target) {
      // here we take the encapsulated attributes
      // convert them to .rs files
      // create Cargo project
      // compile into binaries
      // place binaries into the "target" directory
    }
}
```

The `BinarizeMojo` will understand, from the XMIR file, which objects are the ones that "must be compiled", will instantiate them, and execute their `compile()` methods. This is what we do now inside the Mojo, but now this functionality will be perfectly coupled with the `EOrust` object. In the future, we will be able to create `EOjava`, `EOpython`, and other objects.

**Comment by yegor256** [comment]
@levBagryansky what do you think?

**Comment by levBagryansky** [comment]
I like it. So it should create instance of the right class depending on the eo object. I think we can do it

**Comment by yegor256** [comment]
@levBagryansky let's try to do it then

**Comment by levBagryansky** [comment]
@yegor256 I am not sure it is right to mix runtime with compile time. object `EOrust` has attributes like `code`  and `dependencies` but in compile time we need directories to "Portal" dependency or to `names` file. Maybe it would be better to generalize ffi in compile time separately. Could you please take a look at #2609

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@maxonfjvipon @volodya-lombrozo what do you think?

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2648](https://github.com/objectionary/eo/issues/2648) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2648](https://github.com/objectionary/eo/issues/2648) is solved here.
