### ISSUE TITLE
EO Objects can have the same hash in the new version

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2157]
This test is slight modification from eo-threads:
```
    @Test
    public void phiUniqueHashesInDynamic() {
        final int threads = 1500;
        final Set<Integer> hashes = ConcurrentHashMap.newKeySet();
        new Threads<>(
            threads,
            Stream.generate(
                () -> (Scalar<Integer>) () -> (new EOstring$EOlength(Phi.Φ)).hashCode()
            ).limit(threads).collect(Collectors.toList())
        ).forEach(hashes::add);
        MatcherAssert.assertThat(
            hashes.size(),
            Matchers.equalTo(threads)
        );
    }
```
The test guaranteed that objects created in parallel have different hashcodes. The test does not passes in new version anymore so eo-threads does not work correctly(https://github.com/objectionary/eo-threads/pull/87).
 There is similar test in this repo (https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/java/org/eolang/VerticesTest.java#L70) and it passes. Also the test below:
```
@Test
    public void phiUniqueHashesSeq() {
        final int objects = 1500;
        final Set<Integer> hashes = ConcurrentHashMap.newKeySet();
        for (int i = 0; i < objects; i++) {
            hashes.add((new EOstring$EOlength(Phi.Φ)).hashCode());
        }
        MatcherAssert.assertThat(
            hashes.size(),
            Matchers.equalTo(objects)
        );
    }
```
passes too.
@volodya-lombrozo please take a look.

**Comment by volodya-lombrozo** [comment]
@levBagryansky Looks like it is expected behaviour. The `hashCode` is actually the `PhDefault.vertex`.
Since we have `protected static final ThreadLocal<Vertices> VTX = ThreadLocal.withInitial(Vertices::new);` which is thread-local for now, it is expected that in each thread we have the same `vertex` number. Code from `PhDefault`:

```java
protected static final ThreadLocal<Vertices> VTX = ThreadLocal.withInitial(Vertices::new);

public PhDefault(final Phi sigma) {
    //... 
    this.vertex = PhDefault.VTX.get().next();
    //...
}

@Override
public int hashCode() {
    return this.vertex;
}
```

Why do you need to check this?
> The test guaranteed that objects created in parallel have different hashcodes

**Comment by levBagryansky** [comment]
@volodya-lombrozo We need it to distinguish objects in `eo-threads`.

**Comment by volodya-lombrozo** [comment]
@levBagryansky I'm afraid that it's dangerous, because:
> It is not required that if two objects are unequal according to the [equals(java.lang.Object)](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-) method, then calling the hashCode method on each of the two objects must produce distinct integer results

https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html

In other words, If two objects are unequal, their hash code are not required to be different.

**Comment by levBagryansky** [comment]
@volodya-lombrozo You are right. But In `eo-threads` and in for example `Heaps.java` uses `PhDefault.equals()`  method to distinguish eo objects in the map.
```
@Override
    public boolean equals(final Object obj) {
        return obj instanceof Phi && this.hashCode() == obj.hashCode();
    }
```
That is why it is important to assign different `hashcode`s to different eo objects.

**Comment by volodya-lombrozo** [comment]
@levBagryansky Maybe we have to fix `equals` method either?

**Comment by levBagryansky** [comment]
@volodya-lombrozo I think it would help too

**Comment by levBagryansky** [comment]
@volodya-lombrozo sure

**Comment by levBagryansky** [comment]
@volodya-lombrozo I think we need to fix `vertex`  field instead. 
```
    /**
     * Identity of it (the ID of the vertex).
     * @checkstyle VisibilityModifierCheck (2 lines)
     */
    protected int vertex;
```
Now it cannot be "the ID of the vertex" since the can be the same in different threads.

**Comment by volodya-lombrozo** [comment]
@levBagryansky Or we can make `VTX` as `AtomicInteger`

**Comment by levBagryansky** [comment]
@yegor256 can we release these changes in order to fix eo-threads?

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.6`
