### ISSUE TITLE
Create a cargo project for every rust

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2195]
Now one cargo project is creatig for all `rust insets`. It is wrong since the can have different conflicting dependencies. So it's better to create separate cargo project for `insert`

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2208](https://github.com/objectionary/eo/issues/2208) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the only puzzle [#2208](https://github.com/objectionary/eo/issues/2208) is solved here.
