### ISSUE TITLE
why testing for Java 11, 17, and 18?

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2236]
In GitHub Actions we test for Java 11, 17, and 18. Maybe it's better to switch to 11 and 18? It will speed up the build. Any objections?

**Comment by yegor256** [comment]
@mximp @Graur @volodya-lombrozo @maxonfjvipon any objections?

**Comment by maxonfjvipon** [comment]
@yegor256 no

**Comment by volodya-lombrozo** [comment]
@yegor256 Maybe it's better to leave only stable LTS versions: `11` and `17`?

**Comment by yegor256** [comment]
@volodya-lombrozo I remember we had some problems with 18...

**Comment by Graur** [comment]
@yegor256 I vote for 11 and 18
@volodya-lombrozo We had build fails with 18 version

**Comment by volodya-lombrozo** [comment]
@Graur @yegor256 Then, yes. It seems it makes sense to support one LTS widely-used version and the newest one. What about `11` and `20`?

**Comment by yegor256** [comment]
@volodya-lombrozo I'm afraid `temurin` doesn't have 20, but let's check and set to 20 - in my opinion it will be helpful
