### ISSUE TITLE
Add rust2eo communication to rust object

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2237]
At the moment there is no any way to manage eo object from `rust` object. 
We need to change its code signature to `fn foo(mut env: EOenv) -> Result<i32>`. Where `EOenv` is a structure that provides managing eo objects. `EOenv`  is an analogue  of [`JNIEnv`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#interface_function_table) and needs to have  the methods below:

1. `find(&self, obj: &str) -> Option::<u32>` Find and returns the vertex of the eo object. obj is the path to the object, for instance, `"^.^.other-obj"`. #2267
2. `put(&self, v: u32, bytes: &[u8])` . `bytes` can be for example `&[0x00, 0x1a, 0xEE, 0xf, 0xf3]`.
3. `bind(&self, v1: u32, v2: u32, name: &str) -> Option<()>`  Binds v2 to v1. Thus v1 has attribute `name` with vertex = v2.
4. `copy(&self, v: u32) -> Option<u32>` Copies the object and returns the vertex of new object.
5. ` dataize(&self, v: u32) -> Option<&[u8]>` Dataizes the object and returns data's bytes.
@yegor256 WDYT?

**Comment by levBagryansky** [comment]
@yegor256 @mximp What do you think?

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2280](https://github.com/objectionary/eo/issues/2280) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky 5 puzzles [#2280](https://github.com/objectionary/eo/issues/2280), [#2292](https://github.com/objectionary/eo/issues/2292), [#2293](https://github.com/objectionary/eo/issues/2293), [#2294](https://github.com/objectionary/eo/issues/2294), [#2295](https://github.com/objectionary/eo/issues/2295) are still not solved.

**Comment by 0pdd** [comment]
@levBagryansky 4 puzzles [#2292](https://github.com/objectionary/eo/issues/2292), [#2293](https://github.com/objectionary/eo/issues/2293), [#2294](https://github.com/objectionary/eo/issues/2294), [#2295](https://github.com/objectionary/eo/issues/2295) are still not solved; solved: [#2280](https://github.com/objectionary/eo/issues/2280).

**Comment by 0pdd** [comment]
@levBagryansky 3 puzzles [#2293](https://github.com/objectionary/eo/issues/2293), [#2294](https://github.com/objectionary/eo/issues/2294), [#2295](https://github.com/objectionary/eo/issues/2295) are still not solved; solved: [#2280](https://github.com/objectionary/eo/issues/2280), [#2292](https://github.com/objectionary/eo/issues/2292).

**Comment by 0pdd** [comment]
@levBagryansky 2 puzzles [#2294](https://github.com/objectionary/eo/issues/2294), [#2295](https://github.com/objectionary/eo/issues/2295) are still not solved; solved: [#2280](https://github.com/objectionary/eo/issues/2280), [#2292](https://github.com/objectionary/eo/issues/2292), [#2293](https://github.com/objectionary/eo/issues/2293).

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2294](https://github.com/objectionary/eo/issues/2294) is still not solved; solved: [#2280](https://github.com/objectionary/eo/issues/2280), [#2292](https://github.com/objectionary/eo/issues/2292), [#2293](https://github.com/objectionary/eo/issues/2293), [#2295](https://github.com/objectionary/eo/issues/2295).
