### ISSUE TITLE
Names of native methods are confusing

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2238]
Now names of native methods for `rust` are too long and unreadable like `xhomextardis3xeoxeoxruntimextargetxeoxtest0`. It would be better if they named liked `natve1`, `native2` and so on.

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2257](https://github.com/objectionary/eo/issues/2257) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the only puzzle [#2257](https://github.com/objectionary/eo/issues/2257) is solved here.
