### ISSUE TITLE
Generated files for rust must have explanatory comment

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2239]
Some generated files relating to `rust` does not have comment. We need to add explanatory comment with description what is their purpose.

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2322](https://github.com/objectionary/eo/issues/2322) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the only puzzle [#2322](https://github.com/objectionary/eo/issues/2322) is solved here.
