### ISSUE TITLE
Broken build on ubuntu 22.04

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2240]
@yegor256 I'm afraid after adding `unzip convert` to github actions build had been broken. 
See [this]

(https://github.com/objectionary/eo/actions/runs/5530304921/jobs/10089540003?pr=2228) and screenshot below
<img width="741" alt="image" src="https://github.com/objectionary/eo/assets/37025995/fb311c8a-5224-4110-af86-33672230ce82">

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2243](https://github.com/objectionary/eo/issues/2243) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2243](https://github.com/objectionary/eo/issues/2243) is solved here.
