### ISSUE TITLE
EBNF form in a dark mode

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2254]
I'm using the dark mode in GitHub, so the EBNF description looks as follows for me:
<img width="894" alt="image" src="https://github.com/objectionary/eo/assets/51804353/1d364fbf-70ff-492f-8df2-3fa89c36257a">

I believe, I'm not alone and it's better to make that piece of the documentation is mode-independent

**Comment by yegor256** [comment]
@volodya-lombrozo it's fixed in cf1baa661
