### ISSUE TITLE
Application can't find decorated object

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2291]
I'm trying to run example from #415 issue (slightly modified according with new features):\
`app.eo`:
```eo
[] > app
  (arr.at 0) 33 > @
  [y] > add1
    y.add 1 > @
  * add1 > arr
```
I run the next command with the latest version of `eo-maven-plugin`:
```
eoc dataize app --clean --parser="1.0-SNAPSHOT"
```

**Expected behaviour:**\
Program runs and finishes successfully.
**Actual behaviour:**\
I get the next exception:
```shell
The directory /Users/lombrozo/Workspace/EOlang/learning/415_original_problem/.eoc deleted
[eo:register] 3s; 0 files generated...
EO objects registered in /Users/lombrozo/Workspace/EOlang/learning/415_original_problem/.eoc/eo-foreign.json
[eo:assemble] 23s; 3677 files generated...
EO program assembled in /Users/lombrozo/Workspace/EOlang/learning/415_original_problem/.eoc
[eo:transpile] 16s; 4408 files generated...
Java sources generated in /Users/lombrozo/Workspace/EOlang/learning/415_original_problem/.eoc/generated-sources
[compiler:compile] 7s; 4714 files generated...
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/learning/415_original_problem/.eoc
[jar:jar] 4s; 4722 files generated...
Executable JAR created at /Users/lombrozo/Workspace/EOlang/learning/415_original_problem/.eoc/eoc.jar
Error at "EOapp#Δ" attribute
Can't get(), attribute "Δ" is absent among other 5 attrs (arr, ρ, generated-scope-c015e800-f84c-4ea4-9369-81051f25b95f, σ, add1) and φ is absent
```

**Comment by yegor256** [comment]
@volodya-lombrozo I suspect that the code is understood as such:

```
[] > app
  [] > generated-scope-c015e800-f84c-4ea4-9369-81051f25b95f
    (arr.at 0) 33 > @
  [y] > add1
    y.add 1 > @
  * add1 > arr
```

I don't know why, but this is what the error message is saying.

**Comment by yegor256** [comment]
@maxonfjvipon maybe you can help?

**Comment by yegor256** [comment]
@maxonfjvipon I like it

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon In general I agree that `scope.xsl` should be removed, I don't like it :) 
However I'm afraid you will face with a problem related to methods in the feature. Can you try to apply your algorithm to that code snippets:
```eo
  [] > aliases
    eq. > @
      (1.bar 2).foo (3.bar 4)
```
and
```
  [] > method
    * 1 (* "one" "two") 3 > res
    eq > @
      * (res.length) ((res.at 1).at 1)
      * 3 "two"
```

More interesting examples you can find [here](https://github.com/objectionary/eo/tree/master/eo-parser/src/test/resources/org/eolang/parser/packs). Just check packs that start with `scope-*`.
___
To be honest, I believe we go in a wrong direction here and the problem we are trying to solve already should be solved earlier, maybe by `antlr`. `scope.xsl` and "synthetic" objects looks like a crutch.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo the perfect solution, as for me, is to prohibit complex applications at all. So you won't be able to to do this:
```
(x 1) 2
```
Or this:
```
x (x 1)
```
If we allow this, I don't see any other ways how we can present it in xmir, at least for now

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I don't see any problem with rewriting. We do this with enviable regularity)

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo just FYI:
1.
```
[] > aliases
  eq. > @
    (1.bar 2).foo (3.bar 4)
```

```xml
<objects>
    <o abstract="" line="1" name="aliases" pos="0">
        <o base=".eq" line="2" name="@" pos="2">
            <o abstract="" line="3" pos="4">
                <o base="int" data="bytes" line="3" pos="5">00 00 00 00 00 00 00 01</o>
                <o base=".bar" line="3" method="" name="synth-3824c418-c463-4e5d-9714-572c378236f7" pos="6">
                    <o base="int" data="bytes" line="3" pos="11">00 00 00 00 00 00 00 02</o>
                </o>
                <o base="synth-3824c418-c463-4e5d-9714-572c378236f7" line="3" pos="4"/>
                <o base=".foo" line="3" method="" name="@" pos="13">
                    <o abstract="" line="3" pos="18">
                        <o base="int" data="bytes" line="3" pos="19">00 00 00 00 00 00 00 03</o>
                        <o base=".bar" line="3" method="" name="synth-f1abf79d-764a-48cf-8772-1b6f286d8611" pos="20">
                            <o base="int" data="bytes" line="3" pos="25">00 00 00 00 00 00 00 04</o>
                        </o>
                        <o base="synth-f1abf79d-764a-48cf-8772-1b6f286d8611" line="3" name="@" pos="18"/>
                    </o>
                </o>
            </o>
        </o>
    </o>
</objects>
```
2.
```
[] > method
  * 1 (* "one" "two") 3 > res
  eq > @
    * (res.length) ((res.at 1).at 1)
    * 3 "two"
```

```xml
<objects>
    <o abstract="" line="1" name="method" pos="0">
        <o base="tuple" data="tuple" line="2" name="res" pos="2">
            <o base="int" data="bytes" line="2" pos="4">00 00 00 00 00 00 00 01</o>
            <o abstract="" line="2" pos="6">
                <o base="tuple" data="tuple" line="2" name="synth-cef701b3-ea75-471d-b044-071efba06b1f" pos="7">
                    <o base="string" data="bytes" line="2" pos="9">6F 6E 65</o>
                    <o base="string" data="bytes" line="2" pos="15">74 77 6F</o>
                </o>
                <o base="synth-cef701b3-ea75-471d-b044-071efba06b1f" line="2" name="@" pos="6"/>
            </o>
            <o base="int" data="bytes" line="2" pos="22">00 00 00 00 00 00 00 03</o>
        </o>
        <o base="eq" line="3" name="@" pos="2">
            <o abstract="" line="4" pos="4">
                <o base="tuple" data="tuple" line="4" name="@" pos="4">
                    <o abstract="" line="4" pos="6">
                        <o base="res" line="4" pos="7"/>
                        <o base=".length" line="4" method="" name="synth-34f61868-8363-466d-9c53-765ff36fe1a1" pos="10"/>
                        <o base="synth-34f61868-8363-466d-9c53-765ff36fe1a1" line="4" name="@" pos="6"/>
                    </o>
                    <o abstract="" line="4" pos="19">
                        <o base="res" line="4" pos="21"/>
                        <o base=".at" line="4" method="" name="synth-8622d0ed-3f4c-4595-b13c-cbf0ba5af4ca" pos="24">
                            <o base="int" data="bytes" line="4" pos="28">00 00 00 00 00 00 00 01</o>
                        </o>
                        <o base="synth-8622d0ed-3f4c-4595-b13c-cbf0ba5af4ca" line="4" pos="20"/>
                        <o base=".at" line="4" method="" name="synth-199ae4a8-821f-4988-83be-e8391985452f" pos="30">
                            <o base="int" data="bytes" line="4" pos="34">00 00 00 00 00 00 00 01</o>
                        </o>
                        <o base="synth-199ae4a8-821f-4988-83be-e8391985452f" line="4" name="@" pos="19"/>
                    </o>
                </o>
            </o>
            <o abstract="" line="5" pos="4">
                <o base="tuple" data="tuple" line="5" name="@" pos="4">
                    <o base="int" data="bytes" line="5" pos="6">00 00 00 00 00 00 00 03</o>
                    <o base="string" data="bytes" line="5" pos="8">74 77 6F</o>
                </o>
            </o>
        </o>
    </o>
</objects>
```

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Is it the result of the parsing only? Could you, please, apply `wrap-method-calls.xsl` to your `xmir` and check if it doesn't break anything.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo yes, only of the parsing

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo this is the same examples after `wrap-method-calls.xsl`:
```xml
   <objects>
      <o abstract="" line="1" name="method" pos="0">
         <o base="tuple" data="tuple" line="2" name="res" pos="2">
            <o base="int" data="bytes" line="2" pos="4">00 00 00 00 00 00 00 01</o>
            <o abstract="" line="2" pos="6">
               <o base="tuple"
                  data="tuple"
                  line="2"
                  name="synth-e1d02d70-d623-42a5-bfa8-c3042ac04c78"
                  pos="7">
                  <o base="string" data="bytes" line="2" pos="9">6F 6E 65</o>
                  <o base="string" data="bytes" line="2" pos="15">74 77 6F</o>
               </o>
               <o base="synth-e1d02d70-d623-42a5-bfa8-c3042ac04c78"
                  line="2"
                  name="@"
                  pos="6"/>
            </o>
            <o base="int" data="bytes" line="2" pos="22">00 00 00 00 00 00 00 03</o>
         </o>
         <o base="eq" line="3" name="@" pos="2">
            <o abstract="" line="4" pos="4">
               <o base="tuple" data="tuple" line="4" name="@" pos="4">
                  <o abstract="" line="4" pos="6">
                     <o base=".length"
                        line="4"
                        name="synth-bad475fd-49fa-4a5f-86d6-e57e25ced3b3"
                        pos="10">
                        <o base="res" line="4" pos="7"/>
                     </o>
                     <o base="synth-bad475fd-49fa-4a5f-86d6-e57e25ced3b3"
                        line="4"
                        name="@"
                        pos="6"/>
                  </o>
                  <o abstract="" line="4" pos="19">
                     <o base=".at"
                        line="4"
                        name="synth-d572f889-911c-4dea-8c12-263e32f1d9d1"
                        pos="24">
                        <o base="res" line="4" pos="21"/>
                        <o base="int" data="bytes" line="4" pos="28">00 00 00 00 00 00 00 01</o>
                     </o>
                     <o base=".at"
                        line="4"
                        name="synth-1eef25ac-9653-48cd-83d9-2514283d5214"
                        pos="30">
                        <o base="synth-d572f889-911c-4dea-8c12-263e32f1d9d1" line="4" pos="20"/>
                        <o base="int" data="bytes" line="4" pos="34">00 00 00 00 00 00 00 01</o>
                     </o>
                     <o base="synth-1eef25ac-9653-48cd-83d9-2514283d5214"
                        line="4"
                        name="@"
                        pos="19"/>
                  </o>
               </o>
            </o>
            <o abstract="" line="5" pos="4">
               <o base="tuple" data="tuple" line="5" name="@" pos="4">
                  <o base="int" data="bytes" line="5" pos="6">00 00 00 00 00 00 00 03</o>
                  <o base="string" data="bytes" line="5" pos="8">74 77 6F</o>
               </o>
            </o>
         </o>
      </o>
   </objects>
```

I don't see any problem here

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon It's perfect if it is works. I like it too. The only thing I don't like I have already mentioned above - we probably can solve this problem by using `ANTLR`. Anyway, your solution seems working, comparing with `scopes.xsl` :) 
Maybe we can implement it using your approach and add a new puzzle in order to try to solve this problem without adding artificial objects like `<o base="synth-1eef25ac-9653-48cd-83d9-2514283d5214" name="@" pos="19"/>` and `<o abstract="" line="5" pos="4">...</o>`?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo @yegor256 My experiments tell that the next code is not resolvable at all.
```
[y] > add
  y.plus 1 > @
* add > arr
(arr.at 0) 33 > res
```
Here we want to take first element of `arr` (we assume that it's an abstract object `add`) and set `33` to its free attribute `y`.

Let's disclose the braces:
```
[y] > add
  y.plus 1 > @
* add > arr
arr.at 0 > scope
scope 33 > res # <--- attention here
```
Seems right, but it does not (and won't) work. The problem here is that `scope` is just a reference to `arr.at` object which free attribute is already set. So next three peaces of code are doing the same: taking `arr.at` and setting two ints to it.
```
arr.at 0 33 > res
#######
(arr.at 0) 33 > res
#######
arr.at 0 > scope
scope 33 > res
```
Moreover, if we imagine, that `scope` is already dataized when we do `scope 33` - there'll be error, because:
dataize `scope` -> dataize `arr.at 0` -> dataize `add` -> dataize `y.plus 1` -> `y` is not set -> error.

I don't have a solution for now. Let me know what you think.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo @yegor256 the same story with the next code:
```
* > arr
  1
  * 2 3
(arr.at 1).at 0 > two
```
Here `at.0` will be taken from previous `arr.at` object. We can remove `1` and it becomes clearer `arr.at.at 0`.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Maybe we can fix Dataization process somehow? For now it looks like a problem in java backend: we have to retrieve `arr.at 0` first and only then apply `33` to the retrieved object. In other words, we have a bug now:
we execute the next code:
```
1) arr.at 0
2) arr.at 33 
```
instead of 
```
1) x = arr.at 0
2) x 33
```
Please, correct me if I'm wrong.
 The eo code itself looks logical to me, so I don't think we have to prohibit it, rather we have to fix a bug with dataization. What do you think?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I believe there's nothing wrong with dataization and there's no bug here. Dataization is the process of transformation object to data. Application is just about setting attributes to the object.

You have a object `x`. You do `x 33`. At this step `x` is not dataized, and it shouldn't be. Application does not imply dataization of the "head" (`x`), we just set `33` to the free attribute of `x`, nothing more. So what ever object your `x` is refer to - it won't be dataized when you do `x 33`.

Moreover, take a look at the example again:
```
[y] > add
  y.plus 1 > @
* add > arr
arr.at 0 > scope
scope 33 > res
```
Even if we want, that `scope` is being dataized first, and `33` was applied to the `scope` after, we will get an error here because:
dataize `scope` -> dataize `arr.at 0` -> dataize `add` -> dataize `y.plus 1` -> `y` is not set -> error

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo One more point. As I said, dataization is the process of getting data from the object, so you kind of transform your object to the data. If dataization is happening before application - we get the situation where you set object to the data. Which is not possible obviously.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Should it be the next:
dataize `scope 33` -> dataize `(arr.at 0) 33` -> dataize `add 33` -> dataize `33.plus 1` -> `34` ?

As for "Dataization" and "Application" I agree, but the question remains. Why do we "apply" in this way:
```sh
1) arr.at 0
2) arr.at 33 
``` 
instead of
```
1) x = arr.at 0 
2) x 33
```
?
x == `add` here that actually has a free attribute.

**Comment by maxonfjvipon** [comment]
Proposed solution:
1. Get rid of the current implementation of synthetic objects at all if it's possible. If it's not - remake them so they are not abstract objects but just references.
```
# Example
(x y).z

# Current implementation
[] > scope
  x y > @
scope.z

# New implementation with references
x y > scope
scope.z
```
2. Prohibit using braces for the head of application at the level grammar
```
(x y) z # <--- illegal
(x y).z # <--- legal
x (y z) # <--- legal
```
2. After we are done with scopes and syntax let's get back to the example:
```
[y] > add
  y.plus 1 > @
* add > arr
```
Instead of `(arr.at 0) 33` which does not work and will be prohibited we can do `(arr.at 0).@ 33` that will work
@yegor256 @volodya-lombrozo please have a look

**Comment by maxonfjvipon** [comment]
Why the code `(arr.at 0) 33` is not resolvable:
1. Application is the process of copy of an abstract object, specifying some or all of its free attributes. Simply words - making a copy and changing state.
2. Application does not imply any object executions/calculations/evaluations
3. Object after application does not change its type, it has the same "forma" as an abstract object it was copied of. What is "forma" in details is described [here](https://news.eolang.org/2023-08-04-storing-objects-formed-differently-into-cage.html)
4. Since after application `arr.at 0` - type of object is not changed and no calculations are happen, `33` will be applied to the same `arr.at`

So `(arr.at 0) 33` means 
1. Take object `arr`
2. Take attribute `at` from object `arr` - `arr.at`
3. Copy object `arr.at`
5. Set `0` to 1st free attribute of the copy of `arr.at`
6. Set `33` to 1st free attribute of the copy of `arr.at`

Double setting to the same attribute is not allowed, so the code won't work
