### ISSUE TITLE
OnVersioned.java:51-59: Frontend and backend delimiters...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2382]
The puzzle `2376-007b3f61` from #2376 has to be resolved: 

https://github.com/objectionary/eo/blob/b64b4859994b6848ebad8c2add15b360fc0b4d3d/eo-maven-plugin/src/main/java/org/eolang/maven/name/OnVersioned.java#L51-L59

The puzzle was created by rultor on 11-Aug-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon What do you think?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo Before you identified this problem, I didn't even think about it and didn't have a problem with it. 
EO is something that should live without knowing about java, copiler, tojos and so on. We actually already have such mappings from EO to our compiler: `@` -> `ф`, `^` -> `σ`, ... now there's one more `|` -> `#`. I don't see any problem here and don't see the reason for this ticket, at least for now. 
P.S. And we should remember that `|` is invalid for file naming on windows. That's why it was changed to `#`

**Comment by yegor256** [comment]
@maxonfjvipon if the reason for changing the symbol from `|` to `#` is the restrictions of the file system, maybe we should document it somewhere, in order to avoid similar questions in the future?

**Comment by volodya-lombrozo** [comment]
@yegor256  @maxonfjvipon 
1. As for `@` -> `ф`, `^` -> `σ` symbols: We use this mapping to connect the frontend with phi-calculus (please correct me if I'm wrong), so I can understand the rationale behind it.
2. As for `|` and `#` - they are solutions to the problem with "Windows paths." Why does Windows influence our architecture and code that isn't related to Windows at all? Writing comments isn't a solution at all. I'm more than sure that I'm not the only one who will face this confusion. What do I suggest? Let's use `|` everywhere; it's understandable and easy to maintain. If we have problems with Windows paths, then we should address them where we save data to the filesystem. In other words, right now, Windows is dictating our architecture, which is incorrect. It's better to change direction: our architecture should take precedence.

**Comment by yegor256** [comment]
@maxonfjvipon @volodya-lombrozo I agree, it's better to keep data consistent inside the system and modify them only when we need to play by the rules of external systems (Windows).

**Comment by 0pdd** [comment]
The puzzle `2376-007b3f61` has disappeared from the source code, that's why I closed this issue.
