### ISSUE TITLE
rust object needs [] object

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2400]
In order to have access to eo-objects around, like here
```
[] > test
  1 > a
  QQ.rust > d
    """
    pub fn foo(env: &mut EOEnv) -> EO {
      let v = env.find("^.a") as u32;
      let _bytes = env.dataize(v).unwrap();
      EOInt(v as i64)
    }
    """
    *
```
rust insert needs `[]` since it is formed in `test` so has `test`  as parent. 
That is why rust's semantic should be changed.

**Comment by levBagryansky** [comment]
There are several options how to introduce `[]`:
1)
```
[] > rust-dataize-not-fails
  1 > a
  QQ.rust > dataized
    """
    pub fn foo(env: &mut EOEnv) -> EO {
      let v = env.find("org.eolang.rust-dataize-not-fails.a") as u32;
      let _bytes = env.dataize(v).unwrap();
      EOInt(v as i64)
    }
    """
    *
    []
```
so the third argument means that the insert will use the objects around.

**Comment by levBagryansky** [comment]
2)
[] > example
```
  QQ.rust > rst
    [self]
      self > @
        "rust code here"
        *
```

**Comment by levBagryansky** [comment]
3)
```
[] > test
  1 > a
  QQ.rust > dataized
    []
      """
      pub fn foo(env: &mut EOEnv) -> EO {
        let v = env.find("^.a") as u32;
        let _bytes = env.dataize(v).unwrap();
        EOInt(v as i64)
      }
      """ > code
    *
```

**Comment by levBagryansky** [comment]
@yegor256 @maxonfjvipon WDYT?
As for me the first option is the most clear.

**Comment by maxonfjvipon** [comment]
@levBagryansky the 2nd example contains the least amount of useless objects.
In the 1st example there is `[]` that does nothing and used as kind of proxy to `test` object. I think it's not clear to the end-user.
The 3rd example is ok, but there is an object with name `code` which is present only because we can't have an object without name.

**Comment by levBagryansky** [comment]
@maxonfjvipon the second has `self` entity but the first has just `[]`. The second is also overcomplicated if you ask me. And the second example has one more absttraction layer which make the insert slower. I believe the first variant is the most simple and fast.

**Comment by levBagryansky** [comment]
4) 
```
[] > test
  1 > a
  QQ.rust > dataized
    []
      """
      pub fn foo(env: &mut EOEnv) -> EO {
        let v = env.find("^.a") as u32;
        let _bytes = env.dataize(v).unwrap();
        EOInt(v as i64)
      }
      """ > code
    *
      []
      "next dependency"
```
Make this "portal' the obligatory first dependenncy. Looks good as for me.

**Comment by yegor256** [comment]
@levBagryansky the 4th option suggested seems to be the best
