### ISSUE TITLE
AssembleMojoTest.java:45-51: Create new object that will...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2422]
The puzzle `1602-4a7b3be6` from #1602 has to be resolved: 

https://github.com/objectionary/eo/blob/c84b8c83f8725af850e01ac896fe13308070df85/eo-maven-plugin/src/test/java/org/eolang/maven/AssembleMojoTest.java#L45-L51

The puzzle was created by maxonfjvipon on 18-Aug-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by qlexl** [comment]
@maxonfjvipon, assign this to me, please

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2743](https://github.com/objectionary/eo/issues/2743), [#2744](https://github.com/objectionary/eo/issues/2744) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#2743](https://github.com/objectionary/eo/issues/2743), [#2744](https://github.com/objectionary/eo/issues/2744).
