### ISSUE TITLE
EOmemoryTest.java:44-51: Enable tests that uses memory...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2435]
The puzzle `2211-c8def9e6` from #2211 has to be resolved: 

https://github.com/objectionary/eo/blob/e36d608d202d4798c35549fc685d485d89aedbe7/eo-runtime/src/test/java/EOorg/EOeolang/EOmemoryTest.java#L44-L51

The puzzle was created by rultor on 24-Aug-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@Graur please set "Important" milestone to the issue

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2452](https://github.com/objectionary/eo/issues/2452) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#2452](https://github.com/objectionary/eo/issues/2452) is solved here.
