### ISSUE TITLE
rust inserts' error handling

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2442]
Now it does not provide any information if something goes wrong in rust insert.
It is necessary to implement error handling for rust insert. For example return `EOError` and save stacktrace somewhere in `Univese`

**Comment by 0pdd** [comment]
@levBagryansky 2 puzzles [#2471](https://github.com/objectionary/eo/issues/2471), [#2472](https://github.com/objectionary/eo/issues/2472) are still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#2471](https://github.com/objectionary/eo/issues/2471) is still not solved; solved: [#2472](https://github.com/objectionary/eo/issues/2472).

**Comment by 0pdd** [comment]
@levBagryansky all 2 puzzles are solved here: [#2471](https://github.com/objectionary/eo/issues/2471), [#2472](https://github.com/objectionary/eo/issues/2472).
