### ISSUE TITLE
OnReplaced.java:58-66: Hide static constant DELIMITER. We...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2463]
The puzzle `2394-92a7c10b` from #2394 has to be resolved: 

https://github.com/objectionary/eo/blob/fd7475bc820bfa21b48ad3b2fbe0432ded46a28c/eo-maven-plugin/src/main/java/org/eolang/maven/name/OnReplaced.java#L58-L66

The puzzle was created by rultor on 01-Sep-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by qlexl** [comment]
@maxonfjvipon, assign this to me, please

**Comment by 0pdd** [comment]
The puzzle `2394-92a7c10b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2544](https://github.com/objectionary/eo/issues/2544) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#2544](https://github.com/objectionary/eo/issues/2544) is solved here.
