### ISSUE TITLE
Replace `convertsAntlrToEbnf()` test method with an appropriate CI pipeline.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2464]
This [discussion](https://github.com/objectionary/eo/pull/2459#pullrequestreview-1606801654) reviled the problem with `XMIRTest#convertsAntlrToEbnf()` method. It is actually not a test method, it is ad-hoc solution for creating `ebnf` files:

>I don't know what is a better place for convertsAntlrToEbnf() method... Maybe we can create a new Maven plugin that would take .g4 files, generate .txt files, and then compile them to .png and .svg via pdflatex (this exactly what this test method is doing now).

We have several options here, but the main goal is to move logic from that method to an appropriate place.

**Comment by yegor256** [comment]
@volodya-lombrozo I believe, it's fixed, can be close
