### ISSUE TITLE
What is the difference between `program.name` and `objects.o.name`?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2479]
Let's consider `bool.eo` object. If we compile `bool.eo` file we will get `bool.xmir` file which will contain the next structure:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<program dob="2023-08-29T19:54:35"
         ms="149"
         name="org.eolang.bool"
         revision="d47d103"
         source=".../EOlang/eo/eo-runtime/src/main/eo/org/eolang/bool.eo"
         time="2023-08-29T16:59:22.185400Z"
         version="1.0-SNAPSHOT">
   <listing>...</listing>
   <errors/>
   <sheets/>
   <license>...</license>
   <metas>...</metas>
   <objects>
      <o abstract="" line="29" name="bool" pos="0">
         <o abstract="" line="30" name="eq" pos="2">
          ...
         </o>
         <o abstract="" atom="t" line="36" name="if" pos="2">
         ...
         </o>
         <o abstract="" line="39" name="not" pos="2">
         ...
         </o>
         <o abstract="" atom="bool" line="45" name="and" pos="2">
        ...
         </o>
         <o abstract="" atom="bool" line="48" name="or" pos="2">
        ...
         </o>
         <o abstract="" atom="int" line="51" name="while" pos="2">
         ...
         </o>
         <o abstract="" line="58" name="as-bytes" pos="2">
         ...
         </o>
      </o>
   </objects>
</program>
```

As you can see we have several definitions of `bool` object. The first one in the `\program\@name = org.eolang.bool` the second one in `\program\objects\o[@name='bool']`. I don't clearly see the difference between `program.name` and `objects.o.name` (the high-level object). Could you please help me understand the difference, please? And why do we need to keep both of them?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help me here?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo `\program\@name` <= `tojo.identifier()` <= file name (`org/eolang/bool.eo`). 
`\program\object\o` is taken from the source code.
I believe it's legal to have file with name `org/eolang/bool.eo` where object `[] > int` is placed

**Comment by yegor256** [comment]
@volodya-lombrozo in a perfect world, you should find the answer to your question here: https://www.eolang.org/XMIR.xsd Also, the generated `.xmir` file should have a link to this XSD, in its `<program>` element.

To answer your question: `program.name` is the name of unique ID of the file, as it was found during compilation. You can safely ignore this information, you don't need it for compilation. All attributes of `<program>` are there only for the sake of debugging.

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo `\program\@name` <= `tojo.identifier()` <= file name (`org/eolang/bool.eo`).
> `\program\object\o` is taken from the source code.
> I believe it's legal to have file with name `org/eolang/bool.eo` where object `[] > int` is placed

@maxonfjvipon Seems that technically you are right. Although, It means we don't have any information about FQN of an object inside XMIR. Or FQN in our case is just a path in a filesystem.

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you for the answer. Maybe it worth to implement this? I mean to add link to `xsd` from `xmir`? What do you think?

As for `program.name`: if it is just debugging information, where I can get a FQN of an object then?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo still an issue?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Let's close it.
