### ISSUE TITLE
Make `eo-runtime` totally independent of other eo-repositories

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2498]
We need to make `eo-runtime` totally independent of all other "eo-" repositories (even of `eo-hamcrest`) in order to be able to update it without touching anything else.
When `eo-runtime` is built - it must be solid and mustn't download and extract any other repositories.

**Comment by maxonfjvipon** [comment]
@Graur please set `Urgent` milestone to the ticket

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2516](https://github.com/objectionary/eo/issues/2516) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2516](https://github.com/objectionary/eo/issues/2516) is solved here.
