### ISSUE TITLE
Add one more package layer to all binaries inside `eo-runtime`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2506]
[Here](https://github.com/objectionary/eo/issues/2503) is described that every time we complie `eo-runtime` the result `.class` files should be placed not in `org.eolang` or `EOorg.EOeolnag`, but in `p9c46a67.org.eolang` or `p9c46a67.EOorg.EOeolang` where `9c46a67` is a current version (hash) of `eo-maven-plugin`. `p` is a prefix that stands for "package" and it's needed in order to resolve name conflict (hashes may start with digits like in the giving example)
Problem here is that we need to change this information (FQN and location) in bytecode after the source code is compiled.

**Comment by maxonfjvipon** [comment]
#### Proposed solution
1. Create a special annotation that will be a signal for a class to be moved
2. Add the annotation to all `.java` files in `eo-runtime` that we want to move (almost all, except `Vertex`)
3. Create a new mojo that starts after "compile" step, goes through classes in `classes` folder and checks if there's an annotation from the point 1. If it exists - mojo changes location and package name of the class.

In the end we should get the whole runtime with 3-level package name.

**Comment by yegor256** [comment]
@maxonfjvipon looks correct to me

**Comment by maxonfjvipon** [comment]
Weeks of trying to modify bytecode don't end up with any valuable result. I made up with a bit simpler and straight idea how we can get versionized classes:
1. Copy source files from `src/main/java/org/eolang` to `src/main/java/p{hash}/org/eolang`
2. Modify `.java` files in new directory.
3. Compile several classes from `org.eolang` package (`Phi`, `Vertices`) and from `p{hash}.org.eolang` package
4. Delete copied sources from (remove `src/main/java/p{hash}` directory)

The main advantages here are clarity and simplicity: we need to modify `.java` files (which are just plain text) instead of bytecode.

@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon sounds right, but the location should be `target/generated-sources/p{hash}/

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2539](https://github.com/objectionary/eo/issues/2539) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2539](https://github.com/objectionary/eo/issues/2539) is solved here.

**Comment by yegor256** [comment]
@maxonfjvipon closing this, as it's not in scope anymore: https://github.com/objectionary/eo/issues/3698
