### ISSUE TITLE
EBNF is too wide

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2526]
It's too wide in the image, because of long lines. Let's try to make it more compact.

**Comment by yegor256** [comment]
@maxonfjvipon look at the EBNF picture we have now. There are two very long lines, which make the entire picture hard to read. The plugin would break these lines into multiple lines, if they would be in this format: `x := a | b | c ... | f` See how a few lines in such format are rendered as multiple lines. Can you do something with these two lines?

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2736](https://github.com/objectionary/eo/issues/2736) is still not solved.

**Comment by maxonfjvipon** [comment]
@yegor256 please check if current EBNF is narrow enough

**Comment by yegor256** [comment]
@maxonfjvipon looks good now, thanks!

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#2736](https://github.com/objectionary/eo/issues/2736), [#2806](https://github.com/objectionary/eo/issues/2806).
