### ISSUE TITLE
`test-compile` step replaces binaries generated from sources to downloaded (outdated) ones

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2528]
I'm trying to update `eo-maven-plugin` version in `eo-math` package to `0.32.0` without updating `eo-runtime`.
Expected behaviour:  tests pass successfully because `eo-maven-plugin` should not affect them.
Actual behaviour: many tests fail.

Proofs: current object `number` in `eo-math` has 27 attributes, `EOnumber.java` file in `target/generated-sources` after transpilation has also 27 attributes, but `EOnumber.class` in `target/classes` has 20 attributes and `source = "/home/r/repo/target/eo/04-pull/org/eolang/math/number.eo"` in its `@XmirObject` annotation. 

So compiled from source `EOnumber` was deleted and replaced with downloaded from maven central `EOnumber`.

The same story when trying to update `eo-collections`

**Comment by maxonfjvipon** [comment]
It was accidentally discovered that after `mvn compile` files in `target/generated-sources` and `target/classes` are correct. But `mvn test-compile` step downloads the source from Maven Central and replaces outdated classes with already compiled ones from sources

**Comment by 0pdd** [comment]
@maxonfjvipon 2 puzzles [#2541](https://github.com/objectionary/eo/issues/2541), [#2543](https://github.com/objectionary/eo/issues/2543) are still not solved.

**Comment by maxonfjvipon** [comment]
#2534 is merged so I'm closing it

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2543](https://github.com/objectionary/eo/issues/2543) is still not solved; solved: [#2541](https://github.com/objectionary/eo/issues/2541).

**Comment by 0pdd** [comment]
@maxonfjvipon all 2 puzzles are solved here: [#2541](https://github.com/objectionary/eo/issues/2541), [#2543](https://github.com/objectionary/eo/issues/2543).
