### ISSUE TITLE
to create a translator from `xmir` to `phi-calculus`

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#2535]
We need to create a translator from `xmir` to `phi-calculus`.
It should be a new Mojo. This mojo must get `xmir` as input and transform it to the `phi-calculus`.
Here is some examples of the existing software (can help to implement this task):
- [try-phi,](https://github.com/objectionary/try-phi) 
- [phie](https://github.com/objectionary/phie)

**Comment by 0pdd** [comment]
@Graur the puzzle [#2573](https://github.com/objectionary/eo/issues/2573) is still not solved.

**Comment by yegor256** [comment]
duplicate of #2610
