### ISSUE TITLE
How to run only integration tests in `eo-maven-plugin`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2537]
I want to run only integration tests (that are placed in `eo-maven-plugin/src/it` folder). How can I do it?
@volodya-lombrozo do you know anything?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon, If you under `eo-maven-plugin` folder you can run the next command: 
```
mvn clean integration-test invoker:run -Dinvoker.test=fibonacci -DskipTests
```
Where `fibonacci` is the name of the integration test.  Also I use `-DskipTests` option to avoid unit tests run, so you can omit this parameter if you need to run unit tests.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo thank you so much!

**Comment by maxonfjvipon** [comment]
I think it would be better to extend documentation and add this command to the README

**Comment by Graur** [comment]
@maxonfjvipon Can please you extend it?

**Comment by maxonfjvipon** [comment]
@Graur sure
