### ISSUE TITLE
HmOptional.java:38-39: Add tests for {@link HmOptional}....

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2543]
The puzzle `2528-03b641f4` from #2528 has to be resolved: 

https://github.com/objectionary/eo/blob/624fef320754a2d4a59fc60e332b81b8d21b5066/eo-maven-plugin/src/main/java/org/eolang/maven/util/HmOptional.java#L38-L39

The puzzle was created by rultor on 17-Oct-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon I can take this task

**Comment by 0pdd** [comment]
The puzzle `2528-03b641f4` has disappeared from the source code, that's why I closed this issue.
