### ISSUE TITLE
Make `eq` attribute of standard objects (`int`, `float`, ...) to be an atom.

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo#2547]
IEEE 754 standard states that *"negative zero and positive zero should compare as equal with the usual (numerical) comparison operators"*.  ([check here](https://en.wikipedia.org/wiki/Signed_zero#Comparisons)).
To meet this standard, we need to make `eq` an atom. Then attribute `eq` of `float` will behave like in Java and will meet the standard.

**Comment by Graur** [comment]
@c71n93 But `eq` object was an atom. Then we decided to write it in EO. Now we want to make it an atom again. Can we solve this issue in some different way by EO?

**Comment by c71n93** [comment]
@Graur Yes, in #2554 as a result we decided to do it in EO.
