### ISSUE TITLE
Introduce `λ` attribute

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2566]
In phi-calculus we can strictly say if our object is atom or not - atoms have `λ` attribute and don't have `ϕ` attribute (presence of both attributes at the same time is prohibited in the calculus). Not-atoms don't have `λ` but have `ϕ`. 
But in our java implementation we don't have `λ` attribute at all. 
So need to introduce it in order to be closer to the calculus.

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2568](https://github.com/objectionary/eo/issues/2568) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2844](https://github.com/objectionary/eo/issues/2844) is still not solved; solved: [#2568](https://github.com/objectionary/eo/issues/2568).
