### ISSUE TITLE
org.eolang.morphed with `μ`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2571]
Let's introduce a new atom `morphed`, which will do this (inside of its "lambda" function):

  1. Get the 1st argument encapsulated: `x`
  2. Call `x.attr("μ").get() -> m` 
  3. Make `PhCopy(m) -> c`
  4. Apply 2nd, 3rd and all other arguments to `c`
  5. Give control to `c`

Only `PhDefault` will return itself on this request if "lambda" is absent and evaluate lambda and then return the result otherwise. Everybody else (`PhCopy`, `PhWith`, etc.) will evaluate the encapsulated object and then pass the request through.

Thanks to this new atom, we will be able to do this:

```
[] > app
  cage > x
    [t]
      t.plus 1 > @
  stdout > @
    sprintf
      "Sum is %d\n"
      morphed x 42
```

Should print `Sum is 43`.

**Comment by yegor256** [comment]
@maxonfjvipon thoughts?

**Comment by maxonfjvipon** [comment]
@yegor256 could you please explain what is `μ` attribute? I didn't find such attribute in phi-paper?

**Comment by maxonfjvipon** [comment]
@yegor256 in your example:
```
[] > app
  cage > x
    [t]
      t.plus 1 > @
  stdout > @
    sprintf
      "Sum is %d\n"
      morphed x 42
```
First argument of `morphed` is `x`. What does `x.attr("μ").get()` should return and how `μ` attribute should contain in general?

**Comment by yegor256** [comment]
@maxonfjvipon I think that `PhDefault` should `return this`

**Comment by yegor256** [comment]
no need to do this, I'm closing
