### ISSUE TITLE
Split `OptimizeMojo` into two parts

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2577]
Now we have two "trains" of optimizations that are used in `OpitmizeMojo`: `ParsingTrain` and `OptTrain`.
`ParsingTrain` does real optimizations: cleans xmir, finds warnings and errors. `OptTrain` prepares optimized xmir for transpiling to java. 
So it would be better for design to split the mojo into two mojos: 
- `OptimizeMojo` that does optimizations 
- `ShakeMojo` that does preparations for java

@yegor256 please confirm

**Comment by 0pdd** [comment]
@maxonfjvipon 2 puzzles [#2579](https://github.com/objectionary/eo/issues/2579), [#2580](https://github.com/objectionary/eo/issues/2580) are still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2638](https://github.com/objectionary/eo/issues/2638) is still not solved; solved: [#2579](https://github.com/objectionary/eo/issues/2579), [#2580](https://github.com/objectionary/eo/issues/2580).

**Comment by 0pdd** [comment]
@maxonfjvipon all 3 puzzles are solved here: [#2579](https://github.com/objectionary/eo/issues/2579), [#2580](https://github.com/objectionary/eo/issues/2580), [#2638](https://github.com/objectionary/eo/issues/2638).
