### ISSUE TITLE
EOrust.java:137-145: Fix EOrust. After getting rid of...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2587]
The puzzle `2437-10dd7966` from #2437 has to be resolved: 

https://github.com/objectionary/eo/blob/1325da69ced10e1fb5869424d08970c678848abb/eo-runtime/src/main/java/EOorg/EOeolang/EOrust.java#L137-L145

The puzzle was created by rultor on 14-Nov-23. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me
