### ISSUE TITLE
Mojo that prints XMIR to EO

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2592]
Let's make a new mojo that would take `.xmir` files and translate them to `.eo` files

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.33.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.0`

**Comment by maxonfjvipon** [comment]
@yegor256 repo was no updated in maven central. Let's try to release one more time

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.0`
