### ISSUE TITLE
let's use jhome instead of manually checking for JAVA_HOME

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2607]
See https://github.com/yegor256/jhome

**Comment by volodya-lombrozo** [comment]
@yegor256 Please, take a look on this doc: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by yegor256** [comment]
@volodya-lombrozo I don't do this intentionally, because I'm against automatic closing of tickets, see: https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by volodya-lombrozo** [comment]
@yegor256 I see. Thanks

**Comment by volodya-lombrozo** [comment]
@yegor256 btw, the article you sent says nothing about "automatic closing of tickets", but it is still useful, thanks.
