### ISSUE TITLE
PhiMojo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2610]
Let's create a new `PhiMojo`, which takes `.xmir` files from the `target/eo/2-optimize` directory and generates `.phi` files, saving them into the `target/eo/phi` directory. Let's stick to the format of phi expressions already defined at https://github.com/objectionary/try-phi

**Comment by yegor256** [comment]
@maxonfjvipon it's yours now, please help ASAP

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2825](https://github.com/objectionary/eo/issues/2825) is solved here.
