### ISSUE TITLE
Get rid of varargs at all

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2612]
The hard decision was made: vararg was a big mistake. So we need to get rid of it in eo at all. Only tuples...
It will make EO stronger and stricter. Also there'll be no trouble with translating EO to phi calculus expession

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2622](https://github.com/objectionary/eo/issues/2622) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2622](https://github.com/objectionary/eo/issues/2622) is solved here.
