### ISSUE TITLE
XMIR is insufficiently documented

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2635]
I  think that `XMIR` lacks a specification describing the structure of the file. It would be nice to introduce definitions of attributes `base`, `cut`, `ref`, `pos`, `original-name`, `ancestors`, `abstract`, `data`, `parent`, `level`, `const`, `as`.  Which of them are arbitrary for valid `XMIR` or for `transpilation`.
`XMIR`s are different in different stages, thus I guess its the better to describe the format after `shake`.

**Comment by volodya-lombrozo** [comment]
@levBagryansky I though we have https://github.com/objectionary/eo/blob/master/eo-parser/src/main/resources/XMIR.xsd for it

**Comment by volodya-lombrozo** [comment]
We, for example, can add `xs:documentation` ([doc](https://www.w3schools.com/xml/el_documentation.asp) and `xs:annotation`. Then we will be able to generate documentation from this XSD file, by utilising something like https://github.com/bitfehler/xs3p

**Comment by yegor256** [comment]
@levBagryansky we also have this: https://news.eolang.org/2022-11-25-xmir-guide.html
