### ISSUE TITLE
ShakeMojo.java:45-48: Add tests for ShakeMojo. ShakeMojo...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2638]
The puzzle `2577-73df16a8` from #2577 has to be resolved: 

https://github.com/objectionary/eo/blob/b0532d4031396e761a58cde80dbf5f432f92c524/eo-maven-plugin/src/main/java/org/eolang/maven/ShakeMojo.java#L45-L48

The puzzle was created by Alekseeva Yana on 28-Nov-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon I can do it

**Comment by maxonfjvipon** [comment]
@Yanich96 sure, go ahead

**Comment by 0pdd** [comment]
The puzzle `2577-73df16a8` has disappeared from the source code, that's why I closed this issue.
