### ISSUE TITLE
Abstract objects in horizontal notation

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2640]
Such code is valid at the moment:
```
[a b] (a.plus b > x) (1 > one) ("Hello" > str) > obj
```
It's the same as:
```
[a b] > obj
  a.plus b > x
  1 > one
  "Hello" > str
```
Such abstract objects in horizontal notation can be also used with braces:
```
([] (1 > one) ("Hello" > str)) > obj
```
While remaking grammar an ability to have such a code has been left in order to avoid potential problems. Now we can think about this question again.

@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon I think it's OK to have this in our syntax. Let's just make sure this code works (by adding a test to `SnippedTestCase`).

**Comment by maxonfjvipon** [comment]
@yegor256 we already have such: 
- https://github.com/objectionary/eo/blob/master/eo-parser/src/test/resources/org/eolang/parser/packs/syntax/anonymous.yaml 
- https://github.com/objectionary/eo/blob/master/eo-parser/src/test/resources/org/eolang/parser/packs/syntax/anonymous-more.yaml

**Comment by yegor256** [comment]
@maxonfjvipon they are syntax parsers. But do we have a test of a compiler? Maybe this code won't be able to convert into a working Java.
