### ISSUE TITLE
base attrbute can be ambiguous

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2643]
For example, `QQ.seq` will be 
```
base=".seq"  ..
  base=".eolang"  ..
    base=".org"  ..
..
```
but `seq` will be `base="org.eolang.seq"`. We need to make it more definite.

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me

**Comment by maxonfjvipon** [comment]
@levBagryansky could you please give this task to me? I think it can be part of #1602

**Comment by levBagryansky** [comment]
@maxonfjvipon yes, sure

**Comment by yegor256** [comment]
@levBagryansky @maxonfjvipon we'll make it more formal in #3375
