### ISSUE TITLE
Main.java:174-176: Make type casting when logging an app...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2645]
The puzzle `2591-eade6066` from #2591 has to be resolved: 

https://github.com/objectionary/eo/blob/fd370f69c889515c11f0157cae9d87379d625e85/eo-runtime/src/main/java/org/eolang/Main.java#L174-L176

The puzzle was created by rultor on 29-Nov-23. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@levBagryansky maybe you can take it and make the same printing you did in #2772?

**Comment by levBagryansky** [comment]
@yegor256 
What do you think about overriding of `Dataized.toString()` method which would print multiple representations of byte array like in the following `switch case`: https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/EOorg/EOeolang/EOerror.java#L148 ?
Or maybe it is better to create dedicated class?

**Comment by yegor256** [comment]
@levBagryansky I would create a separate classo for this
