### ISSUE TITLE
BinarizeMojo.java:52-54: Make it more generic. Perhaps by...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2648]
The puzzle `2118-1bbacef7` from #2118 has to be resolved: 

https://github.com/objectionary/eo/blob/f384b1c98c9dc66e18d160cdb4216012a6047bc2/eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java#L52-L54

The puzzle was created by @rultor on 29-Nov-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me
