### ISSUE TITLE
Lambda near package formation in phi calculus

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2655]
Let's add lambda near package formation in phi calculus expression. This will help to [get back](https://github.com/objectionary/eo/issues/2642) from phi to xmir.

Example:
```
+package foo
[] > main
```
phi:
```
{foo ↦ ⟦main ↦ ⟦⟧, λ ⤍ Package⟧}
```
@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon let's do it
