### ISSUE TITLE
VerifyMojoTest.java:36-39: Add test that checks the...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2674]
The puzzle `2546-12d07944` from #2546 has to be resolved: 

https://github.com/objectionary/eo/blob/9061ce97fd847cfd34b11269ad65f011728d9e45/eo-maven-plugin/src/test/java/org/eolang/maven/VerifyMojoTest.java#L36-L39

The puzzle was created by rultor on 05-Dec-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon I can take this task

**Comment by maxonfjvipon** [comment]
@Yanich96 sure, go ahead

**Comment by Yanich96** [comment]
@maxonfjvipon Did I understand correctly that this message should be in this directory  eo-parser/src/main/resources/org/eolang/parser/fail-on-critical.xsl?

**Comment by maxonfjvipon** [comment]
@Yanich96 no, it's the xsl transformation that puts error message to parsed xmir

**Comment by 0pdd** [comment]
The puzzle `2546-12d07944` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2746](https://github.com/objectionary/eo/issues/2746), [#2747](https://github.com/objectionary/eo/issues/2747) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2747](https://github.com/objectionary/eo/issues/2747), [#2764](https://github.com/objectionary/eo/issues/2764) are still not solved; solved: [#2746](https://github.com/objectionary/eo/issues/2746).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2747](https://github.com/objectionary/eo/issues/2747), [#2790](https://github.com/objectionary/eo/issues/2790), [#2791](https://github.com/objectionary/eo/issues/2791) are still not solved; solved: [#2746](https://github.com/objectionary/eo/issues/2746), [#2764](https://github.com/objectionary/eo/issues/2764).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#2747](https://github.com/objectionary/eo/issues/2747), [#2820](https://github.com/objectionary/eo/issues/2820), [#2821](https://github.com/objectionary/eo/issues/2821), [#2822](https://github.com/objectionary/eo/issues/2822) are still not solved; solved: [#2746](https://github.com/objectionary/eo/issues/2746), [#2764](https://github.com/objectionary/eo/issues/2764), [#2790](https://github.com/objectionary/eo/issues/2790), [#2791](https://github.com/objectionary/eo/issues/2791).

**Comment by 0pdd** [comment]
@0pdd all 8 puzzles are solved here: [#2746](https://github.com/objectionary/eo/issues/2746), [#2747](https://github.com/objectionary/eo/issues/2747), [#2764](https://github.com/objectionary/eo/issues/2764), [#2790](https://github.com/objectionary/eo/issues/2790), [#2791](https://github.com/objectionary/eo/issues/2791), [#2820](https://github.com/objectionary/eo/issues/2820), [#2821](https://github.com/objectionary/eo/issues/2821), [#2822](https://github.com/objectionary/eo/issues/2822).
