### ISSUE TITLE
AssembleMojo.java:112-114: Remove the following...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2678]
The puzzle `2443-427f9946` from #2443 has to be resolved: 

https://github.com/objectionary/eo/blob/015f73814c9f158357866a07200b653cbcf0417d/eo-maven-plugin/src/main/java/org/eolang/maven/AssembleMojo.java#L112-L114

The puzzle was created by @rultor on 06-Dec-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by c71n93** [comment]
@maxonfjvipon could you assign me please?
