### ISSUE TITLE
BinarizeParseMojo.java:148-154: This method may be more...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2683]
The puzzle `2649-2559f1c7` from #2649 has to be resolved: 

https://github.com/objectionary/eo/blob/14ca213bd98ebb45341b93cb34ba094dc371e6e8/eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeParseMojo.java#L148-L154

The puzzle was created by @rultor on 07-Dec-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me
