### ISSUE TITLE
eo-runtime must not have ANY non-test dependencies

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2684]
The `resolve` goal in our plugin can't deal with JAR artifacts that have transitive dependencies. It simply ignores them. However, `commons-text` was added to eo-runtime, by mistake. Let's 1) delete it from there, and 2) introduce a check into the build of eo-runtime (together with documentation) that would prevent this from happening in the future.

**Comment by yegor256** [comment]
@maxonfjvipon please, help us here

**Comment by yegor256** [comment]
@maxonfjvipon this should help, I believe: https://maven.apache.org/enforcer/enforcer-rules/banTransitiveDependencies.html

**Comment by yegor256** [comment]
@maxonfjvipon the flag works only for dependencies that are not eo-runtime. It works for those packages that we resolve, like eo-strings, etc. Thus, eo-runtime is unpackaged by its dependencies are ignored. This is the log I'm getting: 

```
java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
      at org.eolang.Data$ToPhi.toPhi (Data.java:237)
      at org.eolang.Data$ToPhi.<init> (Data.java:161)
      at org.eolang.PhSafe.attr (PhSafe.java:93)
      at org.eolang.PhNamed.attr (PhNamed.java:88)
      at org.eolang.PhSafe.attr (PhSafe.java:90)
```

Here: https://github.com/objectionary/eo/actions/runs/7126950802/job/19405845463

**Comment by yegor256** [comment]
@maxonfjvipon maybe the flag should also work for eo-runtime, but currently it doesn't

**Comment by yegor256** [comment]
@maxonfjvipon this bug holds this ticket: https://github.com/objectionary/normalizer-maven-plugin/issues/4

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2702](https://github.com/objectionary/eo/issues/2702) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2702](https://github.com/objectionary/eo/issues/2702) is solved here.

**Comment by yegor256** [comment]
@rultor release, tag is `0.34.1`
