### ISSUE TITLE
ANTLR Tool version 4.11.1 used for code generation does not match the current runtime version 4.12.0

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2691]
There is an annoying log warning message, which is printed by the `eo-maven-plugin` when the version of ANTLR used inside `eo-parser` is different from the version used in `eo-maven-plugin`. I suggest adding a compile-time check into the `eo-maven-plugin`, which would fail the build if the version of ANTLR in `eo-parser` is different from the version in the plugin.

**Comment by maxonfjvipon** [comment]
@yegor256 `eo-maven-plugin` and `eo-parser` both uses `antlr4` version from `eo-parent`. So when it's updated, it's updated in both plugins.

Speaking about the next warnings:
![image](https://github.com/objectionary/eo/assets/37025995/4f53212b-72fd-4798-9805-5b01a154fca0)

It's related to antlr versions in `qulice`. So we can't handle them here.

May we close the ticket it such case?

**Comment by yegor256** [comment]
@maxonfjvipon got it, thanks!
