### ISSUE TITLE
Can't read EBNF in Dark Mode in GitHub

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2696]
What I see in `eo` repository in readme:
![image](https://github.com/objectionary/eo/assets/51804353/a5eead0d-b6a4-4a9f-86c2-e96d0ea6a1c6)

I use GitHub dark mode.

**Comment by yegor256** [comment]
@volodya-lombrozo I believe it's fixed in b4d80e7

**Comment by volodya-lombrozo** [comment]
@yegor256 only for EO. Phi-calculus remains the same: 
<img width="868" alt="image" src="https://github.com/objectionary/eo/assets/51804353/15b0f65f-eea4-496c-bd40-6f9e83187f91">

**Comment by yegor256** [comment]
@volodya-lombrozo I believe, it's fixed in 6b9de2ca6, please check

**Comment by volodya-lombrozo** [comment]
@yegor256 Now it's visible, thank you
