### ISSUE TITLE
OptCached doesn't take into account the date of the source

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2713]
At the moment, `OptCached` accepts an XML document and returns its optimized version. It also checks, whether an already optimized XML exists in the cache. However, it doesn't pay attention to the date of the original XML and the date of the document in the cache. This often leads to errors because the data in the cache is already expired.

I think, we should change the interface of `Optimization` from `Function<XML, XML>` to `Function<Path, XML>`. It should accept the path of the source document, not the content of it.

Also, I think it's better to use `Func` from Cactoos instead of `Function` from JDK, since it allows checked exceptions to be thrown from the `apply` method.

**Comment by yegor256** [comment]
@volodya-lombrozo can you please fix this? it's pretty urgent, since it blocks this: https://github.com/objectionary/eo/pull/2711

**Comment by volodya-lombrozo** [comment]
@yegor256 Yes, I'll

**Comment by yegor256** [comment]
@volodya-lombrozo it doesn't block #2711 anymore, but still would be nice to fix, since the entire caching mechanism is kind of broken now
