### ISSUE TITLE
EBNF not rendered for README.md

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#2719]
Related issue: https://github.com/objectionary/eo/issues/2706
I think this issue shouldn't be closed until it's fixed.

## Example

Commit: 692061d6121e53fdf3bd91b045e73791ea4bf34f

![image](https://github.com/objectionary/eo/assets/48378098/5eb8157f-0d5d-46d4-b5fe-107d57a068cd)

**Comment by yegor256** [comment]
@deemp I'm trying: https://stackoverflow.com/questions/77721596/why-convert-from-imagemagick-makes-an-empty-blank-png-image-on-some-machines

**Comment by yegor256** [comment]
@deemp fixed in 6b9de2ca6
