### ISSUE TITLE
MainTest.java:43-48: Enable the tests. Tests {@link...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2723]
The puzzle `2718-833aa636` from #2718 has to be resolved: 

https://github.com/objectionary/eo/blob/aaf5969452699c72bfcd9c33fc1299e3df77f845/eo-runtime/src/test/java/org/eolang/MainTest.java#L43-L48

The puzzle was created by rultor on 22-Dec-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by c71n93** [comment]
@maxonfjvipon what did you mean here: "arguments after "org.eolang.io.stdout" are stored into "tuple"". What sort of arguments?

**Comment by maxonfjvipon** [comment]
@c71n93 if you check `run` method in `Main.java` class you'll see that first argument is used as program to run, for example `org.eolang.io.stdout`, but all other arguments are used as parameters for such program and to pass to to the program - they are stored into tuple.

For example in `deliversCleanOutput` test we do `MainTest.exec("org.eolang.io.stdout", "Hello!"),`
Here `org.eolang.io.stdout` is our program, `"Hello!"` is a parameter. "Hello!" will be stored to `tuple` and then the tuple will be passed to `stdout`.

But `stdout` does not accept `tuple`, it accepts `string`

**Comment by c71n93** [comment]
@maxonfjvipon could you assign me, please?
