### ISSUE TITLE
Explaining of immutability

### ISSUE THREAD

**Issue by support512** [objectionary/eo#2728]
Statement: we don't tolerate mutability.
I expect: only constants and no variables like in Haskell.
I see: mutable variable x in the example in readme:

```
x.write 2
```
Could please someone clarify this misunderstanding, Immutability of what is meant by the statement (for end programmer)

**Comment by yegor256** [comment]
@support512 see the explanation here: https://www.yegor256.com/2016/09/07/gradients-of-immutability.html (also, updated our README: [73732dc](https://github.com/objectionary/eo/commit/73732dc11f75f504f74449986a5bcb89e8e17299))

**Comment by support512** [comment]
OK, thanks 

x.write 2
x.write 3
x.write 4

Look, the encapsulated data (some number) is mutating line by line.

It isn't that programmer expects from the "immutable object". Even it creates new instance for each change of any prop, it still destroy encapsulation in common.

The statement has to be: "we don't tolerate mutability of **instance** of object after it was created".
