### ISSUE TITLE
OptCachedTest.java:55-58:...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2744]
The puzzle `2422-ec85e516` from #2422 has to be resolved: 

https://github.com/objectionary/eo/blob/da9e7dc5798b3ccf315ee5a80b643afef83b8d87/eo-maven-plugin/src/test/java/org/eolang/maven/optimization/OptCachedTest.java#L55-L58

The puzzle was created by rultor on 27-Dec-23. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon assign me please
