### ISSUE TITLE
VerifyMojoTest.java:46-51: The messages "Warnings...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2747]
The puzzle `2674-94c2148b` from #2674 has to be resolved: 

https://github.com/objectionary/eo/blob/9be0d3238b317ea4026f598ef671dc693d38ad8f/eo-maven-plugin/src/test/java/org/eolang/maven/VerifyMojoTest.java#L46-L51

The puzzle was created by rultor on 28-Dec-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon assign me please

**Comment by 0pdd** [comment]
The puzzle `2674-94c2148b` has disappeared from the source code, that's why I closed this issue.
