### ISSUE TITLE
XMIRTest.java:49-54: Xmir samples are not converted...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2750]
The puzzle `2729-2c784c24` from #2729 has to be resolved: 

https://github.com/objectionary/eo/blob/44724edad3564d1bf9847445cd492ed94939cb6c/eo-parser/src/test/java/org/eolang/parser/XMIRTest.java#L49-L54

The puzzle was created by maxonfjvipon on 28-Dec-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by c71n93** [comment]
@maxonfjvipon could you assign me please?

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2779](https://github.com/objectionary/eo/issues/2779), [#2780](https://github.com/objectionary/eo/issues/2780) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#2779](https://github.com/objectionary/eo/issues/2779), [#2780](https://github.com/objectionary/eo/issues/2780).
