### ISSUE TITLE
How to read objects with dots?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2751]
I received the following `eo` code:
```eo
$
.foo
  .a
.plus
  1
```
It should be something like `this.a.foo() + 1` in java. To be honest, I just can't understand if I received the correct output. How should I read `eo` objects with dots in the beginning? 
Maybe you can add some examples to the README?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you help here?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I think we can write a blog post about it where we can explain syntax notations in EO.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you help me here for now, please? It's kind of urgent.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo we have 4 notations for methods. For `this.a.foo() + 1` it would be: 
1. horizontal
```
$.a.foo.plus 1
```
2. vertical
```
$
.a
.foo
.plus
  1
```
3. reversed horizontal
```
plus. (foo. (a. $)) 1
```
4. reversed vertical
```
plus.
  foo.
    a.
      $
  1
```
You output is not really correct

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Thanks

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo let me know if you have any more questions

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon If I have `1 + 2`, what should I get:
```xml
 <o base="plus">
      <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
      <o base="int" data="bytes">00 00 00 00 00 00 00 02</o>
 </o>
``` 
or 
```
 <o base=".plus">
      <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
      <o base="int" data="bytes">00 00 00 00 00 00 00 02</o>
</o>
```

**Comment by yegor256** [comment]
@volodya-lombrozo it's the second option:

```
<o base=".plus">
      <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
      <o base="int" data="bytes">00 00 00 00 00 00 00 02</o>
</o>
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Ok, then I confused. For the `this.a.foo() + 1` I got the following XMIR:
```xml
<o base=".plus">
    <o base=".intValue">
       <o base="$"/>
       <o base=".a"/>
    </o>
    <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
</o>
```
And it seems correct to me according with your answer. But this XMIR is represented as follows:
```eo
tuple
  $
  .intValue
    .a
  .plus
    1
```

**Comment by yegor256** [comment]
@volodya-lombrozo don't you miss the `method` attribute? I think you got this:

```
<o base=".plus">
    <o base=".intValue">
       <o base="$"/>
       <o base=".a" method=""/> <!-- here! -->
    </o>
    <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
</o>
```

**Comment by yegor256** [comment]
@volodya-lombrozo simply put, this:

```
<o base="a"/>
<o base=".foo" method=""/>
```

is the same as:

```
<o base=".foo">
  <o base="a"/>
</o>
```

But the parser produces the first form, while a special XSL transformation turns it into the second one.

**Comment by volodya-lombrozo** [comment]
@yegor256 Since I don't use `wrap-method-calls.xsl`,  adding `method` attribute won't help me.

**Comment by yegor256** [comment]
@volodya-lombrozo you should use it, I believe. You should not work with the XMIR produced by the parser _without_ optimizations provided by the `eo:optimize` mojo.

**Comment by volodya-lombrozo** [comment]
@yegor256 So, I have to receive the following XMIR:
```xml
<o base=".plus">
    <o base=".intValue">
      <o base=".a">
       <o base="$"/> 
      </o>    
    </o>
    <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
</o>
```

for `this.a.foo() + 1` ?

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo you should use it, I believe. You should not work with the XMIR produced by the parser _without_ optimizations provided by the `eo:optimize` mojo.

I don't use parser either, I'm trying to construct XMIR from bytecode instructions.

**Comment by yegor256** [comment]
@volodya-lombrozo yes, this is correct:

```
<o base=".plus">
    <o base=".intValue">
      <o base=".a">
        <o base="$"/> 
      </o>    
    </o>
    <o base="int" data="bytes">00 00 00 00 00 00 00 01</o>
</o>
```

**Comment by maxonfjvipon** [comment]
> It's a technical limitation of the parser, we can't overcome it :(

@yegor256 I think maybe we actually can... let me inverstigate

**Comment by yegor256** [comment]
@volodya-lombrozo still a bug?

**Comment by volodya-lombrozo** [comment]
@yegor256 I believe we need to add some docs about `method-wraps` and dot notation. Otherwise, somebody else will face with the same question again.

**Comment by yegor256** [comment]
@volodya-lombrozo this mechanism is explained here: https://news.eolang.org/2022-11-25-xmir-guide.html (see the "methods" section)

**Comment by volodya-lombrozo** [comment]
@yegor256 First of all, this link is far from the repository. When you close this ticket, I will loose it immediately.
Moreover, it's a blog post, not official documentation. I believe a **blog post** is typically informal and narrative, aimed at engaging readers with stories, opinions, or updates. **Documentation** is formal and structured, designed to provide clear instructions, guidelines, or reference information for using a product or system.  So, when I read a "blog post", I just have no trust to it.

**Comment by yegor256** [comment]
@volodya-lombrozo I agree, we'll deal with it in #3375
