### ISSUE TITLE
Program braces in phi-calculus expression

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2754]
This is a canonical phi-calculus EBNF:
![photo_2023-12-28 17 38 08](https://github.com/objectionary/eo/assets/37025995/764fed68-a9bd-4b9b-99d8-3bb9950b6050)

Here we assume that `program` is a special alpha binding where attribute is `Φ`. 
In order not to write such top level alpha binding explicitly in every expression we decided to replace it with `{ }` brackets.
Current [Phi.g4](https://github.com/objectionary/eo/blob/fa24c7cc47e1ac473fb930f3a08ccc4d88d9d1e3/eo-parser/src/main/antlr4/org/eolang/parser/Phi.g4) has `bindings` rule between `{ }` brackets which seems wrong (because object is not always bindings).

If we replace current rule `program: '{' bindings '}'` with `program: '{' object '}'` (to be more canonical) then we get not really pretty phi expression, for example: `{[x -> y]}`.

I suggest to get rid of `{ }` brackets and write top level alpha binding with `Φ` explicitly.
@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon this is what is legal:

```
{ a -> [ a -> 42 ] }
{ a1 -> 42, a2 -> [] }
```

This is NOT legal:

```
{ [ a -> 42 ] }
{ 42 }
{ [] }
```

I don't think that `program: { object }` makes sense.

It seems that I didn't understand your question.

**Comment by maxonfjvipon** [comment]
@yegor256 I'm just trying to figure out what we're trying to replace with `{ }` brackets.
In case: `program: Φ -> formation` => `program: Φ -> [ bindings ]` we replace `Φ -> []`
In case: `program: Φ -> dispatch` or `program: Φ -> application` we replace something else, because `dispatch` may contain no `bindings` at all.

I think we should decide what exactly syntax (or semantic) rule we replace with `{ }` brackets.

**Comment by yegor256** [comment]
@maxonfjvipon what's wrong with `program: Φ -> application`? Something like this is valid: `{ $.int(42) }`. It's similar to: `Φ -> $.int(42)`. Dataization of `Φ` is the execution of a program. Thus, this program will fail, since there is no `int` in `Φ`, but syntactically it's correct.

**Comment by maxonfjvipon** [comment]
@yegor256 here `Φ -> $.int(42)` => `{ $.int(42) }` brackets `{ }` are replacing `Φ ->`
But here `Φ -> [ x -> Φ.org.eolang.int ]` => `{ x -> Φ.org.eolang.int }` brackets `{ }` are replacing `Φ -> []`.
I think it may confuse some devs who works with our interpretation of phi-calculus expression.

**Comment by yegor256** [comment]
@maxonfjvipon I agree. Let's make it this way: `{[ x -> Φ.int(42) ]}`, if they mean `Φ -> [ x -> Φ.int(42) ]`

**Comment by maxonfjvipon** [comment]
@yegor256 so we establish that brackets `{ }` are replacing top level alpha binding `Φ -> `.

**Comment by yegor256** [comment]
@maxonfjvipon yes
