### ISSUE TITLE
OptCached.java:44-49: Use checksum, not time. The...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2764]
The puzzle `2746-c8b58fdb` from #2746 has to be resolved: 

https://github.com/objectionary/eo/blob/00a9eb28b78462487afdff4cefc6dffcb8743f93/eo-maven-plugin/src/main/java/org/eolang/maven/optimization/OptCached.java#L44-L49

The puzzle was created by rultor on 09-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon assign me please
