### ISSUE TITLE
StEoLoggedTest.java:80-82: After removing conversion from...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2779]
The puzzle `2750-1a6a1697` from #2750 has to be resolved: 

https://github.com/objectionary/eo/blob/12bc87384f14ebb58865166e3226d0de66063f1d/eo-parser/src/test/java/org/eolang/parser/StEoLoggedTest.java#L80-L82

The puzzle was created by rultor on 15-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by c71n93** [comment]
@maxonfjvipon could you assign me, please?
