### ISSUE TITLE
Tests of `bool.while` with iteration over a `tuple`

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo#2785]
There is no tests of `bool.while` that iterates over a tuple. 
I ran into the problem of iterating over a `tuple`, and I didn't find a single working example in tests. I think we need to add some tests to [`eo-runtime/src/test/eo/org/eolang/bool-tests.eo`](https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/eo/org/eolang/bool-tests.eo). 
@yegor256 @maxonfjvipon WDYT?

**Comment by c71n93** [comment]
@yegor256 @maxonfjvipon What about this? Can I write some tests for `while`?

**Comment by maxonfjvipon** [comment]
@c71n93 sure, you can, especially if your tests will break something

**Comment by 0pdd** [comment]
@c71n93 the puzzle [#2818](https://github.com/objectionary/eo/issues/2818) is still not solved.

**Comment by maxonfjvipon** [comment]
@c71n93 still an issue?

**Comment by c71n93** [comment]
@maxonfjvipon no, tests in [while-tests.eo](https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/eo/org/eolang/while-tests.eo) are pretty good, thanks!
