### ISSUE TITLE
OptCached.java:52-56: Unify caching mechanism on stages:...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2791]
The puzzle `2746-ac77dd68` from #2746 has to be resolved: 

https://github.com/objectionary/eo/blob/036be9f42fa55cf7015dbc66068cccfeb055a93f/eo-maven-plugin/src/main/java/org/eolang/maven/optimization/OptCached.java#L52-L56

The puzzle was created by rultor on 17-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon assign me please

**Comment by 0pdd** [comment]
The puzzle `2746-ac77dd68` has disappeared from the source code, that's why I closed this issue.
