### ISSUE TITLE
Can we use single quote instead of tripled?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2802]
I started using `Xmir.Default::new::toEO` method and here is some of the results:
```eo
1 > access
"""
(Lcom/example/A;)V
""" > descriptor
"""
""" > signature
* > exceptions
```

As you can see they are rather hard readable. Can we use something like:
```
1 > access
"(Lcom/example/A;)V" > descriptor
"" > signature
* > exceptions
```

or if you need tripled quotes:
```eo
1 > access
"""(Lcom/example/A;)V""" > descriptor
"""""" > signature
* > exceptions
```

**Comment by volodya-lombrozo** [comment]
Sometimes I can even get the following:
```eo
  field > j$a
    18
    """
    Lcom/example/A;
    """
    """
    """
    """
    """
```

Which also looks interesting.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Can you help here, please?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo sure

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.1`

**Comment by yegor256** [comment]
@volodya-lombrozo 0.35.1 was released, please try it out

**Comment by volodya-lombrozo** [comment]
@yegor256 Now it works like a charm. @maxonfjvipon Thank you!
