### ISSUE TITLE
hmethod-after-vmethod.yaml:1-4: Enable the test when it's...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2806]
The puzzle `2736-68649196` from #2736 has to be resolved: 

https://github.com/objectionary/eo/blob/ba5f30b29e4ce78dc8e9c31248d183902591d080/eo-parser/src/test/resources/org/eolang/parser/packs/syntax/hmethod-after-vmethod.yaml#L1-L4

The puzzle was created by rultor on 22-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@yegor256 please take a look. Should we all horizontal method after vertical one?
```
x
.y.z
```

**Comment by yegor256** [comment]
@maxonfjvipon I believe, this syntax should be prohibited. We should either use horizontal or vertical syntax, not a mix of them.

**Comment by maxonfjvipon** [comment]
@yegor256 ok, then I have a few more questions about syntax. What syntax should be valid, what should not:
1. vertical method after vertical application
```
x
  y
.z
```
2. vertical method after horizontal application
```
x y
.z
```
3. vertical method after horizontal method
```
x.y
.z
```
4. horizontal application after vertical method
```
x
.y z
```
5. vertical application after vertical method
```
x
.y
  z
```

**Comment by maxonfjvipon** [comment]
@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon I thinks (2) and (3) must be illegal
