### ISSUE TITLE
bool-tests.eo:164-166: Enable this test. For some reason...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2818]
The puzzle `2785-8797cda9` from #2785 has to be resolved: 

https://github.com/objectionary/eo/blob/2d5a46e634bfb21cec4d184bd82414fc3e2551e5/eo-runtime/src/test/eo/org/eolang/bool-tests.eo#L164-L166

The puzzle was created by rultor on 26-Jan-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
Similar to #2834

**Comment by 0pdd** [comment]
The puzzle `2785-8797cda9` has disappeared from the source code, that's why I closed this issue.
