### ISSUE TITLE
OptCached.java:45-55: Refactor OptCache Class Currently,...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2820]
The puzzle `2790-ef16f785` from #2790 has to be resolved: 

https://github.com/objectionary/eo/blob/99ed421b3d855afe6a55c2b0f97dae824dc4549b/eo-maven-plugin/src/main/java/org/eolang/maven/optimization/OptCached.java#L45-L55

The puzzle was created by rultor on 26-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon assign me, please

**Comment by 0pdd** [comment]
The puzzle `2790-ef16f785` has disappeared from the source code, that's why I closed this issue.
