### ISSUE TITLE
Question about cache and inheritance

### ISSUE THREAD

**Issue by Yanich96** [objectionary/eo#2832]
Now I'm trying to come up with better caching logic. At this moment I'm researching code, that I can know what I need to work with. I'm thinking about how to make a unified logic for working with the cache for all mojos. But there are several cache mechanisms in code inherited from different interfaces, and this mechanisms use some functions inside.

For example: `FtCached` is implemented from `Footprint` and  `OptCached` is implemented from `Optimization`. For data verification they have a common logic. If you look at the names of these classes, they should check whether there are cached files, save the files to the cache and load them from there. But this classes have many unnecessary methods: 
`FtCached`  has method 
```ruby
@Override
public List<Path> list(final String ext) throws IOException {
    return this.origin.list(ext);
    }
``` 
that returns list of files from main directory, but not from cache directory.
`OptCached` has method
```ruby
@Override
public XML apply(final XML xml)
```
that performs checking, loading, saving files in cache and transformation files. 

I believe that it is wrong. Need to remove unnecessary logic from this classes. As you can see, unnecessary logic appears as a result of inheritance. 

My idea is to create a class that will verify data in the cache, save it to the cache and load from it. At the moment, in order not to break the current logic and tests, it uses absolute paths of the source file and the cached one, if any. Since each mojo has its own cache directories, the path to the cached file can be created.

I want to show the work of the shared cache in `ParseMojo`. But I need remove implementation from `Footprint` and unnecessary tests. Do I have the right to do this? Or what is the best way for me to proceed? 
@yegor256 @volodya-lombrozo @maxonfjvipon

**Comment by volodya-lombrozo** [comment]
@Yanich96, before delving into details, I would recommend you to read [this post about formatting issues](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Applying some of the suggestions might help readers to understand you:

1.  Use  \`\` quotes to separate technical terms from ordinary text: **UNADVISABLE**: FtCached **BETTER**: `FtCached`
2. Code formatiing.

**UNADVISABLE**:
```
@Override
    public List<Path> list(final String ext) throws IOException {
        return this.origin.list(ext);
    }
```

**BETTER**
```
@Override
public List<Path> list(final String ext) throws IOException {
  return this.origin.list(ext);
}
```

3. Use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)
 
**UNADVISABLE**
```
@Override
public List<Path> list(final String ext) throws IOException {
  return this.origin.list(ext);
}
```

**BETTER**
```java
@Override
public List<Path> list(final String ext) throws IOException {
  return this.origin.list(ext);
}
```

**Comment by volodya-lombrozo** [comment]
@Yanich96 

>  FtCached is inherited from Footprint and OptCached is inherited from Optimization.

We typically don't employ "inheritance." What you are attempting to clarify is subtyping. You can learn more about the difference [here](https://stackoverflow.com/questions/23592131/what-is-the-difference-between-subtyping-and-inheritance-in-oo-programming). We "implement" these interfaces; we don't "inherit" them.

**Comment by volodya-lombrozo** [comment]
@Yanich96 Regarding caching:
> But this classes have many unnecessary methods

Why? These methods are necessary in their context.

> Need to remove unnecessary logic from this classes. As you can see, unnecessary logic appears as a result of inheritance.

Are you suggesting removing `implements Footprint` and  `List<Path> list(final String ext) throws IOException` from `FtCached`?

I would propose the following implementation algorithm:
1. Create a class; let's name it `Cache` for now.
2. Attempt to use `Cache` in  both `FtCache` and `OptCache`
3. If `FtCache` and `OptCache` end up doing nothing except redirecting calls to  `Cache`, we can easily replace  `FtCache` and `OptCache` with `Cache`

**Comment by Yanich96** [comment]
@volodya-lombrozo I have changed my issue. Check please

**Comment by volodya-lombrozo** [comment]
@Yanich96 What about [this](https://github.com/objectionary/eo/issues/2832#issuecomment-1920806973)?

**Comment by Yanich96** [comment]
@volodya-lombrozo I have created class `Cache` and I used it in `FtCache`. But I have problems because of `FtCache` implements `Footprint`. I can demonstrate that my current result - working prototype, but its code isn't correctly.

**Comment by volodya-lombrozo** [comment]
@Yanich96 Can we close this issue then?

**Comment by Yanich96** [comment]
@volodya-lombrozo we can
