### ISSUE TITLE
cage.eo:62-66: Make up with an idea how to prevent...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2836]
The puzzle `1698-c7207422` from #1698 has to be resolved: 

https://github.com/objectionary/eo/blob/bfd4e77eeef8acb49147707f0849c2c9c246abdf/eo-runtime/src/main/eo/org/eolang/cage.eo#L62-L66

The puzzle was created by rultor on 01-Feb-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896) are still not solved; solved: [#2890](https://github.com/objectionary/eo/issues/2890).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2896](https://github.com/objectionary/eo/issues/2896) is still not solved; solved: [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#3181](https://github.com/objectionary/eo/issues/3181) is still not solved; solved: [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#2890](https://github.com/objectionary/eo/issues/2890), [#2891](https://github.com/objectionary/eo/issues/2891), [#2896](https://github.com/objectionary/eo/issues/2896), [#3181](https://github.com/objectionary/eo/issues/3181).
