### ISSUE TITLE
bool-tests.eo:84-87: Enable the test. After getting rid...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2837]
The puzzle `2437-9d2cb92f` from #2437 has to be resolved: 

https://github.com/objectionary/eo/blob/bfd4e77eeef8acb49147707f0849c2c9c246abdf/eo-runtime/src/test/eo/org/eolang/bool-tests.eo#L84-L87

The puzzle was created by rultor on 01-Feb-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
Similar to #2834

**Comment by 0pdd** [comment]
The puzzle `2437-9d2cb92f` has disappeared from the source code, that's why I closed this issue.
