### ISSUE TITLE
duplication production rule `comment`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2846]
EBNF fails now: https://github.com/objectionary/eo/actions/runs/7767407515/job/21184221160#step:9:16

**Comment by yegor256** [comment]
@maxonfjvipon please, check this one

**Comment by maxonfjvipon** [comment]
@yegor256 you're right. `comment` is a parser rule, `COMMENT` is a lexer rule. They actually may be the same (in lowcase). Do you suggest to rename one of them?

**Comment by yegor256** [comment]
@maxonfjvipon yes, we have to rename. This is the only way to make EBNF rendering work.

**Comment by yegor256** [comment]
@maxonfjvipon I enable EBNF job for pull requests too, in 7089d7dc5
