### ISSUE TITLE
XeEoListener.java:52-55: Change severity on comments...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2860]
The puzzle `2841-24b89c01` from #2841 has to be resolved: 

https://github.com/objectionary/eo/blob/2dda397a5c41ec4d074e63b8a579b47c590e6015/eo-parser/src/main/java/org/eolang/parser/XeEoListener.java#L52-L55

The puzzle was created by rultor on 05-Feb-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by c71n93** [comment]
@maxonfjvipon could you assign me, please?

**Comment by maxonfjvipon** [comment]
The main goal here - to write a description/documentation for every named abstract object in `eo-runtime` module. The description should:
1. start with capital letter
2. end with dot
3. consist of at least 64 characters
4. explain the main purpose of the object
5. [optional, but preferable] show an example of usage

After all objects are documented, we will get rid of noisy logs and can change severity on comments validation.

It's not necessarily to document all objects in one pull request. 3-5 would be enough.

**Comment by 0pdd** [comment]
The puzzle `2841-24b89c01` has disappeared from the source code, that's why I closed this issue.
