### ISSUE TITLE
Does Phi.g4 supports XI without dispatch?

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2864]
> I see [here](https://github.com/objectionary/eo/blob/6ea26b8615cdce73aab004a1faac403c9f1f14c5/eo-parser/src/main/antlr4/org/eolang/parser/Phi.g4#L77) that XI must have at least one dispatch. However, the following EO program uses $ without an attribute:
> 
> ```
> [] > prints-itself
>   assert-that > @
>    length.
>      as-phi $
>    $.greater-than 0
> ```
> 
> And it is translated into a ϕ-term with XI and without an attribute:
>
> 
> ```
> {org ↦ ⟦eolang ↦ ⟦prints-itself ↦ ⟦φ ↦ Φ.org.eolang.as-phi(α0 ↦ ξ).length.gt(α0 ↦ Φ.org.eolang.int(α0 ↦ Φ.org.eolang.bytes(Δ ⤍ 00-00-00-00-00-00-00-00)))⟧, prints-itself-to-console ↦ ⟦x ↦ Φ.org.eolang.int(α0 ↦ Φ.org.eolang.bytes(Δ ⤍ 00-00-00-00-00-00-00-2A)), φ ↦ Φ.org.eolang.io.stdout(α0 ↦ Φ.org.eolang.as-phi(α0 ↦ ξ))⟧, λ ⤍ Package⟧, λ ⤍ Package⟧}
> ```
>
> In particular, it has a subterm
>
> Φ.org.eolang.as-phi(α0 ↦ ξ)
>
> Just want to clarify that this is normal and XI can be used without a dispatch.

It seems our Phi.g4 grammar does not support XI without dispatch, let's find out

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2866](https://github.com/objectionary/eo/issues/2866) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2866](https://github.com/objectionary/eo/issues/2866) is solved here.

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.35.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.2`
