### ISSUE TITLE
Issue from Sonar (PhPackage.java): Call "remove()" on "objects".

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo#2887]
Check [this issue from Sonar](https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&resolved=false&id=com.objectionary%3Aeo&open=AYhNMJGi3sXPtjcNjexI). This issue need to be resolved to fix Sonar workflow CI https://github.com/objectionary/eo/issues/2251.

**Comment by yegor256** [comment]
fixed
