### ISSUE TITLE
PhTracedEnclosure.java:36-38: Make the class thread safe....

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2891]
The puzzle `2836-88180ad7` from #2836 has to be resolved: 

https://github.com/objectionary/eo/blob/7b604a832154a5ebd0e3f030bd9e6451a71afc53/eo-runtime/src/main/java/org/eolang/PhTracedEnclosure.java#L36-L38

The puzzle was created by Yegor Bugayenko on 22-Feb-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@volodya-lombrozo why don't you like `ConcurrentHashMap` here?
I think `ThreadLocal` could not help in scenario, something like that: Dataizing of `cage`'s enclosure means firstly creating new thread, closing thread, and dataizing next in the new thread. So every next entry to cage would mean you should trace again.

**Comment by volodya-lombrozo** [comment]
@levBagryansky I was afraid of the following case: 
```java
    @Test
    void dataizesManyCagesInParallel() {
        MatcherAssert.assertThat(
            "We have to be able to dataize many cages in parallel",
            Stream.generate(() -> (Supplier<Long>) this::dataizeOneMoreCage)
                .limit(1000)
                .parallel()
                .map(Supplier::get)
                .mapToLong(Long::longValue)
                .sum(),
            Matchers.equalTo(11000L)
        );
    }

    private long dataizeOneMoreCage() {
        final Phi cage = new EOcage(Phi.Φ);
        // Enable the "hack" method to break the test
        // this.hack();
        EOcageTest.writeTo(cage, new Data.ToPhi(11L));
        return new Dataized(cage).take(Long.class);
    }

    /**
     * How to break the test.
     * Here, I just reset the counter of vertices to 0.
     * The test above works only because {@link org.eolang.Vertices} is thread save and
     * smart enough. Each time when you create a new cage, it gets a new unique vertex. 
     * Exactly this behavior saves the test from failing.
     * But if somebody changes this logic, the test will fail. For example, if each dataization
     * process starts with zero vertex, the test will fail.
     * So even if you use {@link java.util.concurrent.ConcurrentHashMap}, it won't save you
     * in this scenario.
     */
    private void hack() {
        try {
            final Field vtxfield = PhDefault.class.getDeclaredField("VTX");
            vtxfield.setAccessible(true);
            final Object vtx = vtxfield.get(null);
            final Field count = vtx.getClass().getDeclaredField("count");
            count.setAccessible(true);
            final AtomicInteger atomic = (AtomicInteger) count.get(vtx);
            atomic.set(0);
        } catch (final NoSuchFieldException | IllegalAccessException exception) {
            throw new IllegalStateException(exception);
        }
    }
```
But it seems, `Vertices` saves us from it. The test above shows that using `ConcurrentHashMap` doesn't help in this particular scenario.

**Comment by levBagryansky** [comment]
@volodya-lombrozo I see. `ConcurrentHashMap` requires different `hashcode`s for any different objects independently of thread. As for me this is a fundamental feature of eo hashcode. `eo-threds` requires this feature too.

**Comment by 0pdd** [comment]
The puzzle `2836-88180ad7` has disappeared from the source code, that's why I closed this issue.
