### ISSUE TITLE
VerifyMojoTest.java:53-57: Fix this {@link...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2896]
The puzzle `2890-c492b9ca` from #2890 has to be resolved: 

https://github.com/objectionary/eo/blob/8090e4b101f534bbe15c5685ad5d0cb6b4ce351c/eo-maven-plugin/src/test/java/org/eolang/maven/VerifyMojoTest.java#L53-L57

The puzzle was created by Yegor Bugayenko on 27-Feb-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#3181](https://github.com/objectionary/eo/issues/3181) is solved here.
