### ISSUE TITLE
Add flag to `UnphiMojo` that adds `+tests` meta to XMIR

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2909]
[Here](https://github.com/objectionary/eo/issues/2873#issuecomment-1972619137) we get the situation where `+tests` meta is not transfered to XMIR while `unphi` stage.
The solution is to add flag to `UnphiMojo` that adds such meta.
Then we also need to add such flag to `eoc`

**Comment by yegor256** [comment]
@maxonfjvipon maybe we can make it possible to add different metas (like `+package`, etc):

```
mvn eo:unphi "-Deo.unphiMeta=+tests" "-Deo.unphiMeta=+package"
```

**Comment by maxonfjvipon** [comment]
@yegor256 `+package` is converted as an object with lambda in phi

**Comment by yegor256** [comment]
@maxonfjvipon let's prohibit the usage of `+package`, but others may be necessary to use in the future. It would be great to make it possible now.

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.35.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.6`

**Comment by maxonfjvipon** [comment]
@yegor256 did it get to maven central?
