### ISSUE TITLE
Check if there's `+rt` meta in object without atoms

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2921]
The `+rt` meta is needed only in objects which are atoms or contain atoms inside. In all other cases `+rt` should be prohibited. Let's add checker for it (xsl transformation)

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2948](https://github.com/objectionary/eo/issues/2948) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2948](https://github.com/objectionary/eo/issues/2948) is solved here.
