### ISSUE TITLE
Can delta binding map to "nothing"?

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2924]
In the Phi calculus paper, the syntax allows delta-bindings to map to the empty object: 
![telegram-cloud-photo-size-4-5999275637371686314-y](https://github.com/objectionary/eo/assets/37025995/48afce7b-0324-4301-b5f0-bba27aa73db0)
But in our Phi.g4 grammar delta can only map to bytes.
<img width="372" alt="image" src="https://github.com/objectionary/eo/assets/37025995/7b5d5015-5dcc-42ce-ba5d-87d7116068f4">

@yegor256 How should we resolve that?

**Comment by yegor256** [comment]
@maxonfjvipon it should be possible to bind `\varnothing` to `\Delta`, for example:

```
int -> [ \Delta -> ? ]
five -> int( \Delta -> 5 )
```

**Comment by maxonfjvipon** [comment]
@yegor256 how should `\Delta -> \varempty` be converted to EO?

**Comment by yegor256** [comment]
@maxonfjvipon it's impossible to represent this in EO. If we see this in calculus, we should fail the unphi process with an error.
