### ISSUE TITLE
Explain what is `Package`

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#2940]
@yegor256, @maxonfjvipon 

I do `eoc phi` on [unit-tests.eo](https://github.com/objectionary/eo/blob/f1f3960d728a6fc7c8c61ff87aa78decbfc5f97a/eo-runtime/src/test/eo/org/eolang/unit-tests.eo) and get the following `.phi` program that contains `λ ⤍ Package` mappings.

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        x ↦ ⟦
          φ ↦ Φ.org.eolang.bool(
            α0 ↦ Φ.org.eolang.bytes(
              Δ ⤍ 01-
            )
          )
        ⟧,
        z ↦ ⟦
          y ↦ ⟦
            x ↦ ∅,
            φ ↦ ξ.x
          ⟧,
          φ ↦ Φ.org.eolang.bool(
            α0 ↦ Φ.org.eolang.bytes(
              Δ ⤍ 01-
            )
          )
        ⟧,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

What is a `Package`?

How to dataize it?

**Comment by fizruk** [comment]
@maxonfjvipon Thank you for the explanation! The question is rather how to properly handle this atom in the normalizer. When you say 

> Here you need to dataize org.eolang.x or org.eolang.z object.

It is unclear instruction for the normalizer. I assume that we want to dataize **both**, but preserving their context (enclosing objects). So in @deemp's example, we would expect the result to be

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        x ↦ ⟦ Δ ⤍ 01- ⟧,
        z ↦ ⟦ Δ ⤍ 01- ⟧,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

Is my understanding correct?

**Comment by maxonfjvipon** [comment]
@fizruk here `x` and `z` are two independent and equal rights objects. And there's only one entry point for dataization process. It can either `org.eolang.x` or `org.eolang.y`. You can't dataize them both during one dataization process. If you want it - introduce one more object which would use `x` and `z`.
```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        x ↦ ⟦ Δ ⤍ 01- ⟧,
        z ↦ ⟦ Δ ⤍ 01- ⟧,
        a ↦ ⟦ φ ↦ ξ.x.plus(α0 ↦ ξ.z) ⟧,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```
Here you can dataize `org.eolang.a` and it dataizes `x` and `z`. @yegor256 correct me, if I'm wrong

**Comment by yegor256** [comment]
@deemp to answer the original question: "how to dataize `λ ⤍ Package`?" --- if case of phi-calculus expression, you can simply assume that the `Package` atom always returns an error. If this is my expression:

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        x ↦ ...,
        λ ⤍ Package
      ⟧
    ⟧
  ⟧
}
```

And I dataize `Q.org.eolang.x` -- I get something, if I dataize `Q.org.eolang.y` -- I get an error.

**Comment by maxonfjvipon** [comment]
@yegor256 yes, this lambda is used while unphi process

**Comment by maxonfjvipon** [comment]
@deemp are there any more questions?

**Comment by deemp** [comment]
@maxonfjvipon, I don't have any.

**Comment by maxonfjvipon** [comment]
@deemp then I'm closing it
