### ISSUE TITLE
Printed EO after `unphi` is not supported

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2943]
Such code (reversed method -> formation -> object) is legal in EO:
```
while.
  []
    TRUE > @
  nop
```
But if we convert it to phi, convert given phi back to XMIR, and convert this XMIR to EO we get:
```
[]
  TRUE > @
.while
  nop
```
Current EO grammar does not support vertical method after formation. Let's implement it

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.35.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.10`

**Comment by yegor256** [comment]
@maxonfjvipon done

**Comment by maxonfjvipon** [comment]
@deemp In EO 0.35.10 I tried to fix the bug you reported. Please use `--parser=0.35.10`

**Comment by deemp** [comment]
Okay, it worked https://github.com/deemp/eo/actions/runs/8294508536
