### ISSUE TITLE
Error: the name ... was already used

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#2952]
@maxonfjvipon, I enabled [compiles-correctly-with-long-duplicate-names](https://github.com/objectionary/eo/blob/9ecb995a5fd89dda83cbf4eb490ed05cf88c6ad4/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo#L218-L230) and got an error during a test after `phi -> unphi`:

```
 /home/runner/work/eo/eo/pipeline/.data/eo-not-normalized/runtime-tests.eo, 1047: The name "long-object-name" was already used on the same line;
```

https://github.com/deemp/eo/actions/runs/8294521206/job/22699697131#step:6:286

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.35.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.11`

**Comment by maxonfjvipon** [comment]
@deemp please try to use version `0.35.11`

**Comment by maxonfjvipon** [comment]
@deemp brilliant. I'm closing this one
