### ISSUE TITLE
AtConst.java:35-37: Class does not work properly. Also...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2966]
The puzzle `2931-d3bfc986` from #2931 has to be resolved: 

https://github.com/objectionary/eo/blob/2ee92f60d2a3c1faa3e58ebd8e44176bc49ad4a2/eo-runtime/src/main/java/org/eolang/AtConst.java#L35-L37

The puzzle was created by rultor on 18-Mar-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@maxonfjvipon we cache only the output, not the method of its calculation. Thus, `x` caches only the `delta` before its return. How it was calculated - doesn't matter. So, answers to your questions:

1. no
2. no
3. no
