### ISSUE TITLE
rust-tests.eo:29-31: Enable rust tests. They were fully...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2973]
The puzzle `2931-ad3f15a5` from #2931 has to be resolved: 

https://github.com/objectionary/eo/blob/446d62f268ac3224a2927fccfba20a7f444576ce/eo-runtime/src/test/eo/org/eolang/rust-tests.eo#L29-L31

The puzzle was created by rultor on 18-Mar-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me
