### ISSUE TITLE
DataizedTest.java:43-44: Enable the disabled tests. The...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2978]
The puzzle `2931-0831d4d9` from #2931 has to be resolved: 

https://github.com/objectionary/eo/blob/97054f31cc87f264dcc140718d5cd410835d4924/eo-runtime/src/test/java/org/eolang/DataizedTest.java#L43-L44

The puzzle was created by rultor on 18-Mar-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
After we changed a bit some logic in `Dataized` and `PhDefault` we started to get a different logs. So some tests in `DataizedTest` were disabled. 
No we need to check what logs we get and refactor tests so they confirm the logs are correct.
