### ISSUE TITLE
Let's add trufflehog-oss GHA to the organization

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3038]
This one: https://github.com/marketplace/actions/trufflehog-oss

Just to be safe.

**Comment by slry** [comment]
@yegor256 I would like to start working on this issue, but I do not really understand what do you mean by "adding gha to organization".
I can definitely add this gha to this repository, but I am not sure about whole organization.

**Comment by yegor256** [comment]
@slry let's add to the repo
