### ISSUE TITLE
Performance issue with `seq` due to unnecessary 'Dataize' calls in 'for' loop

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3048]
If you take a look at the current implementation of `seq`:
```java
@Override
public Phi lambda() {
    final Phi steps = this.take("steps");
    final Long length = new Dataized(
        steps.take("length")
    ).take(Long.class);
    for (long idx = 0; idx < length - 1; ++idx) {
        new Dataized(
            new PhWith(
                steps.take("at").copy(),
                0, new Data.ToPhi(idx)
            )
        ).take();
    }
    final Phi ret;
    if (length > 0) {
        final Phi last = steps.take("at").copy();
        last.put(0, new Data.ToPhi(length - 1));
        ret = last;
    } else {
        ret = new Data.ToPhi(false);
    }
    return ret;
}
```
you may see that in `for` loop we dataize `length - 1` times `steps.at index` . `tuple.at` is a quite convenient interface to obtain objects by their index, but it's heavy.
Instead in `tuple` we already have `head` and `tail` where `head` is inner `tuple` and `tail` is a value.

So instead of:
```
Dataize(steps.at 0)
Dataize(steps.at 1)
Dataize(steps.at 2)
....
```

We can do just:
```
Dataize(steps.head.head.head.tail)
Dataize(steps.head.head.tail)
Dataize(steps.head.tail)
```

which is quite faster. 

Moreover, we can save every `head` when we take them for the first time so we won't retrieve them on the next steps.

**Comment by levBagryansky** [comment]
@maxonfjvipon pls assign me, I have already implemented it here 2 months ago: https://github.com/levBagryansky/eo/commit/6bb47baf9288be4907766a68cb2c36381d0a5749
