### ISSUE TITLE
All objects in `EOorg` package must be package private

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3059]
For some reason all atoms and generated from EO java object has `public` in front of class and constructor.
There's no need for that. All of them should be package private

**Comment by levBagryansky** [comment]
@maxonfjvipon I can do it

**Comment by maxonfjvipon** [comment]
@levBagryansky I think there should be a way to get access to package private constructor via reflection

**Comment by levBagryansky** [comment]
@maxonfjvipon It's not clean to use reflection to circumvent our own rules. I try to solve it in java semantic

**Comment by maxonfjvipon** [comment]
@yegor256 it seems to resolve it we should do something like:
```
Constructor<Phi> constructor = constructor = Class.forName(target).getConstructor(Phi.class)
constructor.setAccessible(true);
Phi phi = constructor.newInstance(Phi.Ф);
```
WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon @levBagryansky I suggest we close this issue. Reflection is not a good idea in this case.

**Comment by levBagryansky** [comment]
@yegor256 @maxonfjvipon Now `PhPackage` depends on `EOorg/` classes. I think we can create a public class
 in `EOorg/` and interface for it in `org/eolang` package in order to reverse this dependency.

**Comment by maxonfjvipon** [comment]
@levBagryansky let's try. If there's no luck, then we should just make sure all classes in `EOorg/` package has the same access level.

**Comment by maxonfjvipon** [comment]
@levBagryansky looks like some kind of portal from `org.eolang` to `EOorg.EOeolang` package. I don't think it's a good idea. 
@yegor256 we already use reflection [here](https://github.com/objectionary/eo/blob/1394961b40390ae745a3afc84c1cf55ada343374/eo-runtime/src/main/java/org/eolang/PhPackage.java#L158) because there's no other way to get object by name.
So there are two options:
1. We extend this reflection with `constructor.setAccessible(true);`. It allows us to make all classes in `EOorg/` package private
2. We don't touch the code. Then I think we should make all classes in `EOorg/` public just for consistency.

What's your desicion?

**Comment by levBagryansky** [comment]
@maxonfjvipon wait for my pr

**Comment by yegor256** [comment]
@maxonfjvipon @levBagryansky `setAccessible(true)` is pure evil. I vote for the second option.

**Comment by levBagryansky** [comment]
@yegor256 @maxonfjvipon I faced the problem that inner packages like `EOio` will not be accessible for my `EOorg.EOeolang.PhiFactory` so I just will do them all `public`

**Comment by maxonfjvipon** [comment]
Done in #3103
