### ISSUE TITLE
Let's get rid of the `nop` object

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3069]
We don't have varargs anymore. That's why, the `nop` object doesn't make much sense. Moreover, we don't use it anywhere.

**Comment by yegor256** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 it's used in `try` as `finally` object, but we can use just `TRUE` instead

**Comment by maxonfjvipon** [comment]
@levBagryansky @c71n93 can any of you take care of this?

**Comment by levBagryansky** [comment]
@maxonfjvipon I can do it
