### ISSUE TITLE
`malloc.read` needs offset and size

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3071]
Currently, `malloc.read` reads the entire memory block, which is not effective. Let's make it read from `offset` provided and only the `size` of bytes.

```
(malloc 1024).pointer > p
p.write 100 "Hello!"
QQ.io.stdout
  (p.read 100 6).as-string
```

**Comment by yegor256** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 sounds reasonable, let's do it
