### ISSUE TITLE
We can get rid of explicit object copying using `'`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3073]
Since we got rid of [vertex](https://github.com/objectionary/eo/issues/3037) in EO it seems we don't need the explicit copying functionality

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.36.0`

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag 0.36.0

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.0`
