### ISSUE TITLE
`eo:phi` doesn't generate an empty \Delta binding for `int`, `bool`, etc.

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3082]
It seems, that it should be generated

**Comment by yegor256** [comment]
@maxonfjvipon please, check

**Comment by maxonfjvipon** [comment]
We have an empty `\delta` binding only in `bytes`. I'll add it

**Comment by maxonfjvipon** [comment]
@yegor256 after we add empty delta binding to `bytes` objects we can't `unphi` it because of [this](https://github.com/objectionary/eo/issues/2924#issuecomment-1980790007). Ideas?

**Comment by yegor256** [comment]
@maxonfjvipon I believe, we should allow `\Delta` only in `bytes`. In all other cases, we throw an error.
