### ISSUE TITLE
Limit `memory` usage scope

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3084]
Current implementation of `memory` object leads to potential memory leaks because we except end-user to `free` allocated memory block. Of course user may just forget to do it. It's called "Hello, C++".
We should limit the scope of `memory` usage and free allocated memory automatically when scope is ended.
We can do using abstract objects:
```
(memory 0).alloc > mem
  [m] # here m is memory itself
    seq > @
      *
        m.write 42
        m.write (m.plus 1)
        m.read 
```
When abstract object finishes its execution, memory is freed automatically

**Comment by maxonfjvipon** [comment]
@yegor256 check this out:
```
# Test.
[] > writes-into-memory
  memory > mem
    0
    [m]
      seq > @
        *
          m.write 10
          # do something else
  mem.eq 10 > @ # true
```
What do you think if this abstract object (I called it `scope`) would return last data written into `memory`? So
`memory` dataizes `scope`, reads last written data, frees memory and return the data.

**Comment by yegor256** [comment]
@maxonfjvipon sounds good

**Comment by yegor256** [comment]
@maxonfjvipon I believe, this change deserves a blog post

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.36.1`
