### ISSUE TITLE
Test that `phi` -> `unphi` does not break the EO tests

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3092]
We have two mojos:
[`PhiMojo`](https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/java/org/eolang/maven/PhiMojo.java) - converts XMIR to phi calculus expression
[`UnphiMojo`](https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/java/org/eolang/maven/UnphiMojo.java) - convert phi calculus expression to XMIR

We need to test that all our EO tests will pass if we:
1. parse them to XMIR
2. convert XMIRs to PHIs
3. revert back from PHIs to XMIRs
4. compile to java and run

The issue should be done in `eo-runtime` module. 
The issue may be done with help of [farea](https://github.com/yegor256/farea). See [SnippetTestCase](https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/java/org/eolang/SnippetTestCase.java) for example. 

The test that do all necessary steps + no broken tests = resolved issue

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#3162](https://github.com/objectionary/eo/issues/3162) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#3162](https://github.com/objectionary/eo/issues/3162) is solved here.
