### ISSUE TITLE
Run qulice as early as possible

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo#3094]
When I use `-Pqulice` my changes almost ready to push, I just want to check if my code style is Ok. At this point, I'm sure that all tests are passed, so I should write `mvn clean install -DskipTests -Pqulice` to skip them. But even in this case I should wait for other checks(groovy, license, jtcop), that was already passed when I used `mvn clean install` without `-Pqulice`.

Therefore, I think it would be better to make the qulice check a first priority, because when I use `-Pqulice`, I want to know the result of the style check as early as possible. Or maybe there is already a quick way to run the qulice without other checks?

@yegor256 WDYT?

**Comment by yegor256** [comment]
@c71n93 your concern is valid, but the solution should be different. All our other steps (license, groovy, jtcop) must listed to the presence of `-DskipTests` and not do anything in case it's present.
