### ISSUE TITLE
Add "good first issue" Label

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3099]
Some people ask me how to contribute to the project and what would be the best 'first issue' to start with. What do you think if we add this label to this project? Then we could mark some of the issues as a 'good first issue'.

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo I think it's a good idea

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you add it, please?

**Comment by yegor256** [comment]
@volodya-lombrozo done
