### ISSUE TITLE
We can get rid of `bool` object

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3115]
After introducing the objects `true` and `false' it seems that object `bool` is redundant now. It's used as kind of proxy between `true` and `bytes`. 
The benefits:
1. We will get the less amount of object in `eo-runtime`
2. There will be no chance for end-user to create a `bool` with unexpected amount of bytes
3. There will be no chance for end-user to create an instance of `bool` and expect it has a `if` attribute

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#3120](https://github.com/objectionary/eo/issues/3120) is solved here.
