### ISSUE TITLE
DcsWithRuntime is thread-unsafe

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#3122]
DcsWithRuntime is thread-unsafe since it has `private static final Unchecked<Dependency> MAVEN_DEPENDENCY = DcsWithRuntime.mavenDependency()` which is `Sticky` (thread-unsafe) inside.

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#3158](https://github.com/objectionary/eo/issues/3158) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the only puzzle [#3158](https://github.com/objectionary/eo/issues/3158) is solved here.
