### ISSUE TITLE
`malloc.pointer` needs `realloc` object

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3125]
I think it'll be useful to be able to reset and change size of allocated block in memory via `realloc` (the similar way it's implemented in C):
```
(malloc 8).pointer > p
seq
  *
    p.write 0 42
    p.realloc 1 # remove current data (all bytes to 0) and change size of block to 1 with the same identifier
    p.write true
    p.free
    p.realloc 8 # make the block in memory available for writing and reading after clearing it
    p.write 0 42
    p.read 0 8 # => 42
```

It would be also convenient for #3084 because we may use scoped `memory` many times which should lead to new allocation and clearing the memory. It would be better one instance of `memory` object uses one block in memory and does not create new one on every dataization.
@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon I suggest joining `memory` and `malloc` into one object `malloc`

**Comment by yegor256** [comment]
@rultor release, tag is `0.37.0`
