### ISSUE TITLE
Fix: no top-level lamdba package in generated PHI programs

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#3129]
## Problem

When a formation has a `λ ⤍ Package`, the `normalizer` dataizes formations in sibling bindings.
Otherwise, the `normalizer` doesn't dataize formations in sibling bindings.
However, there's no top-level `λ ⤍ Package` binding in generated PHI programs.

`pipeline/phi/as-phi-tests.phi` (see [this artefact](https://github.com/objectionary/normalizer/actions/runs/8741809193/artifacts/1426749476)):

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
         ...
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

## Suggestion

Make `eoc` optionally keep the information about tests.
That is, both `eoc phi` and `eoc unphi` should have a `--tests` flag.

For `eoc phi --tests`, write a `λ ⤍ Test` binding in the top-level formation.

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
         ...
      ⟧,
      λ ⤍ Package
    ⟧,
    λ ⤍ Test
  ⟧
}
```

For `eoc unphi --tests`, handle this binding too.

**Comment by maxonfjvipon** [comment]
@yegor256 @deemp why do we need this? Does not [this](https://github.com/objectionary/eo/issues/2909) help?

**Comment by deemp** [comment]
@maxonfjvipon, I updated the issue description

**Comment by yegor256** [comment]
@deemp in general, it's better to submit a new issue instead of editing description/title of existing one -- this will help us keep discussions more concise.

**Comment by deemp** [comment]
@yegor256, sure. However, there's no discussion in this issue apart from the current meta-discussion.

**Comment by yegor256** [comment]
@deemp I believe, we can close this ticket. If you have similar problems, please submit a new one.
