### ISSUE TITLE
@Reload(MyClass.class) annotation

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#3141]
In order to initialize static fields of class for test we can implement such annotation. I should reinitialize static fields of class before test starting. The problem is which value to init them.

**Comment by levBagryansky** [comment]
@volodya-lombrozo WDYT

**Comment by volodya-lombrozo** [comment]
@levBagryansky I don't think we need it. Explained it [here](https://github.com/objectionary/eo/pull/3114#pullrequestreview-2022654753)
