### ISSUE TITLE
let's get rid of `\sigma`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3147]
Let's remove `\sigma` from the syntax entirely

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#3176](https://github.com/objectionary/eo/issues/3176) is still not solved.

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.38.0`

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.38.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.0`

**Comment by maxonfjvipon** [comment]
@yegor256 something's wrong with Rultor

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.0`

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#3176](https://github.com/objectionary/eo/issues/3176) is solved here.
