### ISSUE TITLE
PMD check disabled for entire `eo-runtime`

### ISSUE THREAD

**Issue by c71n93** [objectionary/eo#3160]
Check out this line:
https://github.com/objectionary/eo/blob/f184d9a4197ad8e972ee1ae7970ccf3cb334e60e/eo-runtime/pom.xml#L327

Do we really need to disable PMD check for the whole `eo-runtime`? We should ignore [eo-runtime/src/main/java/EOorg](https://github.com/objectionary/eo/tree/f184d9a4197ad8e972ee1ae7970ccf3cb334e60e/eo-runtime/src/main/java/EOorg) because of upper case in package name and `$` in class names, but should we ignore the rest of `eo-runtime`?

There would be a lot of PMD violations for classes from [eo-runtime/src/main/java/org/eolang](https://github.com/objectionary/eo/tree/f184d9a4197ad8e972ee1ae7970ccf3cb334e60e/eo-runtime/src/main/java/org/eolang) if we turned PMD on.

@yegor256 WDYT?

**Comment by yegor256** [comment]
@c71n93 we just don't know how to enable it. If you know, please try

**Comment by c71n93** [comment]
> @c71n93 we just don't know how to enable it. If you know, please try

@yegor256 Did you mean this (https://github.com/objectionary/eo/pull/3171#issuecomment-2096721543) problem in your comment?

**Comment by 0pdd** [comment]
@c71n93 3 puzzles [#3238](https://github.com/objectionary/eo/issues/3238), [#3239](https://github.com/objectionary/eo/issues/3239), [#3240](https://github.com/objectionary/eo/issues/3240) are still not solved.

**Comment by 0pdd** [comment]
@c71n93 3 puzzles [#3238](https://github.com/objectionary/eo/issues/3238), [#3240](https://github.com/objectionary/eo/issues/3240), [#3265](https://github.com/objectionary/eo/issues/3265) are still not solved; solved: [#3239](https://github.com/objectionary/eo/issues/3239).

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#3238](https://github.com/objectionary/eo/issues/3238), [#3265](https://github.com/objectionary/eo/issues/3265) are still not solved; solved: [#3239](https://github.com/objectionary/eo/issues/3239), [#3240](https://github.com/objectionary/eo/issues/3240).

**Comment by 0pdd** [comment]
@c71n93 the puzzle [#3265](https://github.com/objectionary/eo/issues/3265) is still not solved; solved: [#3238](https://github.com/objectionary/eo/issues/3238), [#3239](https://github.com/objectionary/eo/issues/3239), [#3240](https://github.com/objectionary/eo/issues/3240).

**Comment by 0pdd** [comment]
@c71n93 all 4 puzzles are solved here: [#3238](https://github.com/objectionary/eo/issues/3238), [#3239](https://github.com/objectionary/eo/issues/3239), [#3240](https://github.com/objectionary/eo/issues/3240), [#3265](https://github.com/objectionary/eo/issues/3265).
