### ISSUE TITLE
Extend grammar to mark objects to be named automatically

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3164]
It would be convenient to have a syntax construction in EO which would signal to compiler that object should be named automatically without explicit name from end-user.
For example:
```
[] > object
  x
    [] >>
      5.plus 5 > ten
```

Here `>>` signals that this abstract object should be uniquely named automatically by compiler.
Only abstract objects should be able to use such syntax

**Comment by yegor256** [comment]
@maxonfjvipon if this is only applicable for abstract objects, maybe we can use this syntax:

```
[] > object
  x
    []>
      5.plus 5 > ten
```
