### ISSUE TITLE
eo-runtime doesn't build when offline (no Internet connection)

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3182]
We have a configuration parameter `offline` of the `eo-maven-plguin`, which is set to `true` for `eo-runtime`. However, if you turn off the Internet connection and try to build the entire project -- it fails in the `eo-runtime` module. Let's find out what's the problem and fix.

**Comment by maxonfjvipon** [comment]
@yegor256 the command you run was `mvn clean install -DskiptTests`?

**Comment by yegor256** [comment]
@maxonfjvipon nope, just `mvn clean install`. It should pass when I have no Internet connection.

**Comment by yegor256** [comment]
waiting for #3559
