### ISSUE TITLE
Object Name Already In Use

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3195]
I'm still trying to print PHI expressions from Java bytecode. This time I faced with the problem which I don't know how to solve. In java bytecode we can have several methods with the same name (method overloading), but in eo, we can't. 

So I'm getting the following exception:
```
[ERROR] net.sf.saxon.style.XSLMessage@1e4b3054: Critical error identified:
  , : The name "j$annotateParameter" is already in use;
  , : The name "j$annotateParameter" is already in use;
  , : The name "j$annotateParameter" is already in use;
```
The same problem is happening with constructors.

Can I ignore this check somehow? Later we will be able to solve this problem appropriately. 

BTW, I used `<phiOptimize>false</phiOptimize>` option and it didn't help.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you help here, please?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo `PhiMojo` checks critical errors anyway because it should generate valid phi so it can be converted back to EO and compiled. I can add a flag that would disable this behaviour

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon I need to print at least some phi expressions. Since I have many files (some of them are valid), I can just skip those that inappropriately formatted. In other words, I need something like   `skipFailed`.

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.2`

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo 
1. use `phiFailOnError` = false if you don't want to check critical errors
2. use `phiSkipFailed` = true if you want to skip failed xmirs

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Thank you. This temporary solution works fine.
