### ISSUE TITLE
`eoc phi` translates `int.eo` in a wrong way

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#3201]
@maxonfjvipon, @yegor256

For `eoc 0.38.0`, the `neg` object is translated to PHI in a wrong way.

The `neg` object in EO:

https://github.com/objectionary/eo/blob/312daf1e0e7735bbcd3d52e7c2c14ca633883c77/eo-runtime/src/main/eo/org/eolang/int.eo#L62-L63

The `neg` object in PHI ([link](https://github.com/objectionary/normalizer/blob/42fa5463e9f0af9580de3ce001f33aa4491d5df9/eo-phi-normalizer/data/0.38.0/org/eolang/int.phi#L53-L61)).

Expected `neg` object in PHI:

```
neg ↦ ⟦
  φ ↦ ξ.ρ.times(
    α0 ↦ Φ.org.eolang.int(
      α0 ↦ Φ.org.eolang.bytes(
        Δ ⤍ FF-FF-FF-FF-FF-FF-FF-FF
      )
    )
  )
⟧,
```

**Comment by maxonfjvipon** [comment]
@deemp it's not wrong, it's just one more way to convert this particular object to PHI

**Comment by maxonfjvipon** [comment]
@deemp since we're inside `org.eolang.int.times` to get `org.eolang.int` we can do:
1. `Φ.org.eolang.int`
2. `ξ.ρ.ρ.int`: 
- `ξ` -> `org.eolang.int.times`
- `ξ.ρ` -> `org.eolang.int`
- `ξ.ρ.ρ` -> `org.eolang`
- `ξ.ρ.ρ.int` -> `org.eolang.int`

**Comment by deemp** [comment]
OK, thanks for clarifications.
