### ISSUE TITLE
"good-first-task" -> "good first issue"

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3211]
`good-first-task` is a good and well-understandable label for the appropriate type of issues. However, recent changes on GitHub allow the use of a special label, `good first issue`:

<img width="769" alt="Screenshot 2024-06-03 at 15 28 26" src="https://github.com/objectionary/eo/assets/51804353/754d2b60-3071-4d76-bbc7-a839fa93001b">

It seems, that this label will work better than `good-first-task`.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by yegor256** [comment]
@volodya-lombrozo renamed
