### ISSUE TITLE
How do you check that programs in the README work?

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#3224]
EO versions change, so demo programs in README may become invalid. How do you check that programs are always valid?

In particular, I'm interested in the multiplication table example.

https://github.com/objectionary/eo/blob/c5bbe0462581c86dbc2e523afa69066d958b1d71/README.md?plain=1#L150-L168

In the [normalizer](https://github.com/objectionary/normalizer) repo, I use [mdsh](https://github.com/zimbatm/mdsh) to check that commands indeed work and to update their input ([link](https://github.com/objectionary/normalizer/blob/8347f003d7269a3cbe6a05072082808206257ec2/scripts/update-markdown.sh)).

**Comment by yegor256** [comment]
@deemp it's a duplicate of #3134
