### ISSUE TITLE
Move `eo-sys` to `eo-runtime`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3236]
The library [`eo-sys`](https://github.com/objectionary/eo-sys) contains 3 objects which interact with operating system via system calls. They should be part of `eo-runtime` as well as `io` subpackage.

**Comment by maxonfjvipon** [comment]
The important thing here is that we should not introduce dependencies into `eo-runtime` meanwhile `eo-sys` depends on `com.sun.jna` for making system calls

**Comment by c71n93** [comment]
@maxonfjvipon assign me please

**Comment by yegor256** [comment]
@maxonfjvipon I believe, it's fixed
