### ISSUE TITLE
BytesOf.java:34-38: This class requires refactoring. As a...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#3239]
The puzzle `3160-01d3ed77` from #3160 has to be resolved: 

https://github.com/objectionary/eo/blob/ba2a9e3861918f0173da5b3609cefb1a52d7e002/eo-runtime/src/main/java/org/eolang/BytesOf.java#L34-L38

The puzzle was created by Roman Korostinskiy on 24-Jun-24. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
> @0pdd thanks for the report, here is a feedback: * The todo message does not specify what aspects of...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign

**Comment by 0pdd** [comment]
@0pdd the puzzle [#3265](https://github.com/objectionary/eo/issues/3265) is still not solved.
