### ISSUE TITLE
merge smaller libs into this repo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3251]
Let's move these repositories to this repo:

  * eo-strings
  * eo-math
  * eo-files
  * eo-collections (rename to eo-structs)
  * eo-sys
  * eo-hamcrest

Those repos let's just remove.

**Comment by levBagryansky** [comment]
@maxonfjvipon I'd like to transfer some of them

**Comment by maxonfjvipon** [comment]
@levBagryansky let me start with `hamcrest` and `collections` because they require some important refactoring. Then you can continue

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#3262](https://github.com/objectionary/eo/issues/3262) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#3262](https://github.com/objectionary/eo/issues/3262), [#3269](https://github.com/objectionary/eo/issues/3269) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#3262](https://github.com/objectionary/eo/issues/3262), [#3269](https://github.com/objectionary/eo/issues/3269), [#3277](https://github.com/objectionary/eo/issues/3277) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#3262](https://github.com/objectionary/eo/issues/3262), [#3269](https://github.com/objectionary/eo/issues/3269) are still not solved; solved: [#3277](https://github.com/objectionary/eo/issues/3277).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#3262](https://github.com/objectionary/eo/issues/3262), [#3269](https://github.com/objectionary/eo/issues/3269), [#3405](https://github.com/objectionary/eo/issues/3405) are still not solved; solved: [#3277](https://github.com/objectionary/eo/issues/3277).

**Comment by yegor256** [comment]
@maxonfjvipon I believe, we are done with this one. Thanks to you!

**Comment by 0pdd** [comment]
@yegor256 all 4 puzzles are solved here: [#3262](https://github.com/objectionary/eo/issues/3262), [#3269](https://github.com/objectionary/eo/issues/3269), [#3277](https://github.com/objectionary/eo/issues/3277), [#3405](https://github.com/objectionary/eo/issues/3405).
