### ISSUE TITLE
PhPackage need update

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#3263]
We need update it in several places:
1) https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/java/org/eolang/PhPackageTest.java#L171
`goto` does not exist now, we have `go`. Currently it returns new `PhPackage` according to https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/org/eolang/PhPackage.java#L96
2) https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/org/eolang/PhPackage.java#L57
We can get rid of `ConcurrentHashMap`  or `ThreadLock` here.
3) Now if `PhPackage` does not have attribute to be found, it returns `new PhPackage(this.eoPackage(name))` (in https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/org/eolang/PhPackage.java#L96) .  So it does not even check if the package exists. May be it would be better to throw exception if there is not such package? @yegor256 WDYT?

Also there is `deadlock` somewhere according to #3245 but I cannot repeat error.

**Comment by levBagryansky** [comment]
@volodya-lombrozo WDYT

**Comment by yegor256** [comment]
@levBagryansky I suggest we split this ticket into at least three. Now, a few unrelated issues are grouped together for no obvious reason.
