### ISSUE TITLE
`eo-maven-plugin` allows attributes without names in an abstract object

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3294]
The current version of `eo-maven-plugin` allows to declare attributes without names in abstract objects.

```
new-KClW ↦ ⟦
  Φ.org.eolang.int(
    α0 ↦ Φ.org.eolang.bytes(
      Δ ⤍ 00-00-00-00-00-00-00-00
    )
  )
⟧
```

`new-KClW` is an abstract object (as far as I know,) and the `Φ.org.eolang.int` is its attribute without a name. When I run `xmir` -> `phi` transformation, I don't see any errors, but I should. Attributes in abstract objects must have names.

If we ignore this issue, we will face with [such errors](https://github.com/objectionary/normalizer/issues/379#issuecomment-2245619152).

I use the fooling plugin configuration in the project:

```xml
<plugin>
  <groupId>org.eolang</groupId>
  <artifactId>eo-maven-plugin</artifactId>
  <version>0.38.4</version>
  <executions>
    <execution>
      <id>convert-xmir-to-phi</id>
      <phase>process-classes</phase>
      <goals>
        <goal>xmir-to-phi</goal>
      </goals>
      <configuration>
        <phiInputDir>${project.build.directory}/generated-sources/opeo-decompile-modified-xmir</phiInputDir>
        <phiOutputDir>${project.build.directory}/generated-sources/phi-expressions</phiOutputDir>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you take a look please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you release a new version, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.0`

**Comment by yegor256** [comment]
@maxonfjvipon the problem in rultor was, as expected, in the size of the machine. Now, we are using AWS t2.xlarge and it all works.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon How can I use the new version?

**Comment by yegor256** [comment]
@volodya-lombrozo just change the version in the `pom.xml`. It doesn't work? Maybe it's better to report a new ticket, if it doesn't.

**Comment by volodya-lombrozo** [comment]
@yegor256 Yes, changing version helps. Thank you.
