### ISSUE TITLE
XMIR representation of an alias?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3333]
Since I [can't](https://github.com/objectionary/eo/issues/3332) compile any EO program I'm stacked with the following problem. Let's imagine we have the following EO program:

```eo
# Comment here.
[args] > app
  seq > @
    "a" > a
    QQ.io.stdout
      a
```

As you can see, I declare the `a` variable. Most probably, it will be presented in `xmir` as the following definition:

```xml
 <o base="string" line="4" name="a">... hex...</o>
```

But how will it be represented as an argument of `QQ.io.stdout`?

Should it be:
```xml
 <o name="a"/>
```

or 

```xml
 <o base="string" name="a"/>
```

or 

```xml
 <o base="string" line="4" name="a"/>
```
or 

```xml
 <o line="4" name="a"/>
```
?

Of course, it would be much (!) faster if I were able to check these transformations on my own by using the compiler.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please? It's kind of blocking issue.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo it'll be present as 
```xml
<o base="a" line="6"/>
```

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Thank you. Will implement it as you suggested.
