### ISSUE TITLE
PhiMojo doesn't fail on invalid identifiers

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3346]
See https://github.com/objectionary/opeo-maven-plugin/issues/411

If I pass this XMIR to `PhiMojo`, it generates `.phi` file:

```
         DRETURN-1 ↦ Φ.org.eolang.jeo.opcode(
            α0 ↦ Φ.org.eolang.int(
              α0 ↦ Φ.org.eolang.bytes(
                Δ ⤍ 00-00-00-00-00-00-00-AF
              )
            )
          )
 
```

This is an obvious syntax error in phi (the identifier name `DRETURN-1` is not valid, it must start with a small English letter). `PhiMojo` should not generate such files, but fail with an error.

**Comment by volodya-lombrozo** [comment]
@yegor256 I is a duplicate of https://github.com/objectionary/eo/issues/3322
