### ISSUE TITLE
`UnphiMojo` can't parse `ξ()`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3347]
`UnphiMojo` can't parse this:

```
  {
    ⟦
      α1 ↦ ξ()
    ⟧
  }
```

I believe, it's a bug, since the expression is legal.

**Comment by yegor256** [comment]
@maxonfjvipon can you please help?

**Comment by maxonfjvipon** [comment]
@yegor256 are you sure it's legal to do Xi application? It seems meanless

**Comment by yegor256** [comment]
@maxonfjvipon it's perfectly legal in phi-calculus. You take yourself and make a copy of it, recursively.

**Comment by maxonfjvipon** [comment]
@yegor256 do we allow such behavior in EO?
```
[x] > y
  $ 5 > a
```

**Comment by yegor256** [comment]
@maxonfjvipon of course we do (well, we must)

**Comment by maxonfjvipon** [comment]
@yegor256 what's up with this one? Is `ξ()` still legal?

**Comment by yegor256** [comment]
@maxonfjvipon I believe, it should be legal

**Comment by maxonfjvipon** [comment]
@yegor256 what about `Ф()` then?

**Comment by yegor256** [comment]
@maxonfjvipon OK, let's forbid them both

**Comment by maxonfjvipon** [comment]
@yegor256 ok, so the issue can be closed?

**Comment by yegor256** [comment]
@maxonfjvipon this way:

<img width="702" alt="Screenshot 2024-11-02 at 14 28 26" src="https://github.com/user-attachments/assets/95e89358-3e51-4701-87f2-e83bd7d28d90">
