### ISSUE TITLE
Is there a way to disable `xmir-to-phi` and `phi-to-xmir` goals?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3371]
I have the following `eo-maven-plugin` configuration:

```xml
<plugin>
  <groupId>org.eolang</groupId>
  <artifactId>eo-maven-plugin</artifactId>
  <version>0.39.0</version>
  <executions>
    <execution>
      <id>xmir-to-phi</id>
      <phase>process-classes</phase>
      <goals>
        <goal>xmir-to-phi</goal>
      </goals>
      <configuration>
        <phiInputDir>${jeo.disassemble}</phiInputDir>
        <phiOutputDir>${eo.phi}</phiOutputDir>
      </configuration>
    </execution>
    <execution>
      <id>phi-to-xmir</id>
      <phase>process-classes</phase>
      <goals>
        <goal>phi-to-xmir</goal>
      </goals>
      <configuration>
        <unphiInputDir>${eo.phi}</unphiInputDir>
        <unphiOutputDir>${eo.unphi}</unphiOutputDir>
      </configuration>
    </execution>
  </executions>
</plugin>
```

Since these goals have bugs, I can't use them for now. But I don't want to remove the entire configuration from my integration test. Is there a way to "skip" this goals?

Maybe some `disable` or `skip` configuration?

```xml
<disabled>true</disabled>
```

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon could you help with this please? This issue blocks https://github.com/objectionary/jeo-maven-plugin/pull/704

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo there are no such options for now, but I can add them

**Comment by yegor256** [comment]
@maxonfjvipon we [already have](https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/java/org/eolang/maven/SafeMojo.java#L277-L282) this feature implemented. Just use `skip` option, setting it to true.
