### ISSUE TITLE
formal XMIR specification must be generated from the XSD

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3375]
I usually work closely with `xmir` files. So, I need to understand this format to be able to work with it. However, I failed to find any developer specification on this format. It is extremely important to have this specification, otherwise any work with `xmir` becomes fortune telling on coffee grounds.

As far as I know we have some separate knowledge isles like [comments](https://github.com/objectionary/eo/issues/3373#issuecomment-2355161204) or [blog posts](https://news.eolang.org/2022-11-25-xmir-guide.html) (it's written in 2022 btw). 

But it's extremely hard to find them. Actually you need to know where to find them. And it is the only chance. 
I suggest to create a centralised documentation for `xmir` format.

**Comment by yegor256** [comment]
@volodya-lombrozo we intentionally did it like this (with a blog post) because the format is still rather volatile: we change it once in a while. I suggest we keep it like this, only updating the blog post when something is missing or changing. If you have questions to any parts of the XMIR format, ask them, I will update the blog post.

**Comment by yegor256** [comment]
@maxonfjvipon in the mean time, can we add a text to _all_ error messages that are related to XMIR:

```
More detailed information about XMIR format you can find here: https://news.eolang.org/2022-11-25-xmir-guide.html
```

This will help everybody.

**Comment by volodya-lombrozo** [comment]
@yegor256 There are some problems with the blog post:

- It lies separately from the repository. Where can I find a link to it?
- It is attached to a particular date `25 Nov 2022`. So when I see it, I assume that it is outdated already. And it is outdated indeed.
- You can't create several separate documents and link them - you need to keep everything at one place. "God Documentation File" :)   
- nit: The format is a bit different, it is not what you expect from the technical documentation.

**Comment by yegor256** [comment]
@volodya-lombrozo maybe we can generate documentation right from our XSD: https://stackoverflow.com/questions/237938/how-to-convert-xsd-to-human-readable-documentation

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo maybe we can generate documentation right from our XSD: https://stackoverflow.com/questions/237938/how-to-convert-xsd-to-human-readable-documentation

Sounds cool

**Comment by yegor256** [comment]
@volodya-lombrozo this is what we have out of the box: https://www.eolang.org/XMIR.html I will try to make it more readable

**Comment by yegor256** [comment]
@volodya-lombrozo this is the best we can do: https://www.eolang.org/XMIR.html

**Comment by volodya-lombrozo** [comment]
@yegor256 What do you think about mentioning it int the `README`? Otherwise this link will be lost as soon as we close this ticket. Currently, the `README` links to the https://news.eolang.org/2022-11-25-xmir-guide.html (some outdated guide.)

**Comment by yegor256** [comment]
@volodya-lombrozo I added links: aa691eb6b

**Comment by volodya-lombrozo** [comment]
@yegor256 Awesome. Thank you.
