### ISSUE TITLE
How to use `EoSyntax` class?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3380]
I'm trying to parse EO file by using `EoSyntax` class:

```java
new EoSyntax("name?", new InputOf(this.toEo())).parsed()
```

The problem here is the first parameter `nme`. I just don't know what it is and what I should pass. I guess, it's some name. 
Should `EoSyntax` know my name to parse EO files? 

```java
new EoSyntax("Volodya", new InputOf(this.toEo())).parsed()
```
Is it for blaming purposes? Well... I tried to open `EoSyntax` class to read the javadoc about this parameter:

```java
    /**
     * Ctor.
     *
     * @param nme The name of it
     * @param ipt Input text
     */
    public EoSyntax(final String nme, final Input ipt) {
        this.name = nme;
        this.input = ipt;
    }
```

"The name of it". [It](https://en.wikipedia.org/wiki/It_(2017_film))? What "it" should I pass?

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon Could you help here, please?

**Comment by yegor256** [comment]
@volodya-lombrozo see the changes in [a0f2e2b](https://github.com/objectionary/eo/commit/a0f2e2b4342cb0cfe87705692a46a2f81ff06a76)

**Comment by volodya-lombrozo** [comment]
@yegor256 If this parameter is needed only for "the sake of traceability", may be we can add one more constructor to `EoSyntax` that would pass a dummy name? Otherwise I don't know which value to set. Can I pass any random name? Actually, I don't have any `.eo` file in my case - I parse it directly from `XML` object.

**Comment by yegor256** [comment]
@volodya-lombrozo I agree, see [77c3fa9](https://github.com/objectionary/eo/commit/77c3fa9ccef1c498f185943a3a3c708b9d1e481e)

**Comment by volodya-lombrozo** [comment]
@yegor256 Looks good, thank you! Could you release these changes, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.1`

**Comment by yegor256** [comment]
@volodya-lombrozo we'll release soon: https://github.com/objectionary/eo/issues/3381

**Comment by volodya-lombrozo** [comment]
@yegor256 I guess, you were mistaken about the traceability: https://github.com/objectionary/eo/issues/3373#issuecomment-2370906281

**Comment by maxonfjvipon** [comment]
This "name" is used in the `name` attribute of `<program>` tag in XMIR, so we need to extend documentation for the field in `EoSyntax` class.

**Comment by yegor256** [comment]
@volodya-lombrozo the version 0.39.1 has been released, try it please

**Comment by volodya-lombrozo** [comment]
@yegor256 Now the documentation looks a bit better. Thank you
