### ISSUE TITLE
rultor release fails

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3381]
See https://github.com/objectionary/eo/issues/3380#issuecomment-2368043331

**Comment by yegor256** [comment]
@maxonfjvipon can you please help?

**Comment by maxonfjvipon** [comment]
@yegor256 Rultor failed with:
```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.7.0:jar (jcabi-javadoc) on project eo-runtime: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1
[ERROR] /home/r/repo/eo-runtime/src/main/java/EOorg/EOeolang/EOsys/Posix/CStdLib.java:30: error: package com.sun.jna does not exist
[ERROR] import com.sun.jna.Library;
```
Is it problem with `jcabi-javadoc` or it's just our `DepsMojo` which does not download `jna` dependencies

**Comment by yegor256** [comment]
@maxonfjvipon it's a problem with our configuration of maven-javadoc-plugin. It can't find `com.sun.jna.*` classes in classpath (I believe). Why this happens and how to fix I would ask ChatGPT :)

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.1`
