### ISSUE TITLE
The logging of errors in the `SnippetIT` test is poor

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3402]
See this CI failure report: https://github.com/objectionary/eo/actions/runs/11072598428/job/30767181819?pr=3397 (part of this [PR](https://github.com/objectionary/eo/pull/3397)).

It's impossible to understand why `SnippetIT` failed. Let's print its full error log in case of failure.

**Comment by yegor256** [comment]
@maxonfjvipon please, take a look

**Comment by maxonfjvipon** [comment]
@yegor256 actually it's printed [here](https://github.com/objectionary/eo/blob/bb7ac319f9512d1a8aa97ddfdccb7cdb543179a6/eo-runtime/src/test/java/org/eolang/SnippetIT.java#L319), but for some reason we don't see it in CI

**Comment by maxonfjvipon** [comment]
@yegor256 seems, you fixed it [here](https://github.com/objectionary/eo/commit/51cae990f59a76951cc422ae4e5d3cac6d1c6e2c)
