### ISSUE TITLE
`PhiUnphiIT` test is broken in CI

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3410]
Take a look: https://github.com/objectionary/eo/actions/runs/11161986556/job/31025666946

It's a stable problem, it happens in every CI build. However, locally, this test works just fine.

**Comment by yegor256** [comment]
@maxonfjvipon please, take a look

**Comment by maxonfjvipon** [comment]
@yegor256 can the problem be related to https://github.com/objectionary/eo/commit/de01d1ef301f2d82221ef8a6a6fe3130f868a211?
Because it works fine right before this update, for example [here](https://github.com/objectionary/eo/pull/3407)

**Comment by yegor256** [comment]
@maxonfjvipon yes, good guess. Let me take a look.
