### ISSUE TITLE
Getstr object would be helpful

### ISSUE THREAD

**Issue by kreofil** [objectionary/eo#343]
Насколько я понимаю, сейчас весь ввод данных осуществляется только через командную строку. Почему бы не разработать объект типа getstr, который порождал бы на выходе строковый объект, значение которого вводилось бы с консоли? Это позволило бы повысить интерактивность языка и динамичность кода. А различные преобразования в другие варианты объектов (числа, булевские и прочие) уже бы решалось внутри объекта string. Что-то подобное есть, например, в Питоне. Ограничитель ввода - Enter.

**Comment by yegor256** [comment]
@kreofil да, планировали сделать `org.eolang.io.stdin`. Сделаю в ближайшее время!

**Comment by nlchar** [comment]
#253

**Comment by yegor256** [comment]
@Graur maybe you can help here?

**Comment by Graur** [comment]
Can anyone help me clarify these questions:
1. Do I need to implement stdin here? 
2. Do I need to implement something like this: https://docs.python.org/3/library/curses.html#curses.window.getstr?

**Comment by yegor256** [comment]
@Graur yes, we are looking for `stdin` object. I think it should work like this: when you dataize it, it read everything that it can from the console, until there is nothing left, and returns as a `string`. That's it.

**Comment by Graur** [comment]
@yegor256 please, assign. It was my ticket all this time

**Comment by yegor256** [comment]
@Graur go ahead

**Comment by yegor256** [comment]
@kreofil мы сделали объект `QQ.io.stdin`. он делает именно то, что описано в тикете выше. поэтому, закрываем)
