### ISSUE TITLE
PhiMojo presents strings, numbers, and booleans as bytes

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3474]
Currenlty, `PhiMojo` converts this XMIR:

```
<o base="org.eolang.string" line="11" name="foo">
  <o base="bytes" data="bytes">48 65 6C 6C 6F</o>
</o>
```

to this `.phi`:

```
foo ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 48-65-6C-6C-6F))
```

This makes phi-text less readable than it could be. I suggest converting such XML blocks to:

```
foo ↦ "Hello"
```

`UnphiMojo` should be able to understand it.

The same should be done for NUMBER and BOOLEAN.

**Comment by maxonfjvipon** [comment]
@yegor256 you suggest to extend `phi` grammar so it supports more primitive types like `strings`, `numbers`, etc, not only bytes?

**Comment by yegor256** [comment]
@maxonfjvipon yes, would be great to enable syntax sugar in our ANTLR grammar, for strings, integers and floats.
