### ISSUE TITLE
get rid of "data" attribute in XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#348]
Say, this is the code in EO:

```
[] > foo
  42 > a
  3.1415926 > b
  "hello" > c
```

It will be translated to XMIR:

```xml
<o name="foo">
  <o name="a" data="int" base="int">42</o>
  <o name="b" data="float" base="float">3.1415926</o>
  <o name="c" data="string" base="string">hello, друг</o>
</o>
```

I suggest to get rid of `data` attribute and use only bytes inside the element text:

```xml
<o name="foo">
  <o name="a" base="int">2a</o>
  <o name="b" base="float">40-49-0f-da</o>
  <o name="с" base="string">68-65-6c-6c-6f-2c-20-d0-b4-d1-80-d1-83-d0-b3</o>
</o>
```

Thus, the parser will translate primitive types to bytes.

**Comment by nikololiahim** [comment]
This wouldn't be ideal for applications that work with literals directly (e.g. eo2py), unless there is a way to decode these bytes into literals they represent.

**Comment by nikololiahim** [comment]
What are the benefits of this change? 

As I see it, this would only make XMIR less human-readable and introduce additional overhead of decoding the bytes for applications that rely on XMIR.

**Comment by yegor256** [comment]
@nikololiahim the main reason is uniformity between implementations. Now, when we keep `3.1415926` in the XMIR, each reader of XMIR can interpret it their own way. Some may think it's float (4 bytes), while others may think it's double (8 bytes). With the proposed changes we get rid of this problem: different interpretations of data.

**Comment by nikololiahim** [comment]
Ok, I see, but I still think that this change would introduce even more problems than it would solve. Every implementer would come up with their own way to decode the bytes which would spawn even more ambiguity and even bugs.

**Comment by yegor256** [comment]
@nikololiahim each EO2? compiler will have to be integrated into [objectionary](https://github.com/yegor256/objectionary), in order to become an official one. In order to be integrated there, all tests for all existing EO objects have to pass with this compiler. Thus, we will have no misunderstandings between compilers.

**Comment by yegor256** [comment]
@Graur please, help

**Comment by yegor256** [comment]
@Graur if you can make this top priority, would be great

**Comment by Graur** [comment]
@andreoss Can you help us with this issue? The budget is 30 minutes

**Comment by yegor256** [comment]
@andreoss this is urgent, would be great if you put it to the highest priority

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1084](https://github.com/objectionary/eo/issues/1084), [#1085](https://github.com/objectionary/eo/issues/1085), [#1086](https://github.com/objectionary/eo/issues/1086) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1086](https://github.com/objectionary/eo/issues/1086) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1085](https://github.com/objectionary/eo/issues/1085) is still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1099](https://github.com/objectionary/eo/issues/1099) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099).

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1103](https://github.com/objectionary/eo/issues/1103), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104).

**Comment by 0pdd** [comment]
@yegor256 6 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1103](https://github.com/objectionary/eo/issues/1103), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1116](https://github.com/objectionary/eo/issues/1116) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110).

**Comment by 0pdd** [comment]
@yegor256 5 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1103](https://github.com/objectionary/eo/issues/1103), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@yegor256 6 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1103](https://github.com/objectionary/eo/issues/1103), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@yegor256 5 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1103](https://github.com/objectionary/eo/issues/1103), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1085](https://github.com/objectionary/eo/issues/1085), [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#1115](https://github.com/objectionary/eo/issues/1115), [#1144](https://github.com/objectionary/eo/issues/1144) are still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1085](https://github.com/objectionary/eo/issues/1085), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1144](https://github.com/objectionary/eo/issues/1144) is still not solved; solved: [#1084](https://github.com/objectionary/eo/issues/1084), [#1085](https://github.com/objectionary/eo/issues/1085), [#1086](https://github.com/objectionary/eo/issues/1086), [#1099](https://github.com/objectionary/eo/issues/1099), [#1103](https://github.com/objectionary/eo/issues/1103), [#1104](https://github.com/objectionary/eo/issues/1104), [#1110](https://github.com/objectionary/eo/issues/1110), [#1111](https://github.com/objectionary/eo/issues/1111), [#1114](https://github.com/objectionary/eo/issues/1114), [#1115](https://github.com/objectionary/eo/issues/1115), [#1116](https://github.com/objectionary/eo/issues/1116).

**Comment by yegor256** [comment]
this is done, thanks to all

**Comment by Graur** [comment]
@andreoss Please, check the SolarStaff platform
