### ISSUE TITLE
Flaky test `PhiMojoTest.convertsSimpleObjectToPhi`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3492]
From this action: https://github.com/objectionary/eo/actions/runs/11799301160/job/32867479024?pr=3491

I can't build `eo-maven-plugin`, because of this error:
```
Error:    PhiMojoTest.convertsSimpleObjectToPhi:57->lambda$convertsSimpleObjectToPhi$0:65 » FileSystem C:\Users\runneradmin\.m2\repository\org\eolang\eo-maven-plugin\1.0-SNAPSHOT\eo-maven-plugin-1.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process

Error:  Tests run: 522, Failures: 0, Errors: 1, Skipped: 3
```

**Comment by volodya-lombrozo** [comment]
This flaky `PhiMojoTest.convertsSimpleObjectToPhi` test blocks this PR: https://github.com/objectionary/eo/pull/3491

**Comment by volodya-lombrozo** [comment]
I tried locally and also got the following errors (from `master` branch) :

```
[ERROR] Errors: 
[ERROR]   ParseMojoTest.parsesSimpleFile:62->lambda$parsesSimpleFile$0:73 » BuildFailure build failed
[ERROR]   PhiMojoTest.convertsSimpleObjectToPhi:57->lambda$convertsSimpleObjectToPhi$0:68 » BuildFailure build failed

```

I don't know how it might happen, but it seem, but `master` is broken.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please? It's a dangerous blocker.

**Comment by yegor256** [comment]
@volodya-lombrozo I'm on it

**Comment by yegor256** [comment]
@volodya-lombrozo should be OK now, please check

**Comment by volodya-lombrozo** [comment]
@yegor256 It's hard to say. Blocked by https://github.com/objectionary/eo/issues/3495

**Comment by volodya-lombrozo** [comment]
The problem seems gone. Thank you. I checked locally and in this PR:https://github.com/objectionary/eo/pull/3491
