### ISSUE TITLE
`@data` attribute removal from `org.eolang.bytes` leads to loss of byte data in `eo-maven-plugin:xmir-to-phi` goal

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3494]
I tried to remove `@data` attribute from  `org.eolang.bytes` object and failed. When we do this, `eo-maven-plugin:xmir-to-phi` goal removes all the bytes from the object.

After disassembling (without `data` attribute):

```xml
<o base="jeo.int" line="1246658856" name="version">
   <o base="org.eolang.bytes">00 00 00 00 00 00 00 34</o>
</o>
```

Then, after `eo-maven-plugin:xmir-to-phi` goal:

```phi
version ↦ ξ.jeo.int(
  α0 ↦ Φ.org.eolang.bytes
),
```

As you can see, bytes are lost.
If I leave `@data` attribute, everything works just fine.
**Expected behaviour:** `eo-maven-plugin:xmir-to-phi`  preserves all the bytes.

**Comment by volodya-lombrozo** [comment]
This issue blocks https://github.com/objectionary/jeo-maven-plugin/issues/850

**Comment by volodya-lombrozo** [comment]
@yegor256 I see, thank you

**Comment by volodya-lombrozo** [comment]
I [tried](https://github.com/objectionary/jeo-maven-plugin/pull/903) one more time and the exact problem persists.

**Comment by volodya-lombrozo** [comment]
@yegor256 Please, have a look.

**Comment by yegor256** [comment]
@volodya-lombrozo you need to use eo-maven-plugin 0.43.0, please try again

**Comment by volodya-lombrozo** [comment]
@yegor256 With the version `0.43.0`, `eo-maven-plugin` keeps bytes in `phi` format:
```phi
version ↦ Φ.jeo.int(
  α0 ↦ Φ.org.eolang.bytes(
    α0 ↦ ⟦ Δ ⤍ 00 00 00 00 00 00 00 34 ⟧
  )
),
```

Thank you!
