### ISSUE TITLE
`SnippetIT` silently stays in idle state

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3495]
I cloned the recent version of the repository, then run
```
mvn clean install
```
and after some time, the process stacked with the following message:
```
[INFO] Running org.eolang.SnippetIT
```
And nothing happens. It just doing something for a long time. I waited around `~5 min` and stopped the test.
I believe we should remove this test from "unit" tests and add at least some logging.

**Comment by yegor256** [comment]
@volodya-lombrozo are you sure `mvn clean test` runs those integration tests? I just checked and they don't (on my machine):

```
mvn test -pl :eo-runtime
```

**Comment by yegor256** [comment]
@volodya-lombrozo after 6ae091863, it should be a bit better

**Comment by volodya-lombrozo** [comment]
Yes, it is a bit better, thank you:
```
[INFO] Running org.eolang.SnippetIT
WARN  c.y.MayBeSlow - We're still running runsAllSnippets[#2] (6s), please wait...
WARN  c.y.MayBeSlow - We're still running runsAllSnippets[#2] (16s), please wait...
WARN  c.y.MayBeSlow - We're still running runsAllSnippets[#2] (31s), please wait...
WARN  c.y.MayBeSlow - We're still running runsAllSnippets[#2] (51s), please wait...
```
