### ISSUE TITLE
the `org.eolang.maven.optimization` package is over-design

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3519]
I believe that the `org.eolang.maven.optimization` package is not necessary -- all classes from it may be placed right into the `OptimizeMojo`, in order to improve readability.

**Comment by ArtemGet** [comment]
@yegor256 In addition, i wish to some more improvements and tests, but it would be too much for 1PR. 
I.E replacing the OptTrain.DEFAULT_TRAIN constant or replacing optimization() methods in Mojo's to something like:

```java
new OptSpyFork(
  ()-> //reason to spy
  ()-> new OptimizeMojo.OptSpy(...),
  ()-> new OptimizeMojo.OptTrain(...)
)
```

WDYT?

**Comment by yegor256** [comment]
@ArtemGet I'd suggest to start with the smallest PR possible, it will help us review it faster
