### ISSUE TITLE
Invalid phi syntax doesn't lead to UnphiMojo crash

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3530]
If I pass this phi code to `UnphiMojo`, it gets processed without errors:

```
            access ↦ Φ.jeo.int (
              α0 ↦ Φ.org.eolang.bytes (
                Δ ⤍ 00-00-00-00-00-00-00-21
              )
            ),

```

However, it should fail, since the syntax is not valid: the `Δ` may not be used in application.

**Comment by maxonfjvipon** [comment]
@yegor256 could you please provide some CI failed, because I can't reproduce it

**Comment by yegor256** [comment]
@maxonfjvipon you are right, I added a few tests in 3ca1f865f
