### ISSUE TITLE
data rendering in `.phi` is broken

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3534]
`PhiMojo` renders data values incorrectly: with spaces instead of dashes.

**Comment by yegor256** [comment]
@maxonfjvipon please, help us fix this (I reproduced the problem in d183103bc)

**Comment by yegor256** [comment]
@maxonfjvipon it works fine, if `01-02-03` is used in the XMIR, instead of `01 02 03`. However, I believe, we must support both formats and print `.phi` correctly in either case.

**Comment by maxonfjvipon** [comment]
@yegor256 after removing `@data` bytes in XMIR must be without spaces. We need to cover this in XSD

**Comment by maxonfjvipon** [comment]
@yegor256 and I think we should not support both, the less - the better

**Comment by yegor256** [comment]
@maxonfjvipon let's try to add a test for our XSD? The test should be parametrized and have a number of YAML files, each of which should have a wrongly formatted XMIR. We should check that all of them fail when being passed through the XSD. Then, let's implement the check in the XSD, which you are talking about.
