### ISSUE TITLE
No viable alternative at input after `eo:0.43.0:xmir-to-phi`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3535]
I tried to upgrade `eo-maven-plugin` up to the `0.43.0` version and got a bunch of errors, the main is:

```phi
org/eolang/hone/App.phi:
	[9:27] no viable alternative at input 'j$org↦⟦j$eolang↦⟦j$hone↦⟦j$App↦⟦version↦Φ.jeo.int(α0↦Φ.org.eolang.bytes(α0↦⟦Δ⤍0': "EOF"
	[9:27] no viable alternative at input 'α0↦Φ.org.eolang.bytes(α0↦⟦Δ⤍0': "EOF"
	[9:27] no viable alternative at input 'α0↦⟦Δ⤍0': "EOF"
	[11:12] mismatched input ')' expecting {'}', '(', '.'}: "EOF"
```

**How to reproduce:**

1. I disassemble java bytecode by using `jeo-maven-plugin:disassemble` into `xmir`
2. Convert this `xmir` to `phi` by using `eo-maven-plugin:0.43.0:xmir-to-phi`
3. Convert the `phi` back to `xmir` by using `eo-maven-plugin:0.43.0:phi-to-xmir`

On the (3) step I get the exception.

**Expected behaviour:** all the transformation work without errors. Moreover, `xmir-to-phi` and `phi-to-xmir` shouldn't alter the original `xmir`.

Also I attach all the files that might be helpful:
[App.xmir.disassemble.txt](https://github.com/user-attachments/files/17892400/App.xmir.disassemble.txt)
[App.phi.txt](https://github.com/user-attachments/files/17892399/App.phi.txt)
[App.xmir.unphi.txt](https://github.com/user-attachments/files/17892401/App.xmir.unphi.txt)

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look please?

**Comment by yegor256** [comment]
@volodya-lombrozo I believe, it's a duplicate of https://github.com/objectionary/eo/issues/3534

**Comment by volodya-lombrozo** [comment]
@yegor256 I don't know. It's impossible to say something from the error output. But I would suggest to keep both issues, at least for now.

**Comment by yegor256** [comment]
@volodya-lombrozo the problem is that you are generating bytes in XMIR in `00 01 02` format, but it should be `00-01-02`, starting from 0.43.0.

**Comment by yegor256** [comment]
@volodya-lombrozo try to format bytes differently, with a dash between them, not space. This is what 0.43.0 expects

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo empty bytes must look like `--` and one byte must end with dash: `00-`, the same as in EO original grammar

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon Please note that the exception was thrown **after** the `xmir-to-phi` phase, specifically during the `phi-to-xmir` phase. This means that `xmir-to-phi` **accepts** the XMIR and produces incorrect `phi`. If `xmir-to-phi` had given me an error message about dashes and bytes formatting, it would indicate a bug in `jeo-maven-plugin`, but that is not the case now. Please add some sort of checking or specification that I can rely on. Otherwise, I have no way of knowing how many else inconsistencies `jeo-maven-plugin` might produce.

**Comment by volodya-lombrozo** [comment]
It's kinda blocker.

**Comment by yegor256** [comment]
@volodya-lombrozo we are planning to make XSD stronger, in https://github.com/objectionary/eo/issues/3534

**Comment by volodya-lombrozo** [comment]
@yegor256 It would be awesome, I'm waiting for it

**Comment by yegor256** [comment]
@volodya-lombrozo try latest version (0.48.2), where XMIR is the strongest possible

**Comment by volodya-lombrozo** [comment]
@yegor256 When this PR https://github.com/objectionary/jeo-maven-plugin/pull/942 will be merged, I will be able to check and close this issue.

**Comment by volodya-lombrozo** [comment]
I can't reproduce this issue with the latest eo version `0.50.0`
