### ISSUE TITLE
Comments in the XMIR are not separated

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/eo#3536]
Consider the following EO program:

```eo
# Foo.
# Bar.
# Xyz.
[] > foo
```

XMIR I've got for this program:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This is XMIR - a dialect of XML, which is used to present a parsed EO program. For more information please visit https://news.eolang.org/2022-11-25-xmir-guide.html-->
<program dob="2024-11-19T15:27:42"
         ms="152"
         name="unknown"
         revision="a884294"
         time="2024-11-24T10:13:43.149561Z"
         version="0.42.0">
   <listing># Foo.
# Bar.
# Xyz.
[] &gt; foo
</listing>
   <errors/>
   <sheets/>
   <license/>
   <metas/>
   <objects>
      <o abstract="" line="4" name="foo" pos="0"/>
   </objects>
   <comments>
      <comment line="4">Foo.Bar.Xyz.</comment>
   </comments>
</program>
```

In the program we obviously had all three comments, separated by new line, however in XMIR we got just one "merged" comment. It would be convenient to to have information about newlines (`\n`) in the XMIR (in order to be able treat each individual comment granularly)

**Comment by h1alexbel** [comment]
@maxonfjvipon take a look, please

**Comment by h1alexbel** [comment]
@maxonfjvipon could you assign me?

**Comment by 0crat** [comment]
@h1alexbel Thank you for your contribution! While this ticket wasn't accepted, your effort is valuable. You've earned -16 points, but don't be discouraged. Your bug reports and enhancement suggestions are crucial for improving our project's quality. Keep them coming, and remember to [be thorough](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) in your submissions. We appreciate your commitment and [welcome all feedback](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html), as it helps us grow and refine our work. 👍
