### ISSUE TITLE
Does EO allow `null` values?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3545]
I thought, that EO doesn't use `null` objects, references or values.  I read it from this [README](https://github.com/objectionary/eo/blob/master/README.md) excerpt:

> ... we don't tolerate:
> ...
> NULL ([why?](http://www.yegor256.com/2014/05/13/why-null-is-bad.html)) 

However, from this [comment](https://github.com/objectionary/eo/issues/3535#issuecomment-2496103025) I can see, that EO actually **can** define some mysterious "empty" bytes which are null values actually:

> empty bytes must look like `--`

It seems, we need to fix the README and say the truth.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by yegor256** [comment]
@volodya-lombrozo the "empty bytes" is not null. Instead, it's similar to `new byte[0]` in Java

**Comment by volodya-lombrozo** [comment]
@yegor256 What's the difference with `00-` value then?

**Comment by yegor256** [comment]
@volodya-lombrozo even though we claim that "we don't have NULL", there is something that people may consider to be NULL in EO. We can do this, in EO (pseudo-code):

```
// create an object with the "k" attribute, not yet attached to any object
a = [ k: ∅ ]   

// create a copy of "a", attaching {42" to the "k" attribute
b = a(k -> 42)
```

Here, we can think that `k` is attached to NULL, but the semantic is different. How? In EO, unlike _all_ other language that have NULL, it's impossible to re-attach `k`.

**Comment by yegor256** [comment]
@volodya-lombrozo here, `00-` means `new byte[1] {0x00}` (one byte), while `--` means `new byte[0]` (no bytes).

**Comment by volodya-lombrozo** [comment]
@yegor256 However, if I try to access `a.k` attribute I will get some sort of NPE, isn't it?

> @volodya-lombrozo even though we claim that "we don't have NULL", there is something that people may consider to be NULL in EO. We can do this, in EO (pseudo-code):
> 
> ```
> // create an object with the "k" attribute, not yet attached to any object
> a = [ k: ∅ ]   
> 
> // create a copy of "a", attaching "42" to the "k" attribute
> b = a(k -> 42)
> ```
> 
> Here, we can think that `k` is attached to NULL, but the semantic is different. How? In EO, unlike _all_ other language that have NULL, it's impossible to re-attach `k`. Thus, it's not NULL, but a **placeholder** for an object.

**Comment by yegor256** [comment]
@volodya-lombrozo indeed, if you do `a.k`, you will get a runtime error

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo here, `00-` means `new byte[1] {0x00}` (one byte), while `--` means `new byte[0]` (no bytes). You can do:
> 
> ```
> --.length   // this is zero
> ```

@yegor256  What about just `00`, can I save it to `org.eolang.bytes` ?

**Comment by yegor256** [comment]
@volodya-lombrozo if you say `00` in EO, it will mean instance of 8-bytes `org.eolang.number`. If you need `org.eolang.bytes` with a single byte inside, you have to say `00-`

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo if you say `00` in EO, it will mean instance of 8-bytes `org.eolang.number`. If you need `org.eolang.bytes` with a single byte inside, you have to say `00-`

I guess it's related to this issue more https://github.com/objectionary/eo/issues/3546. I don't use `org.eolang.number`

**Comment by yegor256** [comment]
@volodya-lombrozo did I answer the original question? Or still not clear why NULL is here?)

**Comment by volodya-lombrozo** [comment]
@yegor256 You answered, yes, thank you! Actually `--` is not a null value, it's  `new byte[0]`. Although, I'm wondering where we might need such objects, it more or less clear.

However, as for `NULL` values, we actually have them. You call these values as attributes that "not yet attached to any object". 

Maybe we can mention these important findings somewhere in the README? What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo we can write a blog post about it: https://github.com/objectionary/news.eolang.org/issues/74

**Comment by volodya-lombrozo** [comment]
@yegor256 Blog posts are news. We need a proper reliable documentation.

**Comment by yegor256** [comment]
@volodya-lombrozo we don't have "language manual" so far, we use blog posts instead, while the language is in active development

**Comment by volodya-lombrozo** [comment]
@yegor256 Even if it's in active development, it's better to have some document to rely on. Otherwise, it makes the development of tools related to the language extremely hard. Blog posts do not solve the problem—they aren't reliable.

To put it another way, just as an analogy: If I want to make people use my imaginary "server," I need to provide an API for them. Otherwise, how will they know about the endpoints and in what format to make HTTP requests? The same applies here. Of course, we can say that we are in "development," but that means we block the development of tools around the language.

**Comment by yegor256** [comment]
@volodya-lombrozo I can move this ticket to this repo: https://github.com/objectionary/eo-book Eventually, we will put this information into the book. How does this sound?

**Comment by volodya-lombrozo** [comment]
@yegor256 a bit better. Thank you.
