### ISSUE TITLE
spaces are allowed in metas, which leads to broken XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3556]
Try to parse this code:

```
+foo hello  world

# test.
[] > foo
```

The XMIR generated will contain this:

```
<meta>
  <head>foo</head>
  <tail>hello  world</tail>
  <part>hello</part>
  <part/>                        # this is illegal!
  <part>world</part>
</meta>
```

Let's make it impossible to use spaces inside metas.

**Comment by yegor256** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 you suggest to make it via grammar?

**Comment by maxonfjvipon** [comment]
@yegor256 what about `+rt jvm org.eolang:eo-runtime:0.0.0` meta?
