### ISSUE TITLE
Why it's illegal to make a copy of a terminator?

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3557]
Why this is not a legal phi expression?

```
{⟦ k ↦ ⊥ (t ↦ ξ.t) ⟧}
```

`PhiSyntax` complains about it, here: https://github.com/objectionary/eo/blob/master/eo-parser/src/test/resources/org/eolang/parser/phi-typos/_application-to-terminator.phi

Also, we can't use dot notation with it too: https://github.com/objectionary/eo/blob/master/eo-parser/src/test/resources/org/eolang/parser/phi-typos/_dot-to-terminator.phi

**Comment by yegor256** [comment]
@maxonfjvipon is it a bug or a feature?

**Comment by maxonfjvipon** [comment]
@yegor256 I think it's a bug

**Comment by maxonfjvipon** [comment]
@yegor256 how to convert termination + application or dispatch to XMIR?

**Comment by yegor256** [comment]
@maxonfjvipon like this, I believe:

```
org.eolang.error > k
  $.t > t
```

Isn't it what the terminator is: `error` atom?

**Comment by maxonfjvipon** [comment]
@yegor256 so both `⟦ k ↦ ⊥.t ⟧` and `⟦ k ↦ ⊥ (t ↦ ξ.t) ⟧` should be legal?
