### ISSUE TITLE
`attribute-name` in XSD may contain integers, which is wrong

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3569]
In `XMIR.xsd`, if I change the `attribute-name` type by removing the `[0-9]+` from its regular expression, `UnphiMojoTest` fails. Looks like we use this attribute (`o/@name`) incorrectly, holding their numbers when necessary. Let's get rid of this hack.

**Comment by yegor256** [comment]
@maxonfjvipon need your help here

**Comment by maxonfjvipon** [comment]
@yegor256 I believe @volodya-lombrozo won't like it since he uses numbers in attributes in jeo a lot

**Comment by yegor256** [comment]
@maxonfjvipon we'll ask JEO to use something else, maybe same numbers but with a letter as a prefix

**Comment by yegor256** [comment]
@maxonfjvipon maybe let's allow `α0` in the `@as` attribute?

**Comment by maxonfjvipon** [comment]
@yegor256 then we should catch it when we print XMIR to EO and remove `α`, or add `α` when we parse the next EO: `string 01-02:0`

**Comment by maxonfjvipon** [comment]
@yegor256 but how to deal with this: `⟦ α65536 ↦ Φ.r ⟧`. Here `α65536` goes to `@name` attribute and there's no way it can be converted to EO properly

**Comment by yegor256** [comment]
@maxonfjvipon indeed, this

```
⟦ α65536 ↦ Φ.r ⟧
```

Can't be converted to XMIR/EO anyhow. We must throw an exception in this case, since it's not a valid phi-expression either. All `α`-prefixed attributes in a formation must start with zero and go one after another without any gaps. Maybe, we should create a lint for this too.

**Comment by maxonfjvipon** [comment]
@yegor256 so the result `attribute-name` pattern would be: `α[0-9]+|@|[a-z][^ \n\t\r]*`?

**Comment by yegor256** [comment]
@maxonfjvipon correct
