### ISSUE TITLE
syntax suggar is not supported by Phi.g4

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3571]
I'm trying to add this to `all-the-basics.phi` and the build fails in `eo-parser`:

```
  primitives ↦ ⟦
    string ↦ "hello, друг!",
    int ↦ 42,
    float ↦ 3.14
  ⟧,
```

Would be great if we can support this syntax. Moreover, we should use it when printing XMIR to PHI too.

**Comment by yegor256** [comment]
@maxonfjvipon this is your, please help

**Comment by maxonfjvipon** [comment]
@yegor256 still an issue?

**Comment by yegor256** [comment]
@maxonfjvipon fixed, thanks!
