### ISSUE TITLE
\Lambda goes into the `@base` attribute of XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3605]
For this phi expression:

```
foo ↦ ⟦ λ ⤍ Bar ⟧
```

I'm getting something like this in XMIR:

```
<o base="Bar"/>
```

This doesn't look correct. Instead, we should put `Bar` into the `@atom` attribute, I believe.

**Comment by yegor256** [comment]
@maxonfjvipon please, check this one

**Comment by maxonfjvipon** [comment]
@yegor256 I'm trying to parse `{⟦ foo ↦ ⟦ λ ⤍ Bar ⟧ ⟧}` and I'm getting:
```xml
<objects>
      <o atom="Bar" name="foo"/>
   </objects>
```
So I can't reproduce it. Could you please provide a full example where the error appears

**Comment by yegor256** [comment]
@maxonfjvipon my mistake, you are right
