### ISSUE TITLE
syntax sugar for more compact array passing

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3619]
How about we introduce a new syntax sugar, making this code:

```
[] > app
  seq > @
    * 
      QQ.io.stdout "Hello, "
      QQ.io.stdout "dude!"
```

writable as such:

```
[] > app
  seq * > @
    QQ.io.stdout "Hello, "
    QQ.io.stdout "dude!"
```

If `*` follows application, all objects passed as arguments are wrapped into a `tuple`.

**Comment by yegor256** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 so it may work only if `tuple` is the only argument, I believe this should be illegal:
```
x y z *
  1
  2
```

**Comment by yegor256** [comment]
@maxonfjvipon well, why not make it legal too?

```
QQ.txt.sprintf 
  "hello, %s, your salary is %d" *
  "Jeff"
  199.99
```

**Comment by maxonfjvipon** [comment]
@yegor256 it's kind of mixing vertical and horizontal applications, looks a bit confusing.

**Comment by yegor256** [comment]
@maxonfjvipon ok, agree. Just this will be enough:

```
[] > app
  seq * > @
    QQ.io.stdout "Hello, "
    QQ.io.stdout "dude!"
```

**Comment by maxonfjvipon** [comment]
@yegor256 the second argument of `sprintf` is tuple so they must be packed to tuple anyway

**Comment by maxonfjvipon** [comment]
@yegor256 looks interesting, let's try to implement

**Comment by yegor256** [comment]
@maxonfjvipon this is the most needed now, please implement this first
