### ISSUE TITLE
let's remove `@method`, `@star`, and `@const` from XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3624]
We can remove these three attributes from XMIR, if we do the following:

First, move `wrap-method-calls.xsl` to the top of the `TrParsing` train and make sure the build is clean.

Then, move `const-to-dataized.xsl` also to the top and make sure the build is clean

Then, move three shifts (`stars-to-tuples.xsl`, `wrap-method-calls.xsl`, `const-to-dataized.xsl`) to `EoSyntax` -- apply them there, before the final XMIR file is produced.

Then, get rid of the attributes in XSD.

**Comment by yegor256** [comment]
@maxonfjvipon WDYT

**Comment by maxonfjvipon** [comment]
@yegor256 we can try

**Comment by yegor256** [comment]
@maxonfjvipon we can try step by step, in a few pull requests (as outlined above)

**Comment by yegor256** [comment]
@rultor release, tag is `0.48.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.48.1`
