### ISSUE TITLE
too many CodeNarc violations for our Groovy files

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3643]
In the `codenarc.yml`, it is configured to set `-maxPriority2Violations=50` and `-maxPriority3Violations=200`. Instead, the numbers should be zero and zero. Let's set them to zeroes and also fix our Groovy files so that CodeNarc doesn't complain.

**Comment by coutvv** [comment]
Done, please review:
https://github.com/objectionary/eo/pull/3667

**Comment by yegor256** [comment]
@coutvv thanks a lot!!
