### ISSUE TITLE
invalid lambda names in some .phi files

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3650]
In some files, I see this:

```
            φ ↦ ⟦
              λ ⤍ Lorg_eolang_malloc_of_φ
            ⟧,

```

Looks like a wrong syntax for the value of `λ`. Must be only English letters and underscores. Let's make syntax stricter (when parsing) and convert `φ` to `phi` when printing.

**Comment by yegor256** [comment]
@maxonfjvipon please, help us here

**Comment by maxonfjvipon** [comment]
@yegor256 this atom in EO looks like this:
```
[] > malloc
  [] > of
    [] > @ /bytes
```
We have an XSL transformation what converts atoms like this:
```
x ↦ ⟦
  text ↦ Φ.org.eolang.bytes (α0 ↦ ⟦ Δ ⤍ 48-65-6C-6C-6F-20-77-6F-72-6C-64-0A ⟧),
  size ↦ Φ.org.eolang.bytes (α0 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-00-08 ⟧),
  λ ⤍ Lorg_eolang_io_stdout
⟧
```

to the application:
```
x ↦ Φ.org.eolang.io.stdout(
  text ↦ Φ.org.eolang.bytes (α0 ↦ ⟦ Δ ⤍ 48-65-6C-6C-6F-20-77-6F-72-6C-64-0A ⟧),
  size ↦ Φ.org.eolang.bytes (α0 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-00-08 ⟧)
)
```

I'm afraid if we will replace `φ` with `phi` - we will lose the original atom FQN

**Comment by yegor256** [comment]
@maxonfjvipon got it. Let's update he grammar for phi in this case, allowing `λ ⤍` to have only this: `^[A-Z][A-Za-z_φ]*`

**Comment by maxonfjvipon** [comment]
@yegor256 this is the current rule for lambda function: `[A-Z] ~[ \r\n\t,.|':;!\-?\][}{)(⟧⟦]*`
