### ISSUE TITLE
logging features in `PhDefault` are rudimentary

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3690]
We introduced them (e.g. `PhDefault.NESTING`, `Phi.φTerm()`, and `Phi.toString()`) when the language was rather young and we needed lowest level debugging instruments. Currently, I believe, we can easily remove them.

**Comment by yegor256** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 totally agree

**Comment by yegor256** [comment]
@maxonfjvipon maybe also logging in `Dataized`, which is not about errors (this part we need!)

**Comment by yegor256** [comment]
@maxonfjvipon please, help with this one

**Comment by maxonfjvipon** [comment]
@yegor256 so what about logging in `Dataize`, do we remove it or not?
