### ISSUE TITLE
Remove current implementation of objection versioning

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#3698]
Now we have a lot of kind of dead code related to object versioning in `eo-parser` and `eo-maven-plugin`. 
1. There are so much code in `eo-maven-plugin` that must be refactored. 
2. Since the object versioning is put on hold, it may create difficulties for refactoring. 
3. Also maybe the current implementation of object versioning should be refactored as well. 

My suggestion is to remove the current functionality of object versioning. It'll speed up the build, EO grammar and `eo-maven-plugin` itself.

Then, when EO is stable, `eo-maven-plugin` is well designed and refactored and we're totally ready to introduce object versioning - try to implement it one more time in a good way.

@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon I agree
