### ISSUE TITLE
ParsingErrors.java:87-90: Add more specific error...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#3706]
The puzzle `3332-e91c74c1` from #3332 has to be resolved: 

https://github.com/objectionary/eo/blob/32d00ed860d5f83e93ff1fe3ecf80bdc70e68c41/eo-parser/src/main/java/org/eolang/parser/ParsingErrors.java#L87-L90

The puzzle was created by Yegor Bugayenko on 19-Dec-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@volodya-lombrozo please, go ahead

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744), [#3745](https://github.com/objectionary/eo/issues/3745), [#3746](https://github.com/objectionary/eo/issues/3746) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744), [#3745](https://github.com/objectionary/eo/issues/3745), [#3746](https://github.com/objectionary/eo/issues/3746) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#3744](https://github.com/objectionary/eo/issues/3744), [#3745](https://github.com/objectionary/eo/issues/3745), [#3746](https://github.com/objectionary/eo/issues/3746) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#3745](https://github.com/objectionary/eo/issues/3745), [#3746](https://github.com/objectionary/eo/issues/3746), [#3828](https://github.com/objectionary/eo/issues/3828), [#3829](https://github.com/objectionary/eo/issues/3829) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#3745](https://github.com/objectionary/eo/issues/3745), [#3828](https://github.com/objectionary/eo/issues/3828), [#3829](https://github.com/objectionary/eo/issues/3829), [#3851](https://github.com/objectionary/eo/issues/3851) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744), [#3746](https://github.com/objectionary/eo/issues/3746).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#3745](https://github.com/objectionary/eo/issues/3745), [#3829](https://github.com/objectionary/eo/issues/3829), [#3851](https://github.com/objectionary/eo/issues/3851) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744), [#3746](https://github.com/objectionary/eo/issues/3746), [#3828](https://github.com/objectionary/eo/issues/3828).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#3829](https://github.com/objectionary/eo/issues/3829), [#3851](https://github.com/objectionary/eo/issues/3851) are still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744), [#3745](https://github.com/objectionary/eo/issues/3745), [#3746](https://github.com/objectionary/eo/issues/3746), [#3828](https://github.com/objectionary/eo/issues/3828).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#3829](https://github.com/objectionary/eo/issues/3829) is still not solved; solved: [#3714](https://github.com/objectionary/eo/issues/3714), [#3715](https://github.com/objectionary/eo/issues/3715), [#3742](https://github.com/objectionary/eo/issues/3742), [#3743](https://github.com/objectionary/eo/issues/3743), [#3744](https://github.com/objectionary/eo/issues/3744), [#3745](https://github.com/objectionary/eo/issues/3745), [#3746](https://github.com/objectionary/eo/issues/3746), [#3828](https://github.com/objectionary/eo/issues/3828), [#3851](https://github.com/objectionary/eo/issues/3851).
