### ISSUE TITLE
maven-invoker-plugin tests are not skipped with `-DskipTests`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3711]
This is the [default behavior](https://maven.apache.org/plugins/maven-invoker-plugin/examples/skipping.html), but it will be more convenient if in our project we skip invoker when `skipTests` property is set.

**Comment by ArtemGet** [comment]
@yegor256 This PR solves an issue, but, tests in eo-maven-plugin would still run if only property -DskipITs is set. It is confusing, so I suggest using profiles -PskipTests -PskipITs -PskipUTs to achieve [this](https://github.com/objectionary/eo/issues/3696#issuecomment-2554040718) logic. This requires to change actions scripts and not setting properties -DskipTests -DskipUTs -DskipITs manually. I can do this if there are no objections.
