### ISSUE TITLE
syntax sugar to put array elements in horizontal mode after other arguments

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3727]
related to #3619

Now, I have to write this:

```
sprintf
  "Hello, %s!"
  * "Jeff"
```

How about this instead:

```
sprintf "Hello, %s!" * "Jeff"
```

Everything after `*`, in hotizontal notation, are the elements of array.

**Comment by yegor256** [comment]
@maxonfjvipon WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 well, it may work, looks not bad

**Comment by yegor256** [comment]
@maxonfjvipon we can write like this instead:

```
sprintf "Hello, %s!" (* "Jeff")
```
