### ISSUE TITLE
broken-binding.yaml:24-26: Add exact location of the...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#3743]
The puzzle `3706-9d5eb2d7` from #3706 has to be resolved: 

https://github.com/objectionary/eo/blob/bc3cebd7cd2ae060d558087787d6d537b7a5536d/eo-parser/src/test/resources/org/eolang/parser/eo-typos/broken-binding.yaml#L24-L26

The puzzle was created by Yegor Bugayenko on 23-Dec-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@yegor256 I can work on this
