### ISSUE TITLE
The `phi/unphi` Phases Create Duplicates 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3770]
I'm trying to use `objectionary/lints` inside `objectionary/jeo-maven-plugin`. I used to use the plugin after the disassemble phase of `jeo`, and everything worked just fine. However, when I added a check after the `phi/unphi/unroll` phases, the build started to fail with the following exception:

```java
Caused by: java.lang.IllegalStateException: XMIR is incorrect: [[same-line-names ERROR]:374 The name "param-Ljava%2Flang%2FString%3B-arg0-0-0" has been used twice on line no.374, [same-line-names ERROR]:380 The name "param-annotations-0-541252607" has been used twice on line no.380, [same-line-names ERROR]:374 The name "param-Ljava%2Flang%2FString%3B-arg0-0-0" has been used twice on line no.374, [same-line-names ERROR]:380 The name "param-annotations-0-541252607" has been used twice on line no.380]
```

I've checked the files and there is the duplication of `param-Ljava%2Flang%2FString%3B-arg0-0-0` indeed.

Full log is here: 
[build.log](https://github.com/user-attachments/files/18259755/build.log)
[D.disassemble.xmir.txt](https://github.com/user-attachments/files/18259759/D.disassemble.xmir.txt)
[D.phi.txt](https://github.com/user-attachments/files/18259761/D.phi.txt)
[D.unphi.xmir.txt](https://github.com/user-attachments/files/18259764/D.unphi.xmir.txt)
[D.unroll.xmir.txt](https://github.com/user-attachments/files/18259767/D.unroll.xmir.txt)

Could you fix this bug, please?

**Comment by volodya-lombrozo** [comment]
This issue blocks https://github.com/objectionary/jeo-maven-plugin/pull/955

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Can you take a look please? It's rather urgent.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo in `D.disassemble.xmir` you have two `<o name="param-Ljava%2Flang%2FString%3B-arg0-0-0">` elements. Since you got rid of abstract objects - these two elements are in the same global scope

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo in `D.disassemble.xmir` you have two `<o name="param-Ljava%2Flang%2FString%3B-arg0-0-0">` elements. Since you got rid of abstract objects - these two elements are in the same global scope

@maxonfjvipon Thanks, most probably I will be able to solve this particular case on my side. However, please, pay attention, that plugin reports `"param-annotations-0-541252607"` as well - in this case we have only one `"param-annotations-0-541252607"`  after `disassemble` phase and two after `phi/unphi/unroll`.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I strongly believe that duplication of `param-annotations-0-541252607` will be resolved when you resolve duplication of `param-Ljava%2Flang%2FString%3B-arg0-0-0` because `param-annotations-0-541252607` is child element of `param-Ljava%2Flang%2FString%3B-arg0-0-0` and it's copied together with all inner elements. So duplication of `param-Ljava...` causes `param-annotation...`. Try to resolve the first duplication and let me know if problem exists

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Seems, the problem is gone: https://github.com/objectionary/jeo-maven-plugin/pull/955. Thank you for the help!
