### ISSUE TITLE
code duplication inside Program.g4

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#390]
This block contains duplicated code: https://github.com/cqfn/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L131-L180 Would be great to get rid of duplication. I made it like this, after the discussion: https://stackoverflow.com/questions/64635366/how-to-make-antlr-consume-all-available-elements-using-recursion

**Comment by yegor256** [comment]
@andreoss it's done, I believe?

**Comment by andreoss** [comment]
@yegor256 The structural duplication between `application` and `htail` remains, but many improvements had been done.
In #570, #611, #567, #563, which are PRs for this issue. 

So this issue can be closed with a new one

**Comment by Graur** [comment]
@andreoss Did you finish this issue?

**Comment by yegor256** [comment]
@andreoss @Graur I'm closing. I will submit new issues, if see more problems
