### ISSUE TITLE
Recursive update exception

### ISSUE THREAD

**Issue by dours** [objectionary/eo#445]
```
[] > trivial
  memory > f1
  cage > f2
  memory > f0
  seq > @
    f0.write 0
    f1.write 1
    f2.write ((f0).add (f1))
    f1.write (f2)
    TRUE
```

Also this way
```
[] > trivial
  cage > f1
  cage > f2
  cage > f0
  seq > @
    f0.write 0
    f1.write 1
    f2.write ((f0).add (f1))
    f1.write (f2)
    f1
```

**Comment by yegor256** [comment]
@dours well, of course, this leads to endless recursion. Why it surprises you?

**Comment by dours** [comment]
@yegor256 in line `f1.write (f2)` dataization of f2 is called before assigment to f1, so f1 should store data `1`. Why then the dataization leads to recursion?

**Comment by dours** [comment]
@yegor256 It leads to recursion, because dataization of `f2` in line `f1.write (f2)` creates a copy of object `((f0).add (f1))` with new rho, that is add.rho becomes f2, not f0. So, it calculates f2+f1 instead of f0+f1, which is indeed an endless recursion. This behavior  still does surprise me. 

I hacked EOcage.java: `return object.copy(object.attr("ρ").get());` on line 56 instead of `return object.copy(rho);` 

My generated Fibonacci test passes with the hack. Is there a better way?

**Comment by yegor256** [comment]
@dours nice catch! Please, submit a PR with the change at the line 56, I'll merge it. BTW, I suggest making the same change in the `EOmemory` class.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#445](https://github.com/cqfn/eo/issues/445); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by dours** [comment]
@yegor256 alright, I'll do it. But still, it looks like a hack to me: it looks that there are 2 objects here: an abstract object `add` (which has rho equal to f0) and an object application `add f1`, which may have a different rho (f2 for example). If this is only one object, then I don't understand why, for example, in this code
```
[] > o1
  f0.add f1 > f2
```
`(f0.add f1).rho` does not become equal to `o1`, while this is what definiton 8 of section 3.5 of the paper https://www.eolang.org/eolang-paper.pdf tells us (me at least).

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#445` is not assigned, can't get performer
