### ISSUE TITLE
catch redundant brackets

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#485]
I suggest we create a new XSL checker for eo-parser, which will prohibit the usage of redundant brackets, for example, this code should not parse:

```
[] > foo
  (1.add (a.add 5) (4)) > x
```

This one should be expected instead:

```
[] > foo
  1.add (a.add 5) 4 > x
```

**Comment by yegor256** [comment]
@andreoss what do you think?

**Comment by andreoss** [comment]
@yegor256 Please, assign to me.
Are you positive that it should be XSL? 
It seems that it would be easier to count and discard extra parenthesis in `XeListener`.

**Comment by yegor256** [comment]
@andreoss I'm not sure about XSL. I actually don't know how this can be implemented at all :) You go ahead.

**Comment by yegor256** [comment]
@volodya-lombrozo try this one please

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1490](https://github.com/objectionary/eo/issues/1490) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1490](https://github.com/objectionary/eo/issues/1490) is solved here.
