### ISSUE TITLE
object "ram" and refactoring of "heap"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#505]
Let's introduce a new object `ram`, which will have just two sub-atoms:

```
[size] > ram
  [p b] > write /bool
  [p] > read /bytes
```

It should be possible to create a block of random-access byte array and then write a few bytes there and read them back:

```
ram 1024 > m
m.write 100 ("hello".as-bytes)
(m.read 100).eq ("hello".as-bytes)
```

And then refactor the object `heap` so that it doesn't have any atoms, but only encapsulate this new `ram`.

**Comment by yegor256** [comment]
@andreoss what do you think about this?

**Comment by andreoss** [comment]
@yegor256 Please, assing

**Comment by andreoss** [comment]
@yegor256 Should there be one more parameter indication the length for read?
```
[size] > ram
  [p b] > write /bool
  [p l] > read /bytes

```

**Comment by yegor256** [comment]
@andreoss yes, you are right

**Comment by Graur** [comment]
@yegor256 @andreoss I believe we can close it. The next step is to solve #684

**Comment by yegor256** [comment]
@Graur ok, closing
