### ISSUE TITLE
`+package` after `+alias` is valid

### ISSUE THREAD

**Issue by i582** [objectionary/eo#510]
I looked at the grammar and at this point it is possible to write an alias first and then package.

```
+alias org.eolang.io.stdout
+package main
+alias org.eolang.txt.sprintf

[] > app
  (stdout (sprintf "Hello, %s!" "Jeffrey")) > @
```

It seems wrong to allow such code. It might be valid if we consider these metas at the same level, but in other languages the package name always comes first.

By the way, as I understand it, it is not necessary to include the package name, did you think to make it mandatory, as in Java or Kotlin? 

`package main` for single main file might be the default.

P.S.

Oh, and the fact that a package can be written several times is also not very good.

**Comment by yegor256** [comment]
@i582 I agree that multiple `package` metas should definitely be a bug, let's fix it. As for the location of the meta -- in EO this should not matter, they all are at the same level of semantics.

**Comment by yegor256** [comment]
@i582 as for the mandatory usage of `package`, I suggest you create a new ticket. In general, try to report only ONE problem per issue.

**Comment by yegor256** [comment]
@i582 btw, maybe you want to fix this and submit a pull request? :)

**Comment by i582** [comment]
> @i582 as for the mandatory usage of `package`, I suggest you create a new ticket. In general, try to report only ONE problem per issue.

Yep, I will create a separate issue, I wanted to clarify in this issue that it makes sense so as not to produce unnecessary issues.

**Comment by i582** [comment]
> @i582 I agree that multiple `package` metas should definitely be a bug, let's fix it. As for the location of the meta -- in EO this should not matter, they all are at the same level of semantics.

However, existence for them at the same level of semantics does not provide any advantages, but will only confuse people who come to the language and see the code in which aliases go first, and only then the package (although this language is able to confuse the person who previously wrote on common languages ​​like C++ or Golang 😄).

What's more important, if we take the package out of the meta at the parser level, we will immediately solve the problem of multiple packages, since the parser will not be able to parse it. It seems to me that the language will not lose anything from the fact that you can define a package after aliases.

**Comment by yegor256** [comment]
@i582 OK, you convinced me. Let's add a rule that will allow `+package` to be only the first meta.

**Comment by andreoss** [comment]
@i582 Lack of `+package` should be interpreted as unnamed package (https://docs.oracle.com/javase/specs/jls/se17/html/jls-7.html#jls-7.4.2)
@yegor256
Can package be different from file location? If not,  why `+package` is needed at all? It will always be the same a path relative to compilation root.

**Comment by yegor256** [comment]
@andreoss I agree, let's get rid of `+package` all together

**Comment by i582** [comment]
@yegor256 But why? Explicit definition is better than implicit one. I cannot give significant examples, they are all more about convenience. What is the general advantage of removing the explicit definition? This does not make the language easier, as the concept remains.

**Comment by yegor256** [comment]
@i582 I believe it's a duplication of information. On one hand, you specify the package in `+package`, on the other hand you place your `.eo` file into a directory with the name of a package. Which information is right? Your `+package` or the directory? Duplication is bad.

**Comment by i582** [comment]
@yegor256 Let's first decide which information is main, the location of the file relative to the root folder, or the package name that is defined in the file.

Let's start with the package name inside the file: a package definition is a language construct that is described in its grammar and is directly part of the language. The package name defines the package name in the generated Java file.

The location of the files is the developer's choice of how to store the code. The location of files according to the package name, this is the recommended style of file location, which is not described in the formal definition of the language (I did not find it in the file `eolang-paper.pdf`, in section `Metas and License` or any other). 
But as I understand it, if the compiler does not find the necessary folders for alias, then it considers it is an external dependency and starts downloading files from the repository. In general, this can be considered as checking that the file is in the correct folders. But since this is not described in the formal description of the language, it can be considered as a specific feature of the implementation in the compiler.

Thus, at the moment, it is the package name that is part of the formal description of the language and is the main information.

**Comment by i582** [comment]
> Duplication is bad.

The implicitness is even worse.

Let's say I have a big project with many files, what package do I need to import to include this class?

<img width="771" alt="Снимок экрана 2021-12-24 в 00 10 14" src="https://user-images.githubusercontent.com/51853996/147291682-5b89c747-ba4e-459f-becf-bb17a1030ebf.png">

Due to the fact that at the beginning of the file there is a package name, there are no problems, but if it were not there, you would have to deal with collecting it piece by piece from folders. Not the most enjoyable thing to do, is it?

**Comment by andreoss** [comment]
@i582 Having a big project with many files is the problem, packages in your example don't convey any information, but rather provide already redundant taxonomy (i.e *Filters go to 'filters' package, *Actions go to 'action' package).

Using FS as a namespace abstraction gives other advantages as well:
- refactoring is easier (rename package = rename directory)
- consistency among compilation steps (compiled files share relative path)

Also, you are mistaken neither in Java nor in Kotlin `package` is mandatory. 
In Go, it is, by the compiler requires package name to match directory name, https://go.dev/ref/spec#Source_file_organization

**Comment by i582** [comment]
@andreoss Perhaps I put it wrong somewhere and you think that I think the idea of ​​matching the names of packages and paths where files are located in the filesystem is bad. This is not true. I am only trying to show the inconvenience that can be encountered if you remove the explicit declarations of package names.

About the first benefit that you described. Let's say you have a project and you rename the folder with files. Wouldn't you need to change paths in aliases in the entire project anyway? Yes, this removes the need to change the package name even in the explicit definition of the package name, but if we consider that the names are FQN everywhere, then the text replacement will change them everywhere, so I don't see a big advantage.

As for the second, I agree, this is convenient, and I will say again I am against only removing the explicit definition of the package name, otherwise it is really convenient.


As for the mistakes, yes, thanks for correcting it, I have not written much in Kotlin or Java, and did not know that the package name could be omitted (and is someone using this?). About Go, yes, but I only mentioned it in the context of the mandatory package definition.

**Comment by yegor256** [comment]
@andreoss @i582 one of the main ideas behind EO is that objects are unique and their entire catalog is in the objectionary.com. Thus, any object is not so much a file in a directory, but mostly a text resource with a URL. Like this one: https://github.com/yegor256/objectionary/blob/master/objects/org/eolang/io/stdout.eo So, when you open this URL you will see the package into in the URL _and_ inside the text. Duplication, obviously.

As for the missing information about this in the PDF document -- you are right! I will have to update it once we remove `+package` from the code.

**Comment by i582** [comment]
@yegor256 But what about user objects? Not all objects will be taken from objectionary.com. For them there is no URL with the package name.

**Comment by yegor256** [comment]
@i582 they are more like exceptions and for them we treat directory paths as URLs

**Comment by yegor256** [comment]
@i582 we decide to make them sorted alphabetically: #808
