### ISSUE TITLE
Make `+package` meta mandatory?

### ISSUE THREAD

**Issue by i582** [objectionary/eo#511]
In Java, Kotlin, and Golang, you must always specify package for the file. 
Perhaps in EO this can be made mandatory as well.

This will make the structure of the program more uniform.

**Comment by yegor256** [comment]
@i582 you are welcome to submit a PR

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#511](https://github.com/cqfn/eo/issues/511); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@mximp let's implement a new XSL inside `eo-parser`, which will create a warning if `+package+` meta is not present.

**Comment by mximp** [comment]
@Karina5005 Could you please help with this issue.

**Comment by Karina5005** [comment]
@mximp, do I understand correctly that we want to have exactly one meta "+package" and it should not be empty?

**Comment by mximp** [comment]
@Karina5005 exactly

**Comment by mximp** [comment]
@Karina5005 - anything left for this task?

**Comment by Karina5005** [comment]
@mximp no, it's finished

**Comment by mximp** [comment]
Thank you, @Karina5005!
@yegor256 @i582 this can be closed

**Comment by yegor256** [comment]
@Karina5005 @mximp thanks!
