### ISSUE TITLE
Too long compilation time for a simple script

### ISSUE THREAD

**Issue by i582** [objectionary/eo#529]
This issue was created to track compilation speed.

At the moment, compiling a simple script takes about 20 seconds, while, for example, compiling a small Java file takes less 1 second. It is very sad when for every small change you have to wait 20 seconds.

**Comment by yegor256** [comment]
@i582 yes, this indeed is a problem

**Comment by i582** [comment]
> This issue was created to track compilation speed.
> 
> At the moment, compiling a simple script takes about 20 seconds, while, for example, compiling a small Java file takes less 1 second. It is very sad when for every small change you have to wait 20 seconds.

**Comment by yegor256** [comment]
@i582 we are working on this, in other tickets.
