### ISSUE TITLE
EODataizeAppCallsVarargsFuncTest.java:46-50: Fix bug EO...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#534]
The puzzle `414-78631059` from #414 has to be resolved: 

https://github.com/cqfn/eo/blob/2c0047c25774494530df2a2067d5a58acbd29e19/eo-runtime/src/test/java/EOorg/EOeolang/EODataizeAppCallsVarargsFuncTest.java#L46-L50

The puzzle was created by @baudoliver7 on 23-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by baudoliver7** [comment]
@yegor256 let's me take this

**Comment by yegor256** [comment]
@baudoliver7 go ahead

**Comment by baudoliver7** [comment]
@yegor256 To simplify, here is the root of the problem : looking at the generated code, I noticed that we apply dataization multiple times on an abstract object which owns a free varargs attribute while we call it.
Let's me explain that. If you have this EO abstract object :
```eo
[args...] > f
  1 > a
  2 > @
```

And you call it here :
```eo
[] > app
  (f 1 2) > @
```
You dataize abstract object `f`, 2 times. That's because the generated code of `app` is (to simplify it) :
```java
private static class EOapp extends PhDefault {
    public EOapp(Phi sigma) {
        super(sigma);
        this.add(
            "φ",
            new AtOnce(
                new AtComposite(
                    this,
                    (rho) -> {
                        Phi fvar = new PhCopy(new EOf(rho));
                        fvar = new PhWith(fvar, 0, new Data.ToPhi(1L));
                        fvar = new PhWith(fvar, 1, new Data.ToPhi(2L));
                        return fvar;
                    }
                )
            )
        );
    }
}
```
You could notice that each decoration of `fvar` with `PhWith` represents a future dataization of `fvar` for the value provided (1 and 2).
So, for the first time (value 2 - the order is backwards), `fvar` is dataized defining its inner attribute `a` to 1 and making it immutable. The second time, the result of previous dataization is submitted to another dataization with 1 as value provided, trying this way to modify again the immutable attribute `a` already defined during the previous dataization (hence the exception `You can't overwrite X`).
What I suggest is to generate `app` code like this :
```java
private static class EOapp extends PhDefault {
    public EOapp(Phi sigma) {
        super(sigma);
        this.add(
            "φ",
            new AtOnce(
                new AtComposite(
                    this,
                    (rho) -> {
                        Phi fvar = new PhCopy(new EOf(rho));
                        fvar = new PhWith(
                            fvar, 0,
                            Arrays.asList(
                                new Data.ToPhi(1L),
                                new Data.ToPhi(2L)
                            )
                        );
                        return fvar;
                    }
                )
            )
        );
    }
}
```
with a third constructor for `PhWith` defined like this :
```java
/**
 * Ctor.
 *
 * @param phi The object
 * @param pos The position
 * @param attrs The values
 */
public PhWith(final Phi phi, final int pos, final List<Phi> attrs) {
    super(
        () -> {
            final Attr attr = phi.attr(pos);
            for (int i = 0; i < attrs.size(); i++) {
                attr.put(attrs.get(i));
            }
            return phi;
        },
        () -> String.format(
            "%s[#%d=%s]",
            phi,
            pos,
            attrs.stream()
                .map(attr -> new Indented(attr))
                .map(Indented::toString)
                .collect(Collectors.joining(", "))
        ),
        () -> String.format(
            "%s(%s#%d=%s)",
            phi,
            pos,
            IntStream.range(0, attrs.size())
                .mapToObj(
                    i -> {
                        final String term = attrs.get(i).φTerm();
                        final String txt;
                        if (term.contains("\n")) {
                            txt = String.format(
                                "\n\t#%d ↦ %s\n",
                                phi.φTerm(),
                                i,
                                new Indented(term)
                            );
                        } else {
                            txt = String.format(
                                "#%d ↦ %s",
                                phi.φTerm(),
                                i,
                                term
                            );
                        }
                        return txt;
                    }
                ).collect(Collectors.joining(", "))
        )
    );
}
```
WDYT ? (This solution already works.)

**Comment by baudoliver7** [comment]
@yegor256 WDYT ?

**Comment by yegor256** [comment]
@baudoliver7 how will you understand during Java code generation that you have to provide a list a arguments to PhWith instead of one argument?

**Comment by baudoliver7** [comment]
@yegor256 For that, we need another parser before java code generation that will include `xmir` of each object (if it is not present yet) called with its free arguments only. So, we will therefore consider `varargs` as `array` according to what you said in `arXiv.2111.13384v1.pdf` section `2.5`.
For java code generation, I would suggest rather to use this code (that avoids us to modify `PWith` class) :
```java
/**
 * Main program sample.
 * {@code
 *  [] > app
 *    (f 1 2 3).eq 2 > @
 * }
 * @since 0.22
 */
private static class EOappThatCallsVarargsFunc extends PhDefault {
    public EOappThatCallsVarargsFunc(Phi sigma) {
        super(sigma);
        this.add(
            "φ",
            new AtOnce(
                new AtComposite(
                    this,
                    (rho) -> {
                        Phi fvar = new PhCopy(new Fvarargs(rho));
                        Phi arr = new EOarray(rho);
                        Phi[] values = new Phi[3];
                        Phi value1 = new EOint(rho);
                        Phi value_a1 = new PhWith(value1, "Δ", new Data.Value<>(1L));
                        values[0] = value_a1;
                        Phi value2 = new EOint(rho);
                        Phi value_a2 = new PhWith(value2, "Δ", new Data.Value<>(2L));
                        values[1] = value_a2;
                        Phi value3 = new EOint(rho);
                        Phi value_a3 = new PhWith(value3, "Δ", new Data.Value<>(3L));
                        values[2] = value_a3;
                        Phi arr_a = new PhWith(arr, "Δ", new Data.Value<>(values));
                        fvar = new PhWith(fvar, 0, arr_a);
                        return new PhWith(
                            new PhCopy(new PhMethod(fvar, "eq")), 0, new Data.ToPhi(2L)
                        );
                    }
                )
            )
        );
    }
}
```
It works also.

**Comment by yegor256** [comment]
@baudoliver7 we don't know during Java code generation what is the "type" of the argument: is it "vararg" or just an "int".

**Comment by baudoliver7** [comment]
@yegor256 You are right. Currently we are not able to know it. So I will introduce this feature :-)

**Comment by baudoliver7** [comment]
@yegor256 Not to know the type of argument, but just to know if it is a simple argument or a `vararg`. That's all we need to know to fix this ticket :)

**Comment by yegor256** [comment]
@baudoliver7 it's not possible. The sources of the object may not be available for us:

```
+alias org.eolang.txt.sprint

sprintf "%d %d" 1 2
```

Here, you don't know that the second argument of `sprintf` is vararg. The sources of `sprintf` are not available.

**Comment by baudoliver7** [comment]
@yegor256 Ok, we will discuss that in the PR, the time for me to express my idea of how to know it.
