### ISSUE TITLE
Duplication between Param & Dataized

### ISSUE THREAD

**Issue by andreoss** [objectionary/eo#544]
`Param` & `Dataized` & `Data.ToPhi` do similar operations
`Dataized` almost not used directly.
`ToPhi` always consumes results of `Param`
Proposal:
1) Join `Param` and `Dataized`
2) Make `Dataized` implement `Phi` as a smart-class with extra methods
So instead of 
```
new Data.ToPhi(new Dataized(...).take(Long.class) + 1)
```
we could write
```
new DataizedPhi(phi).as(Long.class).apply(x -> x + 1)
```

**Comment by yegor256** [comment]
@andreoss I added some explanation at bff11216

**Comment by volodya-lombrozo** [comment]
@yegor256 Are we going to continue here?

**Comment by yegor256** [comment]
@andreoss I'm closing this, since it's pretty debatable and we are pretty stable in this part of the code
