### ISSUE TITLE
redirect JUL calls to SLF4J only in eo-runtime

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#554]
In #553 I just deleted `EoTest`, which we added earlier in #500. It was a wrong idea: we should not make our unit tests use SLF4J by default. We should configure ONLY eo-runtime module to catch JUL calls our code makes and forward them to SLF4J.

**Comment by yegor256** [comment]
@andreoss can you fix this somehow?

**Comment by yegor256** [comment]
@mximp maybe you can also help?

**Comment by yegor256** [comment]
@mximp we want to keep eo-runtime completely dependency-free. JUL is part of JDK, that's why we use it.

**Comment by mximp** [comment]
@yegor256 all is done in this task

**Comment by yegor256** [comment]
@mximp thanks!
