### ISSUE TITLE
RemoteObjectionary.java:59-62: Resolve abbreviated hash...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#562]
The puzzle `490-82991e51` from #490 has to be resolved: 

https://github.com/cqfn/eo/blob/16f840437832445f7b8602b6e63291a07f1feb84/eo-maven-plugin/src/main/java/org/eolang/maven/RemoteObjectionary.java#L59-L62

The puzzle was created by @andreoss on 29-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by andreoss** [comment]
@yegor256 Maybe instead of doing that, we could only use tags & master?
Using sha-hashes won't help with caching a lot, `EOPATH` will end up polluted.
It's also an option to clone `objectionary` to `EOPATH`, and avoid doing http requests completely .

**Comment by yegor256** [comment]
@andreoss we rely on hashes in Objectionary, not tags. There won't be many of them -- I wouldn't worry about this. Also, if we have the problem of "too many files in the cache", we can always introduce a feature for deleting the oldest ones.

**Comment by marceloamadeu** [comment]
@yegor256 Can I try to solve this issue?
