### ISSUE TITLE
Is there a necessity of math operations like sin, cos? 

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#597]
[This ticket](https://github.com/yegor256/objectionary/issues/10) is about that there are must be wrappers for floats/ints.
I would start to create some of them (for example `sin`, `cos`, `tan`, etc)

**Comment by yegor256** [comment]
@maxonfjvipon yes, we definitely need them, but as objects of `float`, I believe:

```
3.14.sin > x
```

**Comment by yegor256** [comment]
@maxonfjvipon only float. If you want to calculate a sin of an int, you do this:

```
42.as-float.sin
```

Why not a standalone object? Because the only "type" of its first argument is `float`. That's why we ship it together with `float`.

**Comment by yegor256** [comment]
@maxonfjvipon let's add `ln` and `log`?

**Comment by maxonfjvipon** [comment]
> @maxonfjvipon let's add `ln` and `log`?

No problem. What about `tan` (sin/cos), `ctan`(1/tan)?

**Comment by yegor256** [comment]
@maxonfjvipon yes, `tan`/`ctan` are good candidates, but I believe they can be implemented in pure EO, without Java. right?

**Comment by maxonfjvipon** [comment]
@yegor256 definitely yes

**Comment by yegor256** [comment]
@maxonfjvipon like this (to avoid division by zero):

```
if.
  a.eq 0
  []
  42.div a
```

Here, we either return `[]` or divide 42 by `a`. Returning `[]` means an errors, since any attempt to dataize it will lead to exception. You can add a message to it:

```
if.
  a.eq 0
  []
    "You can't divide by zero" > msg
  42.div a
```

**Comment by maxonfjvipon** [comment]
@yegor256 there are some questions about trigonometry:
1. According to trigonometry circle, `tan` of `pi/2` does not exist because lines are parallel
1. In Java `tan` of `pi/2` exists and it equals to `1.633123935319537E16` (which `Integer.MAX_VALUE`) and there is no any exceptions
1. Same story about `ctan`
1. If we will define `tan` as `sin/cos` t  
 
So, what I'm gonna do in that case? Should EO behave like Java?  
And one more: what about `pi` number? In trigonometry `pi` and `n*pi/2, (n∈{-∞;+∞})` are kind of constants. And if we do in java `Math.PI / 2` we get `1.5707963267948966` which is not really `pi/2` because `pi` has infinite amount of digits.
So, what's your thoughts about it? Mb EO should have kind of constant object `pi` with specific accuracy? Then we somehow would define `n*pi/2, (n∈{-∞;+∞})` objects and then we would create correct checking for `tan` and `ctan`
![image](https://user-images.githubusercontent.com/37025995/160289875-69b8d252-726f-48d2-84e8-d13a7c014d1b.png)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/37025995/160289906-0d7dfaca-2b9d-48da-a460-afbd78596761.png">

**Comment by yegor256** [comment]
@maxonfjvipon I suggest we introduce `org.eolang.math.nan` object, as per [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754). Then, we'll be able to return `nan` from `tan`, when the input is `pi/2`. Also, I agree with you, let's create object `org.eolang.math.pi`.

**Comment by yegor256** [comment]
@maxonfjvipon also, maybe we should make another object `angle`, where all `sin`, `cos`, `tan`, etc. methods will move? Then, we use it like this:

```
+alias org.eolang.math.angle
+alias org.eolang.math.pi

tan.
  angle
    pi.div 2
```

**Comment by maxonfjvipon** [comment]
> @maxonfjvipon I suggest we introduce `org.eolang.math.nan` object, as per [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754). Then, we'll be able to return `nan` from `tan`, when the input is `pi/2`. Also, I agree with you, let's create object `org.eolang.math.pi` (maybe also `org.eolang.math.e`). I would define `nan` as such:
> 
> 
> 
> ```
> 
> +package org.eolang.math
> 
> 
> 
> [] > nan
> 
>   1.633123E16 > @
> 
>   [x] > add
> 
>     []
> 
>       msg > "You can't add to NaN"
> 
>   # and other methods too...
> 
> ```

I like the idea about `nan` but should it be a decorator of `1.633123E16`? `Not a number` is a decorator of big number. Or it's just for making it behave like float?

**Comment by yegor256** [comment]
@maxonfjvipon indeed, `nan` has to "be" a `float`, but with some behavior changed. That's why the decoration.

**Comment by yegor256** [comment]
@maxonfjvipon I'm closing this one in favor of https://github.com/maxonfjvipon/eo-math
