### ISSUE TITLE
Different XMIR outputs for equivalent EO code: priority of SPACE is higher than of DOT in ANTLR grammar

### ISSUE THREAD

**Issue by nikololiahim** [objectionary/eo#614]
## Description
There are 3 files. 
`horizontal.eo`
```
[self] > a
  self.m self self.state y > @
```
`vertical.eo`
```
[self] > a
  self.m > @
    self
    self.state
    y
```
`horizontal_parenthesized.eo`
```
[self] > a
  self.m self (self.state) y > @
```

They are supposed to be equivalent, however they produce (what I think are) incorrect outputs when run through EO parser:
1. `horizontal.xml`
```xml
<objects>
    <o line="1" name="a" pos="0">
       <o line="1" name="self" pos="1"/>
       <o base="self" line="2" pos="2"/>
       <o base=".m" line="2" method="">
          <o base="self" line="2" pos="9"/>
          <o base="self" line="2" pos="14"/>
       </o>
       <o base=".state" line="2" method="" name="@">
          <o base="y" line="2" pos="25"/>
       </o>
    </o>
 </objects>
```
The XMIR corresponds (I think?) to the following EO code:
```
[self] > a
  self
  self.m self
  y.state > @
```
2. `vertical.xml`
```xml
<objects>
    <o line="1" name="a" pos="0">
       <o line="1" name="self" pos="1"/>
       <o base="self" line="2" pos="2"/>
       <o base=".m" line="2" method="" name="@">
          <o base="self" line="3" pos="4"/>
          <o base="self" line="4" pos="4"/>
          <o base=".state" line="4" method=""/>
          <o base="y" line="5" pos="4"/>
       </o>
    </o>
 </objects>
```
This is closer, but still not correct:
```
[self] > a
  self
  self.m > @
    self
    .state # ???
    y 
```
3. `horizontal_parenthesized.xml`
```xml
<objects>
    <o line="1" name="a" pos="0">
       <o line="1" name="self" pos="1"/>
       <o base="self" line="2" pos="2"/>
       <o base=".m" line="2" method="" name="@">
          <o base="self" line="2" pos="9"/>
          <o base="self" line="2" pos="15"/>
          <o base=".state" line="2" method=""/>
          <o base="y" line="2" pos="27"/>
       </o>
    </o>
 </objects>
```
Other than line numbers, The same as `vertical.xml`.

## Expected Output
I think the expected output should be (omitted some `pos` and `line` attrubutes for brevity):
```xml
<objects>
      <o line="1" name="a" pos="0">
         <o line="1" name="self" pos="1"/>
         <o base=".m" name="@">
            <o base="self"></o>
            <o base="self"></o>
            <o base=".state">
               <o base="self"></o>
            </o>
            <o base="y"></o>
         </o>
      </o>
   </objects>
```

## Notes
I think the problem here is that the precedence of application is higher than the precedence of the attribute access (`.`) operator, which is unusual and most probably not intended.

@yegor256 what do you think?

**Comment by yegor256** [comment]
@nikololiahim this code

```
[self] > a
  self.m self self.state y > @
```

reads as

```
[self] > a
  (self.m self self).state y > @
```

I do agree that it doesn't look usual... let's change this to:

```
[self] > a
  self.m self (self.state) y > @
```

you are welcome to submit a PR. can you?

**Comment by nikololiahim** [comment]
@yegor256 I can try

**Comment by yegor256** [comment]
@Graur please, try to help here

**Comment by yegor256** [comment]
@volodya-lombrozo this is a pretty complex problem, but very important. Please, try to help.

**Comment by yegor256** [comment]
@volodya-lombrozo the problem is that our ANTLR grammar treats SPACE as a token with higher priority than DOT. That's why:

```
a b.c
```

is read as

```
(a b).c
```

First, it reads SPACE and then the DOT. I believe, if we change somehow the priority of SPACE, it will read it right:

```
a (b.c)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.12`

**Comment by yegor256** [comment]
@volodya-lombrozo can you please take a look? Maybe you can fix the code to get rid of the warnings in `master` branch?

**Comment by volodya-lombrozo** [comment]
@yegor256 ok, I'll check
