### ISSUE TITLE
How to implement new classes from Java?

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#620]
I'm trying to connect a new class from java (HashMap). But when I use the PhNamed function, the third argument must be of Phi type, how to bring the new class to Phi type?

Here is the code where I try to do this, but I can't use Data.ToPhi(...) because inside this method checks if our type is a primitive.

```
public EOcreate_map(final Phi sigma) {
        super(sigma);
        this.add("φ", new AtComposite(this, rho -> {
            return new PhWith(
                    new EOmap(rho), "m",
                    // this is a temporary decision, in the future I will use HashMap
                    <Phi should be here>
            );
        }));
    }
```

Are there ways around this?

**Comment by EugeneDar** [comment]
Yes, you're right. I'll add a few more details.

The code below does compile.
```
return new PhWith(
        new EOmap(rho), "m",
        new Data.ToPhi(new HashMap<>())
);
```

But, if you want to get the data from your object (map.eo in my case), this code doesn't compile.
```
this.add("φ", new AtComposite(this, rho -> {
    final HashMap hashMap = new Param(rho).strong(HashMap.class);
    return new PhWith(
            new EOmap(rho), 0,
            new Data.ToPhi(hashMap)
    );
}));
```

**Comment by yegor256** [comment]
@EugeneDar do you still need a solution here or we can close this ticket?
