### ISSUE TITLE
PullMojo.java:41-45: Add a parameter to bypass/overwrite...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#624]
The puzzle `561-386b5824` from #561 has to be resolved: 

https://github.com/objectionary/eo/blob/fc50206199f6755fa41df9e6df198127ddf10a09/eo-maven-plugin/src/main/java/org/eolang/maven/PullMojo.java#L41-L45

The puzzle was created by @yegor256 on 09-May-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp please help

**Comment by 0pdd** [comment]
The puzzle `561-386b5824` has disappeared from the source code, that's why I closed this issue.
