### ISSUE TITLE
OyRemote.java:59-62: Resolve abbreviated hash to a proper...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#625]
The puzzle `490-82991e51` from #490 has to be resolved: 

https://github.com/objectionary/eo/blob/fc50206199f6755fa41df9e6df198127ddf10a09/eo-maven-plugin/src/main/java/org/eolang/maven/OyRemote.java#L59-L62

The puzzle was created by @yegor256 on 09-May-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@MCJOHN974 try to fix this one

**Comment by MCJOHN974** [comment]
@yegor256 doed it mean i should leave unchanged this constant url, and find full hash via this url and abbreviated hash ?

**Comment by MCJOHN974** [comment]
@yegor256 can you explain please what I should do. Have I understand correctly in comment above?

**Comment by yegor256** [comment]
@MCJOHN974 let's just check that the hash provided is either short Git hash or a long one, according to their standards. If not, throw an exception.

**Comment by MCJOHN974** [comment]
@yegor256 thanks, now it becames clear. But what I should do with the ```url``` field? Just left it uninitialized?

**Comment by MCJOHN974** [comment]
@yegor256 sorry. ```OyRemote``` objects have ```address``` field. Arguments of this constructor provides no information about this field. I should left it unchanged, right?

**Comment by yegor256** [comment]
@mximp can you help?

**Comment by yegor256** [comment]
@yasamprom please help

**Comment by 0pdd** [comment]
The puzzle `490-82991e51` has disappeared from the source code, that's why I closed this issue.
