### ISSUE TITLE
array.equal object needed

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#628]
Do we need to compare arrays?

e.g.
```
[] > two-arrays
  eq. > @
    * 1 2 3
    * 1 2 3
```

I want to add  `[] > eq` to `array.eo`

**Comment by yegor256** [comment]
@Graur good idea, let's add it. You are welcome to submit a PR

**Comment by Graur** [comment]
@yegor256  I will do it

**Comment by yegor256** [comment]
@Graur I think your `eq` method should just assume that the argument provided is an array. what happens if it's not, should not bother you.

**Comment by Graur** [comment]
done by #647
