### ISSUE TITLE
Can't implement eo methods in java

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#633]
When I try to implement some eo method in java code, I get an error.

For example if I create a function is-true for bool.eo, I get an error when I implement the function in the java code (EObool$EOis_true.java). If I implement everything only in eo, there is no error.

This may have happened after the last kernel update in the main project repository. If I am wrong, please correct me.

**Comment by yegor256** [comment]
@EugeneDar what is the error? Can you post stacktrace here please?

**Comment by EugeneDar** [comment]
@yegor256 this problem is similar to the one @proxzi wrote in https://github.com/objectionary/eo/pull/630.

**Comment by EugeneDar** [comment]
stacktrace is here https://pastebin.com/QJ8NTCQs

**Comment by Graur** [comment]
@EugeneDar  I've dot the same issue.

I think the main reason is in the SnippetTest.java. According to it's description:

```
 * Integration test for simple snippets.
 *
 * This test will/may fail if you change something in {@code to-java.xsl}
 * or some other place where Java sources are generated. This happens
 * because this test relies on {@code eo-runtime.jar}, which it finds in your local
 * Maven repository. This file is supposed to be generated by a previous run
 * of Maven, but will not exist at the first run. Thus, when changes are made
 * it is recommended to disable this test. Then, when new {@code eo-runtime.jar} is
 * released, you enable this test again.
 * 
 ```

So, @EugeneDar , I think if you add `@Disabled` annotation above this test, it could solve current issue.

Or above method name, e.g.:
```
    @Disabled
    @ParameterizedTest
    @MethodSource("yamlSnippets")
    @SuppressWarnings("unchecked")
    public void testFullRun(final String yml) throws Exception {

**Comment by proxzi** [comment]
@Graur This solves the problem, but is it the right thing to do?

**Comment by EugeneDar** [comment]
@yegor256 can I use Graur's idea to solve this problem?

**Comment by Graur** [comment]
I think it's like a defense mechanism. But you better ask @yegor256 about it

**Comment by yegor256** [comment]
@proxzi @Graur yes, you should disable the test by adding `@Disabled` annotation to the class
