### ISSUE TITLE
cage.is-empty error

### ISSUE THREAD

**Issue by proxzi** [objectionary/eo#635]
I have a problem with checking for is-empty
my code:
```
[] > test-cage
  cage > a
  seq > @
    a.is-empty
    TRUE

```
i get this error:
`EOtest_cageTest.testWorks:41->PhDefault.attr:227->PhDefault.attr:226 » ClassCast
`

**Comment by yegor256** [comment]
@proxzi there is no such attribute as `is-empty` in `cage`, see: https://github.com/objectionary/home/blob/master/objects/org/eolang/gray/cage.eo
