### ISSUE TITLE
to change the behavior of the EO junit test to provide return text in addition to FALSE value

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#637]
It would be very convenient for[ eo-hamcrest](https://github.com/Graur/eo-hamcrest) to make it possible in tests to return text, in addition to the value of `TRUE` or `FALSE`.

I mean, if you are trying to run this test:
```
+package org.eolang.smth
+junit

[] > test-case
  if. > @
    5.eq 4
    TRUE
    "readable message"
```
You will get the class cast exception output.
And i suggest output like this:  `readable message`, and then return `FALSE`

**Comment by yegor256** [comment]
@Graur you can submit a PR with this change. Should be pretty straight forward, I believe.

**Comment by Graur** [comment]
I decided  to call Assertions.fail() method, because we don't need to return false and message simultaneously.
