### ISSUE TITLE
array.append bug

### ISSUE THREAD

**Issue by proxzi** [objectionary/eo#639]
if i write like this:

```
[args...] > arr
  args.append "hi" > @
```
or like this:
```
[args...] > arr
  seq > @
    args.append "hi"
```
it works.

but if i write like this:
```
[args...] > arr
  seq > @
    args.append "hi" > tmp
    tmp
```
this doesn't work.

**Comment by yegor256** [comment]
@proxzi what is the error you are getting?

**Comment by proxzi** [comment]
@yegor256 there is no error. Just endless waiting.

**Comment by yegor256** [comment]
@proxzi I tried to reproduce the bug in a test, but it passes: 6f0e26b8 please, suggest a better test.

**Comment by proxzi** [comment]
@yegor256 I'm expecting an array, not a boolean, because the documentation says that append returns a new array with the element added, which emphasizes the immutability of this array
<img width="401" alt="Снимок экрана 2022-05-20 в 16 50 09" src="https://user-images.githubusercontent.com/33073543/169542270-c63847fd-565f-4e3c-978b-18b03e763883.png">
.
