### ISSUE TITLE
RegisterMojo.java:80-85: Here, the "property" attribute...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#640]
The puzzle `636-57a3ebdc` from #636 has to be resolved: 

https://github.com/objectionary/eo/blob/59079f6a983651efc77280ec322a1a011a92b936/eo-maven-plugin/src/main/java/org/eolang/maven/RegisterMojo.java#L80-L85

The puzzle was created by @yegor256 on 16-May-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp can you try?

**Comment by mximp** [comment]
@yegor256 how do you expect to pass a set of values via command-line props?
Seems there is no way to do this: 
https://stackoverflow.com/questions/7351533/set-multiple-system-properties-java-command-line

**Comment by yegor256** [comment]
@mximp other params I pass with `-D` flag, and they work. This one doesn't work. But it should.

**Comment by mximp** [comment]
@yegor256 In your example `sourceDir` is not a collection, it's a `File`. 
I checked (Surefire Plugin sources)[https://github.com/apache/maven-surefire/blob/0e5de8f9f1351c6e88c31cff99fb7600e86ffe07/maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java#L212] as an example of such properties: 
```
@Parameter( property = "surefire.includes" )
// TODO use regex for fully qualified class names in 3.0 and change the filtering abilities
private List<String> includes;
```
It uses `property` argument and defaults are defined explicitly in the code:
```
@Override
protected String[] getDefaultIncludes()
{
    return new String[]{ "**/Test*.java", "**/*Test.java", "**/*Tests.java", "**/*TestCase.java" };
}

if ( asScanList && includes.isEmpty() )
{
    addAll( includes, getDefaultIncludes() );
}
```
And I believe the intention is to set this property within `<configuration>` tag for the plugin - not `-D` parameters.
Maybe we can do the same way?

**Comment by yegor256** [comment]
@mximp so, it's impossible to set such params from command line? If so, let's add a comment about this to our code base and remove this TODO puzzle, and that's it.

**Comment by mximp** [comment]
Closing as resolved
