### ISSUE TITLE
int.mod replace with EO code

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#641]
At the moment `int.mod` attribute is an atom. I believe we can implement it in EO code, instead of Java. Let's try.

**Comment by yegor256** [comment]
@Graur can you try to help?

**Comment by Graur** [comment]
@yegor256 Sure, I will do it

**Comment by Graur** [comment]
Do we need to implement this function in Java way or in more math way?

e.g. in Java: `-5 % 3` return `-2`
```
in Python: `-5 % 3` return `1`

Right now we use the first way.

**Comment by yegor256** [comment]
@Graur let's do the Java way

**Comment by Graur** [comment]
@yegor256 I think we can close this issue, because #657 was merged. Can you help to do it? I don't have such button.

**Comment by yegor256** [comment]
@Graur read this: https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html
