### ISSUE TITLE
int.pow implement in EO

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#642]
At the moment `int.pow` is implemented in Java as an atom. I believe, we can implement it in EO.

**Comment by yegor256** [comment]
@Graur can you try to help?

**Comment by Graur** [comment]
@yegor256 Sure, I will do it

**Comment by Graur** [comment]
@yegor256 Do we need to implement the entire Math.pow() function? Or without much optimisation and then iteratively adding new features?

**Comment by yegor256** [comment]
@Graur it's always better to go iteratively, leaving some PDD puzzles where necessary

**Comment by Graur** [comment]
I decided to choose the `(long) Math.pow()` implementation way :
if exponent is negative, return 0: `(20.pow -1).eq 0`
if exponent is zero, return 1: `(-20.pow 0).eq 1`

**Comment by Graur** [comment]
@yegor256 How do you think, maybe we need just delegate computing `int.pow` to the `float.pow` object ? Something like this:

```
[] > int
...
  [x] > pow
    as-int. > @ 
      pow.
        ^.as-float
        x.as-float
```

**Comment by yegor256** [comment]
@Graur this is a good idea, I don't mind at all

**Comment by yegor256** [comment]
@Graur thanks!
