### ISSUE TITLE
get rid of CHAR object

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#643]
Let's get rid of `char` object:

  * `'\t'` and `'\n'` and `'\07'` should mean object `bytes` of one byte
  * update `data.xsl` (remove char from there)
  * update `xmir-to-eo.xsl`
  * `"\u0123 hello"` should parse as Unicode string (it works like this now)
  * delete `string.char-at` attribute
  * delete `char.eo` file
  * delete `bytes.as-char` attribute

**Comment by yegor256** [comment]
@andreoss can you please help?

**Comment by yegor256** [comment]
@Graur you try it please

**Comment by Graur** [comment]
@yegor256 Sure, I'll do it

**Comment by Graur** [comment]
> '\t' and '\n' and '\07' should mean object bytes of one byte

@yegor256 Do you mean double quotes in `"\t"` and `"\n"` and `"\07"`? If I understood correctly, quotes `''` should be removed

**Comment by yegor256** [comment]
@Graur would be great if you fix the paper as well, in `paper/` directory. It mentions `char` object in a few places.

**Comment by Graur** [comment]
@yegor256 Yes, I missed that. Thanks!

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
