### ISSUE TITLE
array.is-empty doesn't need to be an atom

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#644]
It seems that `array.is-empty` can be implemented in EO, just by using `array.length`. Let's get rid of the atom here.

**Comment by yegor256** [comment]
@EugeneDar can you please help here?

**Comment by EugeneDar** [comment]
@yegor256 sure, I'll do it.

**Comment by yegor256** [comment]
@EugeneDar what is the status?

**Comment by EugeneDar** [comment]
@yegor256 this problem has been solved.

**Comment by yegor256** [comment]
@EugeneDar thanks!
