### ISSUE TITLE
bool.not doesn't need to be an atom

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#645]
It seems that `bool.not` can easily be implement through `bool.if`. Let's get rid of the atom here.

**Comment by yegor256** [comment]
@EugeneDar can you please help here?

**Comment by EugeneDar** [comment]
@yegor256 sure, I'll do it.

**Comment by yegor256** [comment]
@EugeneDar what is the status?

**Comment by yegor256** [comment]
@EugeneDar thanks for solving it
