### ISSUE TITLE
ClassCastException: Cannot cast org.eolang.AtPhiSensitive to EOorg.EOeolang.EOgray.AtCage

### ISSUE THREAD

**Issue by dours** [objectionary/eo#658]
This one leads to `java.lang.ClassCastException: Cannot cast org.eolang.AtPhiSensitive to EOorg.EOeolang.EOgray.AtCage`:
```
[] > test-my-array
  cage.is-empty > @
```

Also like this if you prefer
```
[] > test-my-array
  cage > value
  value.is-empty > @
```

**Comment by yegor256** [comment]
@dours should be fixed in 0.23.4, please try it out
