### ISSUE TITLE
apply eo-hamcrest to `.eo` tests

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#660]
Since [eo-hamcrest](https://github.com/objectionary/eo-hamcrest) was released (v0.1.5), we need to redo all `.eo` tests to make failed output more readable.

e.g. was:
```
[] > converts-to-string
  eq. > @
    "42"
    42.as-string
```

become:
```
[] > converts-to-string
  assert-that > @
    "42"
    $.equal-to
      42.as-string
```

**Comment by Graur** [comment]
Should I test `int.leq`:
```
[] > leq-true
  leq. > @
    -200
    -100
```
like this:
```
[] > leq-true
  assert-that > @
    leq.
      -200
      -100
    $.equal-to TRUE
```
or like this:
```
[] > leq-true
  assert-that > @
    -200
    $.any-of
      $.less-than -100
      $.equal-to -100
```
If I use `assert-that` object to test that `-200` is less than or equal to `-100`, we skip the process of testing the `int.leq` object. Otherwise we have lost the understandable output message.
@yegor256 WDYT ?

**Comment by yegor256** [comment]
@Graur in this case we should test the `leq` object, not the integer -200, that's why your first option is right.

**Comment by yegor256** [comment]
@Graur thanks!
