### ISSUE TITLE
rename array methods

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#661]
Let's rename `array.append` to `array.with`. Also, let's add `array.without x`, which should return a new array, but without the i-th element.

**Comment by yegor256** [comment]
@Graur please, help with this

**Comment by Graur** [comment]
@yegor256 Sure, I will do it. Should I implement `array.without x` by Java or by EO?

**Comment by yegor256** [comment]
@Graur good question. Let's do it in Java, since in EO it would have too many copying operations.

**Comment by yegor256** [comment]
@Graur you know... I changed my mind. Let's do it in EO. All optimizations we'll do later, inside `with` method.

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
