### ISSUE TITLE
implement array.mapi in EO

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#662]
I have a strong feeling that `array.mapi` can be implemented in EO (instead of Java), with the help of `reducei`.

**Comment by yegor256** [comment]
@Graur please, try to help

**Comment by Graur** [comment]
@yegor256 I can do it. But I have doubts about storing the array in the accumulator and calling the `array.append` object on each iteration, which uses `System.arraycopy()`. I think it will cost a lot for such operation. Or it's ok?

e.g.
```
  [f] > mapi
    ^.reducei
      *
      [a i x]
        append. > @
          a
          &.f x i
```

**Comment by yegor256** [comment]
@Graur it's OK. we should do all optimizations later inside `append`.

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
