### ISSUE TITLE
infinity numbers

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#665]
Do we need a `POSITIVE_INFINITY` (= 1.0 / 0.0) and `NEGATIVE_INFINITY` = (-1.0 / 0.0) in EO?
Also `NaN`, `max`, `min` int and float values and others constants?

**Comment by yegor256** [comment]
@Graur most probably. That's why we have this: https://github.com/objectionary/home/issues/10

**Comment by Graur** [comment]
@yegor256 Thanks! So I create this issue after `eo-math` release

**Comment by yegor256** [comment]
@Graur better report everything about math directly to eo-math repository
