### ISSUE TITLE
int.mod work incorrect

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#668]
I added new test (localy) to int-tests.eo.
```
[] > mod-1-2
  eq. > @
    1.mod 2
    1
```
Result is Failure.
@Graur, please, check it.

**Comment by Graur** [comment]
@EugeneDar Yes, you right. I will fix it.
@yegor256 please assign to me.

@EugeneDar BTW, you can write your tests in this way:
```
+alias org.eolang.hamcrest.assert-that

[] > mod-1-2
  assert-that > @
    1.mod 2
    $.equal-to 1
```

**Comment by EugeneDar** [comment]
@Graur this code also doesn't work correct?
```
[] > mod-1-2
  assert-that > @
    1.mod 2
    $.equal-to 1
```
