### ISSUE TITLE
can't we implement reducei using WHILE recursion

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#670]
Can't we get rid of Java in `reducei` and implement it with only EO. Most probably with recursion.

**Comment by yegor256** [comment]
@Graur please, try this one

**Comment by Graur** [comment]
@yegor256 Sure, I will do it

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
