### ISSUE TITLE
EOregex$EOmatch return type

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#675]
Why does `regex.match` have the `array` return type and return `matcher.groupCount()` in Java representation?

So, when I'm trying to match some word ignoring case: 
```
/word/i
.match "WORD"
.is-empty
```
I've got `FALSE`, because `groupCount()` returned the number of capturing groups in this matcher's pattern. And then when comparing the whole word, this method returned 0, according to Java docs:

> Group zero denotes the entire pattern by convention. It is not included in this count.

@yegor256 How do you think, maybe we need to return the result of `new Data.ToPhi(matcher.matches())` as `bool` value in `EOregex$EOmatch`  instead?

**Comment by yegor256** [comment]
@Graur a better option would be to include the "entire pattern" matching group into the resulting array, I believe

**Comment by Graur** [comment]
@yegor256 I've created [PR](https://github.com/objectionary/eo/pull/692) of this issue, but now I have doubts to apply these changes. Perhaps the presence of additional parentheses improves the readability of the regex. So, it's up to you.

**Comment by yegor256** [comment]
@Graur fixed?

**Comment by Graur** [comment]
@yegor256 yes, I will close it
