### ISSUE TITLE
bytes.and and bytes.or must accept vararg

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#677]
At the moment only a single argument can be applied to `bytes.and` and `bytes.or`. Let's make it possible to apply vararg, like it works for `bool.and` and `bool.or`.

**Comment by yegor256** [comment]
@MCJOHN974 please help

**Comment by Graur** [comment]
@kerelape please, take this task, the budget is 30 minutes
@mximp please, check it

**Comment by kerelape** [comment]
Shouldn't `bytes.xor` support vararg as well?

**Comment by mximp** [comment]
> Shouldn't `bytes.xor` support vararg as well?
@kerelape Indeed, it should.. Please implement.
