### ISSUE TITLE
regex atom DOTALL flag

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#678]
Why is the name of `DOTALL` flag mode in EO regex atom is `a`? (In [data.xls](https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/main/resources/org/eolang/maven/pre/data.xsl), s. 107)
According to[ Perl expression documentation](https://perldoc.perl.org/perlop#Regexp-Quote-Like-Operators) this flag should be `s`.

**Comment by yegor256** [comment]
@Graur let's fix this

**Comment by Graur** [comment]
@yegor256 I changed the regex flag. Can you tell me how I can make sure I don't break other EO based projects?
