### ISSUE TITLE
heap.malloc and heap.free implement in EO

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#684]
At the moment they are implemented in Java, which is redundant. We can easily implement them in EO.

**Comment by yegor256** [comment]
@Graur please, help us here

**Comment by Graur** [comment]
@yegor256 Sure, I will do it

**Comment by Graur** [comment]
@yegor256 Should these objects incapsulate `ram.write` and `ram.read` atoms?

**Comment by yegor256** [comment]
@Graur I'm not sure I understood the question. You will have to use `ram` object, since it's the only possible way to access random-access memory.

**Comment by Graur** [comment]
@yegor256 I decided to fix `ram` object first. According to [this](https://github.com/objectionary/on-the-origin-of-objects/blob/master/paper.tex#L357) `ram.slice` should works like this:

```
ram 1024 > r
seq
  write.
    r.slice 200 13 > s
    "Hello, world!".as-bytes
  QQ.io.stdout
    as-string.
      s.slice 0 5
```

But I still can't find a way to make the `slice` object behave like `bytes` and `ram` at the same time. Maybe we need some intermediate operation before `s.slice 0 5`, like `as-bytes`? e.g. `s.as-bytes.slice 0 5`

**Comment by yegor256** [comment]
@Graur I suggest this:

```
[size] > ram
  [position data] > write 
  [position size] > slice /ram-slice

[\rho position1 size1] > ram-slice
  [] > @ /bytes   # here you read bytes from \rho and return
  [position2 size2] > slice
  [data] > write
```

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#945](https://github.com/objectionary/eo/issues/945) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.

**Comment by Graur** [comment]
@MCJOHN974 Please, take this task. You need to get rid of `Heaps.java` , `EOheap$EOmalloc` and `EOheap$EOfree.java` and redo `heap.malloc` and `heap.free` objects by EO. I think you can start from `malloc` object and create first PR, then redo `free` object and create another one PR.

**Comment by MCJOHN974** [comment]
@Graur does heap allow two or more allocations ?
```
heap (ram 1024) > h
  seq
  h.malloc > p
  h.malloc > q
  h.free p
  h.free q
```
Is code above valid or not ?

**Comment by Graur** [comment]
@MCJOHN974 This code is valid. Moreover, we already have such test in heap-tests.eo: https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/eo/org/eolang/heap-tests.eo#L45-L54

**Comment by Graur** [comment]
@MCJOHN974 What about the progress of this task? Do you need some help?

**Comment by yegor256** [comment]
@Graur where we are with this problem?

**Comment by Graur** [comment]
@yegor256 Looks like we have no progress here
@levBagryansky Please, take care of this task

**Comment by levBagryansky** [comment]
@Graur `heap.malloc` was implemented in #1916

**Comment by Graur** [comment]
@levBagryansky Thanks!

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#unknown]() is solved here.
