### ISSUE TITLE
Show file and location in compilation errors

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#685]
For example, I'm trying to compile my project and I get this error.
The result does not provide information about the file and the location of the error. -X -e flags also don't help

![image](https://user-images.githubusercontent.com/33983579/170854168-cfe9f6ad-78ac-4168-93da-46c35182e088.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware try to run `mvn compile -e` -- you will see much more information

**Comment by IngeniariusSoftware** [comment]
@yegor256 -X -e flags also don't help

**Comment by yegor256** [comment]
@IngeniariusSoftware show what you get with `-e` flag

**Comment by IngeniariusSoftware** [comment]
@yegor256 

<pre>[<font color="#12488B"><b>INFO</b></font>] <b>---------------------&lt; </b><font color="#2AA1B3">org.eolang:c2eo-transpiler</font><b> &gt;---------------------</b>
[<font color="#12488B"><b>INFO</b></font>] <b>Building c2eo-transpiler 1.0-SNAPSHOT</b>
[<font color="#12488B"><b>INFO</b></font>] <b>--------------------------------[ jar ]---------------------------------</b>
[<font color="#12488B"><b>INFO</b></font>] 
[<font color="#12488B"><b>INFO</b></font>] <b>--- </b><font color="#26A269">maven-clean-plugin:2.5:clean</font> <b>(default-clean)</b> @ <font color="#2AA1B3">c2eo-transpiler</font><b> ---</b>
[<font color="#12488B"><b>INFO</b></font>] Deleting /home/maksim/Projects/result/target
[<font color="#12488B"><b>INFO</b></font>] 
[<font color="#12488B"><b>INFO</b></font>] <b>--- </b><font color="#26A269">eo-maven-plugin:0.22.2:register</font> <b>(default)</b> @ <font color="#2AA1B3">c2eo-transpiler</font><b> ---</b>
[<font color="#12488B"><b>INFO</b></font>] Registered 14 EO sources from ./eo to ./target/eo-foreign.csv
[<font color="#12488B"><b>INFO</b></font>] 
[<font color="#12488B"><b>INFO</b></font>] <b>--- </b><font color="#26A269">eo-maven-plugin:0.22.2:assemble</font> <b>(default)</b> @ <font color="#2AA1B3">c2eo-transpiler</font><b> ---</b>
[<font color="#12488B"><b>INFO</b></font>] 53 attributes loaded from 47 stream(s) in 84ms, 53 saved, 584 ignored: [&quot;Agent-Class&quot;, &quot;Ant-Version&quot;, &quot;Archiver-Version&quot;, &quot;Automatic-Module-Name&quot;, &quot;Bnd-LastModified&quot;, &quot;Build-Jdk&quot;, &quot;Build-Jdk-Spec&quot;, &quot;Built-By&quot;, &quot;Bundle-Copyright&quot;, &quot;Bundle-Description&quot;, &quot;Bundle-Developers&quot;, &quot;Bundle-DocURL&quot;, &quot;Bundle-License&quot;, &quot;Bundle-ManifestVersion&quot;, &quot;Bundle-Name&quot;, &quot;Bundle-RequiredExecutionEnvironment&quot;, &quot;Bundle-SCM&quot;, &quot;Bundle-SymbolicName&quot;, &quot;Bundle-Vendor&quot;, &quot;Bundle-Version&quot;, &quot;Can-Redefine-Classes&quot;, &quot;Can-Retransform-Classes&quot;, &quot;Can-Set-Native-Method-Prefix&quot;, &quot;Created-By&quot;, &quot;Dependencies&quot;, &quot;EO-Version&quot;, &quot;Eclipse-ExtensibleAPI&quot;, &quot;Eclipse-SourceReferences&quot;, &quot;Export-Package&quot;, &quot;Extension-Name&quot;, &quot;Implementation-Build&quot;, &quot;Implementation-Title&quot;, &quot;Implementation-URL&quot;, &quot;Implementation-Vendor&quot;, &quot;Implementation-Vendor-Id&quot;, &quot;Implementation-Version&quot;, &quot;Import-Package&quot;, &quot;Include-Resource&quot;, &quot;JCabi-Build&quot;, &quot;JCabi-Date&quot;, &quot;JCabi-Version&quot;, &quot;Main-Class&quot;, &quot;Manifest-Version&quot;, &quot;Multi-Release&quot;, &quot;Premain-Class&quot;, &quot;Project-Name&quot;, &quot;Require-Capability&quot;, &quot;Specification-Title&quot;, &quot;Specification-Vendor&quot;, &quot;Specification-Version&quot;, &quot;Tool&quot;, &quot;X-Compile-Source-JDK&quot;, &quot;X-Compile-Target-JDK&quot;]
[<font color="#12488B"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#12488B"><b>INFO</b></font>] <font color="#C01C28"><b>BUILD FAILURE</b></font>
[<font color="#12488B"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#12488B"><b>INFO</b></font>] Total time:  2.281 s
[<font color="#12488B"><b>INFO</b></font>] Finished at: 2022-05-30T17:48:10+03:00
[<font color="#12488B"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#C01C28"><b>ERROR</b></font>] Failed to execute goal <font color="#26A269">org.eolang:eo-maven-plugin:0.22.2:assemble</font> <b>(default)</b> on project <font color="#2AA1B3">c2eo-transpiler</font>: <font color="#C01C28"><b>Execution default of goal org.eolang:eo-maven-plugin:0.22.2:assemble failed: For input string: &quot;321352532432332231422343223&quot;</b></font> -&gt; <b>[Help 1]</b>
<font color="#C01C28"><b>org.apache.maven.lifecycle.LifecycleExecutionException</b></font>: <font color="#C01C28"><b>Failed to execute goal </b></font><font color="#26A269"><b>org.eolang:eo-maven-plugin:0.22.2:assemble</b></font> <b>(default)</b> on project <font color="#2AA1B3">c2eo-transpiler</font>: <font color="#C01C28"><b>Execution default of goal org.eolang:eo-maven-plugin:0.22.2:assemble failed: For input string: &quot;321352532432332231422343223&quot;</b></font>
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:215</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:156</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:148</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (<b>LifecycleModuleBuilder.java:117</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (<b>LifecycleModuleBuilder.java:81</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (<b>SingleThreadedBuilder.java:56</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleStarter.execute (<b>LifecycleStarter.java:128</b>)
    <b>at</b> org.apache.maven.DefaultMaven.doExecute (<b>DefaultMaven.java:305</b>)
    <b>at</b> org.apache.maven.DefaultMaven.doExecute (<b>DefaultMaven.java:192</b>)
    <b>at</b> org.apache.maven.DefaultMaven.execute (<b>DefaultMaven.java:105</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.execute (<b>MavenCli.java:957</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.doMain (<b>MavenCli.java:289</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.main (<b>MavenCli.java:193</b>)
    <b>at</b> jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (<b>Native Method</b>)
    <b>at</b> jdk.internal.reflect.NativeMethodAccessorImpl.invoke (<b>NativeMethodAccessorImpl.java:62</b>)
    <b>at</b> jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (<b>DelegatingMethodAccessorImpl.java:43</b>)
    <b>at</b> java.lang.reflect.Method.invoke (<b>Method.java:566</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (<b>Launcher.java:282</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.launch (<b>Launcher.java:225</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (<b>Launcher.java:406</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.main (<b>Launcher.java:347</b>)
<b>Caused by</b>: org.apache.maven.plugin.PluginExecutionException: <font color="#C01C28"><b>Execution default of goal org.eolang:eo-maven-plugin:0.22.2:assemble failed: For input string: &quot;321352532432332231422343223&quot;</b></font>
    <b>at</b> org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (<b>DefaultBuildPluginManager.java:148</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:210</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:156</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:148</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (<b>LifecycleModuleBuilder.java:117</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (<b>LifecycleModuleBuilder.java:81</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (<b>SingleThreadedBuilder.java:56</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleStarter.execute (<b>LifecycleStarter.java:128</b>)
    <b>at</b> org.apache.maven.DefaultMaven.doExecute (<b>DefaultMaven.java:305</b>)
    <b>at</b> org.apache.maven.DefaultMaven.doExecute (<b>DefaultMaven.java:192</b>)
    <b>at</b> org.apache.maven.DefaultMaven.execute (<b>DefaultMaven.java:105</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.execute (<b>MavenCli.java:957</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.doMain (<b>MavenCli.java:289</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.main (<b>MavenCli.java:193</b>)
    <b>at</b> jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (<b>Native Method</b>)
    <b>at</b> jdk.internal.reflect.NativeMethodAccessorImpl.invoke (<b>NativeMethodAccessorImpl.java:62</b>)
    <b>at</b> jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (<b>DelegatingMethodAccessorImpl.java:43</b>)
    <b>at</b> java.lang.reflect.Method.invoke (<b>Method.java:566</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (<b>Launcher.java:282</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.launch (<b>Launcher.java:225</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (<b>Launcher.java:406</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.main (<b>Launcher.java:347</b>)
<b>Caused by</b>: java.lang.NumberFormatException: <font color="#C01C28"><b>For input string: &quot;321352532432332231422343223&quot;</b></font>
    <b>at</b> java.lang.NumberFormatException.forInputString (<b>NumberFormatException.java:65</b>)
    <b>at</b> java.lang.Long.parseLong (<b>Long.java:692</b>)
    <b>at</b> java.lang.Long.parseLong (<b>Long.java:817</b>)
    <b>at</b> org.eolang.parser.XeListener.enterData (<b>XeListener.java:362</b>)
    <b>at</b> org.eolang.parser.ProgramParser$DataContext.enterRule (<b>ProgramParser.java:1557</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule (<b>ParseTreeWalker.java:50</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:33</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.antlr.v4.runtime.tree.ParseTreeWalker.walk (<b>ParseTreeWalker.java:36</b>)
    <b>at</b> org.eolang.parser.Syntax.parse (<b>Syntax.java:120</b>)
    <b>at</b> org.eolang.maven.ParseMojo.parse (<b>ParseMojo.java:108</b>)
    <b>at</b> org.eolang.maven.ParseMojo.exec (<b>ParseMojo.java:87</b>)
    <b>at</b> org.eolang.maven.SafeMojo.execute (<b>SafeMojo.java:104</b>)
    <b>at</b> org.eolang.maven.Moja.execute (<b>Moja.java:121</b>)
    <b>at</b> org.eolang.maven.AssembleMojo.exec (<b>AssembleMojo.java:181</b>)
    <b>at</b> org.eolang.maven.SafeMojo.execute (<b>SafeMojo.java:104</b>)
    <b>at</b> org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (<b>DefaultBuildPluginManager.java:137</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:210</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:156</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.MojoExecutor.execute (<b>MojoExecutor.java:148</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (<b>LifecycleModuleBuilder.java:117</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (<b>LifecycleModuleBuilder.java:81</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (<b>SingleThreadedBuilder.java:56</b>)
    <b>at</b> org.apache.maven.lifecycle.internal.LifecycleStarter.execute (<b>LifecycleStarter.java:128</b>)
    <b>at</b> org.apache.maven.DefaultMaven.doExecute (<b>DefaultMaven.java:305</b>)
    <b>at</b> org.apache.maven.DefaultMaven.doExecute (<b>DefaultMaven.java:192</b>)
    <b>at</b> org.apache.maven.DefaultMaven.execute (<b>DefaultMaven.java:105</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.execute (<b>MavenCli.java:957</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.doMain (<b>MavenCli.java:289</b>)
    <b>at</b> org.apache.maven.cli.MavenCli.main (<b>MavenCli.java:193</b>)
    <b>at</b> jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (<b>Native Method</b>)
    <b>at</b> jdk.internal.reflect.NativeMethodAccessorImpl.invoke (<b>NativeMethodAccessorImpl.java:62</b>)
    <b>at</b> jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (<b>DelegatingMethodAccessorImpl.java:43</b>)
    <b>at</b> java.lang.reflect.Method.invoke (<b>Method.java:566</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (<b>Launcher.java:282</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.launch (<b>Launcher.java:225</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (<b>Launcher.java:406</b>)
    <b>at</b> org.codehaus.plexus.classworlds.launcher.Launcher.main (<b>Launcher.java:347</b>)
[<font color="#C01C28"><b>ERROR</b></font>] 
[<font color="#C01C28"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#C01C28"><b>ERROR</b></font>] 
[<font color="#C01C28"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#C01C28"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
<span style="background-color:#12488B"><font color="#E4E4E4"> </font></span><span style="background-color:#12488B"><font color="#EEEEEE"><b>~</b></font></span><span style="background-color:#12488B"><font color="#E4E4E4">/Projects/</font></span><span style="background-color:#12488B"><font color="#EEEEEE"><b>result</b></font></span><span style="background-color:#12488B"><font color="#E4E4E4"> </font></span>      </pre>

**Comment by yegor256** [comment]
@Graur can you fix this please? I think `ParseMojo.parse` should catch `RuntimeException` and re-throw it with a message that includes the name of the file.

**Comment by Graur** [comment]
@yegor256 Is it a good way to catch `RuntimeException`?

**Comment by yegor256** [comment]
@Graur yes, it's OK to catch, at the highest level of an app. This level if the highest. See: https://www.yegor256.com/2015/07/09/catch-if-cant-otherwise.html

**Comment by Graur** [comment]
@IngeniariusSoftware You can check this update by increasing the version of EO up to `0.23.6`. Please, let me know if you have any further questions

**Comment by IngeniariusSoftware** [comment]
@Graur It works, thanks
