### ISSUE TITLE
Unexpected behaviour during dataization

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#686]
Code:
```
[text] > p
  seq > @
    stdout
      text
    stdout
      "\n"

[] > class
  [] > new
    [] > this
      "THIS" > @
      memory > v
    seq > @
      this

  [this v] > constructor
    seq > @
      p "class.constructor"
      this.v.write
        v
      this

[args...] > main
  cage > o
  seq > @
    p "main"
    o.write
      class.constructor
        class.new
        4
    p
      as-string.
        o.v
```

It runs well and prints expected "main" and 4. However, during dataization of last object in `seq` I thought that would be printed also "class.constructor", but it was not. Can somebody explain why it works so?

**Comment by someilay** [comment]
@yegor256, can you help?

**Comment by yegor256** [comment]
@someilay your example is too big, try to do some home work and make it shorter, read: https://www.yegor256.com/2022/03/29/bugs-occam-razor.html

**Comment by someilay** [comment]
@yegor256, ok. What about this?
```
[] > this
  "THIS" > @
  memory > v

[this v] > init
  seq > @
    println "init"
    this.v.write
      v
    this

[args...] > main
  cage > o
  seq > @
    println "main"
    o.write
      init
        this
        4
    println
      as-string.
        o.v
```

It doesn't print "init".

**Comment by Graur** [comment]
@someilay I think it's because `cage.write` just store the object and do not dataized it. According to `cage.eo` description:

```
# This object is doing exactly the same as "memory", but allows
# you to store objects, not only data. In other words, it doesn't
# do dataization when objects are being stored.
[] > cage /?
```

**Comment by someilay** [comment]
@Graur. Last statement in `seq` is dataized as well. It prints 4, but it cannot be obtained without dataizaition of `init`. Moreover, if change name of free attribute `v` to `k` inside an `init` object, then program starts printing "init".

**Comment by Graur** [comment]
@someilay 

> @Graur. Last statement in seq is dataized as well. It prints 4, but it cannot be obtained without dataizaition of init.

If I understood your example correctly, I think it can
e.g. this test is green

```
+alias org.eolang.io.stdout
+junit

[] > test
  [x] > a
    22 > @

  eq. > @
    (a 42).x
    42
```

> Moreover, if I change name of free attribute v to k inside an init object, then program starts printing "init".

Could you provide an example?

**Comment by someilay** [comment]
@yegor256, I fixed [example](https://github.com/objectionary/eo/issues/686#issuecomment-1141111858)

**Comment by yegor256** [comment]
@someilay is `println "main"` absolutely necessary for this test? If I remove this line, the test will stop failing?

**Comment by someilay** [comment]
@yegor256, it's just for telemetry. `println` signalizes what is dataized and what is not.

**Comment by yegor256** [comment]
@someilay try to find what else we can safely remove. Reading the code of that size is hard.

**Comment by yegor256** [comment]
@someilay why do you think it's a bug? In the first example, when `init` has `v` attribute, `o.v` reads it directly and prints (number `4`). In the second example, `init` doesn't have `v`, that's why its attribute `@` first gets dataized, which lead to `println`. I don't see a contradiction.

**Comment by someilay** [comment]
Ok, thanks
