### ISSUE TITLE
QQ object as an alias of Q.org.eolang

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#690]
Let's make a built-in alias, which will help using standard objects in a more compact way:

```
QQ.io.stdout
  "Hello, world!"
```

instead of

```
Q.org.eolang.io.stdout
  "Hello, world!"
```

Let's not forget to update the paper in the `paper/` directory.

**Comment by yegor256** [comment]
@Graur can you try this one?

**Comment by Graur** [comment]
@yegor256 Should I remove `Q` object and add `QQ` instead? Or just add `QQ` and leave `Q` as is?

**Comment by yegor256** [comment]
@Graur both of them should exist. `QQ` should just point to `Q.org.eolang`

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions

**Comment by yegor256** [comment]
@Graur thanks!
