### ISSUE TITLE
Need a flag for skiping invalid eo files during compilation

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#694]
Let's suppose I have two eo files: first is valid and runnable and second is invalid, non-compiliable. If I will try to execute `mvn clean compile`, it would fail due to invalid file. Therefore, I possibly cannot run valid one. It would be great if there will be special flag for compiling that allows to skip invalid files and handle valid ones.

**Comment by someilay** [comment]
@yegor256. Can you implement this?

**Comment by yegor256** [comment]
@Graur this is getting more urgent. can you please fix?

**Comment by Graur** [comment]
@yegor256 Sure. Should we run it like a part of configuration (similar to `hash`)? Or like a profile `mvn clean compile -DfailOnError=false` ? Or maybe another approach?

**Comment by Graur** [comment]
@someilay I think you can try it in `0.23.15` just like this:
```
<project>
  [...]
  <build>
    [...]
    <plugins>
      [...]
      <plugin>
        <groupId>org.eolang</groupId>
        <artifactId>eo-maven-plugin</artifactId>
        <configuration>
          <failOnError>false</failOnError>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

When the next release will be published, this feature will be more stable.

**Comment by yegor256** [comment]
@someilay what's up with this? let's close?

**Comment by volodya-lombrozo** [comment]
@yegor256 @someilay Why do we need to compile "invalid, non-compiliable" files at all? It's seems logical to stop entire compiling process if we have something broken. What I'm missing here?

**Comment by yegor256** [comment]
@volodya-lombrozo sometimes a user may want to compile a collection of 1000 files. The user doesn't want to stop after the first error. Instead, the user wants to get a full report of all errors, after which the decision will be made: how many of them to fix, when and who will do it.
