### ISSUE TITLE
Multiple dataization of the same object

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#695]
Code:
```
[] > this
  "THIS" > @
  memory > v

[this global] > constructor
  seq > @
    this.v.write
      global
    global.write
      global.add
        1
    this

[args...] > main
  memory > g
  cage > a
  seq > @
    g.write
      0
    a.write
      constructor  # put g in this.v, increment g 
        this
        g
    a
    ...  # repeats n-th times
    a
    println a.v
```

It seems that `constructor` object is dataized `n + 1` times, because program prints `n`.
@yegor256. Is it a bug or a feature?

**Comment by yegor256** [comment]
@someilay I'm not sure about `n+1`, but indeed every tie you say `a` inside `seq`, `constructor.@` gets dataized.

**Comment by someilay** [comment]
@yegor256, Ok. What about `println a.v`? What is dataized? `constructor.v` or `constructor.@`?

**Comment by someilay** [comment]
@yegor256. Just for clarifying. Does it skip dataization of `constructor.@` when `constructor.@.v` is being dataized?

**Comment by yegor256** [comment]
@someilay it's impossible to get `a.@.v` without dataizing `a.@`. How can we know where to get `v` if we don't dataize `@` first?

**Comment by someilay** [comment]
@yegor256. Ok. If dataization of `constructor.@.v` implies dataization of `constructor.@`, why does code bellow prints 0 instead of 1?
Code:
```
[] > this
  "THIS" > @
  memory > v

[this global] > constructor
  seq > @
    this.v.write
      global
    global.write
      global.add
        1
    this

[args...] > main
  memory > g
  cage > a
  seq > @
    g.write
      0
    a.write
      constructor  # put g in this.v, increment g 
        this
        g
    a.v
    println a.v
```
It seems that `constructor` should be dataized twice. So `g` would be incremented also two times.

**Comment by yegor256** [comment]
@someilay your example is too large for such an educating question :) Make a smaller one and I will try to answer.

**Comment by someilay** [comment]
> @someilay Could you add `println a.v` one more time at the end of `seq` object in `main` ? It would be printed `1` or `2` at the end?

@Graur. It prints `0` again.

**Comment by someilay** [comment]
> @someilay your example is too large for such an educating question :) Make a smaller one and I will try to answer.

@yegor256. It's minimal example for reproducing such behaviour.

**Comment by someilay** [comment]
@yegor256. The idea of example is that internal attribute of object depends from global state and durring its' initialization global state changes. It's also important to mention that it should be used `cage`, because dataization `write` allows to store object without its' own datatization. With those constraints it's imposible to create short example. Maybe It can be cut for few lines,but it is a limit.

**Comment by yegor256** [comment]
@someilay let's close this one as a duplicate
