### ISSUE TITLE
Why the regexp for aliases is SO strict? Shouldn't it be the same as for other identifiers?

### ISSUE THREAD

**Issue by dours** [objectionary/eo#699]
Here: https://github.com/objectionary/eo/blob/a56537b3a1b102dc5e1b0be18627c9212fcea7f0/eo-parser/src/main/resources/org/eolang/parser/errors/broken-aliases.xsl#L31
For example, it does not allow to use `pyInt` as an external identifier

**Comment by dours** [comment]
because, say, `+alias pyInt preface.pyInt` does not match, as far as I understand. And it definityle generates the "broken alias" error

**Comment by yegor256** [comment]
@dours I agree, it's a bug, thanks for reporting

**Comment by Graur** [comment]
@yegor256 Sure, I'll fix this

**Comment by Graur** [comment]
@yegor256 Can identifiers be only digits? Like: `+alias 0 1.2.3`.
Or can they contain digits? Like: `+alias myAlias1 org.eolang.smthng`

**Comment by yegor256** [comment]
@Graur check this: https://github.com/objectionary/eo/blob/master/paper/sections/syntax.tex#L20-L27

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.6`

**Comment by Graur** [comment]
@dours You can check this update by increasing the version of EO up to `0.23.6`. Please, let me know if you have any further questions

**Comment by yegor256** [comment]
@dours I believe it's fixed, I'm closing the ticket. If you still see the problem, please submit a new ticket.
