### ISSUE TITLE
error.eo is redundant

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#702]
Let's get rid of `error.eo`. It's not actively used anyway.

**Comment by yegor256** [comment]
@Graur please help

**Comment by yegor256** [comment]
@Graur the second option. we should NOT throw Java exceptions. instead, we should return something like `EOerror`

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
