### ISSUE TITLE
array.get must not throw RuntimeException

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#703]
When an element of an array is not found by `get` it should not throw Java `RuntimeException`, but instead should return an error object, with `msg` attribute set to the error message.

**Comment by yegor256** [comment]
@Graur please, fix this one

**Comment by Graur** [comment]
@yegor256 Sure. I'll do it. Could you describe, please: what should user do, if he got `EOerror` instead of expected object?

**Comment by yegor256** [comment]
@Graur nothing. The user should continue working with the object. The runtime will terminate the program, if the element was not found. Read section 8.5 of this paper: https://arxiv.org/pdf/2111.13384.pdf

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks
