### ISSUE TITLE
error associated with LaTeX

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#708]
An error occurred when I'm trying to build latex pdf locally and also [broken build happen](https://github.com/objectionary/eo/runs/6726034248?check_suite_focus=true):
```
! LaTeX Error: Command \anon already defined.
               Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
l.67 }
      \makeatother
? 
! Emergency stop.
 ...                                              
l.67 }
      \makeatother
!  ==> Fatal error occurred, no output PDF file produced!

```
There is the command collision in `eo.sty` and `acmart.cls`.
I tried to fix this by changing `newcommand` to `renewcommand`, but that didn't work.

**Comment by yegor256** [comment]
@Graur all fixed, the build is clean, thanks for reporting
