### ISSUE TITLE
stackOverflowError

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#713]
## Problem
if I use `n.mod`, I get the stackOverflowError, if I replace `mod` with `add` or something else, result is ok
## code
```c
[condition body] > while-loop
  while. > @
    condition
    [i]
      body > @

[args...] > app
  memory > n
  seq > @
    n.write 0
    while-loop
      n.less 5
      seq
        n.write (n.add 1)
        (n.mod 2).eq 0
        TRUE
    TRUE
```
## result of `app` execution

![image](https://user-images.githubusercontent.com/33983579/172244066-0bf38fd0-9b5b-41e4-af17-45011196b0b1.png)

**Comment by yegor256** [comment]
@Graur try this one

**Comment by Graur** [comment]
@yegor256 Sure, I'll fix this
