### ISSUE TITLE
to get rid of regex, text, sscanf and sprintf objects from eo-runtime

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#715]
We need to:

- [x] move regex atom from `eo.eolang` to `eo.eolang.txt` package
- [x] wait until [eo-string](https://github.com/InnoSWP/eo-strings) would be ready to implement it to their project
- [x] get rid of `regex` from `eo-runtime` in EO

**Comment by Graur** [comment]
@yegor256 according to [this paper](https://arxiv.org/pdf/2206.02585.pdf), I suggest that we don't need `regex` in parser too. New `regex` would just store `string`. And all matching manipulation would be in `regex.match` object. Am I right?

**Comment by yegor256** [comment]
@Graur did you see the suggestion I made in this document: https://arxiv.org/abs/2206.02585 I understand that the "compile" is step is missing in my design. Maybe this one would be better:

```
[txt] > regex
  [] > compile /regex
  [] > match /array
```

**Comment by Graur** [comment]
@yegor256 What suggestion do you mean?
How can I use this design of `regex` object? Like this 
```
/([a-z]+)/i "word"
.compile
.match
```
?
I thought that we need two parameters: regex string and matching string.

**Comment by yegor256** [comment]
@Graur should be something like this:

```
match. > m
  compile.
    regex 
      "/([a-z]+)/i"
  "word"
```

**Comment by Graur** [comment]
@yegor256 So the design would be:
```
[r] > regex
  [] > compile /regex
  [txt] > match /array
  [txt] > matches /bool
```
?

**Comment by Graur** [comment]
@yegor256 How do you think, should we get rid of `regex` object from eo-parser too? I still have a problem with combining both of them: `/([.])/` and `(regex "/([.])/").compile`. I suggest that only second option will be available.

**Comment by Graur** [comment]
related issue: https://github.com/objectionary/eo-strings/issues/7

**Comment by Graur** [comment]
@levBagryansky I think we can use this issue to remove objects from eo-runtime according to this issues: https://github.com/objectionary/eo-strings/issues/6, https://github.com/objectionary/eo-strings/issues/7, https://github.com/objectionary/eo-strings/issues/8, https://github.com/objectionary/eo-strings/issues/9

**Comment by levBagryansky** [comment]
@yegor256 , @Graur 
I think since we want to implement regex by eo it will be better to compile the regex in `complile` attribute. It can be useful if we are going to match severall strings.

**Comment by yegor256** [comment]
@levBagryansky this is what `compile` is for: to pre-process the expression

**Comment by Graur** [comment]
@levBagryansky What's up with this issue?

**Comment by levBagryansky** [comment]
@Graur I copied txt package to eo-strings. So we need release eo-strings and remove them here

**Comment by Graur** [comment]
@levBagryansky Thanks! Can you, please, check `sprintf` object one more time? It was updated by https://github.com/objectionary/eo/issues/1049

**Comment by levBagryansky** [comment]
@Graur done

**Comment by Graur** [comment]
@levBagryansky Thanks!
