### ISSUE TITLE
example from #711 fails to compile with ClassNotFoundException: EOpreface 

### ISSUE THREAD

**Issue by dours** [objectionary/eo#719]
You need to recreate the same test as in #711  in an empty directory!

**Comment by dours** [comment]
The directory EOpreface with sources is generated, but it is not compiled

**Comment by dours** [comment]
though EOorg is compiled

**Comment by yegor256** [comment]
@dours do you still have the same problem? did you try version `0.23.8`?

**Comment by dours** [comment]
@yegor256 No, I don't. No, I didn't, but then I tried and now I don't have the problem. So, all the old regression tests now pass in CI.
