### ISSUE TITLE
StackOverflow because of a chain of 2 assignments

### ISSUE THREAD

**Issue by dours** [objectionary/eo#720]
(version 23.7)
```
+package org.eolang
+alias cage org.eolang.gray.cage
+junit

[] > assign-1
  cage > toReturn
  cage > assertMe
  seq > @
    assertMe.write TRUE
    toReturn.write assertMe
    toReturn
```

But this one passes:
```
+package org.eolang
+alias cage org.eolang.gray.cage
+junit

[] > assign-1
  cage > toReturn
  cage > assertMe
  seq > @
    assertMe.write (TRUE)
    toReturn.write assertMe
    assertMe
```

**Comment by dours** [comment]
@yegor256  this problem currently leads to a failure of *all* of our regression tests . Also our CI fails now, even though it passed ok with the same version 23.6 of EO and exactly the same code in our repo (i.e., I added one space to the README, then the CI failed)

**Comment by yegor256** [comment]
@dours see this: https://news.eolang.org/2022-06-09-memory-enclosure.html Hope it helps

**Comment by dours** [comment]
@yegor256 , thank you, this example now works, but all the tests fail because of #719 : files from a separate package are compiled, but the classes are lost in runtime
