### ISSUE TITLE
Multiple dataization is a problem

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#723]
Let's consider the following code:
```
[x] > inc
  seq > @
    x.write (x.add 1)
    x

[args...] > main
  memory > global_var
  cage > my_object
  seq > @
    global_var.write 0
    my_object.write (inc global_var)
    println my_object
    println my_object
    println global_var
```

If we run it, we get the following output:
```
1
2
2
```

It seems that `my_object` have been dataized twice. And it is a problem, because this code should be equivalent to python code bellow:
```Python
class Number:
    def __init__(self, n):
        self.value = n

    def add(self, n):
        self.value += n

def inc(x):
    x.add(1)
    return x

if __name__ == '__main__':
    global_var = Number(0)
    my_object = inc(global_var)
    print(my_object)
    print(my_object)
    print(global_var)
```

@yegor256. Can you help?

**Comment by someilay** [comment]
@yegor256. You suggest solution that is helpful only for this example. What's about more complex case? Let's suppose that `Number` also should store unique `id`. So, we are forced to use `cage` with this restricition.

**Comment by yegor256** [comment]
@yegor256 `cage` is storing an object, which is a "volatile" creature. It's a data structure, but more like a function, which behaves different way every time you touch it. Better use `memory` if you want to store something "static"

**Comment by someilay** [comment]
@yegor256 . But how can I deal with a such object:
```Python
class Number:
    def __init__(self, n, id):
        self.id = id
        self.value = n

    def add(self, n):
        self.value += n
```

I want to store result of `add` and avoid its` recalculating.

**Comment by someilay** [comment]
@yegor256. 

> @yegor256 . But how can I deal with a such object:
> 
> ```python
> class Number:
>     def __init__(self, n, id):
>         self.id = id
>         self.value = n
> 
>     def add(self, n):
>         self.value += n
> ```
> 
> I want to store result of `add` and avoid its` recalculating.

Possible EO:
```
[value id] > number
  "number" > @

[x] > inc
  seq > @
    x.value.write (x.value.add 1)
    x

[args...] > main
  cage (number (memory 0) 0) > global_var
  cage (inc global_var)> my_object
  seq > @
    println (my_object.value)
    println (my_object.value)
    println (global_var.value)
```

However, this program has more strange behaviour. It some how get `my_object.value` without dataization `inc.@`

**Comment by yegor256** [comment]
@someilay I think you need "constant" objects to help you, see: https://github.com/yegor256/reducing-programs-to-objects/commit/619abc80a6968359636090f460a5f2d14ab53e6b

**Comment by someilay** [comment]
> However, this program has more strange behaviour. It some how get `my_object.value` without dataization `inc.@`

@yegor256. Can you explain why it works so? It seems that I don't fully understand how dataization work)

**Comment by yegor256** [comment]
@someilay I made some tests to confirm that it works. It works. You just need to make your "impure" procedure constant and that's it.
