### ISSUE TITLE
specify runtime version in pom.xml

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#726]
@yegor256, can you please explain in more detail exactly how to use this feature with hash? https://github.com/objectionary/eo/issues/479

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.9`

**Comment by yegor256** [comment]
@IngeniariusSoftware it was a bug, thanks for reporting. try version 0.23.9, it should work

**Comment by IngeniariusSoftware** [comment]
@yegor256, I tried using version 0.23.9, but I still get the same result. For some reason, the main value is still used, and not the specified hash. 

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.eolang</groupId>
  <artifactId>c2eo-transpiler</artifactId>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <eolang.version>0.23.9</eolang.version>
  </properties>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>8</source>
          <target>8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.eolang</groupId>
        <artifactId>eo-maven-plugin</artifactId>
        <version>${eolang.version}</version>
        <configuration>
          <hash>13acd7881c77b055e19971f12b4dcd8f290b8ccd</hash>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>register</goal>
              <goal>assemble</goal>
              <goal>transpile</goal>
            </goals>
            <configuration>
              <sourcesDir>${project.basedir}/eo</sourcesDir>
              <targetDir>${project.basedir}/target</targetDir>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

![image](https://user-images.githubusercontent.com/33983579/173047683-b3a3229f-abbc-4141-b557-c0b70fbcfe91.png)

and as I understand it, this request for hash 0.23.8 (13acd7881c77b055e19971f12b4dcd8f290b8ccd) https://raw.githubusercontent.com/objectionary/home/13acd7881c77b055e19971f12b4dcd8f290b8ccd/objects/org/eolang/int.eo, in theory, was supposed to return me the file with specified object of a certain version, but this does not happen:

![image](https://user-images.githubusercontent.com/33983579/173049674-475b4073-42f8-4457-9b4b-abc84b74f098.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware this one works for me: https://raw.githubusercontent.com/objectionary/home/e2ede05d40361938b93302377da5bd6218239e14/objects/org/eolang/array.eo

**Comment by yegor256** [comment]
@Graur can you try to fix this one?

**Comment by IngeniariusSoftware** [comment]
Thanks!
