### ISSUE TITLE
cannot store a result of a function call, only the function call itself

### ISSUE THREAD

**Issue by dours** [objectionary/eo#730]
```
+package org.eolang
+junit

[] > test
  memory 0 > m
  [unused] > incr
    seq > @
      m.write (m.add 1)
      m
  incr "" > x
  x.eq x > @
```
@yegor256 , should it be this way?

**Comment by yegor256** [comment]
@dours the test works or it doesn't work? I don't understand the description of the problem

**Comment by dours** [comment]
@yegor256  it does not work

**Comment by yegor256** [comment]
@dours I don't understand why it should work. The first dataization of `x` leads to the first increment of `m`. The second leads to the second one. `x.eq x` means two dataizations of `x`. What do I miss?

**Comment by dours** [comment]
@yegor256 how then do I store a result of a function call, so that the function was called only once?

**Comment by yegor256** [comment]
@dours see #723, it's exactly the same problem
