### ISSUE TITLE
stronger validation of identifiers

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#731]

**Comment by yegor256** [comment]
@Graur see my latest commit: 4684b491

**Comment by Graur** [comment]
@yegor256 Should we exclude also: `#`, `<`, `*`, `\` and `/` symbols?

**Comment by yegor256** [comment]
@Graur yes, definitely

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks
