### ISSUE TITLE
leading zeros must be prohibited in int

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#732]
At the moment, this is a valid syntax:

```
QQ.io.stdout
  QQ.txt.sprintf
    "I am %d years old"
    000000025
```

It should be illegal to add leading zeros to a number. Only a single zero is permitted, if the number is zero.

**Comment by mximp** [comment]
I'm on it

**Comment by mximp** [comment]
PR has been raised: #770 
@yegor256
