### ISSUE TITLE
turn on Checkstyle in eo-runtime

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#739]
At the moment it's disabled. Let's turn it on and fix the code.

**Comment by marceloamadeu** [comment]
@yegor256 can you assign to me?
Tks

**Comment by yegor256** [comment]
@marceloamadeu sure, go ahead please!

**Comment by yegor256** [comment]
@marceloamadeu I suggest you move slow in small increments/pull-requests, to avoid big mistakes

**Comment by yegor256** [comment]
@marceloamadeu how is it going? this is of high priority now

**Comment by yegor256** [comment]
@mximp please help us here

**Comment by marceloamadeu** [comment]
@yegor256 Sorry for the delay in responding.

**Comment by mximp** [comment]
667 violations are found in prod sources.
Will start with them.

**Comment by mximp** [comment]
Our EOorg.EOeolang package doesn't fit checkstyle rule:
```
[INFO] Checkstyle: src/main/java/EOorg/EOeolang/EOstring$EOslice.java[42]: Name 'EOstring$EOslice' must match pattern '^[A-Z][a-zA-Z0-9]*$'. (TypeNameCheck)
```

I suggest to exclude this package for now from checking.

To find out an approach how to configure suppression in qulice I raised https://github.com/yegor256/qulice/issues/1109.

**Comment by yegor256** [comment]
@mximp what's up with this? how far are we?

**Comment by yegor256** [comment]
@mximp I suggest we fix them ASAP, because new changes are coming to eo-runtime and they will definitely break Qulice :(

**Comment by mximp** [comment]
@yegor256 this is completed and can be closed

**Comment by mximp** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@mximp thanks!
