### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#743]
In paper/sections/calculus.tex in Section 3.6 need to add " \rho. " to examples 9, 11, 13 at this line:
& \quad \quad \varphi \mapsto \rho.\ff{distance}(\ff{p}).\ff{leq}(\rho.\ff{radius}) \br

**Comment by yegor256** [comment]
@MikhailLipanin feel free to submit a pull request

**Comment by yegor256** [comment]
@MikhailLipanin what's up with this one?

**Comment by MikhailLipanin** [comment]
@yegor256 #849

**Comment by MikhailLipanin** [comment]
@yegor256 #874

**Comment by yegor256** [comment]
@MikhailLipanin I believe, this one is fixed
