### ISSUE TITLE
float objects according to "On the Origins of Objects"

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#748]
Should we get rid of these objects because they are not included in the "Origin of objects" article ? Or we should add them to it?
1. float.neq
2. float.neg
3. float.signum (will be implemented in eo-math)
4. float.pow  (will be implemented in eo-math)
5. float.abs (will be implemented in eo-math)
6. float.sin (will be implemented in eo-math)
7. float.cos (will be implemented in eo-math)
8. float.as-int
9. float.as-string

**Comment by Graur** [comment]
I think, before removing this objects from EO, we need to wait for eo-math release with this objects aboard

**Comment by Graur** [comment]
@yegor256 We've got `pow` object in `float.div`:
```
  [x] > div
    ^.times (x.pow -1.0) > @
```

Should we add a `QQ.math.number.pow` here, or we need to make `float.div` an atom?

**Comment by yegor256** [comment]
@Graur I think we should make `float.div` an atom

**Comment by Graur** [comment]
done in #775
