### ISSUE TITLE
Why does dataization happen on write to memory but not on memory initialization?

### ISSUE THREAD

**Issue by dours** [objectionary/eo#749]
i.e, why does this test fail (to @yegor256 )
```
+package org.eolang
+junit

[] > test
  memory 0 > x
  memory (x.eq 0) > b
  seq > @
    x.write 11
    b
```

**Comment by yegor256** [comment]
@dours because it's a declarative language :) `memory (x.eq 0) > b` doesn't do anything. It only creates object `b`. Only when you touch the object (dataization starts), the calculation happens.
