### ISSUE TITLE
XOR operation is broken

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#756]
Code:
```
(2397719729.as-bytes.xor (4294967295.as-bytes)).as-int
```

It represents following operation: `2397719729 ^ 4294967295`. It should be equal to `1897247566`, but code above returns `8142508126287278926`.

Binary representations:
`00000000 00000000 00000000 00000000 10001110 11101010 01001100 10110001 = 2397719729`
`00000000 00000000 00000000 00000000 11111111 11111111 11111111 11111111 = 4294967295`
`00000000 00000000 00000000 00000000 01110001 00010101 10110011 01001110 = 1897247566`
`01110001 00000000 00000000 00000000 00000000 00010101 10110011 01001110 = 8142508126287278926`

@yegor256. Can you fix it?

**Comment by Graur** [comment]
@yegor256 Sure

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.11`

**Comment by Graur** [comment]
@someilay You can check this update by increasing the version of EO up to `0.23.11`. Please, let me know if you have any further questions.

**Comment by someilay** [comment]
@Graur. 

> You can check this update by increasing the version of EO up to `0.23.11`

Error:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.eolang:sandbox-canonical >--------------------
[INFO] Building sandbox-canonical 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.eolang:eo-maven-plugin:jar:0.23.11 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.046 s
[INFO] Finished at: 2022-06-19T12:51:38+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.eolang:eo-maven-plugin:0.23.11 or one of its dependencies could not be resolved: org.eolang:eo-maven-plugin:jar:0.23.11 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

It seems that version `0.23.11` has not been released yet. However, bug disappeared on version `0.23.10`.
