### ISSUE TITLE
OR operation is broken

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#767]
Code:
```
(2397719729.as-bytes.or (-4294967296).as-bytes).as-int
```

It represents following operation: `2397719729 | -4294967296`. It should be equal to `-1897247567`, but code above returns `2397719729`.

Binary representations:
```
00000000 00000000 00000000 00000000 10001110 11101010 01001100 10110001 = 2397719729
11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 = -4294967296
11111111 11111111 11111111 11111111 10001110 11101010 01001100 10110001 = -1897247567
```

@yegor256. Can you fix it?

**Comment by yegor256** [comment]
@Graur can you please help?

**Comment by Graur** [comment]
@yegor256 Sure, I'll do it

**Comment by someilay** [comment]
@Graur. Bug is still present

**Comment by Graur** [comment]
@someilay I think that is because EO has not been released yet

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.15`

**Comment by yegor256** [comment]
@someilay version 0.23.15 release, please try it

**Comment by someilay** [comment]
FIXED
