### ISSUE TITLE
EO Runtime: prints-complex-string test fails when using specific locales

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#769]
Test fails due to differences in decimal symbol for different locales.
When running for RU locale:
```
org.opentest4j.AssertionFailedError: 
Expected: <Привет 3.14 Jeff X!> equal to value
     but: was <Привет 3,14 Jeff X!>
```

**Suggestion:** make test locale-agnostic

**Comment by yegor256** [comment]
@mximp definitely a bug, let's fix

**Comment by mximp** [comment]
Decimal separator in EO should always be '.' (dot)

**Comment by mximp** [comment]
@yegor256, pls check: #776

**Comment by mximp** [comment]
Fixed
