### ISSUE TITLE
`switch` object needed

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#778]
According to [this](https://github.com/objectionary/on-the-origin-of-objects/blob/3dc098eff3e903690cba60fe8825cbc3172c6d1c/paper.tex#L306) we need to add object `switch` to `eo-runtime`:
```
QQ.switch
  *
    password.eq "swordfish"
    "password is correct!"
  *
    password.eq ""
    "empty password is not allowed"
```

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
