### ISSUE TITLE
Arithmetic issues

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#779]
Suppose we have a following Java code:
```Java
int a = 1_234_567;
int b = 7_654_321;
System.out.println(a * b);
```

It prints `844062807`

One can provide a such analog in EO:
```
1234567 > a
7654321 > b
stdout (sprintf "%d\n" (a.times b)) > @
```

However, this code would print `9449772114007`. It happens because EO uses `int_64` (aka `long`) arithmetic. We can try fix it by finding a mod of multiplication:
```
1234567 > a
7654321 > b
stdout (sprintf "%d\n" ((a.times b).mod 4294967296)) > @
```

Now a result is `844062807`. But, this approach works only for `a * b > 4294967296`. For example, if `a` equals to `321`, Java program would print `-1837930255`, and EO program above would print `2457037041`. Therefore, for handling `int_32` arithmetic  we should use tricky bitwise calculations for achieving the same behaviour. It makes analyzing of such arithmetic expressions a difficult task. Moreover, EO uses `double` for handling floating point values, so mapping `float` arithmetic is also quite tricky.

**Comment by someilay** [comment]
@yegor256. What do you think about it?

**Comment by yegor256** [comment]
@someilay well, EO is 64-bit language. Imagine, you would try to do something like this with 8-bit numbers at 32-bit x86 processor. You would face the same problems. We just need to create a proper library eo-digits for math operations with 8-bit, 16-bit, 32-bit numbers.

**Comment by someilay** [comment]
@yegor256. For me, it is most convinient to introduce built-in `byte`, `short`, `int`, `long`, `float` and `double` as it made in Java.

**Comment by yegor256** [comment]
@someilay we will have them, in eo-digits library, very soon. See this document with the explanation: https://arxiv.org/pdf/2206.02585.pdf
