### ISSUE TITLE
How to convert `float` to `string`?

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#782]
Recently `float` object has lost a `as-string`. So, how to convert `float` to `string`?

@yegor256. Can you explain it?

**Comment by Graur** [comment]
@someilay I think new `number` object can help here. It is a [decorator](https://github.com/objectionary/on-the-origin-of-objects/blob/master/paper.tex#L396) of `int.eo` and `float.eo`.
e.g.
```
number 3.0
.as-string
```
will return "3.0"

Or, maybe, `sprintf` object can help.
