### ISSUE TITLE
Current conversion from `float` to `int` is broken

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#783]
Code:
```
(4294967295.0).as-bytes.as-int
```

It prints `4751297606873776128` instead `4294967295`.

@yegor256. Can you fix it?

**Comment by yegor256** [comment]
@Graur can you please help

**Comment by someilay** [comment]
@yegor256. I think that it is hard to distinguish `float` from 'int' in the byte form

**Comment by someilay** [comment]
@yegor256. For example, how do we distinguish `3.0` from `4613937818241073152`?
```
01000000 00001000 00000000 00000000 00000000 00000000 00000000 00000000 = 3.0
01000000 00001000 00000000 00000000 00000000 00000000 00000000 00000000 = 4613937818241073152
```

**Comment by Graur** [comment]
@someilay I agree. That's why we can do this using our new `number` object.
```
QQ.math.number 3.57
.as-int
```
should return 3.

**Comment by yegor256** [comment]
@someilay indeed, what you are doing is wrong: `float.as-bytes.as-int` doesn't guarantee that the input is equal to the output
