### ISSUE TITLE
varargs for plus, minus, times, and div

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#790]
Let's make it possible to do this:

```
plus.
  5
  4
  12
  8
```

We have similar functionality in `bool.or` and `bool.and` already. Let's introduce it here too, for `int.plus`, `int.minus`, `int.times`, and `int.div`. The same for `float`.

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by mximp** [comment]
@yegor256 this can be closed

**Comment by yegor256** [comment]
@mximp thanks!
