### ISSUE TITLE
QQ.math.random must have a seed

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#791]
Our current interface (and implementation) of `QQ.math.random` is wrong. It must have a seed provided. I suggest this one instead:

```
[seed] > random
  [] > @ /float
  [] > pseudo /random
```

it will be used this way:

```
QQ.io.stdout
  QQ.txt.sprintf
    "random is %f"
    QQ.math.random.pseudo
```

Let's not forget to update the papers.

**Comment by yegor256** [comment]
@mximp can you please help here

**Comment by mximp** [comment]
@yegor256 the task can be closed.

Issue was raised for validation of random distribution #817

**Comment by yegor256** [comment]
@mximp thanks!
