### ISSUE TITLE
string.slice throws one error on three different situations

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#792]
I believe, it would be better if we return three different errors with three different messages instead.

**Comment by yegor256** [comment]
@mximp can you please help

**Comment by mximp** [comment]
@yegor256 Can you please provide code example? What situations are assumed?

**Comment by yegor256** [comment]
@mximp there are three cases here: https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOslice.java#L53

**Comment by mximp** [comment]
@yegor256 the changes are merged. The issue can be closed.

**Comment by mximp** [comment]
@yegor256 reminder - this can be closed.

**Comment by yegor256** [comment]
@mximp thanks!
