### ISSUE TITLE
as-string must be transparent and not create new object

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#793]
I think, this test should pass:

```
[] > as-string-is-transparent
  68-65-6c-6c-6f > b
  b.as-string.as-bytes.<.eq > @
    b.<
```

Now it doesn't pass.

The same should be true for `as-int`, `as-float`, and `as-bool`.

**Comment by yegor256** [comment]
@Graur please, help

**Comment by Graur** [comment]
@mnj2kk Please, help us here

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2142](https://github.com/objectionary/eo/issues/2142) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2142](https://github.com/objectionary/eo/issues/2142) is solved here.
