### ISSUE TITLE
No information about /? atom syntax

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#798]
There is no information about the following syntax for atom declaration:
```
[] > cage /?
```
Checked docs: 
- paper (https://arxiv.org/pdf/2111.13384.pdf)
- ```*.md``` files in the sources

I believe it needs to be added to the paper (section about atoms).

**Comment by mximp** [comment]
@yegor256 FYI

**Comment by yegor256** [comment]
@mximp fixed in c6b21dbc
