### ISSUE TITLE
Wrong rho example in calculus paper

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#799]
![image](https://user-images.githubusercontent.com/40247101/176415617-75703eee-b904-42aa-afb7-1f333bd8d185.png)
If we write it with EO syntax:
```
[] > a
  c > b
  e.f > d
  h.i j > g
```
Should be ```b.rho = c```

**Comment by mximp** [comment]
@yegor256 is my understanding correct?

**Comment by mximp** [comment]
As discussed:
1. b -> c doesn't create a copy (it's not an application). It's just labelling.
2. Expression g -> h.i(j) creates a copy of _i_ (with parameter _j_) and the creator is _h_.

**Comment by mximp** [comment]
@yegor256 can be closed.

**Comment by yegor256** [comment]
@mximp ok
