### ISSUE TITLE
ram.slice object

### ISSUE THREAD

**Issue by Graur** [objectionary/eo#802]
According to [this](https://github.com/objectionary/on-the-origin-of-objects/blob/master/paper.tex#L357) `ram.slice` should works like this:

```
ram 1024 > r
seq
  write.
    r.slice 200 13 > s
    "Hello, world!".as-bytes
  QQ.io.stdout
    as-string.
      s.slice 0 5
```

So, what object will we get after dataization of `s`? Will it be `ram` or `bytes` ? I suggest `ram`, then the code above would look like this:
```
ram 1024 > r
seq
  write.
    r.slice 200 13 > s
    "Hello, world!".as-bytes
  QQ.io.stdout
    as-string.
      as-bytes.
        s.slice 0 5
```

**Comment by yegor256** [comment]
@Graur but `ram` has `as-bytes` attribute already. `(s.slice 0.5).as-string` should work just fine.
