### ISSUE TITLE
Unused import bypasses `failOnError` compilation flag 

### ISSUE THREAD

**Issue by egorklementev** [objectionary/eo#803]
Referring to #694

When I use
```xml
<configuration>
  <failOnError>false</failOnError>
</configuration>
```
flag, it works well when some `.eo` files contain syntactical errors (`\t` symbols, for example).
However, when unused `+alias` occurrs, compiler does not show warning as in the syntactic error case, but cancels the whole compilation process. 

It would be convenient to make EO compiler *not* fail in such cases.

**Comment by yegor256** [comment]
@Graur please, fix it

**Comment by Graur** [comment]
@egorklementev Please, try it. Should work from EO version `0.23.17`. Let me know if you have any further questions.
