### ISSUE TITLE
move array.* methods to org.eolang.collections.list object

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#807]
Let's move methods like `reduce`, `map`, etc to `org.eolang.collections.list` object, which should encapsulate an array.

**Comment by yegor256** [comment]
@Graur would be great if you can help

**Comment by Graur** [comment]
@yegor256 Sure, I will do it

**Comment by Graur** [comment]
@yegor256 Should these objects return `list` or `array` ?
e.g. we can write like this:
```
[] > test
  map. > @
    list 
       map.
         list * 1 2 3
         [i]
            i > @
     [i]
        i > @
```
or like this:
```
[] > test
  map. > @
     map.
         list * 1 2 3
         [i]
            i > @
     [i]
        i > @
```

**Comment by yegor256** [comment]
@Graur I think it's better to return `list`

**Comment by Graur** [comment]
@yegor256 If so, I think it would be better to add `list.as-array` object. WDYT?

**Comment by Graur** [comment]
@yegor256 Maybe we can keep  `array.eq` object?

**Comment by Graur** [comment]
@yegor256 please close the ticket if you don’t have any further questions.

**Comment by yegor256** [comment]
@Graur thanks!
