### ISSUE TITLE
metas-duplicated.xsl

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#809]
Let's catch when meta commands are duplicated and make a warning about it. Similar to what we do in #808. For example:

```
+alias hello
+alias hello
```

No harm done here, but it's not a clean code.

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by yegor256** [comment]
@mximp yes, definitely

**Comment by mximp** [comment]
@yegor256 can be closed

**Comment by yegor256** [comment]
@mximp thanks!
