### ISSUE TITLE
We need have map/multimap classes

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#822]
Many tasks require a map interface for themselves.

**Comment by EugeneDar** [comment]
@Graur in future we will have eo-json object, and this is essentially a wrapper on the map.

**Comment by MCJOHN974** [comment]
@EugeneDar, I think this objects can be implemented in EO

**Comment by EugeneDar** [comment]
@MCJOHN974 do you think it is possible to achieve optimal runtime for this data structure without using Java? Please specify what you mean by that.
