### ISSUE TITLE
We need mutable array-list

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#828]
In many tasks we need to change the values in the array and it takes a very long time to do it in a linear time. For example, we need to be able to change array fields when rebuilding a hash table.
This structure will have three additional attributes: inject, replace, and extract . They encapsulate ★cage object.

**Comment by EugeneDar** [comment]
@yegor256 sure, I will do it.

**Comment by Graur** [comment]
@EugeneDar I think `inject` object should:
1. Return current array if the capacity is enough to add new element to it.
2. Return new array if the capacity is not enough.

**Comment by Graur** [comment]
@EugeneDar My bad, `inject` should returns `bool`

**Comment by EugeneDar** [comment]
@Graur thanks.

**Comment by EugeneDar** [comment]
we will not implement this
