### ISSUE TITLE
int.as-hash doesn't need to be an atom

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#829]
I believe `int.as-hash` can easily be implemented in EO

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by yegor256** [comment]
@mximp we can also fix `float.as-hash`

**Comment by mximp** [comment]
@yegor256 can be closed

**Comment by yegor256** [comment]
@mximp thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.17`
