### ISSUE TITLE
list-tests.eo:321-325: Remove all nop objects from tests....

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#837]
The puzzle `841-d9ebec39` from #841 has to be resolved: 

https://github.com/objectionary/eo/blob/587c476e89c8e64d8aa6e49cc48c158caaec4fe0/eo-runtime/src/test/eo/org/eolang/collections/list-tests.eo#L321-L325

The puzzle was created by @Graur on 07-Jul-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Graur** [comment]
@kerelape Since EO-hamcrest version was up to 0.2.6, we could get rid of nop objects in tests and fix them. Please, take this task, the budget is 30 minutes.
@mximp please, check it

**Comment by mximp** [comment]
I believe this puzzle has wrong reference: it's originated from #807

**Comment by 0pdd** [comment]
The puzzle `841-d9ebec39` has disappeared from the source code, that's why I closed this issue.

**Comment by Graur** [comment]
done in #944
