### ISSUE TITLE
new semantic of `org.eolang.error` object

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#838]
Let's do what is suggested in the "On the Origins of Objects" paper:

<img width="358" alt="Screen Shot 2022-07-07 at 8 20 28 PM" src="https://user-images.githubusercontent.com/526301/177833106-4c8f753d-dedd-483e-9fdb-440c2d2d2c2d.png">

**Comment by Graur** [comment]
@yegor256 Should we use `System.exit(1)` ?

**Comment by yegor256** [comment]
@Graur if you use System.exit you won't be able to implement try/catch. I think we should use exceptions, but of a special time. Something like `ExError extends ExAbstract`
