### ISSUE TITLE
Implement `bytes.as-array`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#841]
The object should return an arrays of `int`s which represent corresponding bytes.

The necessity arose for implementing hash code calculations for #830

**Comment by mximp** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@mximp good idea, but it shouldn't be inside `bytes`. I think we can introduce some decorator of `bytes`, named maybe `byte-array`, and implement such attributes over there.

**Comment by mximp** [comment]
@yegor256 Agree. I only think that 'byte-array' is logically an array and should decorate 'array'. 
The usage example:
```
[] > client
  list > @
    byte-array
      12345.as-bytes
```

**Comment by 0pdd** [comment]
@mximp the only puzzle [#837](https://github.com/objectionary/eo/issues/837) is solved here.
