### ISSUE TITLE
empty objects must be prohibited

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#848]
This is from our paper:

<img width="337" alt="Screen Shot 2022-07-10 at 9 31 34 AM" src="https://user-images.githubusercontent.com/526301/178134056-d725e5c0-79f9-4125-879d-ec443ff283dc.png">

However, this code is still valid in EO of current version:

```
[] > foo
```

Let's make it illegal. I suggest fixing the grammar in `.g4` file.

**Comment by yegor256** [comment]
@yasamprom can you help us here?

**Comment by yasamprom** [comment]
Yes!

**Comment by yegor256** [comment]
@yasamprom I'm closing since it's finished. Next time don't forget to ping the author of a ticket, when implementation is finished
