### ISSUE TITLE
Implement `+version 0.0.0` check for eo modules 

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#854]
The version must not be changed manually during development and must always be `0.0.0`.

Maven verifier plugin can be used to check presence of correct version.
https://maven.apache.org/plugins/maven-verifier-plugin/index.html

**Comment by mximp** [comment]
@kerelape please implement this.
Budget is 30 minutes.

**Comment by yegor256** [comment]
@mximp what's up here?

**Comment by mximp** [comment]
@yegor256 I believe we can reassign it
