### ISSUE TITLE
Create a web server for running EO programs

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [objectionary/eo#866]
Hi! I'd like to have an opportunity to have an [eoc](https://github.com/objectionary/eoc)-like tool in web. E.g., I send a request to a server and get either the errors or the result of running such program. Eventually, I'd like to use it in EO and 𝜑-calculus playground [try-phi](https://br4ch1st0chr0n3.github.io/try-phi-front/?editor=phi&snippet=%5B%0A%20%20a%20-%3E%203%2C%0A%20%20b%20-%3E%20%5E0.a%0A%5D.b).

**Comment by yegor256** [comment]
@br4ch1st0chr0n3 good idea, thanks!
