### ISSUE TITLE
system returned with code 256 (in /paper/Make)

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#874]
[Error log](https://pastebin.com/gNRSm5E1)

**Comment by yegor256** [comment]
@MikhailLipanin try to run this: 

```
$ pdflatex -shell-escape -halt-on-error eolang-paper.tex
```

**Comment by yegor256** [comment]
@MikhailLipanin still having the problem or we can close this one?

**Comment by yegor256** [comment]
@MikhailLipanin I'm closing this one. if you still have a problem, please open a new ticket
