### ISSUE TITLE
Fix checkstyle warnings for `ExprReduce`

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#881]
Split from https://github.com/objectionary/eo/issues/739

Refactor the class to pass all checkstyle checks.
Current warnings:
```
[INFO] Checkstyle: src/main/java/org/eolang/ExprReduce.java[83]: More than 3 parameters (found 5). (ParameterNumberCheck)
[INFO] Checkstyle: src/main/java/org/eolang/ExprReduce.java[104]: More than 3 parameters (found 4). (ParameterNumberCheck)
```

**Comment by mximp** [comment]
@potatmen please assist

**Comment by potatmen** [comment]
@mximp when does this warning occur? During the compiling? As I understand I need to extend the number of parameters passed to `BiFunction ` from 3 to 5 or 4 depending on the case right?

**Comment by potatmen** [comment]
Ignore the last question, I got the idea

**Comment by mximp** [comment]
1. Enable Checkstyle validation for `eo-runtime`:
In `eo-runtime/pom.xml` comment out exclude:
```
<profiles>
    <profile>
      <id>qulice</id>
      <build>
        ...
            <artifactId>qulice-maven-plugin</artifactId>
            <configuration>
              <excludes>
<!--                <exclude>checkstyle:.*</exclude>-->
                <exclude>checkstyle:/src/test/.*</exclude>
                <exclude>pmd:.*</exclude>
              </excludes>
            </configuration>
      ...
      </build>
    </profile>
  </profiles>
```

2. Run `qulice:check` goal:
Within `eo-runtime` folder execute the following command:
```
mvn qulice:check -P qulice
```

This will produce the list of errors from Checkstyle.
Find the ones you are interested in.

**Comment by potatmen** [comment]
@mximp Thanks for the clarification

**Comment by potatmen** [comment]
@mximp done https://github.com/objectionary/eo/pull/1032

**Comment by potatmen** [comment]
@mximp I haven't actually fixed it yet

**Comment by mximp** [comment]
@potatmen was the merge for?

**Comment by mximp** [comment]
@yegor256 this one is completed.
