### ISSUE TITLE
Memory works incorrectly inside array

### ISSUE THREAD

**Issue by potatmen** [objectionary/eo#895]
```
[args...] > app
  memory 0 > x
  x.write 0
  * x > a
  (a.at 0).write 1
  stdout > @
    sprintf
      "%d \n"
      a.at 0
```
In this code I'm creating an array of memory objects storing ints. I have one element, which's value is `0`. Then I change it to `1`, but when I print it, I see `0`, but should be `1`. Something same was stated here https://github.com/objectionary/eo/issues/842.

**Comment by potatmen** [comment]
@yegor256 @Graur @mximp

**Comment by EugeneDar** [comment]
@potatmen may be you should use 'seq'. And code can look like this:
```
[args...] > app
  memory 0 > x
  seq > @
    x.write 0
    * x > a
    (a.at 0).write 1
    stdout
      sprintf
        "%d \n"
        a.at 0
```
This code prints 1.

**Comment by potatmen** [comment]
Thanks!
