### ISSUE TITLE
We need to add more methods to the text.eo

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#901]
Working with strings is a very common task, for example, we can't do without it at all when parsing json strings. 
So we need this methods:
- [ ] contains
- [ ] index-of
- [ ] last-index-of

**Comment by EugeneDar** [comment]
@yegor256 what do you think?

**Comment by Graur** [comment]
@EugeneDar good point, go ahead!

**Comment by EugeneDar** [comment]
I should close this issue, because I'll implement this features in eo-strings.
