### ISSUE TITLE
When Parsing from XMIR to EO, BOOL objects are represented Wrong (as Lowercase)

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#904]
Boolean objects like TRUE/FALSE after applying `xmir-to-eo.xsl` represented as 'true'/'false', not 'TRUE'/'FALSE'.

**Comment by MikhailLipanin** [comment]
@yegor256 #905

**Comment by yegor256** [comment]
@MikhailLipanin thanks!
