### ISSUE TITLE
Parsing objects "QQ.*" to XMIR. Is it works correctly now?

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#908]
If we have this object in EO:
```
QQ.io.stdout "Check\n"
```
it transforms to XMIR as:
```
<o base="QQ"/>
<o base=".io" method=""/>
<o base=".stdout" method="">
   <o base="string" data="string">Check\n</o>
</o>
```
Is it correct now or it should be transformed in another way? 
like:
```
<o base="QQ">
   <o base=".io" method="">
      <o base=".stdout" method="">
         <o base="string" data="string">Check\n</o>
      </o>
   </o>
</o>
```

Same thing appears with other QQ.* objects, for example "QQ.math.number" object transforms to:
```
<o base="QQ"/>
<o base=".math" method=""/>
<o base=".number" method="">
   <o base="x"/>
</o>
```

**Comment by yegor256** [comment]
@MikhailLipanin I believe, this is valid parsing, according to the paper: https://arxiv.org/abs/2111.13384

**Comment by MikhailLipanin** [comment]
Based on the article, the 'method' attribute of objects in XMIR should be replaced with a similar object, but without using this attribute. (Section 6 in paper)

**Comment by MikhailLipanin** [comment]
@yegor256, I misunderstood the possible representation of the 'QQ' object above. After conversion, without the 'method' attribute, it should look like this:
```
<o base=".stdout">
   <o base=".io">
      <o base="QQ"/>
   </o>
   <o base="string" data="string">Check\n</o>
</o>
```

**Comment by MikhailLipanin** [comment]
It is wrong to leave objects with a 'method' attribute, because after applying the Syntax.java class in XMIR, and then back using the XMIR.java class to EO, the following code will as result:
```
QQ
  .io
  .stdout
    "Check\n"
```
which is Wrong and will not dataize.

**Comment by MikhailLipanin** [comment]
@yegor256 So, we need to add a transformation (if there is none), which will replace objects with the 'method' attribute with similar ones.

**Comment by MikhailLipanin** [comment]
I figured out that after using the Syntax.java class, we need to apply the XMIR transformations sheet at the output - already ready-made ParsingTrain.java class.
