### ISSUE TITLE
Conflict of memory and list.reduce

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#912]
```
  [] > foo
    reduce. > res
      list
        * 0
      *
      [acc x]
        acc.with (memory x) > @
    seq > @
      (res.at 0).write 7
      (res.at 0)

  [] > foo2
    (*).with (memory 0) > res
    seq > @
      (res.at 0).write 7
      (res.at 0)
```
Let's look at these two methods, they should return the same thing, which is number 7.
But now let's run tests with these methods, and see that test 2 succeeds and test 1 fails.
```
[] > test-1
  eq. > @
    foo
    7

[] > test-2
  eq. > @
    foo2
    7
```

**Comment by EugeneDar** [comment]
The whole code:
```
[] > some-reduce-test
  eq. > @
    foo
    7

  [] > foo
    reduce. > res
      list
        * 0
      *
      [acc x]
        acc.with (memory x) > @
    seq > @
      (res.at 0).write 7
      (res.at 0)

[] > some-reduce-test-2
  eq. > @
    foo
    7

  [] > foo
    (*).with (memory 0) > res
    seq > @
      (res.at 0).write 7
      (res.at 0)
```

**Comment by EugeneDar** [comment]
I've opened similar issues before.
@Graur perhaps this ticket is similar to the proposed one https://github.com/objectionary/eo/issues/861
Correct me if I'm wrong.

**Comment by EugeneDar** [comment]
@yegor256 it seems to me that list.reduce has some fundamental problems when dealing with cage/memory. The reasons why I think so: https://github.com/objectionary/eo/issues/842 https://github.com/objectionary/eo/issues/861 https://github.com/objectionary/eo/issues/912 .
What do you think about it?

**Comment by yegor256** [comment]
@EugeneDar do you have a solution?

**Comment by EugeneDar** [comment]
@yegor256 unfortunately, I think with the current capabilities of code debugging, I won't be able to find what the error is.

**Comment by EugeneDar** [comment]
It solved in eo-collections
