### ISSUE TITLE
code duplication in PhDefault.toString() and PhDefault.φTerm()

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#917]
The algorithms in `PhDefault.toString()` and `PhDefault.φTerm()` are very similar. Would be great to create a new class implementing such an algorithm and use it from both methods. Besides, the existing implementation doesn't handle recursion correctly. A recursive object leads to endless calculations and eventual hanging of the JVM.

**Comment by yegor256** [comment]
@Graur please, help us here

**Comment by mximp** [comment]
@yegor256 @Graur I believe `PhDefault.toString()` shouldn't repeat `PhDefault.φTerm()`. `toString` should be much simpler.
I'm changing slightly the logic of these methods as part of #865. Let's review the changes and maybe this can be closed.

**Comment by mximp** [comment]
@yegor256 @Graur I believe `PhDefault.toString()` shouldn't repeat `PhDefault.φTerm()`. `toString` should be much simpler.
I'm changing slightly the logic of these methods as part of #865. Let's review the changes and maybe this can be closed.

**Comment by mximp** [comment]
@yegor256, this is fixed as part of #865.
Additionally #931 is raised to apply `Phi.toString()` in dataization logic.

I believe this task can be closed.
