### ISSUE TITLE
+architect meta

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#920]
Let's add `+architect` meta to all `.eo` files, using this format:

```
+architect yegor256@gmail.com
```

Also, let's add an XSL checker into `eo-parser` to make sure the tail of this meta is always an email, nothing else. The checker should complain with a `warning` severity level.

Also, together with this change, let's modify all copyright licenses in all `.java`, `.eo` and other files to this:

```
Copyright (c) 2016-2022 Objectionary.com
```

**Comment by yegor256** [comment]
@mximp please, take care of this (or delegate)

**Comment by mximp** [comment]
@OlesiaSub Could you please assist with this.

**Comment by OlesiaSub** [comment]
To clarify, should I modify licences like this one `Copyright (c) 2020-2022 Yegor Bugayenko` to `Copyright (c) 2020-2022 Objectionary.com`? (years here differ from the ones in the rest of the project)

**Comment by OlesiaSub** [comment]
Same question about copyright licences like this `Copyright (c) 2022 Eugene Darashkevich`.

**Comment by OlesiaSub** [comment]
What about `+architect` meta? Should I check for the maintainers and put their emails into corresponding .eo files or should it be `+architect yegor256@gmail.com` everywhere?

**Comment by mximp** [comment]
I suggest the latter for now:
`+architect yegor256@gmail.com`

**Comment by mximp** [comment]
@yegor256 all is done here, can this be closed?
