### ISSUE TITLE
We need use recursion in list.reduce realization

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#925]
Now we have a lot of problems, because we can't work with complex objects (like array of arrays) in reduce, because we put accumulator to the memory. 
We can solve this problem by using recursion.

**Comment by EugeneDar** [comment]
@yegor256 @Graur @mximp what do you think?

**Comment by Graur** [comment]
@EugeneDar go ahead

**Comment by yegor256** [comment]
@EugeneDar what's up with this?

**Comment by EugeneDar** [comment]
@yegor256 it finished, I'll close it.
