### ISSUE TITLE
Explicitly specifying the type of an object throws an error

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#926]
this code will be successfully dataized:
```
[] > app
  seq > @
    QQ.io.stdout "Hello world!\n"
```
while this one fails:
```
[] > app
  org.eolang.seq > @
    QQ.io.stdout "Hello world!\n"
```

**Comment by Graur** [comment]
@MikhailLipanin Is it legal to use `org.eolang.seq` without Phi? e.g. `Q.org.eolang.seq`

**Comment by MikhailLipanin** [comment]
@Graur, you are right, thanks! Didn't know about that.
