### ISSUE TITLE
Recursion doesn't work

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#927]
```
[] > recursion-falls-test
  eq. > @
    (rec-func 0)
    1

  [index] > rec-func
    if.
      index.lt 1
      (rec-func 1)
      index
```
This test crushes.

**Comment by EugeneDar** [comment]
@Graur please check.

**Comment by mximp** [comment]
@EugeneDar can you please add an error/behaviour of the failure.

**Comment by Graur** [comment]
@EugeneDar please, read this: https://www.yegor256.com/2022/03/29/bugs-occam-razor.html

**Comment by EugeneDar** [comment]
I apologize, there was a typo in the code.
