### ISSUE TITLE
ResolveMojo+Central must fail if there are transitive dependencies

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#934]
If the dependency we found contains any transitive dependencies, we should fail the build.

**Comment by yegor256** [comment]
@Graur pls, take care of this

**Comment by Graur** [comment]
@l3r8yJ please, try to solve this issue

**Comment by l3r8yJ** [comment]
@Graur got it!

**Comment by l3r8yJ** [comment]
@Graur 
Did I understand correctly that if there are such dependencies, it should stop the build?

<img width="778" alt="image" src="https://user-images.githubusercontent.com/46355873/182117609-a86b230e-9963-4311-8480-99ac824c8bb7.png">

**Comment by Graur** [comment]
@l3r8yJ Please, read about transitive dependencies here: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#:~:text=System%20Dependencies-,Transitive%20Dependencies,from%20the%20remote%20repositories%20specified.

**Comment by l3r8yJ** [comment]
@Graur I'm trying to create a method anologue to `checkConflicts()`, is it true that `checkConflicts()` checks for **the same dependencies of different versions**?

**Comment by Graur** [comment]
@l3r8yJ Yes, it is true

**Comment by Graur** [comment]
@DmitryFullStack Please, help us here

**Comment by Graur** [comment]
@volodya-lombrozo Can you help us here?
