### ISSUE TITLE
move Transpiler back into TranspileMojo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#935]
We extracted `Transpiler` some time ago from `TranspilerMojo` because we planned to use different transpilers. Now, let's put it back.

**Comment by yegor256** [comment]
@Graur pls, take care of this

**Comment by Graur** [comment]
@yasamprom can you help us here?

**Comment by Graur** [comment]
@yasamprom What's up with this issue?

**Comment by yasamprom** [comment]
@yegor256  let's close

**Comment by yegor256** [comment]
@yasamprom thanks!
