### ISSUE TITLE
move collections to a separate repository

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#936]
Let's extract `org.eolang.collections` into a separate repository.

**Comment by yegor256** [comment]
@Graur please, take care of this

**Comment by Graur** [comment]
@yegor256 Can you create `eo-collections` repository and give me some privileges?

**Comment by yegor256** [comment]
@Graur see https://github.com/objectionary/eo-collections (you have write-access)

**Comment by Graur** [comment]
@EugeneDar we released eo-collections, so you can start to getting rid of `collections` package from `eo-runtime`

**Comment by EugeneDar** [comment]
@yegor256 it's done.

**Comment by yegor256** [comment]
@EugeneDar thanks!
