### ISSUE TITLE
lower-case, upper-case, contains, ends-with, starts-with, index-of

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#938]
let's implement these attributes for `QQ.txt.text`

**Comment by EugeneDar** [comment]
@yegor256 I can do that.

**Comment by EugeneDar** [comment]
we are going to put all these methods in eo-strings later, aren't we?

**Comment by yegor256** [comment]
@EugeneDar please, go ahead. Let's do it ASAP. for now, in this repo. later, we'll move to eo-strings.

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.0`

**Comment by yegor256** [comment]
@EugeneDar thanks!
