### ISSUE TITLE
both `0.eq 0.0` and `0.0.eq 0` equal to `TRUE`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#942]
It happens because byte array of `0.0` and byte array of `0` have the same length equal to 8 (since all `int` objects cast to `long` in the core of `eo`) and these arrays are identical (they both consist of zeros).
I think it's a bug because, for example, both `10.eq 10.0` and `10.0.eq 10` are `FALSE`

UPD: this behavior below is also weird:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/37025995/181390566-6736af97-0f50-4790-a220-729ca5196c7f.png">

**Comment by Graur** [comment]
@maxonfjvipon I don't think this is a bug since `int` and `float` are 8 bytes. But it's still a good issue. We need to add some kind of type checking. Maybe you have a solution?

**Comment by maxonfjvipon** [comment]
@Graur we can try to use sign bit for an indirect purpose. We can say that 0 is 0x00000000 and 0.0 is 0x80000000 (which is -0 in ieee but we don't have it in EO)

**Comment by yegor256** [comment]
@maxonfjvipon I think I like the idea about `-0.0` (with an extra bit set to one)

**Comment by maxonfjvipon** [comment]
@yegor256 @Graur could you please tell me how I can debug java code inside eo-runtime on `mvn clean install -Pqulice` (or I should run anything else)? `System.out.println` does not output anything to console.

**Comment by maxonfjvipon** [comment]
@yegor256 could you please tell me how I can run the test inside eo-runtime separately? I need to test and debug `Param.asBytes()` method

**Comment by yegor256** [comment]
@maxonfjvipon make a ticket, complain about the absence of documentation in README.

**Comment by Graur** [comment]
@maxonfjvipon The budget is 30 minutes

**Comment by Graur** [comment]
@maxonfjvipon Thanks!
