### ISSUE TITLE
ram.eo:29-32: We need to add ram.ram-slice.slice object...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#945]
The puzzle `684-1cc2eb42` from #684 has to be resolved: 

https://github.com/objectionary/eo/blob/0132dbe6841ef0c7b6c0946f023deb5bce7c50a6/eo-runtime/src/main/eo/org/eolang/ram.eo#L29-L32

The puzzle was created by @rultor on 28-Jul-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Graur** [comment]
@piotrkot please, help us here

**Comment by Graur** [comment]
@piotrkot Do you have any progress here?

**Comment by yegor256** [comment]
@graur what's up with this one?

**Comment by Graur** [comment]
@yegor256 I want to suggest to not to implement `ram.ram-slice.slice` object. Because the chain of `slice` objects can be reached already now through the use of the `bytes.slice` object. 

Proof: #2043 

WDYT?

**Comment by Graur** [comment]
Closed, since #2043 was merged
