### ISSUE TITLE
Relations between eolang and target language objects

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#946]
I think its not enough clear how " / " operator  works. 
The paper says the object after " / " is the name of object, which left part decorates. (page 7 where atoms are discribed).
But i didn't find how fields and methods from target lang object became attribute. And generally what attributes have the object in  in eo after /.

**Comment by Graur** [comment]
@levBagryansky Could you give an example of the part you didn't understand?

**Comment by levBagryansky** [comment]
I already understood it. There was
`[] > compile /regex` in file [https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/txt/regex.eo](url)
So its means that the object compile is implemented on java. You can find the implemetation by looking at this line at the beginning of the file:
`+package org.eolang.txt`
It signify the implementation is here:
[https://github.com/objectionary/eo/tree/master/eo-runtime/src/main/java/EOorg/EOeolang/EOtxt](url)
Maybe it's worth adding a description of this sign "/" somewhere ?
Thanks

**Comment by mximp** [comment]
> So its means that the object "compile" is implemented on java ...
@levBagryansky to be more accurate here - it means that `compile` decorates `regex` and implementation is supplied by the runtime. By definition of _decoration_ `compile` inherits all attributes of `regex`.
That's exactly what the paper says.

**Comment by levBagryansky** [comment]
As I said, it's not clear enough, at least to me. For example it caused questions:
- How eo object `compile` can decorate java object `regex`?
- What is attribute in this context? I though "attribute" is a eo term.
- What runtime means: eo runtime, java runtime or smth else?

So for me it turned out that the article is not enough to understand what it wants to say in this place. Of course, maybe I'm the only one who ever deals with such a problem.
