### ISSUE TITLE
mvn clean test failes right after cloning

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eo#950]
I cloned this repository, tried running mvn clean test and it failed with the following mistakes:
![image](https://user-images.githubusercontent.com/57731693/181523634-0a94c331-9261-4ffa-b333-10e8580f61e0.png)

**Comment by Graur** [comment]
@OlesiaSub Can you try: `mvn clean install -Pqulice`?

**Comment by OlesiaSub** [comment]
It finished successfully.
And I should have done `mvn clean install` first, it worked as well.

**Comment by Graur** [comment]
@OlesiaSub usually, you need to run `mvn clean install -Pqulice` in root directory first, then run `mvn clean test` from eo-runtime directory

**Comment by Graur** [comment]
@OlesiaSub Do you still have an issue?

**Comment by yegor256** [comment]
@Graur I think `mvn clean test` should work too, from the start. If it doesn't, it's a bug.

**Comment by yegor256** [comment]
@Graur I think the solution would be to place [this file](https://github.com/objectionary/eo/blob/master/eo-parser/src/test/resources/META-INF/MANIFEST.MF) in all modules
