### ISSUE TITLE
apply new style of sorting `meta` to native objects

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#971]
on version [0.26.0](https://github.com/objectionary/eo/tree/0.26.0), meta information in native objects still remains unsorted:

![image](https://user-images.githubusercontent.com/33983579/182139975-3171f468-87ab-4aa3-9dea-f0ddcc39f3cf.png)

**Comment by Graur** [comment]
@IngeniariusSoftware I think pull request #960 will fix this issue when it is merged.

**Comment by yegor256** [comment]
Duplicate of #846
