### ISSUE TITLE
JSR-303 validator thrown during initialization: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#973]
I cloned eo and run tests as wrote in README.md
it shows an ERROR:
![image](https://user-images.githubusercontent.com/32939651/182143225-4943debb-e3c8-4896-9b9b-7d0333800203.png)
mvn -v:
![image](https://user-images.githubusercontent.com/32939651/182144306-54b85bd5-9929-48e1-8c0d-58bdde844e5b.png)
Also attached whole file with tests results:
[tests_results.txt](https://github.com/objectionary/eo/files/9233805/tests_results.txt)

**Comment by yegor256** [comment]
@levBagryansky for some weird reason you are using `jcabi-maven-plugin:0.14.1`, while in master we have version 0.16.0. Are you sure you building the latest version from `master` branch?
