### ISSUE TITLE
How to make [args...] work as integers?

### ISSUE THREAD

**Issue by includealex** [objectionary/eo#975]
I want to give some integers to my program by typing this
```
eoc link && eoc --alone dataize app 5
```
to get answer 120 (simple factorial calculation). But if I write such a code, 
```
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[n] > factorial
  if. > @
    lt.
      n
      2
    1
    n.times (factorial (n.minus 1))

[args...] > app
  stdout > @
    sprintf
      "I've got %d\n"
      factorial (args.at 0)

```
I will get an error. Error says that there is no attribute "lt" for EOstring. 
Are there any possibilities to "convert" (args.at 0) into integer?

**Comment by Graur** [comment]
@includealex I think you migth use [sscanf](https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/txt/sscanf.eo) object. And this example can help: https://github.com/objectionary/sandbox/blob/master/eo/sandbox/app.eo
e.g.
```
[args...] > app
  stdout > @
    sprintf
      "I've got %d\n"
      factorial ((sscanf "%d" (args.at 0)).at 0)
```
