### ISSUE TITLE
string abilities

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#977]
Its not clear how to get symbol num i from the string. 
For  example 
![image](https://user-images.githubusercontent.com/32939651/182366968-31a67a13-0030-4002-8a02-5b72bb655be5.png)
does not work. Also
![image](https://user-images.githubusercontent.com/32939651/182366875-de0fe187-8c30-49ff-9238-4074fced2a4d.png)
doesn't work too.
So how to iterate by string symbols?
Thank you

**Comment by kerelape** [comment]
@levBagryansky `string` doesn't have `at` or `as-array`, only `as-bytes`. But you can use `slice` to only take one exact symbol as another string (`my_str.slice 0 1`)

**Comment by levBagryansky** [comment]
Ok, thank you
