### ISSUE TITLE
`string.at`

### ISSUE THREAD

**Issue by kerelape** [objectionary/eo#979]
Could we add `at` object to the `string`? This would simply wrap `string.slice` with a default value for `len`, being `1`.

_Originally posted by @kerelape in https://github.com/objectionary/eo/issues/977#issuecomment-1202478918_

**Comment by Graur** [comment]
@kerelape We will have a similar object in the `text` object, which will be called `index-of`, according to [this](https://github.com/objectionary/on-the-origin-of-objects/blob/master/paper.tex#L448) or [this](https://arxiv.org/pdf/2206.02585.pdf), implemented in: https://github.com/objectionary/eo-strings

**Comment by kerelape** [comment]
@Graur doesn't `index-of` return the numerical index of a sub-string? e.g. `0` for `"abc".index-of "a"`

**Comment by Graur** [comment]
@kerelape I think you can add it in `text` object

**Comment by Graur** [comment]
@kerelape I think it's redundant, but maybe I am wrong.
@mximp  @yegor256 What do you think?

**Comment by yegor256** [comment]
@kerelape yes, this could be a good method for `@@.txt.text`. We try to keep `string` as small as possible.
