### ISSUE TITLE
Map iteratiing

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#986]
I didn't found how can I itearate map, as I see it's impossible. 
I think it is necessory, becouse key mustn;t be a number. So we can't to see any object there.

**Comment by EugeneDar** [comment]
@levBagryansky what solution do you propose?

**Comment by EugeneDar** [comment]
Maybe you can use list.reduce method ffor the result of the multimap.concat-all-arrays function

**Comment by levBagryansky** [comment]
@EugeneDar may be we need to implement smth like iterators for map.

**Comment by yegor256** [comment]
@levBagryansky I think `map.keys` would be nice to have. @EugeneDar WDYT?

**Comment by EugeneDar** [comment]
@yegor256 @levBagryansky I think 'map.keys' it's good idea. This method can decorate the array, and have a 'memory' field to iterate, and a 'next' method.

**Comment by yegor256** [comment]
@EugeneDar please, implement it

**Comment by yegor256** [comment]
@EugeneDar I would just return an array from `map.keys`. for iterating keys we may create another method, like `map.iterate-keys`.

**Comment by EugeneDar** [comment]
@yegor256 sure, I'll do it.
