### ISSUE TITLE
 [Warning]   Meta is out of order: "home https://github.com/objectionary/eo-math" (unsorted-metas:13)

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#988]
I just run tests by command `mvn clean install -Pqulice`
it returns `Meta is out of order: "home https://github.com/objectionary/eo-math" (unsorted-metas:13)` warning and can't build eo-runtime.
I last commits impact because it worked later.
![image](https://user-images.githubusercontent.com/32939651/182841776-09c44aad-c9c1-4d5e-affc-82117c464ca1.png)
I also did not find how to disable warning-as-error in the project.
Thank you

**Comment by Graur** [comment]
@levBagryansky you need to add `failOnWarning` flag to your configuration into `pom` file and set it to `false`.
Or the better way - is to delete `.eo` folder on your local PC (`/Users/{name}/.eo) and run `mvn clean install -Pqulice` again
