### ISSUE TITLE
Build error with -Werror

### ISSUE THREAD

**Issue by victor-yacovlev** [objectionary/eo#992]
OpenJDK 18 on macOS/aarch64 generates build fatal warnings "non-transient instance field of a serializable class declared with a non-serializable type" due to some classes do not implement `Serializable` interface.

Classes/interfaces that must implement `Serializable`:
 * interface `org.eolang.Phi`
 * all generated classes extending `org.eolang.PhDefault`, also these classes must provide `serialVersionUID`.

**Comment by yegor256** [comment]
@Graur please, take care of this or delegate. I think we should add java version 18 to `mvn.yml` GitHub action, to make sure this bug won't happen again

**Comment by Graur** [comment]
@kerelape please take this task, the budget is 30 minutes

**Comment by Graur** [comment]
@kerelape What's up with this task?

**Comment by kerelape** [comment]
@Graur maven does not understand `-W`

**Comment by Graur** [comment]
@kerelape Did you try to rise up java version to 18?

**Comment by kerelape** [comment]
@Graur yes... It is openjdk 18, macos 1.13.6. Maybe I miss something? I have only updated the jdk and ran `mvn ...`, is there something else I need to do?

**Comment by Graur** [comment]
@kerelape Did you try to do this:

> Classes/interfaces that must implement `Serializable`:
> 
> * interface `org.eolang.Phi`
> * all generated classes extending `org.eolang.PhDefault`, also these classes must provide `serialVersionUID`.

?

**Comment by kerelape** [comment]
> @kerelape Did you try to do this:
> 
> > Classes/interfaces that must implement `Serializable`:
> > 
> > * interface `org.eolang.Phi`
> > * all generated classes extending `org.eolang.PhDefault`, also these classes must provide `serialVersionUID`.
> 
> ?

I did make that. But I cannot check if it works because without that it works too.

**Comment by Graur** [comment]
@kerelape If so, just send us a pull request with `mvn.yml` changes and that's it

**Comment by kerelape** [comment]
> @kerelape If so, just send us a pull request with `mvn.yml` changes and that's it

I am sorry, I will do so now

**Comment by yegor256** [comment]
@kerelape @Graur what's up with this one?

**Comment by Graur** [comment]
@kerelape Do you have any progress here?

**Comment by yegor256** [comment]
@Graur time to close this one?

**Comment by mximp** [comment]
@yegor256 @Graur All changes are in open PR. However there is an issue with tests on Win/JDK18.
