### ISSUE TITLE
Duplication in EOLANG and φ-calculus (2111.13384)

### ISSUE THREAD

**Issue by piotrkot** [objectionary/eo#995]
Page 9, 3.7 Atoms: "In atoms, 𝜆-terms are bound to 𝜑 attribute. Thus, a more formal form of the Eq. 15 is: stdout ↦ J text ↦ ∅, 𝜑 ↦ 𝜆𝑠.𝑀stdout K." This text is repeated twice.

**Comment by yegor256** [comment]
@piotrkot fixed in 68952313, thanks!
