### ISSUE TITLE
Missing parent reference EOLANG and φ-calculus (2111.13384)

### ISSUE THREAD

**Issue by piotrkot** [objectionary/eo#996]
Page 8, 3.5 Parent and Home: "In case of application, an object is created by the prepending object: 𝑎 ↦ J𝑏 ↦ 𝑐, 𝑑 ↦ 𝑒.𝑓 , 𝑔 ↦ ℎ.𝑖(𝑗 )K 𝑏.𝜌 = 𝑎 𝑑.𝜌 = 𝑒 (7) 𝑔.𝜌 = ℎ."
In my opinion this should be written: 
𝑎.𝑏.𝜌 = 𝑎
𝑎.𝑑.𝜌 = 𝑒
𝑎.𝑔.𝜌 = ℎ.

**Comment by yegor256** [comment]
@piotrkot you are right, fixed in 58e11576, thanks!
